SELECT CASELINKNUM
       , CELLSAVSAL
       , TRANSFUSION
       , BLDPRODPRBCDUR
       , BLDPRODFFPDUR
       , BLDPRODFRESHPDUR
       , BLDPRODSNGLPLATDUR
       , BLDPRODINDPLATDUR
       , BLDPRODCRYODUR
       , BLDPRODFRESHWBDUR
       , BLDPRODWBDUR


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_TRANSFUSION

ORDER BY 1-- CAST(CASELINKNUM AS INTEGER);