SELECT CASELINKNUM
       , ANTIFIBUSAGE
       , ANTIFIBEPUSE
       , ANTIFIBEPLOAD
       , ANTIFIBEPPRIME
       , ANTIFIBEPINFRATE
       , ANTIFIBTRANEXUSE
       , ANTIFIBTRANEXLOAD
       , ANTIFIBTRANEXPRIME
       , ANTIFIBTRANEXINFRATE


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS
order by 1;