WITH 
EVENTS AS
(
SELECT
        VISIT_KEY
		,EVENT_ID
		,EVENT_DT
FROM 
     VISIT_ED_EVENT EVT 
	 INNER JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY 
WHERE  
      EVTTYPE.EVENT_ID IN ('1120000051','1120000008','1120000049', '1120000002','100248','1120000046','1120000015')

)
,ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY	
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 JOIN CDW_DICTIONARY ANESTYPE ON ANESTYPE.DICT_KEY = ANESSTAFF.DICT_OR_ANES_TYPE_KEY
										 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000051') TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000008' group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000049' group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000002' group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '100248' group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000046' group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000015' group by VISIT_KEY) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
--  AND SERVICE.SRC_ID IN (910,923) --Cardiac Service 
    and ANESTYPE.SRC_ID= 7.0000
	AND VSI_ANES.VSI_KEY > 0
 )

 
  ,PAT_WT AS
 (SELECT FLOW_REC.VSI_KEY,    
       CAST(AVG(CAST(MEAS_VAL/35.274 AS NUMERIC(7,1))) AS NUMERIC(5,1)) PAT_WT
FROM 
     CDW.FLOWSHEET_RECORD FLOW_REC
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY 
WHERE FS_ID IN (14)
GROUP BY 1
)
 

,MEDS AS
(
SELECT DISTINCT
        MEADMIN.MED_ORD_KEY
	   , MED_ORD_NM
	   , MED_ORD_DESC
	   , MEADMIN.SEQ_NUM
	   , MEADMIN.VISIT_KEY
	   , MEADMIN.ACTION_DT
	   , MEADMIN.DOSE
	   , MEADMIN.INFSN_RATE
	, COALESCE(MEDORD.DOSAGE_WEIGHT_KG,PAT_WT.PAT_WT) DOSAGE_WEIGHT_KG 
 FROM  
       ENCS 
	    JOIN MEDICATION_ADMINISTRATION MEADMIN ON MEADMIN.VISIT_KEY = ENCS.ANES_VISIT_KEY  
        JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = MEADMIN.MED_ORD_KEY  
	    LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = MEADMIN.DICT_RTE_KEY
	    LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = MEADMIN.DICT_RSLT_KEY
		LEFT JOIN PAT_WT ON ENCS.HSP_VAI_KEY = PAT_WT.VSI_KEY 
WHERE
	 (
	 (UPPER(MED_ORD_NM) LIKE '%FACTOR%VIIA%') or (UPPER(MED_ORD_DESC) LIKE '%FACTOR%VIIA%')
	 OR (UPPER(MED_ORD_NM) LIKE '%KCENTRA%') or (UPPER(MED_ORD_DESC) LIKE '%KCENTRA%')
	 or (UPPER(MED_ORD_NM) LIKE '%FEIBA%') or (UPPER(MED_ORD_DESC) LIKE '%FEIBA%')
	 OR (UPPER(MED_ORD_NM) LIKE '%PROFILNINE%') or (UPPER(MED_ORD_DESC) LIKE '%PROFILNINE%')
	 OR (UPPER(MED_ORD_NM) LIKE '%OCTAPLEX%') or (UPPER(MED_ORD_DESC) LIKE '%OCTAPLEX%')
	 OR (UPPER(MED_ORD_NM) LIKE '%AT3%') or (UPPER(MED_ORD_DESC) LIKE '%AT3%')
	 OR (UPPER(MED_ORD_NM) LIKE '%FIBRINOGEN%') or (UPPER(MED_ORD_DESC) LIKE '%FIBRINOGEN%')
	 OR (UPPER(MED_ORD_NM) LIKE '%DESMOPRESSIN%')  or (UPPER(MED_ORD_DESC) LIKE '%DESMOPRESSIN%')
	 OR (UPPER(MED_ORD_NM) LIKE '%DDAVP%') or (UPPER(MED_ORD_DESC) LIKE '%DDAVP%')
	 )
	 and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) 
	 AND MEADMIN.VISIT_KEY<>0
)



, FACTORVIIA AS
 (SELECT  VISIT_KEY
       ,1 AS ProcoagUsage
	   ,1 AS ProcoagFactorVIIa
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa3 
FROM
	(
	SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		( 
		SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG 
		FROM MEDS PROCOAG 
		WHERE
		     	 (UPPER(MED_ORD_NM) LIKE '%FACTOR%VIIA%') or (UPPER(MED_ORD_DESC) LIKE '%FACTOR%VIIA%')
		  	
		  ) FACT7 
	)FACT7SEQ
GROUP BY VISIT_KEY 
)


, KCENTRA AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCMPLXCON4
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG 
		FROM  MEDS PROCOAG
		WHERE
		    (UPPER(MED_ORD_NM) LIKE '%KCENTRA%') or  (UPPER(MED_ORD_DESC) LIKE '%KCENTRA%')
		  )FACT7
	)FACT7SEQ
GROUP BY VISIT_KEY 
)


, FEIBA AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCMPLXCON4W7A
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
		FROM  MEDS PROCOAG 
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE
		      (UPPER(MED_ORD_NM) LIKE '%FEIBA%') or  (UPPER(MED_ORD_DESC) LIKE '%FEIBA%')
		  )FACT7
	)FACT7SEQ
GROUP BY VISIT_KEY 
)


, PROFILNINE AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCMPLXCON3
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
		FROM MEDS PROCOAG 
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 
		      (UPPER(MED_ORD_NM) LIKE '%PROFILNINE%') or  (UPPER(MED_ORD_DESC) LIKE '%PROFILNINE%')
		  )FACT7
	  --AND PROCOAG.VISIT_KEY = '112395108' 
	)FACT7SEQ
GROUP BY VISIT_KEY 
)


, OCTAPLEX AS
 (SELECT VISIT_KEY
	   ,1 AS POCTAPLEX
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
		FROM MEDS PROCOAG 
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 
		     (UPPER(MED_ORD_NM) LIKE '%OCTAPLEX%') or  (UPPER(MED_ORD_DESC) LIKE '%OCTAPLEX%')
		  )FACT7
	)FACT7SEQ
GROUP BY VISIT_KEY 
)


, FIBRINOGEN AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGFIBRIN
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN3
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG 
		FROM  MEDS PROCOAG  
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 
		      (UPPER(MED_ORD_NM) LIKE '%FIBRINOGEN%') or  (UPPER(MED_ORD_DESC) LIKE '%FIBRINOGEN%')
	)FACT7SEQ
GROUP BY VISIT_KEY 
)

, AT3 AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGANTITHROM
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
		FROM  MEDS PROCOAG 

		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE
		     (UPPER(MED_ORD_NM) LIKE '%AT3%') or  (UPPER(MED_ORD_DESC) LIKE '%AT3%')
		  )FACT7
	)FACT7SEQ
GROUP BY VISIT_KEY 
)

, DESMOPRESSIN AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGDESMO
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
		FROM  MEDS PROCOAG 

		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 
		     (UPPER(MED_ORD_NM) LIKE '%DESMOPRESSIN%') OR (UPPER(MED_ORD_NM) LIKE '%DDAVP%')
			 OR
			  (UPPER(MED_ORD_DESC) LIKE '%DESMOPRESSIN%') OR (UPPER(MED_ORD_DESC) LIKE '%DDAVP%')

		  )FACT7
	)FACT7SEQ
GROUP BY VISIT_KEY 
)

, ENC AS
(
      SELECT ENCS.*,
			FACTORVIIA.*,
			KCENTRA.*,
			FEIBA.*,
			PROFILNINE.*,
			OCTAPLEX.*,
			FIBRINOGEN.*,
			AT3.*,
			DESMOPRESSIN.*
		FROM ENCS 
				  LEFT JOIN FACTORVIIA   ON FACTORVIIA.VISIT_KEY = ENCS.ANES_VISIT_KEY
				  LEFT JOIN KCENTRA      ON KCENTRA.VISIT_KEY = ENCS.ANES_VISIT_KEY
                  LEFT JOIN FEIBA        ON FEIBA.VISIT_KEY = ENCS.ANES_VISIT_KEY
				  LEFT JOIN PROFILNINE   ON PROFILNINE.VISIT_KEY = ENCS.ANES_VISIT_KEY
                  LEFT JOIN OCTAPLEX     ON OCTAPLEX.VISIT_KEY = ENCS.ANES_VISIT_KEY					  
				  LEFT JOIN FIBRINOGEN   ON FIBRINOGEN.VISIT_KEY = ENCS.ANES_VISIT_KEY	
				  LEFT JOIN AT3          ON AT3.VISIT_KEY = ENCS.ANES_VISIT_KEY	
				  LEFT JOIN DESMOPRESSIN ON DESMOPRESSIN.VISIT_KEY = ENCS.ANES_VISIT_KEY	

)

SELECT 

		CAST(ISNULL(LOG_ID,'') AS INTEGER)  CASENUMBER 
		,CAST(ISNULL(PROCOAGUSAGE,2) AS INTEGER)   PROCOAGUSAGE
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PROCOAGFACTORVIIA,2) AS INTEGER) END PROCOAGFACTORVIIA
		,CAST(PROCOAGFACTORVIIA1 AS INTEGER)  PROCOAGFACTORVIIA1
		,CAST(PROCOAGFACTORVIIA2 AS INTEGER)  PROCOAGFACTORVIIA2
		,CAST(PROCOAGFACTORVIIA3 AS INTEGER) PROCOAGFACTORVIIA3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON4,2) as integer) END  PPROCMPLXCON4
		,CAST(PROCMPLXCON4DS1 as integer) PROCMPLXCON4DS1
		,CAST(PROCMPLXCON4DS2 as integer) PROCMPLXCON4DS2
		,CAST(PROCMPLXCON4DS3 as integer) PROCMPLXCON4DS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON4W7A,2) as integer) END PPROCMPLXCON4W7A
		,CAST(PROCMPLXCON4W7A1 as integer) PROCMPLXCON4W7A1
		,CAST(PROCMPLXCON4W7A2 as integer) PROCMPLXCON4W7A2
		,CAST(PROCMPLXCON4W7A3 as integer) PROCMPLXCON4W7A3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON3,2) as integer) END PPROCMPLXCON3
		,CAST(PROCMPLXCON3DS1 as integer) PROCMPLXCON3DS1
		,CAST(PROCMPLXCON3DS2 as integer) PROCMPLXCON3DS2
		,CAST(PROCMPLXCON3DS3 as integer) PROCMPLXCON3DS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(POCTAPLEX,2) as integer) END POCTAPLEX
		,CAST(OCTAPLEXDS1 as integer) OCTAPLEXDS1
		,CAST(OCTAPLEXDS2 as integer) OCTAPLEXDS2
		,CAST(OCTAPLEXDS3 as integer) OCTAPLEXDS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGFIBRIN,2) as integer) END PPROCOAGFIBRIN
		,CAST(PROCOAGFIBRIN1 as integer) PROCOAGFIBRIN1
		,CAST(PROCOAGFIBRIN2 as integer) PROCOAGFIBRIN2
		,CAST(PROCOAGFIBRIN3 as integer) PROCOAGFIBRIN3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGANTITHROM,2) as integer) END PPROCOAGANTITHROM
		,CAST(PROCOAGANTITHROM1 as integer) PROCOAGANTITHROM1
		,CAST(PROCOAGANTITHROM2 as integer) PROCOAGANTITHROM2
		,CAST(PROCOAGANTITHROM3 as integer) PROCOAGANTITHROM3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGDESMO,2) as integer) END PPROCOAGDESMO
	    ,CAST(PROCOAGDESMO1 as integer) PROCOAGDESMO1
		,CAST(PROCOAGDESMO2 as integer) PROCOAGDESMO2
		,CAST(PROCOAGDESMO3 as integer) PROCOAGDESMO3
   
FROM
     ENC