select
    stg_pcoti_report_code_events.episode_key,
    stg_pcoti_report_code_events.episode_event_key,
    stg_pcoti_report_code_events.pat_key,
    stg_pcoti_report_code_events.visit_key,
    stg_pcoti_report_code_events.code_category,
    stg_pcoti_report_code_events.event_type_name,
    stg_pcoti_report_code_events.event_start_date,
    stg_pcoti_report_code_events.mrn,
    stg_pcoti_report_code_events.csn,
    stg_pcoti_report_code_events.patient_name,
    stg_pcoti_report_code_events.patient_dob,
    stg_pcoti_report_code_events.ip_service_name,
    stg_pcoti_report_code_events.department_name,
    stg_pcoti_report_code_events.department_group_name,
    stg_pcoti_report_code_events.bed_care_group,
    stg_pcoti_report_code_events.campus_name,
    stg_pcoti_report_code_events.cha_code_ind,
    stg_pcoti_report_code_events.cat_called_in_prior_24hrs_ind,
    stg_pcoti_report_code_events.immediate_disposition,
    stg_pcoti_report_code_events.survival_status,
    stg_pcoti_report_code_events.dx_at_event,
    stg_pcoti_report_code_events.pat_died_during_episode_ind,
    stg_pcoti_report_code_events.patient_death_date,
    stg_pcoti_report_code_events.icu_enter_date,
    stg_pcoti_report_code_events.time_to_xfer
from
    {{ ref('stg_pcoti_report_code_events') }} as stg_pcoti_report_code_events
where
    stg_pcoti_report_code_events.code_category = 'chop patients (code team activation)'
