with prematurity_gran as (
select cohort.pat_mrn_id,
cohort.pat_key,
noted_dt,
census_dt,
date(census_dt) - date(noted_dt) as time_to_census,
case when time_to_census >= 0 then 1 else 0 end as keep_ind,
case when lower(dx_nm) in('12 weeks gestation of pregnancy',
--region prematurity
                    '18 weeks gestation of pregnancy',
                    '20 weeks gestation of pregnancy',
                    '22 weeks gestation of pregnancy',
                    '23 weeks gestation of pregnancy',
                    '24 completed weeks of gestation',
                    '24 weeks gestation of pregnancy',
                    '24 wks of gestation completed',
                    '25 weeks gestation of pregnancy',
                    '25-26 completed weeks of gestation',
                    '25-26 wks gestation completed',
                    '26 weeks gestation of pregnancy',
                    '27 weeks gestation of pregnancy',
                    '27-28 completed weeks of gestation',
                    '27-28 wks gestation completed',
                    '28 weeks gestation of pregnancy',
                    '29 weeks gestation of pregnancy',
                    '29-30 completed weeks of gestation',
                    '29-30 wks gestation completed',
                    '30 weeks gestation of pregnancy',
                    '31 weeks gestation of pregnancy',
                    '31-32 completed weeks of gestation',
                    '31-32 wks gestation completed',
                    '32 week prematurity',
                    '32 weeks gestation of pregnancy',
                    '33 weeks gestation of pregnancy',
                    '33-34 completed weeks of gestation',
                    '33-34 wks gestation completed',
                    '34 weeks gestation of pregnancy',
                    '35 weeks gestation of pregnancy',
                    '35-36 completed weeks of gestation',
                    '35-36 wks gestation completed',
                    '36 to less than 38 completed weeks of gestation',
                    '36 weeks gestation of pregnancy',
                    'baby born premature',
                    'baby extremely premature 24-26 weeks',
                    'baby extremely premature 26-28 weeks',
                    'baby extremely premature 28-32 weeks',
                    'baby premature 24-26 weeks',
                    'baby premature 26-28 weeks',
                    'baby premature 28-32 weeks',
                    'baby premature 31 weeks',
                    'baby premature 32 weeks',
                    'baby premature 33 weeks',
                    'baby premature 34 weeks',
                    'baby premature 35 weeks',
                    'extreme immaturity of nb, gestational age less than 23 completed weeks',
                    'extreme immaturity of newborn, gestational age 23 completed weeks',
                    'extreme immaturity of newborn, gestational age 24 completed weeks',
                    'extreme immaturity of newborn, gestational age 25 completed weeks',
                    'extreme immaturity of newborn, gestational age 26 completed weeks',
                    'extreme immaturity of newborn, gestational age 27 completed weeks',
                    'extreme immaturity of newborn, gestational age less than 23 completed weeks',
                    'extreme premature infant < 500 gm',
                    'extreme premature infant, 500-749 gm',
                    'extreme premature infant, 750-999 gm',
                    'extreme prematurity',
                    'extreme prematurity, 500-749 grams, 25-26 completed weeks of gestation',
                    'extreme prematurity, 750-999 grams, 25-26 completed weeks of gestation',
                    'extreme prematurity, birth weight 500-749 grams, 24 completed weeks of gestation',
                    'fetal birthweight less than 1000 gram and gestation less than 28 weeks',
                    'fetus with birthweight less than 1000 grams and gestation less than 28 weeks',
                    'fetus with birthweight of 1000-2499 grams and gestation of 28-37 weeks',
                    'gestation period, 23 weeks',
                    'gestation period, 24 weeks',
                    'gestation period, 25 weeks',
                    'gestation period, 26 weeks',
                    'gestation period, 27 weeks',
                    'gestation period, 28 weeks',
                    'gestation period, 29 weeks',
                    'gestation period, 30 weeks',
                    'gestation period, 31 weeks',
                    'gestation period, 32 weeks',
                    'gestation period, 33 weeks',
                    'gestation period, 34 weeks',
                    'gestation period, 35 weeks',
                    'gestation period, 36 weeks',
                    'gestational age 24 weeks',
                    'gestational age 25-26 weeks',
                    'gestational age 27-28 weeks',
                    'gestational age 29-30 weeks',
                    'gestational age 31-32 weeks',
                    'gestational age 33-34 weeks',
                    'gestational age 35-36 weeks',
                    'gestational age related disorder, 24 completed weeks',
                    'gestational age related disorder, 25-26 completed weeks',
                    'gestational age related disorder, 35-36 completed weeks',
                    'gestational age, 22 weeks',
                    'gestational age, 23 weeks',
                    'gestational age, 25 weeks',
                    'gestational age, 26 weeks',
                    'gestational age, 27 weeks',
                    'gestational age, 28 weeks',
                    'gestational age, 29 weeks',
                    'gestational age, 30 weeks',
                    'gestational age, 31 weeks',
                    'gestational age, 32 weeks',
                    'gestational age, 33 weeks',
                    'gestational age, 34 weeks',
                    'gestational age, 35 weeks',
                    'gestational age, 36 weeks',
                    'h/o prematurity',
                    'history of prematurity',
                    'hx of prematurity',
                    'infant born at 36 weeks gestation',
                    'newborn infant of 23 completed weeks of gestation',
                    'newborn infant of 26 completed weeks of gestation',
                    'newborn of 24 completed weeks of gestation',
                    'newborn of 27 completed weeks of gestation',
                    'premature birth',
                    'premature birth of fraternal twins with both living',
                    'premature birth of identical twins, both living',
                    'premature birth of twins',
                    'premature birth with gestation of 35-36 weeks',
                    'premature birth, 33 to 35 6/7 weeks with 2 or more risk factors',
                    'premature birth, up to 28 6/7 to 32 6/7 weeks during respiratory syncytial virus (rsv) season', --noqa: L016
                    'premature birth, up to 28 6/7 to 32 6/7 weeks during rsv season',
                    'premature birth, up to 28 6/7 to 32 6/7 weeks prior to respiratory syncytial virus (rsv) season', --noqa: L016
                    'premature birth, up to 28 6/7 to 32 6/7 weeks prior to rsv season',
                    'premature births',
                    'premature delivery',
                    'premature delivery before 37 weeks',
                    'premature infant',
                    'premature infant (1000-2499 grams)',
                    'premature infant 24-26 weeks',
                    'premature infant of 23 weeks gestation',
                    'premature infant of 24 weeks gestation',
                    'premature infant of 25 weeks gestation',
                    'premature infant of 26 weeks gestation',
                    'premature infant of 27 weeks gestation',
                    'premature infant of 28 weeks gestation',
                    'premature infant of 29 weeks gestation',
                    'premature infant of 30 weeks gestation',
                    'premature infant of 31 weeks gestation',
                    'premature infant of 32 weeks gestation',
                    'premature infant of 33 weeks gestation',
                    'premature infant of 34 weeks gestation',
                    'premature infant of 35 weeks gestation',
                    'premature infant of 36 weeks gestation',
                    'premature infant of fewer than 30 weeks gestation',
                    'premature infant of less than 30 weeks gestation',
                    'premature infant of more than 35 weeks gestation',
                    'premature infant of unknown gestational age',
                    'premature infant with birthweight 1000-2499 gms or gestation of 28-37 weeks',
                    'premature infant with birthweight 1000-2499 grams',
                    'premature infant with birthweight 1000-2499 grams or gestation of 28-37 weeks',
                    'premature infant with gestation of 28-37 weeks',
                    'premature infant with gestation of 30-35 weeks',
                    'premature infant with gestation over 35 weeks',
                    'premature infant with gestation under 30 weeks',
                    'premature infant, 1000-1249 gm',
                    'premature infant, 1250-1499 gm',
                    'premature infant, 1500-1749 gm',
                    'premature infant, 1750-1999 gm',
                    'premature infant, 2000-2499 gm',
                    'premature infant, 2500 or more gm',
                    'premature infant, 500-749 gm',
                    'premature infant, 750-999 gm',
                    'premature infant, less than 500 gm',
                    'prematurity',
                    'prematurity of fetus',
                    'prematurity, 1,000-1,249 grams, 24 completed weeks',
                    'prematurity, 1,000-1,249 grams, 25-26 completed weeks',
                    'prematurity, 1,000-1,249 grams, 27-28 completed weeks',
                    'prematurity, 1,000-1,249 grams, 29-30 completed weeks',
                    'prematurity, 1,250-1,499 grams, 27-28 completed weeks',
                    'prematurity, 1,250-1,499 grams, 29-30 completed weeks',
                    'prematurity, 1,250-1,499 grams, 31-32 completed weeks',
                    'prematurity, 1,500-1,749 grams, 29-30 completed weeks',
                    'prematurity, 1,500-1,749 grams, 31-32 completed weeks',
                    'prematurity, 1,750-1,999 grams, 31-32 completed weeks',
                    'prematurity, 1,750-1,999 grams, 33-34 completed weeks',
                    'prematurity, 2,000-2,499 grams, 31-32 completed weeks',
                    'prematurity, 2,000-2,499 grams, 33-34 completed weeks',
                    'prematurity, 2,000-2,499 grams, 35-36 completed weeks',
                    'prematurity, 2,500 grams and over, 31-32 completed weeks',
                    'prematurity, 2,500 grams and over, 33-34 completed weeks',
                    'prematurity, 2,500 grams and over, 35-36 completed weeks',
                    'prematurity, 500-749 grams, 25-26 completed weeks',
                    'prematurity, 750-999 grams, 25-26 completed weeks',
                    'prematurity, 750-999 grams, 27-28 completed weeks',
                    'prematurity, 750-999 grams, 29-30 completed weeks',
                    'prematurity, birth weight 1,000-1,249 grams, with 24 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 27 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 27-28 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 28 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 29 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 29-30 completed weeks of gestation',
                    'prematurity, birth weight 1,000-1,249 grams, with 30 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 27-28 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 29 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 29-30 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 30 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 31 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 31-32 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 32 completed weeks of gestation',
                    'prematurity, birth weight 1,250-1,499 grams, with 33 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 29-30 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 30 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 31 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 31-32 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 32 completed weeks of gestation',
                    'prematurity, birth weight 1,500-1,749 grams, with 33 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 31 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 31-32 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 32 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 33 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 33-34 completed weeks of gestation',
                    'prematurity, birth weight 1,750-1,999 grams, with 34 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499  grams, with  35-36 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 31-32 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 32 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 33 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 33-34 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 34 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 35 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 35-36 completed weeks of gestation',
                    'prematurity, birth weight 2,000-2,499 grams, with 36 completed weeks of gestation',
                    'prematurity, birth weight 2,500 grams and over, with 31-32 completed weeks of gestation',
                    'prematurity, birth weight 2,500 grams and over, with 33-34 completed weeks of gestation',
                    'prematurity, birth weight 2,500 grams and over, with 35-36 completed weeks of gestation',
                    'prematurity, birth weight 500-749 grams, with 24 completed weeks of gestation',
                    'prematurity, birth weight 500-749 grams, with 25-26 completed weeks of gestation',
                    'prematurity, birth weight 500-749 grams, with less than 24 completed weeks of gestation',
                    'prematurity, birth weight 750-999 grams, with 24 completed weeks of gestation',
                    'prematurity, birth weight 750-999 grams, with 25-26 completed weeks of gestation',
                    'prematurity, birth weight 750-999 grams, with 27-28 completed weeks of gestation',
                    'prematurity, birth weight 750-999 grams, with 29-30 completed weeks of gestation',
                    'prematurity, fetus 35-36 completed weeks of gestation',
                    'prematurity, foetus 35-36 completed weeks of gestation',
                    'preterm infant, 1,000 grams-1,249 grams, 25-26 completed weeks of gestation',
                    'preterm infant, 24 to 37 completed weeks of gestation',
                    'preterm infant, birth weight 500-749 grams, with 24 completed weeks of gestation',
                    'preterm newborn infant of 23 completed weeks of gestation',
                    'preterm newborn infant of 24 completed weeks of gestation',
                    'preterm newborn infant of 25 completed weeks of gestation',
                    'preterm newborn infant of 26 completed weeks of gestation',
                    'preterm newborn infant of 27 completed weeks of gestation',
                    'preterm newborn infant of 28 completed weeks of gestation',
                    'preterm newborn infant of 29 completed weeks of gestation',
                    'preterm newborn infant of 30 completed weeks of gestation',
                    'preterm newborn infant of 31 completed weeks of gestation',
                    'preterm newborn infant of 32 completed weeks of gestation',
                    'preterm newborn infant of 33 completed weeks of gestation',
                    'preterm newborn infant of 34 completed weeks of gestation',
                    'preterm newborn infant of 35 completed weeks of gestation',
                    'preterm newborn infant of 36 completed weeks of gestation',
                    'preterm newborn infant with birth weight of 1,000 to 1,249 grams and 28 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 1,000 to 1,249 grams and 30 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 1,250 to 1,499 grams and 33 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 1,750 to 1,999 grams and 32 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 1,750 to 1,999 grams and 33 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 2,000 to 2,499 grams and 31 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 2,000 to 2,499 grams and 35 completed weeks of gestation', --noqa: L016
                    'preterm newborn infant with birth weight of 2,000 to 2,499 grams and 36 completed weeks of gestation', --noqa: L016
                    'preterm newborn of unknown gestational age',
                    'preterm newborn, gestational age 28 completed weeks',
                    'preterm newborn, gestational age 29 completed weeks',
                    'preterm newborn, gestational age 30 completed weeks',
                    'preterm newborn, gestational age 31 completed weeks',
                    'preterm newborn, gestational age 32 completed weeks',
                    'preterm newborn, gestational age 33 completed weeks',
                    'preterm newborn, gestational age 34 completed weeks',
                    'preterm newborn, gestational age 35 completed weeks',
                    'preterm newborn, gestational age 36 completed weeks',
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,000-1,249 grams, with 31-32 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,00-1,249 grams, with 27-28 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,250-1,499 grams, with 29-30 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,500-1,749 grams, with 31-32 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,500-1,749 grams, with 33-34 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 1,750-1,999 grams, with 31-32 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 2,000-2,499 grams, with 33-34 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 2,000-2,499 grams, with 35-36 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 2,00-2,499 grams, with 37 or more completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered by cesarean section during current hospitalization, birth weight 2,500 grams and over, with 33-34 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered vaginally during current hospitalization, birth weight 1,500-1,749 grams, with 31-32 completed weeks of gestation, with liveborn mate', --noqa: L016
                    'preterm twin newborn delivered vaginally during current hospitalization, birth weight 2,000-2,499 grams, with 31-32 completed weeks of gestation, with liveborn mate', --noqa: L016
--end region					
                    'very premature baby') then 1 else 0 end as prematurity_ind
from {{ ref('stg_picu_central_line_cohort') }} as cohort
inner join {{ source('cdw', 'patient_problem_list') }} as ppl on ppl.pat_key = cohort.pat_key
inner join {{ source('cdw', 'diagnosis') }} as dx on dx.dx_key = ppl.dx_key
where (lower(dx_nm) like '%gestation%'
      or lower(dx_nm) like '%prematur%'
      or lower(dx_nm) like 'preterm%')
      and keep_ind = 1
)

select distinct pat_mrn_id, pat_key, census_dt, prematurity_ind
from prematurity_gran
where prematurity_ind = 1
