WITH STEP1 AS (
SELECT 
MASTER_DATE.FULL_DT AS POST_MONTH,
loc.LOC_ID,
loc.LOC_NM,
sum(CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_DEBIT_MINUS_CREDIT_AMOUNT) AS AMT
FROM CDWPRD.ADMIN.WORKDAY_GL_SUMMARY
LEFT JOIN CDWPRD.ADMIN.WORKDAY_REVENUE_CATEGORY ON WORKDAY_GL_SUMMARY.REVENUE_CAT_KEY = WORKDAY_REVENUE_CATEGORY.REVENUE_CAT_KEY
LEFT JOIN CDWPRD.ADMIN.WORKDAY_LEDGER_ACCOUNT ON WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY = WORKDAY_LEDGER_ACCOUNT.LEDGER_ACCT_KEY
LEFT JOIN CDWPRD.ADMIN.MASTER_DATE ON WORKDAY_GL_SUMMARY.ACCOUNTING_MONTH_DT_KEY = MASTER_DATE.DT_KEY
LEFT JOIN CDWPRD.ADMIN.COST_CENTER CC ON CC.COST_CNTR_KEY = WORKDAY_GL_SUMMARY.COST_CNTR_KEY
LEFT JOIN (
SELECT distinct
DEPARTMENT.GL_PREFIX,
LOCATION.LOC_ID,
LOCATION.LOC_NM 
FROM CDWPRD.ADMIN.DEPARTMENT
LEFT JOIN CDWPRD.ADMIN.LOCATION ON CDWPRD.ADMIN.DEPARTMENT.REV_LOC_KEY = CDWPRD.ADMIN.LOCATION.LOC_KEY
WHERE CDWPRD.ADMIN.LOCATION.LOC_ID IN (1016,1017,1018,1020,1026,1029,1030,1033,1038)
) loc ON loc.GL_PREFIX = CC.COST_CNTR_ID
WHERE 
CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.REVENUE_CAT_KEY in (1040)
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.COMP_KEY = 100
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY IN (1207)
AND MASTER_DATE.FULL_DT between add_months(date_trunc('month',current_date),-27) and add_months(last_day(current_date),-1)
--AND loc.LOC_NM = 'BEHAVIORAL HEALTH RL'
GROUP BY 1,2,3
),

STEP2 AS (
SELECT 
POST_MONTH,
LOC_ID,
LOC_NM,
AMT,
TRUNC(AVG(AMT) OVER(ORDER BY LOC_ID,POST_MONTH ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2) AS AVG_AMT
FROM STEP1
WHERE POST_MONTH between add_months(date_trunc('month',current_date),-27) and add_months(last_day(current_date),-1)
)

SELECT 
POST_MONTH,
LOC_ID,
LOC_NM,
AMT*-1 as AMT,
AVG_AMT*-1 AS AVG_AMT
FROM STEP2
WHERE POST_MONTH between add_months(date_trunc('month',current_date),-24) and add_months(last_day(current_date),-1)
;
