create PROCEDURE [dbo].sp_CHOP_IMPACT_CATHPROCEDURES


AS
DECLARE @i int 
DECLARE @numrows int 
DECLARE @EventID int, @DBVrsn varchar(5), @EMREventID int, @Sort int, @ProcID int
DECLARE @CathCaseList TABLE (CathID int, ProcID int, EMREventID int, Sort int , DBVrsn varchar(5), RowID int)
DECLARE @ErrMsg nvarchar(4000), @ErrSeverity int


							
	SET NOCOUNT ON 
	
	INSERT INTO @CathCaseList(CathID, EMREventID, ProcID, Sort, DBVrsn, RowID)
	SELECT C.CathID, CATH_SRC.SURG_ENC_ID, CATH_SRC.SpecificProcID,CATH_SRC.Sort, h.IMPACTDataVrsn , ROW_NUMBER() OVER (ORDER BY C.CathID) 
	FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN dbo.CathData C ON CATH_SRC.SURG_ENC_ID = C.EMREventID 
	                                                 INNER JOIN dbo.Hospitalization H on C.HospID = H.HospitalizationID
													 LEFT JOIN CATHPROCEDURES CATH_TGT ON C.CathID = CATH_TGT.CathID AND CATH_SRC.SPECIFICPROCID = CATH_TGT.SpecificProcID
    WHERE PendingImport IN (1,2)   
	  AND CATH_TGT.SpecificProcID IS NULL
	  AND ((PROCDXCATH = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533,535,540,1055,1060,1065,1070,1075,1080,1085,1090,1095,1100,1105,1110,1115,1120,1125,1130,1135)) OR
	    (PROCDXCATH = 2 AND PROCEDUREID = PROCEDUREID) OR
		(PROCASD = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533,1115)) OR
		(PROCASD = 2 AND PROCEDUREID = PROCEDUREID) OR
		(PROCCOARC = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533)) OR
		(PROCCOARC = 2 AND PROCEDUREID = PROCEDUREID) OR
		(PROCAORTICVALV = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533)) OR
		(PROCAORTICVALV = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcPulmonaryValv = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533)) OR
		(ProcPulmonaryValv = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcPDA = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533)) OR
		(ProcPDA = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcProxPAStent = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533,1235,1240)) OR
		(ProcProxPAStent = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcEPCath = 1 AND PROCEDUREID IN (5,10,15,20,25,531,532,533)) OR
		(ProcEPCath = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcEPAblation = 1 AND PROCEDUREID IN (5,10,15,20,25,531,532,533)) OR
		(ProcEPAblation = 2 AND PROCEDUREID = PROCEDUREID) OR
		(ProcTPVR = 1 AND PROCEDUREID IN (5,10,15,20,25,367,368,531,532,533,1565)) OR
		(ProcTPVR = 2 AND PROCEDUREID = PROCEDUREID) 
		)


	ORDER BY C.CathID 

		
	SELECT @numrows = @@RowCount, @i = 1 
	WHILE (@i <= @numrows) 
		BEGIN
			SELECT @EventID = CathID, @DBVrsn = DBVrsn, @ProcID = ProcID, @Sort = Sort, @EMREventID = EMREventID FROM @CathCaseList AC WHERE AC.RowID = @i 

			IF EXISTS(SELECT ASD.CathID FROM CATHPROCEDURES ASD WHERE ASD.CathID = @EventID and ASD.SpecificProcID = @PROCID)  
				BEGIN
					BEGIN TRY
					   BEGIN
						--BEGIN THE TRANSACTION
						BEGIN TRAN
							--UPDATE THE TARGET RECORD
							UPDATE CATH_TRGT
							SET 
								CATH_TRGT.SPECIFICPROCID = CATH_SRC.SPECIFICPROCID,
								CATH_TRGT.PROCEDURENAME = DX_LU.PROCEDURENAME,
								CATH_TRGT.SORT = CATH_SRC.SORT
							FROM CATHPROCEDURES CATH_TRGT INNER JOIN @CathCaseList AC ON CATH_TRGT.CathID = AC.CathID  AND AC.Sort = CATH_TRGT.sort
							INNER JOIN [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC ON AC.EMREventID = CATH_SRC.SURG_ENC_ID AND AC.Sort = CATH_SRC.sort
							INNER JOIN [dbo].[CathProcMaster_LU] DX_LU ON DX_LU.PROCEDUREID = CATH_SRC.SPECIFICPROCID  
							WHERE AC.RowID = @i and CATH_TRGT.SpecificProcID = @PROCID

							
							--UPDATE THE SOURCE RECORD RESETTING THE PENDING IMPORT FLAG TO 0
							UPDATE CATH_SRC 
							SET CATH_SRC.PendingImport = 0
							FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON CATH_SRC.SURG_ENC_ID = AC.EMREventID  
							WHERE AC.RowID = @i and AC.Sort = CATH_SRC.sort
						
						COMMIT TRAN
						--COMMIT THE PENDING TRANSACTION IF NO ERRORS
						
						-- VALIDATE THE RECORD FOR THE END USER
						EXEC Validation_Call_ByTableEventID 'CATHPROCEDURES',@EventID,4,@DBVrsn;
					  END	
					END	TRY
					--IF ERROR IN TRANSACTION, PROVIDE ROLLBACK PROCEDURE
					BEGIN CATCH
						--PRINT 'BEGIN CATCH'
						IF @@TRANCOUNT > 0
							BEGIN
								--PRINT 'BEGIN ROLLBACK'
								
								ROLLBACK TRAN
								
								--PRINT 'BEGIN ERROR UPDATE'
								
								UPDATE CATH_SRC 
								SET CATH_SRC.PendingImport = 3
								FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON CATH_SRC.SURG_ENC_ID = AC.EMREventID  
								WHERE AC.RowID = @i and AC.Sort = CATH_SRC.sort
								
								--PRINT 'END ERROR UPDATE'
								
								SELECT @ErrMsg = ERROR_MESSAGE(), @ErrSeverity = ERROR_SEVERITY()
								
								RAISERROR(@ErrMsg, @ErrSeverity, 1)
							END
					END CATCH
					
				END
			ELSE IF EXISTS(SELECT C.CathID FROM CathData C INNER JOIN @CathCaseList AC ON C.CathID = AC.CathID WHERE AC.RowID = @i) 
				
				BEGIN TRY
				  BEGIN
					BEGIN TRAN
						INSERT INTO dbo.CATHPROCEDURES (CathID,SPECIFICPROCID,PROCEDURENAME, Sort) 
						SELECT AC.CathID,CATH_SRC.SPECIFICPROCID, DX_LU.PROCEDURENAME, CATH_SRC.SORT
						FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON AC.EMREventID = CATH_SRC.SURG_ENC_ID 
						                                                 INNER JOIN [dbo].[CathProcMaster_LU] DX_LU ON DX_LU.PROCEDUREID = CATH_SRC.SPECIFICPROCID  
						WHERE AC.RowID = @i AND AC.procid = CATH_SRC.SPECIFICPROCID

						UPDATE CATH_SRC 
						SET CATH_SRC.PendingImport = 0
						FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON CATH_SRC.SURG_ENC_ID = AC.EMREventID  
						WHERE AC.RowID = @i
					COMMIT TRAN
					--COMMIT THE PENDING TRANSACTION IF NO ERRORS
					
					-- VALIDATE THE RECORD FOR THE END USER
					EXEC Validation_Call_ByTableEventID 'CATHPROCEDURES',@EventID,4,@DBVrsn;
                   END
				END	TRY
				BEGIN CATCH
					IF @@TRANCOUNT > 0
						BEGIN
							ROLLBACK TRAN
							
							UPDATE CATH_SRC 
							SET CATH_SRC.PendingImport = 4
							FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON CATH_SRC.SURG_ENC_ID = AC.EMREventID 
							WHERE AC.RowID = @i and AC.Sort = CATH_SRC.Sort
							
							SELECT @ErrMsg = ERROR_MESSAGE(), @ErrSeverity = ERROR_SEVERITY()
							RAISERROR(@ErrMsg, @ErrSeverity, 1)

							
						END						
				END CATCH
			ELSE
				BEGIN
					UPDATE CATH_SRC 
					SET CATH_SRC.PendingImport = 2
					FROM [dbo].[CHOP_IMPACT_CATHPROCEDURES] CATH_SRC INNER JOIN @CathCaseList AC ON CATH_SRC.SURG_ENC_ID = AC.EMREventID  
					WHERE AC.RowID = @i and AC.Sort = CATH_SRC.Sort
					 
				END

			SET @i = @i + 1
		END
