with project_records as (
    select
        {{ dbt_utils.surrogate_key(['redcap_projects.project_id']) }}
            as redcap_project_key,
        redcap_projects.project_id,
        redcap_projects.project_name,
        redcap_projects.app_title,
        redcap_projects.status,
        redcap_projects.creation_time,
        redcap_projects.production_time,
        redcap_projects.inactive_time,
        redcap_projects.created_by,
        redcap_projects.draft_mode,
        redcap_projects.surveys_enabled,
        redcap_projects.repeatforms,
        redcap_projects.scheduling,
        redcap_projects.purpose,
        redcap_projects.purpose_other,
        redcap_projects.show_which_records,
        redcap_projects.count_project,
        redcap_projects.online_offline,
        redcap_projects.auth_meth,
        redcap_projects.double_data_entry,
        redcap_projects.project_language,
        redcap_projects.is_child_of,
        redcap_projects.date_shift_max,
        redcap_projects.institution,
        redcap_projects.site_org_type,
        redcap_projects.project_contact_name,
        redcap_projects.project_contact_email,
        redcap_projects.headerlogo,
        redcap_projects.auto_inc_set,
        redcap_projects.order_id_by,
        redcap_projects.disable_data_entry,
        redcap_projects.google_translate_default,
        redcap_projects.require_change_reason,
        redcap_projects.dts_enabled,
        redcap_projects.project_pi_firstname,
        redcap_projects.project_pi_mi,
        redcap_projects.project_pi_lastname,
        redcap_projects.project_pi_email,
        redcap_projects.project_pi_alias,
        redcap_projects.project_pi_username,
        redcap_projects.project_pi_pub_exclude,
        redcap_projects.project_irb_number,
        redcap_projects.project_grant_number,
        redcap_projects.history_widget_enabled,
        redcap_projects.secondary_pk,
        redcap_projects.secondary_pk_display_value,
        redcap_projects.secondary_pk_display_label,
        redcap_projects.custom_record_label,
        redcap_projects.display_project_logo_institution,
        redcap_projects.imported_from_rs,
        redcap_projects.display_today_now_button,
        redcap_projects.auto_variable_naming,
        redcap_projects.randomization,
        redcap_projects.enable_participant_identifiers,
        redcap_projects.survey_email_participant_field,
        redcap_projects.survey_phone_participant_field,
        redcap_projects.data_entry_trigger_url,
        redcap_projects.template_id,
        redcap_projects.date_deleted,
        redcap_projects.data_resolution_enabled,
        redcap_projects.field_comment_edit_delete,
        redcap_projects.realtime_webservice_enabled,
        redcap_projects.realtime_webservice_offset_days,
        redcap_projects.last_logged_event,
        redcap_projects.survey_queue_custom_text,
        redcap_projects.survey_auth_enabled,
        redcap_projects.survey_auth_field1,
        redcap_projects.survey_auth_event_id1,
        redcap_projects.survey_auth_field2,
        redcap_projects.survey_auth_event_id2,
        redcap_projects.survey_auth_field3,
        redcap_projects.survey_auth_event_id3,
        redcap_projects.survey_auth_apply_all_surveys,
        redcap_projects.survey_auth_custom_message,
        redcap_projects.survey_auth_fail_limit,
        redcap_projects.survey_auth_fail_window,
        redcap_projects.twilio_enabled,
        redcap_projects.twilio_account_sid,
        redcap_projects.twilio_auth_token,
        redcap_projects.twilio_from_number,
        redcap_projects.twilio_voice_language,
        redcap_projects.twilio_option_voice_initiate,
        redcap_projects.twilio_option_sms_initiate,
        redcap_projects.twilio_option_sms_invite_make_call,
        redcap_projects.twilio_option_sms_invite_receive_call,
        redcap_projects.twilio_option_sms_invite_web,
        redcap_projects.twilio_request_inspector_checked,
        redcap_projects.twilio_request_inspector_enabled,
        redcap_projects.twilio_append_response_instructions,
        redcap_projects.two_factor_exempt_project,
        redcap_projects.two_factor_force_project,
        redcap_projects.disable_autocalcs,
        redcap_projects.custom_public_survey_links,
        redcap_projects.pdf_show_logo_url,
        redcap_projects.pdf_hide_secondary_field,
        redcap_projects.shared_library_enabled,
        redcap_projects.allow_delete_record_from_log,
        redcap_projects.delete_file_repository_export_files,
        redcap_projects.custom_project_footer_text_link,
        redcap_projects.google_recaptcha_enabled,
        redcap_projects.datamart_allow_repeat_revision,
        redcap_projects.datamart_allow_create_revision,
        redcap_projects.datamart_enabled
    from
        {{ source('ods_redcap_porter', 'redcap_projects') }} as redcap_projects
),

record_union as (
    select
        redcap_project_key,
        project_id,
        project_name,
        app_title,
        status,
        creation_time,
        production_time,
        inactive_time,
        created_by,
        draft_mode,
        surveys_enabled,
        repeatforms,
        scheduling,
        purpose,
        purpose_other,
        show_which_records,
        count_project,
        online_offline,
        auth_meth,
        double_data_entry,
        project_language,
        is_child_of,
        date_shift_max,
        institution,
        site_org_type,
        project_contact_name,
        project_contact_email,
        headerlogo,
        auto_inc_set,
        order_id_by,
        disable_data_entry,
        google_translate_default,
        require_change_reason,
        dts_enabled,
        project_pi_firstname,
        project_pi_mi,
        project_pi_lastname,
        project_pi_email,
        project_pi_alias,
        project_pi_username,
        project_pi_pub_exclude,
        project_irb_number,
        project_grant_number,
        history_widget_enabled,
        secondary_pk,
        secondary_pk_display_value,
        secondary_pk_display_label,
        custom_record_label,
        display_project_logo_institution,
        imported_from_rs,
        display_today_now_button,
        auto_variable_naming,
        randomization,
        enable_participant_identifiers,
        survey_email_participant_field,
        survey_phone_participant_field,
        data_entry_trigger_url,
        template_id,
        date_deleted,
        data_resolution_enabled,
        field_comment_edit_delete,
        realtime_webservice_enabled,
        realtime_webservice_offset_days,
        last_logged_event,
        survey_queue_custom_text,
        survey_auth_enabled,
        survey_auth_field1,
        survey_auth_event_id1,
        survey_auth_field2,
        survey_auth_event_id2,
        survey_auth_field3,
        survey_auth_event_id3,
        survey_auth_apply_all_surveys,
        survey_auth_custom_message,
        survey_auth_fail_limit,
        survey_auth_fail_window,
        twilio_enabled,
        twilio_account_sid,
        twilio_auth_token,
        twilio_from_number,
        twilio_voice_language,
        twilio_option_voice_initiate,
        twilio_option_sms_initiate,
        twilio_option_sms_invite_make_call,
        twilio_option_sms_invite_receive_call,
        twilio_option_sms_invite_web,
        twilio_request_inspector_checked,
        twilio_request_inspector_enabled,
        twilio_append_response_instructions,
        two_factor_exempt_project,
        two_factor_force_project,
        disable_autocalcs,
        custom_public_survey_links,
        pdf_show_logo_url,
        pdf_hide_secondary_field,
        shared_library_enabled,
        allow_delete_record_from_log,
        delete_file_repository_export_files,
        custom_project_footer_text_link,
        google_recaptcha_enabled,
        datamart_allow_repeat_revision,
        datamart_allow_create_revision,
        datamart_enabled
    from 
        project_records

    union all

    select 
        -1 as redcap_project_key,
        null as project_id,
        'MISSING' as project_name,
        null as app_title,
        null as status,
        null as creation_time,
        null as production_time,
        null as inactive_time,
        null as created_by,
        null as draft_mode,
        null as surveys_enabled,
        null as repeatforms,
        null as scheduling,
        null as purpose,
        null as purpose_other,
        null as show_which_records,
        null as count_project,
        null as online_offline,
        null as auth_meth,
        null as double_data_entry,
        null as project_language,
        null as is_child_of,
        null as date_shift_max,
        null as institution,
        null as site_org_type,
        null as project_contact_name,
        null as project_contact_email,
        null as headerlogo,
        null as auto_inc_set,
        null as order_id_by,
        null as disable_data_entry,
        null as google_translate_default,
        null as require_change_reason,
        null as dts_enabled,
        null as project_pi_firstname,
        null as project_pi_mi,
        null as project_pi_lastname,
        null as project_pi_email,
        null as project_pi_alias,
        null as project_pi_username,
        null as project_pi_pub_exclude,
        null as project_irb_number,
        null as project_grant_number,
        null as history_widget_enabled,
        null as secondary_pk,
        null as secondary_pk_display_value,
        null as secondary_pk_display_label,
        null as custom_record_label,
        null as display_project_logo_institution,
        null as imported_from_rs,
        null as display_today_now_button,
        null as auto_variable_naming,
        null as randomization,
        null as enable_participant_identifiers,
        null as survey_email_participant_field,
        null as survey_phone_participant_field,
        null as data_entry_trigger_url,
        null as template_id,
        null as date_deleted,
        null as data_resolution_enabled,
        null as field_comment_edit_delete,
        null as realtime_webservice_enabled,
        null as realtime_webservice_offset_days,
        null as last_logged_event,
        null as survey_queue_custom_text,
        null as survey_auth_enabled,
        null as survey_auth_field1,
        null as survey_auth_event_id1,
        null as survey_auth_field2,
        null as survey_auth_event_id2,
        null as survey_auth_field3,
        null as survey_auth_event_id3,
        null as survey_auth_apply_all_surveys,
        null as survey_auth_custom_message,
        null as survey_auth_fail_limit,
        null as survey_auth_fail_window,
        null as twilio_enabled,
        null as twilio_account_sid,
        null as twilio_auth_token,
        null as twilio_from_number,
        null as twilio_voice_language,
        null as twilio_option_voice_initiate,
        null as twilio_option_sms_initiate,
        null as twilio_option_sms_invite_make_call,
        null as twilio_option_sms_invite_receive_call,
        null as twilio_option_sms_invite_web,
        null as twilio_request_inspector_checked,
        null as twilio_request_inspector_enabled,
        null as twilio_append_response_instructions,
        null as two_factor_exempt_project,
        null as two_factor_force_project,
        null as disable_autocalcs,
        null as custom_public_survey_links,
        null as pdf_show_logo_url,
        null as pdf_hide_secondary_field,
        null as shared_library_enabled,
        null as allow_delete_record_from_log,
        null as delete_file_repository_export_files,
        null as custom_project_footer_text_link,
        null as google_recaptcha_enabled,
        null as datamart_allow_repeat_revision,
        null as datamart_allow_create_revision,
        null as datamart_enabled
)

select
    redcap_project_key,
    project_id,
    project_name,
    app_title,
    status,
    creation_time,
    production_time,
    inactive_time,
    created_by,
    draft_mode,
    surveys_enabled,
    repeatforms,
    scheduling,
    purpose,
    purpose_other,
    show_which_records,
    count_project,
    online_offline,
    auth_meth,
    double_data_entry,
    project_language,
    is_child_of,
    date_shift_max,
    institution,
    site_org_type,
    project_contact_name,
    project_contact_email,
    headerlogo,
    auto_inc_set,
    order_id_by,
    disable_data_entry,
    google_translate_default,
    require_change_reason,
    dts_enabled,
    project_pi_firstname,
    project_pi_mi,
    project_pi_lastname,
    project_pi_email,
    project_pi_alias,
    project_pi_username,
    project_pi_pub_exclude,
    project_irb_number,
    project_grant_number,
    history_widget_enabled,
    secondary_pk,
    secondary_pk_display_value,
    secondary_pk_display_label,
    custom_record_label,
    display_project_logo_institution,
    imported_from_rs,
    display_today_now_button,
    auto_variable_naming,
    randomization,
    enable_participant_identifiers,
    survey_email_participant_field,
    survey_phone_participant_field,
    data_entry_trigger_url,
    template_id,
    date_deleted,
    data_resolution_enabled,
    field_comment_edit_delete,
    realtime_webservice_enabled,
    realtime_webservice_offset_days,
    last_logged_event,
    survey_queue_custom_text,
    survey_auth_enabled,
    survey_auth_field1,
    survey_auth_event_id1,
    survey_auth_field2,
    survey_auth_event_id2,
    survey_auth_field3,
    survey_auth_event_id3,
    survey_auth_apply_all_surveys,
    survey_auth_custom_message,
    survey_auth_fail_limit,
    survey_auth_fail_window,
    twilio_enabled,
    twilio_account_sid,
    twilio_auth_token,
    twilio_from_number,
    twilio_voice_language,
    twilio_option_voice_initiate,
    twilio_option_sms_initiate,
    twilio_option_sms_invite_make_call,
    twilio_option_sms_invite_receive_call,
    twilio_option_sms_invite_web,
    twilio_request_inspector_checked,
    twilio_request_inspector_enabled,
    twilio_append_response_instructions,
    two_factor_exempt_project,
    two_factor_force_project,
    disable_autocalcs,
    custom_public_survey_links,
    pdf_show_logo_url,
    pdf_hide_secondary_field,
    shared_library_enabled,
    allow_delete_record_from_log,
    delete_file_repository_export_files,
    custom_project_footer_text_link,
    google_recaptcha_enabled,
    datamart_allow_repeat_revision,
    datamart_allow_create_revision,
    datamart_enabled,
    'REDCAP~' || project_id as integration_id,
    current_timestamp as create_date,
    'REDCAP' as create_source,
    current_timestamp as update_date,
    'REDCAP' as update_source
from
    record_union
