with survey_records as (
    select
        {{ dbt_utils.surrogate_key(
            [
                'redcap_surveys.survey_id',
                'redcap_surveys.project_id',
                'redcap_surveys.form_name'
            ]
        ) }} as redcap_survey_key,
        redcap_surveys.survey_id,
        redcap_surveys.project_id,
        redcap_surveys.form_name,
        redcap_surveys.title,
        redcap_surveys.instructions,
        redcap_surveys.acknowledgement,
        redcap_surveys.question_by_section,
        redcap_surveys.display_page_number,
        redcap_surveys.question_auto_numbering,
        redcap_surveys.survey_enabled,
        redcap_surveys.save_and_return,
        redcap_surveys.save_and_return_code_bypass,
        redcap_surveys.logo,
        redcap_surveys.hide_title,
        redcap_surveys.view_results,
        redcap_surveys.min_responses_view_results,
        redcap_surveys.check_diversity_view_results,
        redcap_surveys.end_survey_redirect_url,
        redcap_surveys.survey_expiration,
        redcap_surveys.promis_skip_question,
        redcap_surveys.survey_auth_enabled_single,
        redcap_surveys.edit_completed_response,
        redcap_surveys.hide_back_button,
        redcap_surveys.show_required_field_text,
        redcap_surveys.confirmation_email_subject,
        redcap_surveys.confirmation_email_content,
        redcap_surveys.confirmation_email_from,
        redcap_surveys.confirmation_email_attach_pdf,
        redcap_surveys.confirmation_email_attachment,
        redcap_surveys.text_to_speech,
        redcap_surveys.text_to_speech_language,
        redcap_surveys.end_survey_redirect_next_survey,
        redcap_surveys.theme,
        redcap_surveys.text_size,
        redcap_surveys.font_family,
        redcap_surveys.theme_text_buttons,
        redcap_surveys.theme_bg_page,
        redcap_surveys.theme_text_title,
        redcap_surveys.theme_bg_title,
        redcap_surveys.theme_text_sectionheader,
        redcap_surveys.theme_bg_sectionheader,
        redcap_surveys.theme_text_question,
        redcap_surveys.theme_bg_question,
        redcap_surveys.enhanced_choices,
        redcap_surveys.repeat_survey_enabled,
        redcap_surveys.repeat_survey_btn_text,
        redcap_surveys.response_limit,
        redcap_surveys.response_limit_include_partials,
        redcap_surveys.response_limit_custom_text,
        redcap_surveys.survey_time_limit_days,
        redcap_surveys.survey_time_limit_hours,
        redcap_surveys.survey_time_limit_minutes,
        redcap_surveys.email_participant_field,
        redcap_surveys.end_of_survey_pdf_download,
        redcap_surveys.pdf_auto_archive,
        redcap_surveys.pdf_econsent_version,
        redcap_surveys.pdf_econsent_type,
        redcap_surveys.pdf_econsent_firstname_field,
        redcap_surveys.pdf_econsent_firstname_event_id,
        redcap_surveys.pdf_econsent_lastname_field,
        redcap_surveys.pdf_econsent_lastname_event_id,
        redcap_surveys.pdf_econsent_dob_field,
        redcap_surveys.pdf_econsent_dob_event_id,
        redcap_surveys.pdf_econsent_allow_edit,
        redcap_surveys.pdf_econsent_signature_field1,
        redcap_surveys.pdf_econsent_signature_field2,
        redcap_surveys.pdf_econsent_signature_field3,
        redcap_surveys.pdf_econsent_signature_field4,
        redcap_surveys.pdf_econsent_signature_field5
    from
        {{ source('ods_redcap_porter', 'redcap_surveys') }} as redcap_surveys
),

record_union as (
    select
        redcap_survey_key,
        survey_id,
        project_id,
        form_name,
        title,
        instructions,
        acknowledgement,
        question_by_section,
        display_page_number,
        question_auto_numbering,
        survey_enabled,
        save_and_return,
        save_and_return_code_bypass,
        logo,
        hide_title,
        view_results,
        min_responses_view_results,
        check_diversity_view_results,
        end_survey_redirect_url,
        survey_expiration,
        promis_skip_question,
        survey_auth_enabled_single,
        edit_completed_response,
        hide_back_button,
        show_required_field_text,
        confirmation_email_subject,
        confirmation_email_content,
        confirmation_email_from,
        confirmation_email_attach_pdf,
        confirmation_email_attachment,
        text_to_speech,
        text_to_speech_language,
        end_survey_redirect_next_survey,
        theme,
        text_size,
        font_family,
        theme_text_buttons,
        theme_bg_page,
        theme_text_title,
        theme_bg_title,
        theme_text_sectionheader,
        theme_bg_sectionheader,
        theme_text_question,
        theme_bg_question,
        enhanced_choices,
        repeat_survey_enabled,
        repeat_survey_btn_text,
        response_limit,
        response_limit_include_partials,
        response_limit_custom_text,
        survey_time_limit_days,
        survey_time_limit_hours,
        survey_time_limit_minutes,
        email_participant_field,
        end_of_survey_pdf_download,
        pdf_auto_archive,
        pdf_econsent_version,
        pdf_econsent_type,
        pdf_econsent_firstname_field,
        pdf_econsent_firstname_event_id,
        pdf_econsent_lastname_field,
        pdf_econsent_lastname_event_id,
        pdf_econsent_dob_field,
        pdf_econsent_dob_event_id,
        pdf_econsent_allow_edit,
        pdf_econsent_signature_field1,
        pdf_econsent_signature_field2,
        pdf_econsent_signature_field3,
        pdf_econsent_signature_field4,
        pdf_econsent_signature_field5 
    from 
        survey_records

    union all

    select 
        -1 as redcap_survey_key,
        null as survey_id,
        null as project_id,
        'MISSING' as form_name,
        null as title,
        null as instructions,
        null as acknowledgement,
        null as question_by_section,
        null as display_page_number,
        null as question_auto_numbering,
        null as survey_enabled,
        null as save_and_return,
        null as save_and_return_code_bypass,
        null as logo,
        null as hide_title,
        null as view_results,
        null as min_responses_view_results,
        null as check_diversity_view_results,
        null as end_survey_redirect_url,
        null as survey_expiration,
        null as promis_skip_question,
        null as survey_auth_enabled_single,
        null as edit_completed_response,
        null as hide_back_button,
        null as show_required_field_text,
        null as confirmation_email_subject,
        null as confirmation_email_content,
        null as confirmation_email_from,
        null as confirmation_email_attach_pdf,
        null as confirmation_email_attachment,
        null as text_to_speech,
        null as text_to_speech_language,
        null as end_survey_redirect_next_survey,
        null as theme,
        null as text_size,
        null as font_family,
        null as theme_text_buttons,
        null as theme_bg_page,
        null as theme_text_title,
        null as theme_bg_title,
        null as theme_text_sectionheader,
        null as theme_bg_sectionheader,
        null as theme_text_question,
        null as theme_bg_question,
        null as enhanced_choices,
        null as repeat_survey_enabled,
        null as repeat_survey_btn_text,
        null as response_limit,
        null as response_limit_include_partials,
        null as response_limit_custom_text,
        null as survey_time_limit_days,
        null as survey_time_limit_hours,
        null as survey_time_limit_minutes,
        null as email_participant_field,
        null as end_of_survey_pdf_download,
        null as pdf_auto_archive,
        null as pdf_econsent_version,
        null as pdf_econsent_type,
        null as pdf_econsent_firstname_field,
        null as pdf_econsent_firstname_event_id,
        null as pdf_econsent_lastname_field,
        null as pdf_econsent_lastname_event_id,
        null as pdf_econsent_dob_field,
        null as pdf_econsent_dob_event_id,
        null as pdf_econsent_allow_edit,
        null as pdf_econsent_signature_field1,
        null as pdf_econsent_signature_field2,
        null as pdf_econsent_signature_field3,
        null as pdf_econsent_signature_field4,
        null as pdf_econsent_signature_field5
)

select
    redcap_survey_key,
    survey_id,
    project_id,
    form_name,
    title,
    instructions,
    acknowledgement,
    question_by_section,
    display_page_number,
    question_auto_numbering,
    survey_enabled,
    save_and_return,
    save_and_return_code_bypass,
    logo,
    hide_title,
    view_results,
    min_responses_view_results,
    check_diversity_view_results,
    end_survey_redirect_url,
    survey_expiration,
    promis_skip_question,
    survey_auth_enabled_single,
    edit_completed_response,
    hide_back_button,
    show_required_field_text,
    confirmation_email_subject,
    confirmation_email_content,
    confirmation_email_from,
    confirmation_email_attach_pdf,
    confirmation_email_attachment,
    text_to_speech,
    text_to_speech_language,
    end_survey_redirect_next_survey,
    theme,
    text_size,
    font_family,
    theme_text_buttons,
    theme_bg_page,
    theme_text_title,
    theme_bg_title,
    theme_text_sectionheader,
    theme_bg_sectionheader,
    theme_text_question,
    theme_bg_question,
    enhanced_choices,
    repeat_survey_enabled,
    repeat_survey_btn_text,
    response_limit,
    response_limit_include_partials,
    response_limit_custom_text,
    survey_time_limit_days,
    survey_time_limit_hours,
    survey_time_limit_minutes,
    email_participant_field,
    end_of_survey_pdf_download,
    pdf_auto_archive,
    pdf_econsent_version,
    pdf_econsent_type,
    pdf_econsent_firstname_field,
    pdf_econsent_firstname_event_id,
    pdf_econsent_lastname_field,
    pdf_econsent_lastname_event_id,
    pdf_econsent_dob_field,
    pdf_econsent_dob_event_id,
    pdf_econsent_allow_edit,
    pdf_econsent_signature_field1,
    pdf_econsent_signature_field2,
    pdf_econsent_signature_field3,
    pdf_econsent_signature_field4,
    pdf_econsent_signature_field5,
    'REDCAP~' || survey_id as integration_id,
    current_timestamp as create_date,
    'REDCAP' as create_source,
    current_timestamp as update_date,
    'REDCAP' as update_source
from
    record_union
