SELECT ACCOUNT
,LAST_NAME
,CLAIMNUMBER
,TRANSDATE
,TRANSTYPE
,TRANSTYPEDESC
,ADJUSTMENTREASON
,TRANSAMOUNT
,CATEGORYDESCRIPTION
,HCPC
,PAYERINDENTIFIER
,PAYERNAME
,UPD_DT
FROM CDW_ODS.ADMIN.HDMS_DS_AR_TRANSACTIONDETAILS