--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_AIRWAY','bkp_CHOP_CCAS_ANESTHESIA_AIRWAY';
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_MONITOR','bkp_CHOP_CCAS_ANESTHESIA_MONITOR';
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_POSTOPICU','bkp_CHOP_CCAS_ANESTHESIA_POSTOPICU';
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_PREOPMEDS','bkp_CHOP_CCAS_ANESTHESIA_PREOPMEDS' ;
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_PROCOAGULANTS','bkp_CHOP_CCAS_ANESTHESIA_PROCOAGULANTS';
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS','bkp_CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS';
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_TECHNIQUE','bkp_CHOP_CCAS_ANESTHESIA_TECHNIQUE' ;
--EXEC SP_RENAME 'CHOP_CCAS_ANESTHESIA_TRANSFUSION','bkp_CHOP_CCAS_ANESTHESIA_TRANSFUSION' ;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_AIRWAY
(
	CASELINKNUM INT NOT NULL,
	AIRWAYINSITU INTEGER,
	AIRWAYTYPE INTEGER,
	AIRWAYSIZELMA INTEGER,
	AIRWAYSIZEINTUB INTEGER,
	CUFFED INTEGER,
	AIRWAYSITE INTEGER,
	ENDOBRONCISO INTEGER,
	ENDOBRONCISOMETH INTEGER,
	ENDOFINDUCTDT DATETIME,
	ICUTYPEVENT INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL

)
;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_MONITOR
(
	CASELINKNUM INT NOT NULL,
	ARTLINE INTEGER,
	ARTLINETYPERAD INTEGER,
	ARTLINETYPEBRACH INTEGER,
	ARTLINETYPEAX INTEGER,
	ARTLINETYPEFEM INTEGER,
	ARTLINETYPEULNAR INTEGER,
	ARTLINETYPEDORS INTEGER,
	ARTLINETYPEPOST INTEGER,
	ARTLINETYPECENT INTEGER,
	ARTLINEPREPROC INTEGER,
	CUTDOWN INTEGER,
	CUTDOWNRAD INTEGER,
	CUTDOWNULN INTEGER,
	CUTDOWNFEM INTEGER,
	CUTDOWNOTH INTEGER,
	PERCENTPRESS INTEGER,
	PCPLOCRJUG INTEGER,
	PCPLOCRSUB INTEGER,
	PCPLOCRFEM INTEGER,
	PCPLOCLJUG INTEGER,
	PCPLOCLSUB INTEGER,
	PCPLOCLFEM INTEGER,
	PCPLOCOTH INTEGER,
	CVPPICCPREPROC INTEGER,
	CVPPLACED INTEGER,
	SCVO2 INTEGER,
	NEUROMONITOR INTEGER,
    NEUROMONBIS INTEGER,
    NEUROMONTCD INTEGER,
	NEUROMONNIRS INTEGER,
    NEUROMONOTH INTEGER,
	SGCATH INTEGER,	
	SURGMONLINES INTEGER,
	LOWINTRAOPTEMP NUMERIC(4,1),
	INTRAOPTEMPSITE INTEGER,
	TEE INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL


)
;


CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_POSTOPICU
(
	CASELINKNUM INT NOT NULL,
	ICUARRDT DATETIME,
	INITIALFIO2 NUMERIC(4,2),
	TEMPICUARR NUMERIC(4,1),
	TEMPSITE INTEGER,
	INITPULSEOX DECIMAL(4,1),
	ICUPACULABS INTEGER,
	PH DECIMAL(4,2),
	PCO2 INTEGER,
	PO2 INTEGER,
	BASEEXCESS INTEGER,
	LACTATE DECIMAL(4,2),
	HEMATOCRIT DECIMAL(4,1),
	DISPUNDERANES INTEGER,
	TEMPPACE INTEGER,
	PERIANESDEMISE INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL

)
;


CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_PREOPMEDS
(
	CASELINKNUM INT NOT NULL,
	PREOPO2SAT NUMERIC(5,2),
	PREOPOXYGEN INTEGER,
	PLOCTRANSDT DATETIME,
	PREOPSED INTEGER,
	PREOPSEDRTE INTEGER,
	PREOPSEDDRUGATRO INTEGER,
	PREOPSEDDRUGDEM INTEGER,
	PREOPSEDDRUGDEX INTEGER,
	PREOPSEDDRUGDIAZ INTEGER,
	PREOPSEDDRUGFENT INTEGER,
	PREOPSEDDRUGGLYCO INTEGER,
	PREOPSEDDRUGKET INTEGER,
	PREOPSEDDRUGLORAZ INTEGER,
	PREOPSEDDRUGMIDAZ INTEGER,
	PREOPSEDDRUGMORPH INTEGER,
	PREOPSEDDRUGPENT INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL


)
;


CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_PROCOAGULANTS
(
	CASELINKNUM INT NOT NULL,
	PROCOAGUSAGE INTEGER,
	PROCOAGFACTORVIIA INTEGER,
	PROCOAGFACTORVIIA1 INTEGER,
	PROCOAGFACTORVIIA2 INTEGER,
	PROCOAGFACTORVIIA3 INTEGER,
	PROCMPLXCON4 INTEGER ,
	PROCMPLXCON4DS1 INTEGER ,
	PROCMPLXCON4DS2 INTEGER ,
	PROCMPLXCON4DS3 INTEGER ,
	PROCMPLXCON4W7A INTEGER ,
	PROCMPLXCON4W7A1 INTEGER ,
	PROCMPLXCON4W7A2 INTEGER ,
	PROCMPLXCON4W7A3 INTEGER ,
	PROCMPLXCON3 INTEGER ,
	PROCMPLXCON3DS1 INTEGER ,
	PROCMPLXCON3DS2 INTEGER ,
	PROCMPLXCON3DS3 INTEGER ,
	OCTAPLEX INTEGER ,
	OCTAPLEXDS1 INTEGER ,
	OCTAPLEXDS2 INTEGER ,
	OCTAPLEXDS3 INTEGER ,
	PROCOAGFIBRIN INTEGER ,
	PROCOAGFIBRIN1 INTEGER ,
	PROCOAGFIBRIN2 INTEGER ,
	PROCOAGFIBRIN3 INTEGER ,
	PROCOAGANTITHROM INTEGER ,
	PROCOAGANTITHROM1 INTEGER ,
	PROCOAGANTITHROM2 INTEGER ,
	PROCOAGANTITHROM3 INTEGER ,
	PROCOAGDESMO INTEGER ,
	PROCOAGDESMO1 INTEGER ,
	PROCOAGDESMO2 INTEGER ,
	PROCOAGDESMO3 INTEGER ,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL
	

)
;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS
(
	CASELINKNUM INT NOT NULL,
	ANTIFIBUSAGE INTEGER,
	ANTIFIBEPUSE INTEGER,
	ANTIFIBEPLOAD INTEGER,
	ANTIFIBEPPRIME INTEGER,
	ANTIFIBEPINFRATE INTEGER,
	ANTIFIBTRANEXUSE INTEGER,
	ANTIFIBTRANEXLOAD INTEGER,
	ANTIFIBTRANEXPRIME INTEGER,
	ANTIFIBTRANEXINFRATE INTEGER,
	ANTIFIBTRANEXPRIMEDOSE INTEGER,
	POCCOAGTSTUTIL INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL
	)
;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_NIRS
(
	CASELINKNUM INT NOT NULL,
	NIRSCERUSED INTEGER,
	NIRSCERPRE INTEGER,
	NIRSCERINTRA INTEGER,
	NIRSCERPOST INTEGER,
	NIRSSOMUSED INTEGER,
	NIRSSOMPRE INTEGER,
	NIRSSOMINTRA INTEGER,
    NIRSSOMPOST INTEGER,	
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL
	)
;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_TECHNIQUE
(
	CASELINKNUM INT NOT NULL,
	INDUCTIONDT DATETIME,
	INDTYPEINH INTEGER,
	INDAGENTINHALSEVO INTEGER,
	INDAGENTINHALISO INTEGER,
	INDTYPEIV INTEGER,
	INDAGENTIVSODT INTEGER,
	INDAGENTIVKET INTEGER,
	INDAGENTIVETOM INTEGER,
	INDAGENTIVPROP INTEGER,
	INDAGENTIVFENT INTEGER,
	INDAGENTIVMID INTEGER,
	INDAGENTIVDEX INTEGER,
	INDAGENTIVSUF INTEGER,
	INDAGENTIVREM INTEGER,
	INDTYPEIM INTEGER,
	INDAGENTIMKET INTEGER,
	INDAGENTIMMID INTEGER,
	REGIONALANES INTEGER,
	REGANESSITE INTEGER,
	REGANESDRUGBUP INTEGER,
	REGANESDRUGBUPFEN INTEGER,
	REGANESDRUGCLON INTEGER,
	REGANESDRUGFEN INTEGER,
	REGANESDRUGHYDRO INTEGER,
	REGANESDRUGLIDO INTEGER,
	REGANESDRUGMORPH INTEGER,
	REGANESDRUGROP INTEGER,
	REGANESDRUGROPFEN INTEGER,
	REGANESDRUGTETRA INTEGER,
	REGANESDRUGOTH INTEGER,
	INTNERVEINF INTEGER,
    REGFIELDBLOCK INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL

)
;

CREATE TABLE DBO.CHOP_CCAS_ANESTHESIA_TRANSFUSION
(
	CASELINKNUM INT NOT NULL,
	AUTOLOGOUSTRANS INTEGER,
	TRANSFUSBLDPRODANY INTEGER,
	CELLSAVSAL INTEGER,
	TRANSFUSION INTEGER,
	BLDPRODPRBCDUR INTEGER,
	BLDPRODFFPDUR INTEGER,
	BLDPRODFRESHPDUR INTEGER,
	BLDPRODSNGLPLATDUR INTEGER,
	BLDPRODINDPLATDUR INTEGER,
	BLDPRODCRYODUR INTEGER,
	BLDPRODFRESHWBDUR INTEGER,
	BLDPRODWBDUR INTEGER,
	LOADDT DATETIME NOT NULL,
	MD5 VARCHAR(50) NOT NULL,
	PENDINGIMPORT INT NOT NULL

)
;


ALTER TABLE CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_AIRWAY ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_AIRWAY PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_MONITOR ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_MONITOR PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_POSTOPICU ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_POSTOPICU PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_PREOPMEDS ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_PREOPMEDS PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_PROCOAGULANTS ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_PROCOAGULANTS PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_TECHNIQUE ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_TECHNIQUE PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_TRANSFUSION ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_TRANSFUSION PRIMARY KEY (CASELINKNUM);
ALTER TABLE CHOP_CCAS_ANESTHESIA_NIRS ADD CONSTRAINT PK_CHOP_CCAS_ANESTHESIA_NIRS PRIMARY KEY (CASELINKNUM);




--DROP TABLE CHOP_CCAS_ANESTHESIA_AIRWAY ;	
--DROP TABLE CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_CASES  ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_CODES ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_MONITOR ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_POSTOPICU;
--DROP TABLE CHOP_CCAS_ANESTHESIA_PREOPMEDS ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_PROCOAGULANTS ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_TECHNIQUE ;
--DROP TABLE CHOP_CCAS_ANESTHESIA_TRANSFUSION;


