DROP TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS
(
	CASELINKNUM INT NOT NULL,
	PROCOAGUSAGE INTEGER,
	PROCOAGFACTORVIIA INTEGER,
	PROCOAGFACTORVIIA1 INTEGER,
	PROCOAGFACTORVIIA2 INTEGER,
	PROCOAGFACTORVIIA3 INTEGER,
	PROCMPLXCON4 INTEGER ,
	PROCMPLXCON4DS1 INTEGER ,
	PROCMPLXCON4DS2 INTEGER ,
	PROCMPLXCON4DS3 INTEGER ,
	PROCMPLXCON4W7A INTEGER ,
	PROCMPLXCON4W7A1 INTEGER ,
	PROCMPLXCON4W7A2 INTEGER ,
	PROCMPLXCON4W7A3 INTEGER ,
	PROCMPLXCON3 INTEGER ,
	PROCMPLXCON3DS1 INTEGER ,
	PROCMPLXCON3DS2 INTEGER ,
	PROCMPLXCON3DS3 INTEGER ,
	OCTAPLEX INTEGER ,
	OCTAPLEXDS1 INTEGER ,
	OCTAPLEXDS2 INTEGER ,
	OCTAPLEXDS3 INTEGER ,
	PROCOAGFIBRIN INTEGER ,
	PROCOAGFIBRIN1 INTEGER ,
	PROCOAGFIBRIN2 INTEGER ,
	PROCOAGFIBRIN3 INTEGER ,
	PROCOAGANTITHROM INTEGER ,
	PROCOAGANTITHROM1 INTEGER ,
	PROCOAGANTITHROM2 INTEGER ,
	PROCOAGANTITHROM3 INTEGER ,
	PROCOAGDESMO INTEGER ,
	PROCOAGDESMO1 INTEGER ,
	PROCOAGDESMO2 INTEGER ,
	PROCOAGDESMO3 INTEGER ,
    LOADDT TIMESTAMP
	

)
;


ALTER TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS PRIMARY KEY (CASELINKNUM);


ALTER TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS OWNER TO CDWSTG ; 


GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS TO ADMINISTRATION_DATA  ;

