DROP TABLE S_CDW_CCAS_ANESTHESIA_CASES;
DROP TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY;
DROP TABLE S_CDW_CCAS_ANESTHESIA_MONITOR;
DROP TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU;
DROP TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS ;
DROP TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS;
DROP TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS;
DROP TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE ;
DROP TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION ;


CREATE TABLE S_CDW_CCAS_ANESTHESIA_CASES
(
	CASELINKNUM INT NOT NULL,
	SURGDT TIMESTAMP,
    LOADDT TIMESTAMP
)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY
(
	CASELINKNUM INT NOT NULL,
	AIRWAYINSITU INTEGER,
	AIRWAYTYPE INTEGER,
	AIRWAYSIZELMA INTEGER,
	AIRWAYSIZEINTUB INTEGER,
	CUFFED INTEGER,
	AIRWAYSITE INTEGER,
	ENDOBRONCISO INTEGER,
	ENDOBRONCISOMETH INTEGER,
	ENDOFINDUCTDT TIMESTAMP,
	ICUTYPEVENT INTEGER,
    LOADDT TIMESTAMP
)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_MONITOR
(
	CASELINKNUM INT NOT NULL,
	ARTLINE INTEGER,
	ARTLINETYPERAD INTEGER,
	ARTLINETYPEBRACH INTEGER,
	ARTLINETYPEAX INTEGER,
	ARTLINETYPEFEM INTEGER,
	ARTLINETYPEULNAR INTEGER,
	ARTLINETYPEDORS INTEGER,
	ARTLINETYPEPOST INTEGER,
	ARTLINETYPECENT INTEGER,
	ARTLINEPREPROC INTEGER,
	CUTDOWN INTEGER,
	CUTDOWNRAD INTEGER,
	CUTDOWNULN INTEGER,
	CUTDOWNFEM INTEGER,
	CUTDOWNOTH INTEGER,
	PERCENTPRESS INTEGER,
	PCPLOCRJUG INTEGER,
	PCPLOCRSUB INTEGER,
	PCPLOCRFEM INTEGER,
	PCPLOCLJUG INTEGER,
	PCPLOCLSUB INTEGER,
	PCPLOCLFEM INTEGER,
	PCPLOCOTH INTEGER,
	CVPPICCPREPROC INTEGER,
	CVPPLACED INTEGER,
	SCVO2 INTEGER,
	NEUROMONITOR INTEGER,
    NEUROMONBIS INTEGER,
    NEUROMONTCD INTEGER,
	NEUROMONNIRS INTEGER,
    NEUROMONOTH INTEGER,
	SGCATH INTEGER,
	SURGMONLINES INTEGER,
	LOWINTRAOPTEMP NUMERIC(4,1),
	INTRAOPTEMPSITE INTEGER,
	TEE INTEGER,
    LOADDT TIMESTAMP


)
;


CREATE TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU
(
	CASELINKNUM INT NOT NULL,
	ICUARRDT TIMESTAMP,
	INITIALFIO2 NUMERIC(4,2),
	TEMPICUARR NUMERIC(4,1),
	TEMPSITE INTEGER,
	INITPULSEOX DECIMAL(4,1),
	ICUPACULABS INTEGER,
	PH DECIMAL(4,2),
	PCO2 INTEGER,
	PO2 INTEGER,
	BASEEXCESS INTEGER,
	LACTATE DECIMAL(4,2),
	HEMATOCRIT DECIMAL(4,1),
	DISPUNDERANES INTEGER,
	TEMPPACE INTEGER,
	PERIANESDEMISE INTEGER,
    LOADDT TIMESTAMP

)
;


CREATE TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS
(
	CASELINKNUM INT NOT NULL,
	PREOPO2SAT NUMERIC(8,2),
	PREOPOXYGEN INTEGER,
	PLOCTRANSDT TIMESTAMP,
	PREOPSED INTEGER,
	PREOPSEDRTE INTEGER,
	PREOPSEDDRUGATRO INTEGER,
	PREOPSEDDRUGDEM INTEGER,
	PREOPSEDDRUGDEX INTEGER,
	PREOPSEDDRUGDIAZ INTEGER,
	PREOPSEDDRUGFENT INTEGER,
	PREOPSEDDRUGGLYCO INTEGER,
	PREOPSEDDRUGKET INTEGER,
	PREOPSEDDRUGLORAZ INTEGER,
	PREOPSEDDRUGMIDAZ INTEGER,
	PREOPSEDDRUGMORPH INTEGER,
	PREOPSEDDRUGPENT INTEGER,
    LOADDT TIMESTAMP


)
;


CREATE TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS
(
	CASELINKNUM INT NOT NULL,
	PROCOAGUSAGE INTEGER,
	PROCOAGFACTORVIIA INTEGER,
	PROCOAGFACTORVIIA1 NUMERIC(10,2),
	PROCOAGFACTORVIIA2 NUMERIC(10,2),
	PROCOAGFACTORVIIA3 NUMERIC(10,2),
    LOADDT TIMESTAMP
	

)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS
(
	CASELINKNUM INT NOT NULL,
	ANTIFIBUSAGE INTEGER,
	ANTIFIBEPUSE INTEGER,
	ANTIFIBEPLOAD INTEGER,
	ANTIFIBEPPRIME INTEGER,
	ANTIFIBEPINFRATE INTEGER,
	ANTIFIBTRANEXUSE INTEGER,
	ANTIFIBTRANEXLOAD INTEGER,
	ANTIFIBTRANEXPRIME INTEGER,
	ANTIFIBTRANEXINFRATE INTEGER,
	ANTIFIBTRANEXPRIMEDOSE INTEGER,
	POCCOAGTSTUTIL INTEGER,
    LOADDT TIMESTAMP
	)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_NIRS
(
	CASELINKNUM INT NOT NULL,
	NIRSCERUSED INTEGER,
	NIRSCERPRE INTEGER,
	NIRSCERINTRA INTEGER,
	NIRSCERPOST INTEGER,
	NIRSSOMUSED INTEGER,
	NIRSSOMPRE INTEGER,
	NIRSSOMINTRA INTEGER,
	NIRSSOMPOST INTEGER,
    LOADDT TIMESTAMP
	)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE
(
	CASELINKNUM INT NOT NULL,
	INDUCTIONDT TIMESTAMP,
	INDTYPEINH INTEGER,
	INDAGENTINHALSEVO INTEGER,
	INDAGENTINHALISO INTEGER,
	INDTYPEIV INTEGER,
	INDAGENTIVSODT INTEGER,
	INDAGENTIVKET INTEGER,
	INDAGENTIVETOM INTEGER,
	INDAGENTIVPROP INTEGER,
	INDAGENTIVFENT INTEGER,
	INDAGENTIVMID INTEGER,
	INDAGENTIVDEX INTEGER,
	INDAGENTIVSUF INTEGER,
	INDAGENTIVREM INTEGER,
	INDTYPEIM INTEGER,
	INDAGENTIMKET INTEGER,
	INDAGENTIMMID INTEGER,
	REGIONALANES INTEGER,
	REGANESSITE INTEGER,
	REGANESDRUGBUP INTEGER,
	REGANESDRUGBUPFEN INTEGER,
	REGANESDRUGCLON INTEGER,
	REGANESDRUGFEN INTEGER,
	REGANESDRUGHYDRO INTEGER,
	REGANESDRUGLIDO INTEGER,
	REGANESDRUGMORPH INTEGER,
	REGANESDRUGROP INTEGER,
	REGANESDRUGROPFEN INTEGER,
	REGANESDRUGTETRA INTEGER,
	REGANESDRUGOTH INTEGER,
	INTNERVEINF INTEGER,
    REGFIELDBLOCK INTEGER,
    LOADDT TIMESTAMP

)
;

CREATE TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION
(
	CASELINKNUM INT NOT NULL,
	AUTOLOGOUSTRANS INTEGER,
	TRANSFUSBLDPRODANY INTEGER,
	CELLSAVSAL INTEGER,
	TRANSFUSION INTEGER,
	BLDPRODPRBCDUR INTEGER,
	BLDPRODFFPDUR INTEGER,
	BLDPRODFRESHPDUR INTEGER,
	BLDPRODSNGLPLATDUR INTEGER,
	BLDPRODINDPLATDUR INTEGER,
	BLDPRODCRYODUR INTEGER,
	BLDPRODFRESHWBDUR INTEGER,
	BLDPRODWBDUR INTEGER,
    LOADDT TIMESTAMP

)
;


--PKS
ALTER TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_AIRWAY PRIMARY KEY (CASELINKNUM);	
ALTER TABLE S_CDW_CCAS_ANESTHESIA_CASES ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_CASES PRIMARY KEY (CASELINKNUM);	
ALTER TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_MONITOR ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_MONITOR PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_POSTOPICU PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_PREOPMEDS PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_TECHNIQUE PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_TRANSFUSION PRIMARY KEY (CASELINKNUM);
ALTER TABLE S_CDW_CCAS_ANESTHESIA_NIRS ADD CONSTRAINT PK_S_CDW_CCAS_ANESTHESIA_NIRS PRIMARY KEY (CASELINKNUM);



--OWNERSHIP
ALTER TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_CASES OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_MONITOR OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION OWNER TO CDWSTG ; 
ALTER TABLE S_CDW_CCAS_ANESTHESIA_NIRS OWNER TO CDWSTG ; 

--GRANTS
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_AIRWAY TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_CASES TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_MONITOR TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_POSTOPICU TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_PREOPMEDS TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_TECHNIQUE TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_TRANSFUSION TO ADMINISTRATION_DATA  ;
GRANT SELECT ON S_CDW_CCAS_ANESTHESIA_NIRS TO ADMINISTRATION_DATA  ;
