SELECT AGE.ID_CLAIM
,AGE.ORGANIZATIONNAME
,AGE.ACCOUNT
,ptd.PATIENTMEDICALRECORDNUMBER 
,AGE.FIRST_NAME 
,AGE.LAST_NAME 
,AGE.BIRTHDATE
,PTD.PATIENTZIP
,AGE.CATEGORYDESCRIPTION
,AGE.BILLING_DATE
,AGE.ID_PAYER
,AGE.PAYERNAME
,AGE.POLICYNUMBER
,AGE.HCPC
,age.BILLINGCODEDESC 
,AGE.AMOUNT
,AGE.CURRENTAMT
,AGE.AGED1
,AGE.AGED2
,AGE.AGED3
,AGE.AGED4
,AGE.AGED5
,AGE.UNBILLEDTOTAL
,AGE.STATUSINDICATOR
,AGE.LASTUBDESCRIPTION
,AGE.ACCOUNTPAYERTYPEBALANCE
,AGE.ASOFDATE
FROM CDW_ODS.ADMIN.HDMS_DS_AR_AGEDARDATEOFSERVICE AGE 
LEFT JOIN CDW_ODS.ADMIN.HDMS_DS_PATIENT_DEMOGRAPHICS PTD ON AGE.ACCOUNT = PTD.ACCOUNT 