SELECT CASH.ACCOUNT,
       cash.CLAIMNUMBER,
       cash.PAYERIDENTIFIER,
       cash.PAYERNAME,
       cash.TRANSACTIONDATE ,
       cash.TRANSACTIONNUMBER,
       CASH.TRANSACTIONTYPE,
       CASH.TRANSACTIONTYPEDESC,
       CASH.TRANSACTIONAMOUNT,
       CASH.PROVIDERIDENTIFIER,
       CASH.ORGANIZATIONNAME,
       CASH.DATEOFSERVICE,
       CASH.HCPC,
       CASH.CHECKDATE,
       CASH.CHECKNUMBER,
       cash.paymentmethod,
       cash.batchpostingnumber,
       cash.depositdate,
       cash.txdatecreated,
       cash.autopostingdate,
       cash.operator
FROM CDW_ODS.admin.HDMS_DS_CASH_TRANSACTIONDETAILS CASH