--CREATE TABLE REGISTRY_STS_ANESTHESIA_PREOPMEDS
--AS

WITH ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY	
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000051') TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000008' group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000049' group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000002' group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '100248' group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000046' group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000015' group by VISIT_KEY) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
  AND SERVICE.SRC_ID = 910 --Cardiac Service 
 )

,
SPO2 AS
(SELECT  fr.vsi_key SP02_VSI_KEY
         ,C.OR_LOG_KEY SPO2_LOG_KEY
         ,REC_DT SPO2_REC_DT
	     ,TO_NUMBER(ISNULL(MEAS_VAL,'0'),'999.99') AS SpO2 --SELECT DISTINCT ISNULL(MEAS_VAL,'0')
 from  ENCS  
    LEFT JOIN ANESTHESIA_ENCOUNTER_LINK c ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY
    LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = C.VISIT_KEY
	INNER JOIN CDW.VISIT_STAY_INFO vsi on VAI_HSP.VISIT_KEY = vsi.VISIT_KEY
	INNER JOIN CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	INNER JOIN CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	INNER JOIN CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
 WHERE 1=1	
	   AND f.FS_KEY IN (121161) --SpO2
       --AND OR_LOG_KEY = '5098014'
)

,O2SUPP AS
(SELECT  fr.vsi_key O2SUPP_VSI_KEY
         , 1 AS O2SUPP
         ,C.OR_LOG_KEY O2SUPP_LOG_KEY
         ,REC_DT O2SUPP_DT
	     ,MEAS_VAL AS O2SUPP_VAL 
 from ENCS  
    LEFT JOIN ANESTHESIA_ENCOUNTER_LINK c ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY
    LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = C.VISIT_KEY
	INNER JOIN CDW.VISIT_STAY_INFO vsi on VAI_HSP.VISIT_KEY = vsi.VISIT_KEY
	INNER JOIN CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	INNER JOIN CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	INNER JOIN CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
 WHERE 1=1	
	   AND f.FS_KEY IN (133355) --O2Supp
	   and MEAS_VAL <> 'Not applicable'
	--   AND OR_LOG_KEY = '5098014'	
)
,
PREMEDS AS 
(SELECT
	vsi.vsi_key,
	min(case when lower(DISP_NM) like '%premed%given%' and UPPER(MEAS_VAL) IN ('CONTINUOUS INFUSION FROM FLOOR', 'YES') THEN 1 ELSE 2 end) as PREMED_GIVEN,
	min(case when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'IM%' THEN '525' 
	         when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'IV%' THEN '525' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'INTRANASAL%' THEN '527' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'PO%' THEN '528' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'RECTAL%' THEN '529' end) as PREMED_ROUTE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%ATROPINE%' then 1 else 2 end) as ATROPINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DEMEROL%' then 1 else 2 end) as DEMEROL,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DEXMEDETOMIDINE%' then 1 else 2 end) as DEXMEDETOMIDINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DIAZEPAM%' then 1 else 2 end) as DIAZEPAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%FENTANYL%' then 1 else 2 end) as FENTANYL,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%GLYCOPYRROLATE%' then 1 else 2 end) as GLYCOPYRROLATE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%KETAMINE%' then 1 else 2 end) as KETAMINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%LORAZEPAM%' then 1 else 2 end) as LORAZEPAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%MIDAZOLAM%' then 1 else 2 end) as MIDAZOLAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%MORPHINE%' then 1 else 2 end) as MORPHINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%PENTOBARBITAL%' then 1 else 2 end) as PENTOBARBITAL --SELECT distinct (case when lower(DISP_NM) like '%premed%route%' then MEAS_VAL end)
from ENCS  
    LEFT JOIN ANESTHESIA_ENCOUNTER_LINK c ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY 
	join CDW.VISIT_STAY_INFO vsi on c.ANES_VISIT_KEY = vsi.VISIT_KEY
	join CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY

where lower(DISP_NM) like '%premed%'
-- and VSI.VSI_KEY = '31604862'
group by vsi.vsi_key
)

, ENC_SPO2 AS 
(SELECT *
   FROM 
       (SELECT ENCS.*
	           ,SPO2.*
			   ,EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT) ANESRECDATEDIFF
			   ,ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT)) SPO2_ORDER
		FROM   ENCS LEFT JOIN  SPO2  ON ENCS.OR_LOG_KEY = SPO2.SPO2_LOG_KEY and EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT) > 0 --> prior to start of procedure AND ROWNO = 1 AND SPORDER = 1
	    )ENC_SPO2_ROWNO
WHERE SPO2_ORDER = 1
)


, ENC_SPO2_O2SUPP AS 
(SELECT *
   FROM 
       (SELECT ENC_SPO2.*
	           ,O2SUPP.*
			   ,EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT) ANESO2DATEDIFF
			   ,ROW_NUMBER() OVER (PARTITION BY ENC_SPO2.OR_LOG_KEY ORDER BY EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT)) O2SUPP_ORDER
		FROM   ENC_SPO2 LEFT JOIN  O2SUPP  ON ENC_SPO2.OR_LOG_KEY = O2SUPP.O2SUPP_LOG_KEY and EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT) > 0 --> prior to start of procedure AND ROWNO = 1 AND SPORDER = 1
	    )ENC_SPO2_O2SUPP_ROWNO
WHERE O2SUPP_ORDER = 1
)


					
--SELECT LOG_ID,SPO2,O2SUPP,ANES_START_TM,PREMED_GIVEN,PREMED_ROUTE,ATROPINE,DEMEROL,DEXMEDETOMIDINE,DIAZEPAM,FENTANYL,GLYCOPYRROLATE,KETAMINE,LORAZEPAM,MIDAZOLAM,MORPHINE,PENTOBARBITAL

SELECT 
cast(ISNULL(LOG_ID,'') as integer) CaseNumber
,CAST(ISNULL(SPO2,'')AS NUMERIC(8,2)) PreopO2Sat
,COALESCE(O2SUPP,2) PreopOxygen
,ANES_START_TM PLocTransDT
,CAST(ISNULL(PREMED_GIVEN,2) AS INTEGER) PreopSed
,CAST((PREMED_ROUTE) AS INTEGER)  PreopSedRte
,CAST(ISNULL(ATROPINE,2) AS INTEGER) PreopSedDrugAtro
,CAST(ISNULL(DEMEROL,2) AS INTEGER) PreopSedDrugDem
,CAST(ISNULL(DEXMEDETOMIDINE,2) AS INTEGER) PreopSedDrugDex
,CAST(ISNULL(DIAZEPAM,2) AS INTEGER) PreopSedDrugDiaz
,CAST(ISNULL(FENTANYL,2) AS INTEGER) PreopSedDrugFent
,CAST(ISNULL(GLYCOPYRROLATE,2) AS INTEGER) PreopSedDrugGlyco
,CAST(ISNULL(KETAMINE,2) AS INTEGER) PreopSedDrugKet
,CAST(ISNULL(LORAZEPAM,2) AS INTEGER) PreopSedDrugLoraz
,CAST(ISNULL(MIDAZOLAM,2) AS INTEGER) PreopSedDrugMidaz
,CAST(ISNULL(MORPHINE,2) AS INTEGER) PreopSedDrugMorph
,CAST(ISNULL(PENTOBARBITAL,2) AS INTEGER) PreopSedDrugPent



FROM

(SELECT ENC_SPO2_O2SUPP.*,
       PREMEDS.*
FROM ENC_SPO2_O2SUPP LEFT JOIN PREMEDS ON PREMEDS.vsi_key = ENC_SPO2_O2SUPP.ANES_vsi_key
			       
) A

ORDER BY 1