WITH C3PO_DATA AS
(SELECT  
--CASEINFO        
		21 AS HOSPITALID, 
	    TO_CHAR(CT.PATIM,'MM-DD-YYYY') AS CATHDATE,
		CASE WHEN PHYS.DOPER = 1 THEN 1081
		     WHEN PHYS.DOPER = 2 THEN 1082
			 WHEN PHYS.DOPER = 3 THEN 1083
			 WHEN PHYS.DOPER = 4 THEN 1084
			 WHEN PHYS.DOPER = 121 THEN 1085
			 ELSE 0
			 END AS OPERATOR,
--CASECLINICALINFO		
		CASE WHEN DATE(NOW())-DATE(PT.PATBIRTH) < 30 THEN DATE(NOW())-DATE(PT.PATBIRTH) --DAYS
		     WHEN DATE(NOW())-DATE(PT.PATBIRTH) BETWEEN 30 AND 365 THEN (DATE(NOW())-DATE(PT.PATBIRTH))/30 --MONTHS
		     WHEN DATE(NOW())-DATE(PT.PATBIRTH) > 365 THEN (DATE(NOW())-DATE(PT.PATBIRTH))/365 --YEARS
         END AS PATIENTAGE,
		CASE WHEN DATE(NOW())-DATE(PT.PATBIRTH) < 30 THEN 0 --DAYS
		     WHEN DATE(NOW())-DATE(PT.PATBIRTH) BETWEEN 30 AND 365 THEN 1 --MONTHS
		     WHEN DATE(NOW())-DATE(PT.PATBIRTH) > 365 THEN 2 --YEARS
        END AS PATIENTAGETYPE,		
		CASE WHEN PATSEX = 1 THEN 2
		     WHEN PATSEX = 2 THEN 1 END AS PATIENTSEX,
		COALESCE(CAST(PD.WEIGHT AS NUMERIC(5,1)),0) PATIENTWEIGHT,
		COALESCE(CAST(PD.HEIGHT AS NUMERIC(5,1)),0) PATIENTHEIGHT,
		CAST(((PD.WEIGHT*PD.HEIGHT)/3600)^.5 AS NUMERIC(4,2)) PATIENTBSA,
		--CAST(PD.BSA AS NUMERIC(4,2)) AS PATIENTBSA,
		'' AS STSDIAGCODE, --NEED FROM CATH GROUP
		CASE WHEN DAYS_BETWEEN(CPOMRCP.CDATE, STUDY.STUDATE) <= 90 THEN 1 ELSE 0 END AS PREVCATHLAST90DIND,
        CASE WHEN DAYS_BETWEEN(CPOMRSP.SDATE, STUDY.STUDATE) <= 90 THEN 1 ELSE 0 END AS PREVSURGLAST90DIND,		
		CASE WHEN GENCOND.IP3100 = 1 THEN 1
			WHEN GENCOND.IP3105 = 1 THEN 1
			WHEN GENCOND.IP3110 = 1 THEN 1
			WHEN GENCOND.IP3115 = 1 THEN 1
			WHEN GENCOND.IP3120 = 1 THEN 1
			WHEN GENCOND.IP3125 = 1 THEN 1
			WHEN GENCOND.IP3130 = 1 THEN 1
			WHEN GENCOND.IP3135 = 1 THEN 1
			WHEN GENCOND.IP3140 = 1 THEN 1
			WHEN GENCOND.IP3145 = 1 THEN 1
			WHEN GENCOND.IP3150 = 1 THEN 1
			WHEN GENCOND.IP3155 = 1 THEN 1
			ELSE 0 END AS GENSYNDROMEIND,	
        CASE WHEN CPONCP IS NOT NULL THEN 1 ELSE 0 END AS NONCARDIACPROBIND, 
		COALESCE(CPONCP,'') NONCARDIACPROBVALUES, --NEED THIS MAPPING
--CASEPROCEDUREINFO		
        COALESCE(XRAYBSUM.FLTIME,'') FLUROTIME,		
	    COALESCE(XRAYBSUM.DOSE,'') TOTALDAP,
		COALESCE(TO_CHAR(COALESCE(ASR.SHTIME, CT.PATIM),'HH:MI'),'') SHEATHCATHINDATETIME,
		COALESCE(TO_CHAR(POCT.PREND,'HH:MI'),'') SHEATHCATHOUTDATETIME,		
        CASE WHEN IPPOEVNT.IP8130 = 1 THEN '1' ELSE '0' END AS BLOODTRANSFUSION,
--CASEEOCADMDISPOSITION		
		CASE WHEN APTVER2.DPRSTAT IN (1370,1371) THEN '1'
		     WHEN APTVER2.DPRSTAT IN (1372,1373,1374) THEN '0'
			 ELSE '' END ADMISSIONSOURCE,
		CASE WHEN APTVER2.PTSTAT in (4,7) THEN 'PCL01'
		     WHEN APTVER2.PTSTAT in (3,6) THEN 'PCL02'
			 WHEN APTVER2.PTSTAT IN (2,5) THEN 'PCL04'
			 ELSE '' END AS POSTCATHLOCATION, 
		''  ISUNPLANNEDADMISSION,
		CASE WHEN (EXTRACT(EPOCH FROM INPT_ENC.HOSPITAL_ADMIT_DATE - COALESCE(ASR.SHTIME, CT.PATIM))) /3600 BETWEEN -48 AND 0 THEN 1 ELSE 0 END AS ADMITGREATERTHAN48HRSPRIORTOCATH,		
		CASE WHEN (EXTRACT(EPOCH FROM INPT_ENC.HOSPITAL_DISCHARGE_DATE - POCT.PREND)) /3600 > 48 THEN 1 ELSE 0 END AS DISCHARGEGREATERTHAN48HRSPOSTCATH,
		CASE WHEN INPT_ENC.DISCHARGE_DISPOSITION = 'Expired' THEN 0 ELSE 1 END AS ISALIVEATDISCHARGE,     		
		CASE WHEN COALESCE(AE2.COMPL,0) > 0 THEN 1 ELSE 0 END AS DIDADVERSEEVENTOCCUR,
--HEMODYNAMICS			 
		CASE WHEN PREPCON.IP3245 = 1 THEN 1 ELSE 0 END AS SINGLEVENTRICLEPHYSIOLOGY, 	
		CASE WHEN HEMODYN.LVD >= 18 THEN 1 ELSE 0 END AS SVEDPGREATERTHANOREQUALTO18MMHG ,
		CASE WHEN HEMODYN.MVSAT < 60 AND PREPCON.IP3245 = 2 THEN 1 ELSE 0 END AS MVSATLESSTHAN60PERCENT,
        CASE WHEN HEMODYN.QPQS > 1.5 THEN 1 ELSE 0 END AS QPQSGREATERTHAN1POINT5,	
		CASE WHEN PREPCON.IP3245 = 2 AND HEMODYN.SASAT < 95 THEN 1 ELSE 0 END AS SYSSATLESSTHAN95PERCENT,
		CASE WHEN HEMODYN.MPAS <= 45 AND PREPCON.IP3245 = 2 THEN 1 ELSE 0 END AS PASYSGREATERTHANOREQUALTO45MMHG,
		CASE WHEN HEMODYN.PVR >3 THEN 1 ELSE 0 END AS  PVRGREATERTHAN3WU,	
		CASE WHEN PREPCON.IP3245 = 1 AND HEMODYN.SASAT < 78 THEN 1 ELSE 0 END AS SYSSATLESSTHAN78PERCENT,
        CASE WHEN HEMODYN.MPAM <= 17 AND PREPCON.IP3245 = 1 THEN 1 ELSE 0 END AS PAMEANLESSTHANOREQUALTO17MMHG,		
		CASE WHEN HEMODYN.MVSAT < 50 AND PREPCON.IP3245 = 1 THEN 1 ELSE 0 END AS MVSATLESSTHAN50PERCENT,
--MAJORADVERSEEVENT
		CASE WHEN IPPOEVNT.IP8000 = 1 THEN '9001' 
			WHEN IPPOEVNT.IP8010 = 1 THEN '9002' 
			WHEN IPPOEVNT.IP8015 = 1 THEN '9003' 
			WHEN IPPOEVNT.IP8020 = 1 THEN '9004' 
			WHEN IPPOEVNT.IP8025 = 1 THEN '9005' 
			WHEN IPPOEVNT.IP8030 = 1 THEN '9006' 
			WHEN IPPOEVNT.IP8035 = 1 THEN '9007' 
			WHEN IPPOEVNT.IP8040 = 1 THEN '9008' 
			WHEN IPPOEVNT.IP8045 = 1 THEN '9009' 
			WHEN IPPOEVNT.IP8050 = 1 THEN '9010' 
			WHEN IPPOEVNT.IP8055 = 1 THEN '9011' 
			WHEN IPPOEVNT.IP8070 = 1 THEN '9012' 
			WHEN IPPOEVNT.IP8075 = 1 THEN '9013' 
			WHEN IPPOEVNT.IP8080 = 1 THEN '9014' 
			WHEN IPPOEVNT.IP8085 = 1 THEN '9015' 
			WHEN IPPOEVNT.IP8090 = 1 THEN '9016' 
			WHEN IPPOEVNT.IP8140 = 1 THEN '9017' 
			WHEN IPPEVEN2.IP8160 = 1 OR IPPEVEN2.IP8165 = 1 OR IPPEVEN2.IP8170 = 1 THEN '9018' 
			WHEN IPPEVEN2.IP8175 = 1 THEN '9019' 
			WHEN DISCH.DSTATUS = 1 THEN '9020' 
			ELSE '' END AS MAJ_AECODE,
		CASE WHEN AE2.AESEV = 1 THEN 'AES01'
		     WHEN AE2.AESEV = 2 THEN 'AES02'
			 WHEN AE2.AESEV = 3 THEN 'AES03'
			 WHEN AE2.AESEV = 4 THEN 'AES04'
			 WHEN AE2.AESEV = 5 THEN 'AES05'
			 ELSE '' END AS MAJ_AESERIOUSNESS,
			 '' OTH_AECODE,
			 '' OTH_AESERIOUSNESS,
			 '' AENOTES,
			 '' REQUIREDRESOURCES
		FROM CDW_ODS..SENSIS_STUDY STUDY LEFT JOIN CDW_ODS..SENSIS_PHYS PHYS ON STUDY.REFNO = PHYS.REFNO AND PHYS.SEQNO = 1
		                        LEFT JOIN CDW_ODS..SENSIS_PATIENT PT ON PT.PATNO = STUDY.PATNO
								LEFT JOIN CDW_ODS..SENSIS_DISCH DISCH ON DISCH.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_PD PD ON PD.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_AE2 AE2 ON AE2.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_CT CT ON CT.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_GENCOND GENCOND ON GENCOND.REFNO = STUDY.REFNO
								--LEFT JOIN CDW_ODS..SENSIS_HISTB HISTB ON HISTB.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_XRAYBSUM XRAYBSUM ON XRAYBSUM.REFNO = STUDY.REFNO
                                LEFT JOIN (SELECT REFNO, SUM(DOSE) DAP FROM CDW_ODS..SENSIS_XRAYSUM GROUP BY REFNO) XRAYSUM ON XRAYSUM.REFNO = STUDY.REFNO
								LEFT JOIN (SELECT REFNO, MIN(SHTIME) SHTIME FROM CDW_ODS..SENSIS_ASR GROUP BY REFNO) ASR ON ASR.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_POCT POCT ON POCT.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_HEMODYN HEMODYN ON STUDY.REFNO = HEMODYN.REFNO
								LEFT JOIN CDW_ODS..SENSIS_PREPCON PREPCON ON STUDY.REFNO = PREPCON.REFNO
								LEFT JOIN CDW_ODS..SENSIS_APTVER2 APTVER2 ON APTVER2.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_IPPOEVNT IPPOEVNT ON IPPOEVNT.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_IPPEVEN2 IPPEVEN2 ON IPPEVEN2.REFNO = STUDY.REFNO
								LEFT JOIN (SELECT REFNO, GROUP_CONCAT(CPONCP,'|') CPONCP FROM
									          (SELECT DISTINCT REFNO, CASE WHEN CPONCP = 3451 THEN 'NCP01'
															     		   WHEN CPONCP IN (3452,3453) THEN 'NCP02'
																           WHEN CPONCP = 3457 THEN 'NCP03'
																           WHEN COALESCE(CPONCP,0) > 0 THEN 'NCP04'
																            ELSE NULL END CPONCP FROM CDW_ODS..SENSIS_CPONCP
												) CPO
												GROUP BY REFNO 
											) CPONCP ON CPONCP.REFNO = STUDY.REFNO
								LEFT JOIN CDW_ODS..SENSIS_CPOMRCP CPOMRCP ON STUDY.REFNO = CPOMRCP.REFNO AND CPOMRCP.SEQNO = 1
								LEFT JOIN CDW_ODS..SENSIS_CPOMRSP CPOMRSP ON STUDY.REFNO = CPOMRSP.REFNO AND CPOMRSP.SEQNO = 1
                                LEFT JOIN chop_analytics.CLINICAL.ENCOUNTER_INPATIENT INPT_ENC ON INPT_ENC.CSN = STUDY.ADMISSID
WHERE DATE(CT.PATIM) >= '2017-01-01'
 and PHYS.DOPER IN (1,2,3,4,121)
--LIMIT 10
 )
 
,XML AS

(SELECT  
'<BCHCPOR3DataImport>' HDR, 1 SORT UNION ALL

SELECT 
(ADMIN.XMLSERIALIZE(
   --   ADMIN.XMLELEMENT('BCHCPOR3DataImport',
        ADMIN.XMLELEMENT('Patient',
		 ADMIN.XMLCONCAT(
		  ADMIN.XMLCONCAT(
			ADMIN.XMLELEMENT('CaseInfo',
			    ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('HospitalID',HOSPITALID),
					ADMIN.XMLELEMENT('CathDate',CATHDATE),
					ADMIN.XMLELEMENT('Operator',OPERATOR)
				               )
				            ),
			ADMIN.XMLELEMENT('CaseClinicalInfo',
			    ADMIN.XMLCONCAT(
				  ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('PatientAge',PATIENTAGE),
					ADMIN.XMLELEMENT('PatientAgeType',PATIENTAGETYPE),
					ADMIN.XMLELEMENT('PatientSex',PatientSex),
					ADMIN.XMLELEMENT('PatientWeight',PatientWeight),
					ADMIN.XMLELEMENT('PatientHeight',PatientHeight)
					              ),
				  ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('PatientBSA',PatientBSA),
					ADMIN.XMLELEMENT('STSDiagCode',STSDiagCode),
					ADMIN.XMLELEMENT('PrevCathlast90dInd',PrevCathlast90dInd),
					ADMIN.XMLELEMENT('PrevSurglast90dInd',PrevSurglast90dInd),
					ADMIN.XMLELEMENT('GenSyndromeInd',GenSyndromeInd)
					              ),
                  ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('NonCardiacProbInd',NonCardiacProbInd),
					ADMIN.XMLELEMENT('NonCardiacProbValues',NONCARDIACPROBVALUES)
	                           )
			                     )
			                ),
			ADMIN.XMLELEMENT('CaseProcedureInfo',
			    ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('FluroTime',FluroTime),
					ADMIN.XMLELEMENT('TotalDap',TotalDap),
					ADMIN.XMLELEMENT('SheathCathInDateTime',SheathCathInDateTime),
                    ADMIN.XMLELEMENT('SheathCathOutDateTime',SheathCathOutDateTime),
					ADMIN.XMLELEMENT('BloodTransfusion',BloodTransfusion)					
						       )
			                ) ,
			ADMIN.XMLELEMENT('CaseEOCAdmDisposition',
			    ADMIN.XMLCONCAT(
				  ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('AdmissionSource',AdmissionSource),
					ADMIN.XMLELEMENT('PostCathLocation',PostCathLocation),
					ADMIN.XMLELEMENT('IsUnplannedAdmission',IsUnplannedAdmission)
					             ),
				  ADMIN.XMLCONCAT(
                    ADMIN.XMLELEMENT('AdmitGreaterThan48HrsPriorToCath',AdmitGreaterThan48HrsPriorToCath),
					ADMIN.XMLELEMENT('DischargeGreaterThan48HrsPostCath',DischargeGreaterThan48HrsPostCath),					
					ADMIN.XMLELEMENT('IsAliveAtDischarge',IsAliveAtDischarge)	
							     )
							   )
			                ) ,
			ADMIN.XMLELEMENT('Hemodynamics',
			    ADMIN.XMLCONCAT(
				  ADMIN.XMLCONCAT(
					ADMIN.XMLELEMENT('SingleVentriclePhysiology',SingleVentriclePhysiology),
					ADMIN.XMLELEMENT('SVEDPGreaterThanOrEqualTo18mmHg',SVEDPGreaterThanOrEqualTo18mmHg),
					ADMIN.XMLELEMENT('MVSatLessThan60Percent',MVSatLessThan60Percent),
					ADMIN.XMLELEMENT('QpQsGreaterThan1Point5',QpQsGreaterThan1Point5),					
					ADMIN.XMLELEMENT('SysSatLessThan95Percent',SysSatLessThan95Percent)
					             ),
				  ADMIN.XMLCONCAT(
                    ADMIN.XMLELEMENT('PASysGreaterThanOrEqualTo45mmHg',PASysGreaterThanOrEqualTo45mmHg),
					ADMIN.XMLELEMENT('PVRGreaterThan3WU',PVRGreaterThan3WU),	
                    ADMIN.XMLELEMENT('SysSatLessThan78Percent',SysSatLessThan78Percent),
					ADMIN.XMLELEMENT('PAMeanLessThanOrEqualTo17mmHg',PAMeanLessThanOrEqualTo17mmHg),						
					ADMIN.XMLELEMENT('MVSatLessThan50Percent',MVSatLessThan50Percent)	
							     )
							   )
			                ) 							
					      ),
				  ADMIN.XMLELEMENT('AdverseEvents',
				   ADMIN.XMLCONCAT(
				  	ADMIN.XMLELEMENT('AeCode',MAJ_AECODE),
				  	ADMIN.XMLELEMENT('AeSeriousness',MAJ_AESERIOUSNESS)
					              )
								  )
							,
				  ADMIN.XMLELEMENT('OtherAdverseEvent',
				   ADMIN.XMLCONCAT(
				  	ADMIN.XMLELEMENT('AeCode',OTH_AECODE),
				  	ADMIN.XMLELEMENT('AeSeriousness',OTH_AESERIOUSNESS)
					              )
								  )
						    ,
				  ADMIN.XMLELEMENT('RequiredResources',REQUIREDRESOURCES)
								  
	                   )      
	                 )
				--	) 
				  )
  ) DATA, 2             
FROM C3PO_DATA		


union all 

select '</BCHCPOR3DataImport>', 3

)

SELECT HDR 
FROM XML
ORDER BY SORT