select distinct  -- the source table "duplicates" much of this data over the worktags
    payroll_result_employee_reference_employee_id as employee_id,
    national_id_data_national_id_data_id as national_id,
    to_timestamp(payroll_result_period_start_date, 'yyyy-mm-dd') as period_start_date,
    to_timestamp(payroll_result_period_end_date, 'yyyy-mm-dd') as period_end_date,
    to_timestamp(payroll_result_subperiod_start_date, 'yyyy-mm-dd') as payroll_result_subperiod_start_date,
    to_timestamp(payroll_result_subperiod_end_date, 'yyyy-mm-dd') as payroll_result_subperiod_end_date,
    to_timestamp(payroll_result_payment_date, 'yyyy-mm-dd') as payment_date,
    to_timestamp(replace(substr(get_payroll_support_orders.payroll_result_result_completed_date_time,1,23),'T',' '),'yyyy-mm-dd hh24:mi:ss.us') - cast(strright(get_payroll_support_orders.payroll_result_result_completed_date_time,5) as time) AS result_completed_date_time,
    employee_name_data_name_data_first_name as first_name,
    employee_name_data_name_data_middle_name as middle_name,
    employee_name_data_name_data_primary as last_name,
    coalesce(cast(name_data_is_legal as int), -2) as name_is_legal_ind,
    coalesce(cast(name_data_is_preferred as int), -2) as name_is_preferred_ind,
    to_timestamp(name_data_effective_date, 'yyyy-mm-dd') as name_effective_date,
    to_timestamp(replace(substr(name_data_last_modified,1,23),'T',' '),'yyyy-mm-dd hh24:mi:ss.us') - cast(strright(name_data_last_modified,5) as time) as name_last_modified_date,
    pay_component_reference_deduction_code as deduction_code,
    cast(payroll_result_payroll_result_data_result_line_amount as numeric(30,2)) as payroll_result_line_amount,
    payroll_worktag_data_withholding_order_worktag_reference_withholding_order_case_id as withholding_order_id,
    payroll_worktag_data_withholding_order_worktag_reference_wid as withholding_order_wid,
    payroll_result_data_withholding_order_data_case_number as case_number,
    payroll_result_data_withholding_order_data_withholding_order_type as withholding_order_type,
    to_timestamp(payroll_result_data_withholding_order_data_order_date, 'yyyy-mm-dd') as withholding_order_date,
    to_timestamp(replace(substr(payroll_result_data_withholding_order_data_received_date,1,19),'T',' '),'yyyy-mm-dd hh24:mi:ss') - cast(strright(payroll_result_data_withholding_order_data_received_date,5) as time) as withholding_received_date,
    to_timestamp(payroll_result_data_withholding_order_data_begin_date, 'yyyy-mm-dd') as withholding_begin_date,
    null as withholding_end_date,
    payroll_result_data_withholding_order_data_order_status as withholding_order_status,
    payroll_result_data_withholding_order_data_order_priority as withholding_order_priority,
    cast(payroll_result_data_withholding_order_data_total_debt_amount as numeric(30,2)) as withholding_total_debt_amount,
    cast(payroll_result_data_withholding_order_data_pay_period_amount as numeric(30,2)) as withholding_pay_period_amount,
    cast({{
        dbt_utils.surrogate_key([
            'employee_id',
            'national_id',
            'period_start_date',
            'period_end_date',
            'payroll_result_subperiod_start_date',
            'payroll_result_subperiod_end_date',
            'payment_date',
            'result_completed_date_time',
            'first_name',
            'middle_name',
            'last_name',
            'name_is_legal_ind',
            'name_is_preferred_ind',
            'name_effective_date',
            'name_last_modified_date',
            'deduction_code',
            'payroll_result_line_amount',
            'withholding_order_id',
            'withholding_order_wid',
            'case_number',
            'withholding_order_type',
            'withholding_order_date',
            'withholding_received_date',
            'withholding_begin_date',
            'withholding_end_date',
            'withholding_order_status',
            'withholding_order_priority',
            'withholding_total_debt_amount',
            'withholding_pay_period_amount'
        ])
    }} as varchar(100)) as md5,
    current_timestamp as create_dt,
    'WORKDAY' as create_by,
    current_timestamp as upd_dt,
    'WORKDAY' as upd_by
from
    {{ source('workday_ods', 'get_payroll_support_orders') }} as get_payroll_support_orders
where
    1=1
    and get_payroll_support_orders.payroll_result_result_completed_date_time is not null
