with level_1_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.organization_type_id,
        supervisory_department.organization_subtype_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_toplevel_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_wid as supervisory_department_level1_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level1_id,
        supervisory_department.supervisory_department_name as supervisory_department_level1_name,
        null as supervisory_department_level2_wid,
        null as supervisory_department_level2_id,
        null as supervisory_department_level2_name,
        null as supervisory_department_level3_wid,
        null as supervisory_department_level3_id,
        null as supervisory_department_level3_name,
        null as supervisory_department_level4_wid,
        null as supervisory_department_level4_id,
        null as supervisory_department_level4_name,
        null as supervisory_department_level5_wid,
        null as supervisory_department_level5_id,
        null as supervisory_department_level5_name,
        null as supervisory_department_level6_wid,
        null as supervisory_department_level6_id,
        null as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    where
        (supervisory_department.organization_type_id = 'Supervisory')
        and (supervisory_department.organization_type_id = 'Supervisory'
            and supervisory_department.supervisory_department_wid = supervisory_department.supervisory_department_toplevel_wid
        )
),
level_2_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_1_hierarchy.supervisory_department_level1_wid,
        level_1_hierarchy.supervisory_department_level1_id,
        level_1_hierarchy.supervisory_department_level1_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level2_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level2_id,
        supervisory_department.supervisory_department_name as supervisory_department_level2_name,
        null as supervisory_department_level3_wid,
        null as supervisory_department_level3_id,
        null as supervisory_department_level3_name,
        null as supervisory_department_level4_wid,
        null as supervisory_department_level4_id,
        null as supervisory_department_level4_name,
        null as supervisory_department_level5_wid,
        null as supervisory_department_level5_id,
        null as supervisory_department_level5_name,
        null as supervisory_department_level6_wid,
        null as supervisory_department_level6_id,
        null as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_1_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_1_hierarchy.supervisory_department_level1_wid
),
level_3_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_2_hierarchy.supervisory_department_level1_wid,
        level_2_hierarchy.supervisory_department_level1_id,
        level_2_hierarchy.supervisory_department_level1_name,
        level_2_hierarchy.supervisory_department_level2_wid,
        level_2_hierarchy.supervisory_department_level2_id,
        level_2_hierarchy.supervisory_department_level2_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level3_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level3_id,
        supervisory_department.supervisory_department_name as supervisory_department_level3_name,
        null as supervisory_department_level4_wid,
        null as supervisory_department_level4_id,
        null as supervisory_department_level4_name,
        null as supervisory_department_level5_wid,
        null as supervisory_department_level5_id,
        null as supervisory_department_level5_name,
        null as supervisory_department_level6_wid,
        null as supervisory_department_level6_id,
        null as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_2_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_2_hierarchy.supervisory_department_level2_wid
),
level_4_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_3_hierarchy.supervisory_department_level1_wid,
        level_3_hierarchy.supervisory_department_level1_id,
        level_3_hierarchy.supervisory_department_level1_name,
        level_3_hierarchy.supervisory_department_level2_wid,
        level_3_hierarchy.supervisory_department_level2_id,
        level_3_hierarchy.supervisory_department_level2_name,
        level_3_hierarchy.supervisory_department_level3_wid,
        level_3_hierarchy.supervisory_department_level3_id,
        level_3_hierarchy.supervisory_department_level3_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level4_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level4_id,
        supervisory_department.supervisory_department_name as supervisory_department_level4_name,
        null as supervisory_department_level5_wid,
        null as supervisory_department_level5_id,
        null as supervisory_department_level5_name,
        null as supervisory_department_level6_wid,
        null as supervisory_department_level6_id,
        null as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_3_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_3_hierarchy.supervisory_department_level3_wid
),
level_5_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_4_hierarchy.supervisory_department_level1_wid,
        level_4_hierarchy.supervisory_department_level1_id,
        level_4_hierarchy.supervisory_department_level1_name,
        level_4_hierarchy.supervisory_department_level2_wid,
        level_4_hierarchy.supervisory_department_level2_id,
        level_4_hierarchy.supervisory_department_level2_name,
        level_4_hierarchy.supervisory_department_level3_wid,
        level_4_hierarchy.supervisory_department_level3_id,
        level_4_hierarchy.supervisory_department_level3_name,
        level_4_hierarchy.supervisory_department_level4_wid,
        level_4_hierarchy.supervisory_department_level4_id,
        level_4_hierarchy.supervisory_department_level4_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level5_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level5_id,
        supervisory_department.supervisory_department_name as supervisory_department_level5_name,
        null as supervisory_department_level6_wid,
        null as supervisory_department_level6_id,
        null as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_4_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_4_hierarchy.supervisory_department_level4_wid
),
level_6_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_5_hierarchy.supervisory_department_level1_wid,
        level_5_hierarchy.supervisory_department_level1_id,
        level_5_hierarchy.supervisory_department_level1_name,
        level_5_hierarchy.supervisory_department_level2_wid,
        level_5_hierarchy.supervisory_department_level2_id,
        level_5_hierarchy.supervisory_department_level2_name,
        level_5_hierarchy.supervisory_department_level3_wid,
        level_5_hierarchy.supervisory_department_level3_id,
        level_5_hierarchy.supervisory_department_level3_name,
        level_5_hierarchy.supervisory_department_level4_wid,
        level_5_hierarchy.supervisory_department_level4_id,
        level_5_hierarchy.supervisory_department_level4_name,
        level_5_hierarchy.supervisory_department_level5_wid,
        level_5_hierarchy.supervisory_department_level5_id,
        level_5_hierarchy.supervisory_department_level5_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level6_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level6_id,
        supervisory_department.supervisory_department_name as supervisory_department_level6_name,
        null as supervisory_department_level7_wid,
        null as supervisory_department_level7_id,
        null as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_5_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_5_hierarchy.supervisory_department_level5_wid
),
level_7_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_6_hierarchy.supervisory_department_level1_wid,
        level_6_hierarchy.supervisory_department_level1_id,
        level_6_hierarchy.supervisory_department_level1_name,
        level_6_hierarchy.supervisory_department_level2_wid,
        level_6_hierarchy.supervisory_department_level2_id,
        level_6_hierarchy.supervisory_department_level2_name,
        level_6_hierarchy.supervisory_department_level3_wid,
        level_6_hierarchy.supervisory_department_level3_id,
        level_6_hierarchy.supervisory_department_level3_name,
        level_6_hierarchy.supervisory_department_level4_wid,
        level_6_hierarchy.supervisory_department_level4_id,
        level_6_hierarchy.supervisory_department_level4_name,
        level_6_hierarchy.supervisory_department_level5_wid,
        level_6_hierarchy.supervisory_department_level5_id,
        level_6_hierarchy.supervisory_department_level5_name,
        level_6_hierarchy.supervisory_department_level6_wid,
        level_6_hierarchy.supervisory_department_level6_id,
        level_6_hierarchy.supervisory_department_level6_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level7_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level7_id,
        supervisory_department.supervisory_department_name as supervisory_department_level7_name,
        null as supervisory_department_level8_wid,
        null as supervisory_department_level8_id,
        null as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_6_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_6_hierarchy.supervisory_department_level6_wid
),
level_8_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_7_hierarchy.supervisory_department_level1_wid,
        level_7_hierarchy.supervisory_department_level1_id,
        level_7_hierarchy.supervisory_department_level1_name,
        level_7_hierarchy.supervisory_department_level2_wid,
        level_7_hierarchy.supervisory_department_level2_id,
        level_7_hierarchy.supervisory_department_level2_name,
        level_7_hierarchy.supervisory_department_level3_wid,
        level_7_hierarchy.supervisory_department_level3_id,
        level_7_hierarchy.supervisory_department_level3_name,
        level_7_hierarchy.supervisory_department_level4_wid,
        level_7_hierarchy.supervisory_department_level4_id,
        level_7_hierarchy.supervisory_department_level4_name,
        level_7_hierarchy.supervisory_department_level5_wid,
        level_7_hierarchy.supervisory_department_level5_id,
        level_7_hierarchy.supervisory_department_level5_name,
        level_7_hierarchy.supervisory_department_level6_wid,
        level_7_hierarchy.supervisory_department_level6_id,
        level_7_hierarchy.supervisory_department_level6_name,
        level_7_hierarchy.supervisory_department_level7_wid,
        level_7_hierarchy.supervisory_department_level7_id,
        level_7_hierarchy.supervisory_department_level7_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level8_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level8_id,
        supervisory_department.supervisory_department_name as supervisory_department_level8_name,
        null as supervisory_department_level9_wid,
        null as supervisory_department_level9_id,
        null as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_7_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_7_hierarchy.supervisory_department_level7_wid
),
level_9_hierarchy as (
    select distinct
        supervisory_department.supervisory_department_wid as supervisory_department_wid,
        supervisory_department.supervisory_department_id as supervisory_department_id,
        supervisory_department.supervisory_department_name as supervisory_department_name,
        supervisory_department.supervisory_department_parent_id,
        supervisory_department.supervisory_department_parent_wid,
        supervisory_department.supervisory_department_toplevel_id,
        supervisory_department.supervisory_department_toplevel_wid,
        level_8_hierarchy.supervisory_department_level1_wid,
        level_8_hierarchy.supervisory_department_level1_id,
        level_8_hierarchy.supervisory_department_level1_name,
        level_8_hierarchy.supervisory_department_level2_wid,
        level_8_hierarchy.supervisory_department_level2_id,
        level_8_hierarchy.supervisory_department_level2_name,
        level_8_hierarchy.supervisory_department_level3_wid,
        level_8_hierarchy.supervisory_department_level3_id,
        level_8_hierarchy.supervisory_department_level3_name,
        level_8_hierarchy.supervisory_department_level4_wid,
        level_8_hierarchy.supervisory_department_level4_id,
        level_8_hierarchy.supervisory_department_level4_name,
        level_8_hierarchy.supervisory_department_level5_wid,
        level_8_hierarchy.supervisory_department_level5_id,
        level_8_hierarchy.supervisory_department_level5_name,
        level_8_hierarchy.supervisory_department_level6_wid,
        level_8_hierarchy.supervisory_department_level6_id,
        level_8_hierarchy.supervisory_department_level6_name,
        level_8_hierarchy.supervisory_department_level7_wid,
        level_8_hierarchy.supervisory_department_level7_id,
        level_8_hierarchy.supervisory_department_level7_name,
        level_8_hierarchy.supervisory_department_level8_wid,
        level_8_hierarchy.supervisory_department_level8_id,
        level_8_hierarchy.supervisory_department_level8_name,
        supervisory_department.supervisory_department_wid as supervisory_department_level9_wid,
        supervisory_department.supervisory_department_id as supervisory_department_level9_id,
        supervisory_department.supervisory_department_name as supervisory_department_level9_name
    from
        {{ref('supervisory_department')}} as supervisory_department
    inner join
        level_8_hierarchy
            on supervisory_department.supervisory_department_parent_wid = level_8_hierarchy.supervisory_department_level8_wid
),
finaloutput as (
    select distinct
        level_1_hierarchy.supervisory_department_wid,
        level_1_hierarchy.supervisory_department_id,
        level_1_hierarchy.supervisory_department_name,
        level_1_hierarchy.supervisory_department_parent_id,
        level_1_hierarchy.supervisory_department_parent_wid,
        level_1_hierarchy.supervisory_department_toplevel_id,
        level_1_hierarchy.supervisory_department_toplevel_wid,
        level_1_hierarchy.supervisory_department_level1_wid,
        level_1_hierarchy.supervisory_department_level1_id,
        level_1_hierarchy.supervisory_department_level1_name,
        level_1_hierarchy.supervisory_department_level2_wid,
        level_1_hierarchy.supervisory_department_level2_id,
        level_1_hierarchy.supervisory_department_level2_name,
        level_1_hierarchy.supervisory_department_level3_wid,
        level_1_hierarchy.supervisory_department_level3_id,
        level_1_hierarchy.supervisory_department_level3_name,
        level_1_hierarchy.supervisory_department_level4_wid,
        level_1_hierarchy.supervisory_department_level4_id,
        level_1_hierarchy.supervisory_department_level4_name,
        level_1_hierarchy.supervisory_department_level5_wid,
        level_1_hierarchy.supervisory_department_level5_id,
        level_1_hierarchy.supervisory_department_level5_name,
        level_1_hierarchy.supervisory_department_level6_wid,
        level_1_hierarchy.supervisory_department_level6_id,
        level_1_hierarchy.supervisory_department_level6_name,
        level_1_hierarchy.supervisory_department_level7_wid,
        level_1_hierarchy.supervisory_department_level7_id,
        level_1_hierarchy.supervisory_department_level7_name,
        level_1_hierarchy.supervisory_department_level8_wid,
        level_1_hierarchy.supervisory_department_level8_id,
        level_1_hierarchy.supervisory_department_level8_name,
        level_1_hierarchy.supervisory_department_level9_wid,
        level_1_hierarchy.supervisory_department_level9_id,
        level_1_hierarchy.supervisory_department_level9_name
    from
        level_1_hierarchy
    union
    select distinct
        level_2_hierarchy.supervisory_department_wid,
        level_2_hierarchy.supervisory_department_id,
        level_2_hierarchy.supervisory_department_name,
        level_2_hierarchy.supervisory_department_parent_id,
        level_2_hierarchy.supervisory_department_parent_wid,
        level_2_hierarchy.supervisory_department_toplevel_id,
        level_2_hierarchy.supervisory_department_toplevel_wid,
        level_2_hierarchy.supervisory_department_level1_wid,
        level_2_hierarchy.supervisory_department_level1_id,
        level_2_hierarchy.supervisory_department_level1_name,
        level_2_hierarchy.supervisory_department_level2_wid,
        level_2_hierarchy.supervisory_department_level2_id,
        level_2_hierarchy.supervisory_department_level2_name,
        level_2_hierarchy.supervisory_department_level3_wid,
        level_2_hierarchy.supervisory_department_level3_id,
        level_2_hierarchy.supervisory_department_level3_name,
        level_2_hierarchy.supervisory_department_level4_wid,
        level_2_hierarchy.supervisory_department_level4_id,
        level_2_hierarchy.supervisory_department_level4_name,
        level_2_hierarchy.supervisory_department_level5_wid,
        level_2_hierarchy.supervisory_department_level5_id,
        level_2_hierarchy.supervisory_department_level5_name,
        level_2_hierarchy.supervisory_department_level6_wid,
        level_2_hierarchy.supervisory_department_level6_id,
        level_2_hierarchy.supervisory_department_level6_name,
        level_2_hierarchy.supervisory_department_level7_wid,
        level_2_hierarchy.supervisory_department_level7_id,
        level_2_hierarchy.supervisory_department_level7_name,
        level_2_hierarchy.supervisory_department_level8_wid,
        level_2_hierarchy.supervisory_department_level8_id,
        level_2_hierarchy.supervisory_department_level8_name,
        level_2_hierarchy.supervisory_department_level9_wid,
        level_2_hierarchy.supervisory_department_level9_id,
        level_2_hierarchy.supervisory_department_level9_name
    from
        level_2_hierarchy
    union
    select
        level_3_hierarchy.supervisory_department_wid,
        level_3_hierarchy.supervisory_department_id,
        level_3_hierarchy.supervisory_department_name,
        level_3_hierarchy.supervisory_department_parent_id,
        level_3_hierarchy.supervisory_department_parent_wid,
        level_3_hierarchy.supervisory_department_toplevel_id,
        level_3_hierarchy.supervisory_department_toplevel_wid,
        level_3_hierarchy.supervisory_department_level1_wid,
        level_3_hierarchy.supervisory_department_level1_id,
        level_3_hierarchy.supervisory_department_level1_name,
        level_3_hierarchy.supervisory_department_level2_wid,
        level_3_hierarchy.supervisory_department_level2_id,
        level_3_hierarchy.supervisory_department_level2_name,
        level_3_hierarchy.supervisory_department_level3_wid,
        level_3_hierarchy.supervisory_department_level3_id,
        level_3_hierarchy.supervisory_department_level3_name,
        level_3_hierarchy.supervisory_department_level4_wid,
        level_3_hierarchy.supervisory_department_level4_id,
        level_3_hierarchy.supervisory_department_level4_name,
        level_3_hierarchy.supervisory_department_level5_wid,
        level_3_hierarchy.supervisory_department_level5_id,
        level_3_hierarchy.supervisory_department_level5_name,
        level_3_hierarchy.supervisory_department_level6_wid,
        level_3_hierarchy.supervisory_department_level6_id,
        level_3_hierarchy.supervisory_department_level6_name,
        level_3_hierarchy.supervisory_department_level7_wid,
        level_3_hierarchy.supervisory_department_level7_id,
        level_3_hierarchy.supervisory_department_level7_name,
        level_3_hierarchy.supervisory_department_level8_wid,
        level_3_hierarchy.supervisory_department_level8_id,
        level_3_hierarchy.supervisory_department_level8_name,
        level_3_hierarchy.supervisory_department_level9_wid,
        level_3_hierarchy.supervisory_department_level9_id,
        level_3_hierarchy.supervisory_department_level9_name
    from
        level_3_hierarchy
    union
    select
        level_4_hierarchy.supervisory_department_wid,
        level_4_hierarchy.supervisory_department_id,
        level_4_hierarchy.supervisory_department_name,
        level_4_hierarchy.supervisory_department_parent_id,
        level_4_hierarchy.supervisory_department_parent_wid,
        level_4_hierarchy.supervisory_department_toplevel_id,
        level_4_hierarchy.supervisory_department_toplevel_wid,
        level_4_hierarchy.supervisory_department_level1_wid,
        level_4_hierarchy.supervisory_department_level1_id,
        level_4_hierarchy.supervisory_department_level1_name,
        level_4_hierarchy.supervisory_department_level2_wid,
        level_4_hierarchy.supervisory_department_level2_id,
        level_4_hierarchy.supervisory_department_level2_name,
        level_4_hierarchy.supervisory_department_level3_wid,
        level_4_hierarchy.supervisory_department_level3_id,
        level_4_hierarchy.supervisory_department_level3_name,
        level_4_hierarchy.supervisory_department_level4_wid,
        level_4_hierarchy.supervisory_department_level4_id,
        level_4_hierarchy.supervisory_department_level4_name,
        level_4_hierarchy.supervisory_department_level5_wid,
        level_4_hierarchy.supervisory_department_level5_id,
        level_4_hierarchy.supervisory_department_level5_name,
        level_4_hierarchy.supervisory_department_level6_wid,
        level_4_hierarchy.supervisory_department_level6_id,
        level_4_hierarchy.supervisory_department_level6_name,
        level_4_hierarchy.supervisory_department_level7_wid,
        level_4_hierarchy.supervisory_department_level7_id,
        level_4_hierarchy.supervisory_department_level7_name,
        level_4_hierarchy.supervisory_department_level8_wid,
        level_4_hierarchy.supervisory_department_level8_id,
        level_4_hierarchy.supervisory_department_level8_name,
        level_4_hierarchy.supervisory_department_level9_wid,
        level_4_hierarchy.supervisory_department_level9_id,
        level_4_hierarchy.supervisory_department_level9_name
    from
        level_4_hierarchy
    union
    select
        level_5_hierarchy.supervisory_department_wid,
        level_5_hierarchy.supervisory_department_id,
        level_5_hierarchy.supervisory_department_name,
        level_5_hierarchy.supervisory_department_parent_id,
        level_5_hierarchy.supervisory_department_parent_wid,
        level_5_hierarchy.supervisory_department_toplevel_id,
        level_5_hierarchy.supervisory_department_toplevel_wid,
        level_5_hierarchy.supervisory_department_level1_wid,
        level_5_hierarchy.supervisory_department_level1_id,
        level_5_hierarchy.supervisory_department_level1_name,
        level_5_hierarchy.supervisory_department_level2_wid,
        level_5_hierarchy.supervisory_department_level2_id,
        level_5_hierarchy.supervisory_department_level2_name,
        level_5_hierarchy.supervisory_department_level3_wid,
        level_5_hierarchy.supervisory_department_level3_id,
        level_5_hierarchy.supervisory_department_level3_name,
        level_5_hierarchy.supervisory_department_level4_wid,
        level_5_hierarchy.supervisory_department_level4_id,
        level_5_hierarchy.supervisory_department_level4_name,
        level_5_hierarchy.supervisory_department_level5_wid,
        level_5_hierarchy.supervisory_department_level5_id,
        level_5_hierarchy.supervisory_department_level5_name,
        level_5_hierarchy.supervisory_department_level6_wid,
        level_5_hierarchy.supervisory_department_level6_id,
        level_5_hierarchy.supervisory_department_level6_name,
        level_5_hierarchy.supervisory_department_level7_wid,
        level_5_hierarchy.supervisory_department_level7_id,
        level_5_hierarchy.supervisory_department_level7_name,
        level_5_hierarchy.supervisory_department_level8_wid,
        level_5_hierarchy.supervisory_department_level8_id,
        level_5_hierarchy.supervisory_department_level8_name,
        level_5_hierarchy.supervisory_department_level9_wid,
        level_5_hierarchy.supervisory_department_level9_id,
        level_5_hierarchy.supervisory_department_level9_name
    from
        level_5_hierarchy
    union
    select
        level_6_hierarchy.supervisory_department_wid,
        level_6_hierarchy.supervisory_department_id,
        level_6_hierarchy.supervisory_department_name,
        level_6_hierarchy.supervisory_department_parent_id,
        level_6_hierarchy.supervisory_department_parent_wid,
        level_6_hierarchy.supervisory_department_toplevel_id,
        level_6_hierarchy.supervisory_department_toplevel_wid,
        level_6_hierarchy.supervisory_department_level1_wid,
        level_6_hierarchy.supervisory_department_level1_id,
        level_6_hierarchy.supervisory_department_level1_name,
        level_6_hierarchy.supervisory_department_level2_wid,
        level_6_hierarchy.supervisory_department_level2_id,
        level_6_hierarchy.supervisory_department_level2_name,
        level_6_hierarchy.supervisory_department_level3_wid,
        level_6_hierarchy.supervisory_department_level3_id,
        level_6_hierarchy.supervisory_department_level3_name,
        level_6_hierarchy.supervisory_department_level4_wid,
        level_6_hierarchy.supervisory_department_level4_id,
        level_6_hierarchy.supervisory_department_level4_name,
        level_6_hierarchy.supervisory_department_level5_wid,
        level_6_hierarchy.supervisory_department_level5_id,
        level_6_hierarchy.supervisory_department_level5_name,
        level_6_hierarchy.supervisory_department_level6_wid,
        level_6_hierarchy.supervisory_department_level6_id,
        level_6_hierarchy.supervisory_department_level6_name,
        level_6_hierarchy.supervisory_department_level7_wid,
        level_6_hierarchy.supervisory_department_level7_id,
        level_6_hierarchy.supervisory_department_level7_name,
        level_6_hierarchy.supervisory_department_level8_wid,
        level_6_hierarchy.supervisory_department_level8_id,
        level_6_hierarchy.supervisory_department_level8_name,
        level_6_hierarchy.supervisory_department_level9_wid,
        level_6_hierarchy.supervisory_department_level9_id,
        level_6_hierarchy.supervisory_department_level9_name
    from
        level_6_hierarchy
    union
    select
        level_7_hierarchy.supervisory_department_wid,
        level_7_hierarchy.supervisory_department_id,
        level_7_hierarchy.supervisory_department_name,
        level_7_hierarchy.supervisory_department_parent_id,
        level_7_hierarchy.supervisory_department_parent_wid,
        level_7_hierarchy.supervisory_department_toplevel_id,
        level_7_hierarchy.supervisory_department_toplevel_wid,
        level_7_hierarchy.supervisory_department_level1_wid,
        level_7_hierarchy.supervisory_department_level1_id,
        level_7_hierarchy.supervisory_department_level1_name,
        level_7_hierarchy.supervisory_department_level2_wid,
        level_7_hierarchy.supervisory_department_level2_id,
        level_7_hierarchy.supervisory_department_level2_name,
        level_7_hierarchy.supervisory_department_level3_wid,
        level_7_hierarchy.supervisory_department_level3_id,
        level_7_hierarchy.supervisory_department_level3_name,
        level_7_hierarchy.supervisory_department_level4_wid,
        level_7_hierarchy.supervisory_department_level4_id,
        level_7_hierarchy.supervisory_department_level4_name,
        level_7_hierarchy.supervisory_department_level5_wid,
        level_7_hierarchy.supervisory_department_level5_id,
        level_7_hierarchy.supervisory_department_level5_name,
        level_7_hierarchy.supervisory_department_level6_wid,
        level_7_hierarchy.supervisory_department_level6_id,
        level_7_hierarchy.supervisory_department_level6_name,
        level_7_hierarchy.supervisory_department_level7_wid,
        level_7_hierarchy.supervisory_department_level7_id,
        level_7_hierarchy.supervisory_department_level7_name,
        level_7_hierarchy.supervisory_department_level8_wid,
        level_7_hierarchy.supervisory_department_level8_id,
        level_7_hierarchy.supervisory_department_level8_name,
        level_7_hierarchy.supervisory_department_level9_wid,
        level_7_hierarchy.supervisory_department_level9_id,
        level_7_hierarchy.supervisory_department_level9_name
    from
        level_7_hierarchy
    union
    select
        level_8_hierarchy.supervisory_department_wid,
        level_8_hierarchy.supervisory_department_id,
        level_8_hierarchy.supervisory_department_name,
        level_8_hierarchy.supervisory_department_parent_id,
        level_8_hierarchy.supervisory_department_parent_wid,
        level_8_hierarchy.supervisory_department_toplevel_id,
        level_8_hierarchy.supervisory_department_toplevel_wid,
        level_8_hierarchy.supervisory_department_level1_wid,
        level_8_hierarchy.supervisory_department_level1_id,
        level_8_hierarchy.supervisory_department_level1_name,
        level_8_hierarchy.supervisory_department_level2_wid,
        level_8_hierarchy.supervisory_department_level2_id,
        level_8_hierarchy.supervisory_department_level2_name,
        level_8_hierarchy.supervisory_department_level3_wid,
        level_8_hierarchy.supervisory_department_level3_id,
        level_8_hierarchy.supervisory_department_level3_name,
        level_8_hierarchy.supervisory_department_level4_wid,
        level_8_hierarchy.supervisory_department_level4_id,
        level_8_hierarchy.supervisory_department_level4_name,
        level_8_hierarchy.supervisory_department_level5_wid,
        level_8_hierarchy.supervisory_department_level5_id,
        level_8_hierarchy.supervisory_department_level5_name,
        level_8_hierarchy.supervisory_department_level6_wid,
        level_8_hierarchy.supervisory_department_level6_id,
        level_8_hierarchy.supervisory_department_level6_name,
        level_8_hierarchy.supervisory_department_level7_wid,
        level_8_hierarchy.supervisory_department_level7_id,
        level_8_hierarchy.supervisory_department_level7_name,
        level_8_hierarchy.supervisory_department_level8_wid,
        level_8_hierarchy.supervisory_department_level8_id,
        level_8_hierarchy.supervisory_department_level8_name,
        level_8_hierarchy.supervisory_department_level9_wid,
        level_8_hierarchy.supervisory_department_level9_id,
        level_8_hierarchy.supervisory_department_level9_name
    from
        level_8_hierarchy
    union
    select
        level_9_hierarchy.supervisory_department_wid,
        level_9_hierarchy.supervisory_department_id,
        level_9_hierarchy.supervisory_department_name,
        level_9_hierarchy.supervisory_department_parent_id,
        level_9_hierarchy.supervisory_department_parent_wid,
        level_9_hierarchy.supervisory_department_toplevel_id,
        level_9_hierarchy.supervisory_department_toplevel_wid,
        level_9_hierarchy.supervisory_department_level1_wid,
        level_9_hierarchy.supervisory_department_level1_id,
        level_9_hierarchy.supervisory_department_level1_name,
        level_9_hierarchy.supervisory_department_level2_wid,
        level_9_hierarchy.supervisory_department_level2_id,
        level_9_hierarchy.supervisory_department_level2_name,
        level_9_hierarchy.supervisory_department_level3_wid,
        level_9_hierarchy.supervisory_department_level3_id,
        level_9_hierarchy.supervisory_department_level3_name,
        level_9_hierarchy.supervisory_department_level4_wid,
        level_9_hierarchy.supervisory_department_level4_id,
        level_9_hierarchy.supervisory_department_level4_name,
        level_9_hierarchy.supervisory_department_level5_wid,
        level_9_hierarchy.supervisory_department_level5_id,
        level_9_hierarchy.supervisory_department_level5_name,
        level_9_hierarchy.supervisory_department_level6_wid,
        level_9_hierarchy.supervisory_department_level6_id,
        level_9_hierarchy.supervisory_department_level6_name,
        level_9_hierarchy.supervisory_department_level7_wid,
        level_9_hierarchy.supervisory_department_level7_id,
        level_9_hierarchy.supervisory_department_level7_name,
        level_9_hierarchy.supervisory_department_level8_wid,
        level_9_hierarchy.supervisory_department_level8_id,
        level_9_hierarchy.supervisory_department_level8_name,
        level_9_hierarchy.supervisory_department_level9_wid,
        level_9_hierarchy.supervisory_department_level9_id,
        level_9_hierarchy.supervisory_department_level9_name
    from
        level_9_hierarchy
)
select distinct
    supervisory_department_wid,
    supervisory_department_id,
    supervisory_department_name,
    supervisory_department_parent_id,
    supervisory_department_parent_wid,
    supervisory_department_toplevel_id,
    supervisory_department_toplevel_wid,
    supervisory_department_level1_wid,
    supervisory_department_level1_id,
    supervisory_department_level1_name,
    supervisory_department_level2_wid,
    supervisory_department_level2_id,
    supervisory_department_level2_name,
    supervisory_department_level3_wid,
    supervisory_department_level3_id,
    supervisory_department_level3_name,
    supervisory_department_level4_wid,
    supervisory_department_level4_id,
    supervisory_department_level4_name,
    supervisory_department_level5_wid,
    supervisory_department_level5_id,
    supervisory_department_level5_name,
    supervisory_department_level6_wid,
    supervisory_department_level6_id,
    supervisory_department_level6_name,
    supervisory_department_level7_wid,
    supervisory_department_level7_id,
    supervisory_department_level7_name,
    supervisory_department_level8_wid,
    supervisory_department_level8_id,
    supervisory_department_level8_name,
    supervisory_department_level9_wid,
    supervisory_department_level9_id,
    supervisory_department_level9_name,
    cast({{
        dbt_utils.surrogate_key([
            'supervisory_department_wid',
            'supervisory_department_id',
            'supervisory_department_name',
            'supervisory_department_parent_id',
            'supervisory_department_parent_wid',
            'supervisory_department_toplevel_id',
            'supervisory_department_toplevel_wid',
            'supervisory_department_level1_wid',
            'supervisory_department_level1_id',
            'supervisory_department_level1_name',
            'supervisory_department_level2_wid',
            'supervisory_department_level2_id',
            'supervisory_department_level2_name',
            'supervisory_department_level3_wid',
            'supervisory_department_level3_id',
            'supervisory_department_level3_name',
            'supervisory_department_level4_wid',
            'supervisory_department_level4_id',
            'supervisory_department_level4_name',
            'supervisory_department_level5_wid',
            'supervisory_department_level5_id',
            'supervisory_department_level5_name',
            'supervisory_department_level6_wid',
            'supervisory_department_level6_id',
            'supervisory_department_level6_name',
            'supervisory_department_level7_wid',
            'supervisory_department_level7_id',
            'supervisory_department_level7_name',
            'supervisory_department_level8_wid',
            'supervisory_department_level8_id',
            'supervisory_department_level8_name',
            'supervisory_department_level9_wid',
            'supervisory_department_level9_id',
            'supervisory_department_level9_name'
        ])
    }} as varchar(100)) as md5,
    current_timestamp as create_dt,
    'WORKDAY' as create_by,
    current_timestamp as upd_dt,
    'WORKDAY' as upd_by
from
    finaloutput
where
    1 = 1     
