SELECT CASELINKNUM
       , ARTLINE
       , ARTLINETYPERAD
       , ARTLINETYPEBRACH
       , ARTLINETYPEAX
       , ARTLINETYPEFEM
       , ARTLINETYPEULNAR
       , ARTLINETYPEDORS
       , ARTLINETYPEPOST
       , ARTLINETYPECENT
       , ARTLINEPREPROC
       , CUTDOWN
       , CUTDOWNRAD
       , CUTDOWNULN
       , CUTDOWNFEM
       , CUTDOWNOTH
       , PERCENTPRESS
       , PCPLOCRJUG
       , PCPLOCRSUB
       , PCPLOCRFEM
       , PCPLOCLJUG
       , PCPLOCLSUB
       , PCPLOCLFEM
       , PCPLOCOTH
       , CVPPICCPREPROC
       , CVPPLACED
       , SURGMONLINES
       , LOWINTRAOPTEMP
       , INTRAOPTEMPSITE
       , TEE


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_MONITOR
order by 1;