SELECT CASELINKNUM
       , INDUCTIONDT
       , INDTYPEINH
       , INDAGENTINHALSEVO
       , INDAGENTINHALISO
       , INDTYPEIV
       , INDAGENTIVSODT
       , INDAGENTIVKET
       , INDAGENTIVETOM
       , INDAGENTIVPROP
       , INDAGENTIVFENT
       , INDAGENTIVMID
       , INDAGENTIVDEX
       , INDAGENTIVSUF
       , INDAGENTIVREM
       , INDTYPEIM
       , INDAGENTIMKET
       , INDAGENTIMMID
       , REGIONALANES
       , REGANESSITE
       , REGANESDRUGBUP
       , REGANESDRUGBUPFEN
       , REGANESDRUGCLON
       , REGANESDRUGFEN
       , REGANESDRUGHYDRO
       , REGANESDRUGLIDO
       , REGANESDRUGMORPH
       , REGANESDRUGROP
       , REGANESDRUGROPFEN
       , REGANESDRUGTETRA
       , REGANESDRUGOTH


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_TECHNIQUE
order by 1;