SELECT CASELINKNUM
       , PROCOAGUSAGE
       , PROCOAGFACTORVIIA1
       , PROCOAGFACTORVIIA2
       , PROCOAGFACTORVIIA3


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS
order by 1;