SELECT CASELINKNUM
       , AIRWAYINSITU
       , AIRWAYTYPE
       , AIRWAYSIZELMA
       , AIRWAYSIZEINTUB
       , CUFFED
       , AIRWAYSITE
       , ENDOBRONCISO
       , ENDOBRONCISOMETH
       , ENDOFINDUCTDT

  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_AIRWAY
ORDER BY 1-- CAST(CASELINKNUM AS INTEGER);