SELECT CASELINKNUM
       , PREOPO2SAT
       , PREOPOXYGEN
       , PLOCTRANSDT
       , PREOPSED
       , PREOPSEDRTE
       , PREOPSEDDRUGATRO
       , PREOPSEDDRUGDEM
       , PREOPSEDDRUGDEX
       , PREOPSEDDRUGDIAZ
       , PREOPSEDDRUGFENT
       , PREOPSEDDRUGGLYCO
       , PREOPSEDDRUGKET
       , PREOPSEDDRUGLORAZ
       , PREOPSEDDRUGMIDAZ
       , PREOPSEDDRUGMORPH
       , PREOPSEDDRUGPENT


  FROM CDW_STG_DEV.RYBAD.S_CDW_CCAS_ANESTHESIA_PREOPMEDS
order by 1;