select
    cast(v_lkp.visit_key as bigint) as visit_key,
    cast(pat.pat_key as bigint) as pat_key,
    cast(idx.fc_key as bigint) as fc_key,
    cast(idx.pc_prov_key as bigint) as pc_prov_key,
    cast(idx.visit_prov_key as bigint) as visit_prov_key,
    cast(idx.dept_key as bigint) as dept_key,
    cast(idx.eff_dept_key as bigint) as eff_dept_key,
    cast(idx.proc_key as bigint) as proc_key,
    cast(idx.acct_key as bigint) as acct_key,
    cast(idx.loc_key as bigint) as loc_key,
    cast(idx.bp_key as bigint) as bp_key,
    cast(idx.payor_key as bigint) as payor_key,
    cast(idx.prgm_key as bigint) as prgm_key,
    cast(idx.svc_area_key as bigint) as svc_area_key,
    cast(idx.contact_dt_key as bigint) as contact_dt_key,
    cast(idx.ref_src_key as bigint) as ref_src_key,
    cast(idx.rfl_key as bigint) as rfl_key,
    cast(idx.appt_visit_type_key as bigint) as appt_visit_type_key,
    cast(idx.hsp_acct_key as bigint) as hsp_acct_key,
    cast(idx.cvg_key as bigint) as cvg_key,
    cast(idx.avs_emp_key as bigint) as avs_emp_key,
    cast(idx.checkin_emp_key as bigint) as checkin_emp_key,
    cast(idx.appt_entry_emp_key as bigint) as appt_entry_emp_key,
    cast(idx.less_72hr_visit_key as bigint) as less_72hr_visit_key,
    cast(idx.res_stdy_key as bigint) as res_stdy_key,
    cast(idx.cosign_emp_key as bigint) as cosign_emp_key,
    cast(idx.supervisor_prov_key as bigint) as supervisor_prov_key,
    cast(idx.ip_documented_visit_key as bigint) as ip_documented_visit_key,
    cast(idx.dict_enc_type_key as bigint) as dict_enc_type_key,
    cast(idx.dict_appt_stat_key as bigint) as dict_appt_stat_key,
    cast(idx.dict_appt_lag_bkt_key as bigint) as dict_appt_lag_bkt_key,
    cast(idx.dict_copay_type_key as bigint) as dict_copay_type_key,
    cast(idx.dict_visit_last_stay_cls_key as bigint) as dict_visit_last_stay_cls_key,
    cast(idx.dim_phone_reminder_stat_key as integer) as dim_phone_reminder_stat_key,
    cast(idx.dim_rsn_disch_key as bigint) as dim_rsn_disch_key,
    cast(idx.dim_adt_pat_class_key as smallint) as dim_adt_pat_class_key,
    cast(idx.dim_visit_cncl_rsn_key as integer) as dim_visit_cncl_rsn_key,
    cast(idx.dim_supervisor_prov_type_key as integer) as dim_supervisor_prov_type_key,
    cast(dim.dim_routed_msg_priority_key as integer) as dim_routed_msg_priority_key,
    cast(idx.level_svc_mod1_key as bigint) as level_svc_mod1_key,
    cast(idx.level_svc_mod2_key as bigint) as level_svc_mod2_key,
    cast(idx.level_svc_mod3_key as bigint) as level_svc_mod3_key,
    cast(idx.level_svc_mod4_key as bigint) as level_svc_mod4_key,
    cast(idx.enc_id as numeric(14, 3)) as enc_id,
    cast(idx.claim_id as bigint) as claim_id,
    cast(idx.age as numeric(9, 4)) as age,
    cast(idx.bp_sys as bigint) as bp_sys,
    cast(idx.bp_dias as bigint) as bp_dias,
    cast(idx.temp as numeric(7, 3)) as temp,
    cast(idx.pulse as bigint) as pulse,
    cast(idx.wt_oz as numeric(10, 4)) as wt_oz,
    cast(idx.wt_kg as numeric(18, 14)) as wt_kg,
    cast(idx.ht_raw as character varying(30)) as ht_raw,
    cast(idx.ht_cm as numeric(11, 7)) as ht_cm,
    cast(idx.respirations as bigint) as respirations,
    cast(idx.head_circ as numeric(7, 3)) as head_circ,
    cast(idx.appt_stat as character varying(254)) as appt_stat,
    cast(idx.appt_block as character varying(254)) as appt_block,
    cast(idx.hosp_admit_type as character varying(254)) as hosp_admit_type,
    cast(idx.entity as character varying(254)) as entity,
    cast(idx.los_hours as numeric(25, 18)) as los_hours,
    cast(idx.age_display as character varying(50)) as age_display,
    cast(idx.appt_lag_days as numeric(12, 2)) as appt_lag_days,
    cast(idx.age_days as numeric(11, 4)) as age_days,
    cast(idx.copay_due as numeric(12, 2)) as copay_due,
    cast(idx.copay_coll as numeric(12, 2)) as copay_coll,
    cast(idx.self_pay_amt as numeric(12, 2)) as self_pay_amt,
    cast(idx.chrg_slip_num as character varying(20)) as chrg_slip_num,
    cast(idx.copay_ref_num as character varying(300)) as copay_ref_num,
    cast(idx.appt_sn as bigint) as appt_sn,
    cast(idx.contact_cmt as character varying(255)) as contact_cmt,
    cast(idx.enc_dt_real as double precision) as enc_dt_real,
    cast(idx.appt_lgth_min as bigint) as appt_lgth_min,
    cast(idx.bmi as numeric(18, 2)) as bmi,
    cast(idx.bill_nbr as character varying(50)) as bill_nbr,
    cast(idx.cancel_reason_cmt as character varying(1200)) as cancel_reason_cmt,
    cast(idx.los_proc_cd as character varying(10)) as los_proc_cd,
    cast(idx.visit_stat_color_cd as character varying(254)) as visit_stat_color_cd,
    cast(idx.eff_dt as timestamp) as eff_dt,
    cast(idx.lmp_dt as timestamp) as lmp_dt,
    cast(idx.appt_dt as timestamp) as appt_dt,
    cast(idx.appt_checkin_dt as timestamp) as appt_checkin_dt,
    cast(idx.appt_checkout_dt as timestamp) as appt_checkout_dt,
    cast(idx.hosp_admit_dt as timestamp) as hosp_admit_dt,
    cast(idx.hosp_dischrg_dt as timestamp) as hosp_dischrg_dt,
    cast(idx.dischrg_dt as timestamp) as dischrg_dt,
    cast(idx.appt_made_dt as timestamp) as appt_made_dt,
    cast(idx.avs_print_dt as timestamp) as avs_print_dt,
    cast(idx.enc_close_dt as timestamp) as enc_close_dt,
    cast(idx.appt_cancel_dt as timestamp) as appt_cancel_dt,
    cast(idx.appt_entry_dt as timestamp) as appt_entry_dt,
    cast(idx.chart_cosign_dt as timestamp) as chart_cosign_dt,
    cast(idx.enc_closed_ind as byteint) as enc_closed_ind,
    cast(idx.adm_for_surg_ind as byteint) as adm_for_surg_ind,
    cast(idx.is_walk_in_ind as byteint) as is_walk_in_ind,
    cast(idx.rfl_req_ind as byteint) as rfl_req_ind,
    cast(idx.less_72hr_hosp_admit_ind as byteint) as less_72hr_hosp_admit_ind,
    cast(idx.appt_cancel_24hr_ind as byteint) as appt_cancel_24hr_ind,
    cast(idx.appt_cancel_48hr_ind as byteint) as appt_cancel_48hr_ind,
    cast(idx.visit_last_stay_class_ind as byteint) as visit_last_stay_class_ind,
    cast(pat.pat_id as character varying(254)) as pat_id,
    cast(visit_provider.prov_id as character varying(254)) as visit_prov_id,
    cast(pc_provider.prov_id as character varying(254)) as pc_prov_id,
    cast(0 as character varying(254)) as dischrg_prov_id,
    cast(coalesce(payor.payor_id, 0) as bigint) as payor_id,
    cast(0 as bigint) as dischrg_prov_key,
    cast(idx.create_dt as timestamp) as create_dt,
    cast(idx.create_by as character varying(20)) as create_by,
    cast(idx.upd_dt as timestamp) as upd_dt,
    cast(idx.upd_by as character varying(20)) as upd_by
from
    {{source('manual_ods', 'idx_visit')}} as idx
    left join {{ref('stg_visit_key_lookup')}} as v_lkp
        on idx.enc_id = v_lkp.encounter_id
            and idx.pat_id = v_lkp.patient_id
            and lower(source_name) = 'idx'
    left join {{source('cdw', 'patient')}} as pat on
        pat.pat_id = idx.pat_id
    left join {{source('cdw', 'dim_routed_msg_priority')}} as dim on
        dim.routed_msg_priority_id = idx.routed_msg_priority_id
    left join {{source('cdw','provider')}} as visit_provider
        on visit_provider.prov_key = idx.visit_prov_key
    left join {{source('cdw','provider')}} as pc_provider
        on pc_provider.prov_key = idx.pc_prov_key
    left join {{source('cdw','payor')}} as payor
        on payor.payor_key = idx.payor_key
