SELECT DISTINCT AGE.ACCOUNT
       , AGE.PATIENT_NAME
       , AGE.PATIENTMEDICALRECORDNUMBER 
       , AGE.BIRTHDATE
       , RNKS.ID_CLAIM AS INVOICE_NUMBER
       , RNKS.BILLING_DATE AS DATE_OF_SERVICE
       , RNKS.BILLINGCODEDESC  AS PRODUCT_DESCRIPTION
       , AGE.ITEM_BALANCE
       , AGE.PATIENTZIP
FROM (SELECT AGE1.ACCOUNT
             , PTD.PATIENTFULLNAME AS PATIENT_NAME
             , PTD.PATIENTMEDICALRECORDNUMBER 
             , AGE1.BIRTHDATE
             , SUM(AGE1.AMOUNT) AS ITEM_BALANCE
             , PTD.PATIENTZIP
      FROM CDW_ODS.ADMIN.HDMS_DS_AR_AGEDARDATEOFSERVICE AGE1
      LEFT JOIN CDW_ODS.ADMIN.HDMS_DS_PATIENT_DEMOGRAPHICS PTD ON AGE1.ACCOUNT = PTD.ACCOUNT 
      WHERE AGE1.ID_PAYER  = 0
      AND AGE1.AMOUNT >0
      GROUP BY AGE1.ACCOUNT
               , PTD.PATIENTFULLNAME 
               , PTD.PATIENTMEDICALRECORDNUMBER 
               , AGE1.BIRTHDATE
               , PTD.PATIENTZIP) AGE
LEFT JOIN (SELECT * 
           FROM (SELECT ACCOUNT
                        , BILLING_DATE
                        , ID_CLAIM
                        , BILLINGCODEDESC
                        , RANK() OVER(PARTITION BY ACCOUNT ORDER BY BILLING_DATE,ID_CLAIM,BILLINGCODEDESC ) AS RNK
                 FROM CDW_ODS.ADMIN.HDMS_DS_AR_AGEDARDATEOFSERVICE)RN WHERE RN.RNK=1 )RNKS ON AGE.ACCOUNT = RNKS.ACCOUNT 
