	
	CREATE TABLE CHOP_IMPACT_CATHARTERIALCLOSUREMETHOD 
	 (SURG_ENC_ID  NVARCHAR(50)      NOT NULL,
	ARTCLOSUREDEVID            INT     NOT NULL,
	SORT            INT       NOT NULL,
	LOADDT      DATETIME  NOT NULL, 
    MD5     VARCHAR(50)     NOT NULL, 
    PENDINGIMPORT     INT     NOT NULL);
    
	CREATE TABLE CHOP_IMPACT_CATHVENOUSCLOSUREMETHOD
	 (SURG_ENC_ID  NVARCHAR(50)      NOT NULL,
	VENCLOSUREDEVID            INT      NOT NULL,
	SORT            INT       NOT NULL,
	LOADDT      DATETIME  NOT NULL, 
    MD5     VARCHAR(50)     NOT NULL, 
    PENDINGIMPORT     INT     NOT NULL)   ; 


ALTER TABLE CHOP_IMPACT_CATHARTERIALCLOSUREMETHOD ADD CONSTRAINT PK_CHOP_IMPACT_CATHARTERIALCLOSUREMETHOD PRIMARY KEY (SURG_ENC_ID,ARTCLOSUREDEVID,SORT);
ALTER TABLE CHOP_IMPACT_CATHVENOUSCLOSUREMETHOD ADD CONSTRAINT PK_CHOP_IMPACT_CATHVENOUSCLOSUREMETHODS PRIMARY KEY (SURG_ENC_ID,VENCLOSUREDEVID, SORT);
