DROP TABLE S_CDW_IMPACT_CATHHEMODYNAMICS;

CREATE TABLE S_CDW_IMPACT_CATHHEMODYNAMICS 
	 (SURG_ENC_ID  NVARCHAR(50)      NOT NULL,
	SYSTEMICARTSATNA      INT      NULL,
	SYSTEMICARTSAT  DECIMAL(4,1)      NULL,
	MIXVENSATNA      INT      NULL,
	MIXVENSAT      INT      NULL,
	SYSTEMVENTSYSPRESNA      INT      NULL,
	SYSTEMVENTSYSPRES  DECIMAL(4,1)      NULL,
	SYSTEMVENTENDDIAPRESNA      INT      NULL,
	SYSTEMVENTENDDIAPRES      INT      NULL,
	SYSTEMSYSBPNA      INT      NULL,
	SYSTEMSYSBP      INT      NULL,
	SYSTEMDIABPNA      INT      NULL,
	SYSTEMDIABP      INT      NULL,
	SYSTEMMEANBPNA      INT      NULL,
	SYSTEMMEANBP      INT      NULL,
	PULMARTSYSPRESNA      INT      NULL,
	PULMARTSYSPRES  DECIMAL(4,1)     NULL,
	PULMARTMEANPRESNA      INT      NULL,
	PULMARTMEANPRES  DECIMAL(3,1)     NULL,
	PULMVENTSYSPRESNA      INT      NULL,
	PULMVENTSYSPRES      INT      NULL,
	PULMVASCRESTINDNA      INT      NULL,
	PULMVASCRESTIND  DECIMAL(3,1)      NULL,
	CARDINDNA      INT      NULL,
	CARDIND  DECIMAL(3,1)     NULL,
	QPQSRATIONA      INT      NULL,
	QPQSRATIO  DECIMAL(3,1)       NULL,
	LOADDT      TIMESTAMP  NOT NULL)
	DISTRIBUTE ON RANDOM;


ALTER TABLE S_CDW_IMPACT_CATHHEMODYNAMICS OWNER TO CDWSTG;

GRANT SELECT ON S_CDW_IMPACT_CATHHEMODYNAMICS TO ADMINISTRATION_DATA;
