 
                      CREATE TABLE S_CDW_IMPACT_CathAorticValvuloplasty 
                         (AORTICVALVULOPLASTYID      INT  NOT NULL,
               CATHID      INT      NULL,
            AVPROCIND      INT      NULL,
         AVMORPHOLOGY      INT      NULL,
          AVPREINSUFF      INT      NULL,
           AVDIAMETER  DECIMAL      NULL,
      AVPREPKSYSTGRAD  DECIMAL      NULL,
      AVDEFECTTREATED      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathAorticValvuloplasty ADD CONSTRAINT PK_S_CDW_IMPACT_CathAorticValvuloplasty PRIMARY KEY (AORTICVALVULOPLASTYID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathArrhythmiaHistory 
                         (ARRID            INT  NOT NULL,
HOSPITALIZATIONID            INT  NOT NULL,
     ARRHYTHMIAHX            INT      NULL,
 ARRHYTHMIAHXTERM  NVARCHAR(200)      NULL,
       CREATEDATE      TIMESTAMP  NOT NULL,
       LASTUPDATE      TIMESTAMP  NOT NULL,
        UPDATEDBY   NVARCHAR(50)   NOT NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathArrhythmiaHistory ADD CONSTRAINT PK_S_CDW_IMPACT_CathArrhythmiaHistory PRIMARY KEY (ARRID,HOSPITALIZATIONID,CREATEDATE,LASTUPDATE,...);
                       
                      CREATE TABLE S_CDW_IMPACT_CathASDClosure 
                         (ASDCLOSUREID      INT  NOT NULL,
         CATHID      INT  NOT NULL,
     ASDPROCIND      INT      NULL,
  ASDSEPTLENGTH  DECIMAL      NULL,
    ASDANEURYSM      INT      NULL,
    ASDMULTIFEN      INT      NULL,
ASDSEPTLENGTHNA      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathASDClosure ADD CONSTRAINT PK_S_CDW_IMPACT_CathASDClosure PRIMARY KEY (ASDCLOSUREID,CATHID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathASDDefect 
                         (DEFECTID      INT  NOT NULL,
               ASDSIZE  DECIMAL      NULL,
        ASDBALLSIZPERF      INT      NULL,
    ASDSTRETCHDIAMETER      INT      NULL,
ASDSTRETCHDIAMETERSIZE      INT      NULL,
       ASDSTOPFLOWTECH      INT      NULL,
   ASDSTOPFLOWTECHSIZE      INT      NULL,
            ASDRIMMEAS      INT      NULL,
       ASDIVCRIMLENGTH  DECIMAL      NULL,
      ASDAORTRIMLENGTH  DECIMAL      NULL,
           ASDDEFTREAT      INT      NULL,
      ASDNOTREATREASON      INT      NULL,
           ASDRESSHUNT      INT      NULL,
                  SORT      INT  NOT NULL,
          ASDCLOSUREID      INT  NOT NULL,
      ASDPOSTRIMLENGTH  DECIMAL      NULL,
   ASDMULTIFENESTRATED      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathASDDefect ADD CONSTRAINT PK_S_CDW_IMPACT_CathASDDefect PRIMARY KEY (DEFECTID,SORT,ASDCLOSUREID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathCoarcProc 
                         (COARCPROCID      INT  NOT NULL,
              CATHID      INT      NULL,
        COARCPROCIND      INT      NULL,
    COARCPREDIAMETER  DECIMAL      NULL,
   COARCPREPKSYSGRAD  DECIMAL      NULL,
  COARCDEFECTTREATED      INT      NULL,
   COARCPOSTDIAMETER  DECIMAL      NULL,
  COARCPOSTPKSYSGRAD  DECIMAL      NULL,
         COARCNATURE      INT      NULL,
     COARCPRIORTREAT      INT      NULL,
    COARCADDLAORTOBS      INT      NULL,
COARCAORTICARCHINTER      INT      NULL,
 COARCPRESYSGRADIENT  DECIMAL      NULL,
COARCPOSTSYSGRADIENT  DECIMAL      NULL,
  COARCPREDIAMETERNA      INT      NULL,
 COARCPREPKSYSGRADNA      INT      NULL,
 COARCPOSTDIAMETERNA      INT      NULL,
COARCPOSTPKSYSGRADNA      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathCoarcProc ADD CONSTRAINT PK_S_CDW_IMPACT_CathCoarcProc PRIMARY KEY (COARCPROCID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathCoarcProcDevice 
                         (DEVICECOUNTERID      INT  NOT NULL,
                 COARCPROCID      INT      NULL,
                  COARCDEVID      INT      NULL,
                COARCDEVTYPE      INT      NULL,
               COARCBALLPURP      INT      NULL,
           COARCBALLPRESSURE      INT      NULL,
            COARCBALLOUTCOME      INT      NULL,
           COARCSTENTOUTCOME      INT      NULL,
    COARCPOSTINSTENTDIAMETER  DECIMAL      NULL,
                        SORT      INT      NULL,
COARCPOSTINSTENTDIAMASSESSED      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathCoarcProcDevice ADD CONSTRAINT PK_S_CDW_IMPACT_CathCoarcProcDevice PRIMARY KEY (DEVICECOUNTERID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathData 
                         (CATHID           INT  NOT NULL,
         CATHLABARRDATE     TIMESTAMP      NULL,
         CATHLABDEPDATE     TIMESTAMP      NULL,
         CATHINSERTDATE     TIMESTAMP      NULL,
            CATHOUTDATE     TIMESTAMP      NULL,
             PROCDXCATH           INT      NULL,
                PROCASD           INT      NULL,
                 HEIGHT       DECIMAL      NULL,
                 WEIGHT       DECIMAL      NULL,
             PREPROCHGB       DECIMAL      NULL,
           PREPROCCREAT       DECIMAL      NULL,
              PREPROCO2           INT      NULL,
                    NEC           INT      NULL,
                 SEPSIS           INT      NULL,
                   PREG           INT      NULL,
         PREPROCANTIARR           INT      NULL,
        PREPROCANTICOAG           INT      NULL,
         PREPROCANTIHYP           INT      NULL,
    PREPROCANTIPLATELET           INT      NULL,
              PREPROCBB           INT      NULL,
        PREPROCDIURETIC           INT      NULL,
          PREPROCPROSTA           INT      NULL,
             PREPROCSED           INT      NULL,
            PREPROCVASO           INT      NULL,
           PREPROCSINUS           INT      NULL,
             PREPROCAET           INT      NULL,
             PREPROCSVT           INT      NULL,
            PREPROCAFIB           INT      NULL,
           PREPROCJUNCT           INT      NULL,
            PREPROCIDIO           INT      NULL,
            PREPROCAVB2           INT      NULL,
            PREPROCAVB3           INT      NULL,
           PREPROCPACED           INT      NULL,
      PREPROCOTHRHYTHYM           INT      NULL,
              PROCCOARC           INT      NULL,
         PROCAORTICVALV           INT      NULL,
      PROCPULMONARYVALV           INT      NULL,
                PROCPDA           INT      NULL,
        PROCPROXPASTENT           INT      NULL,
         SPECIFICPROCID           INT      NULL,
             HOSPSTATUS           INT      NULL,
             PROCSTATUS           INT      NULL,
                TRAINEE           INT      NULL,
             OPERATORID           INT      NULL,
         CATHLABARRTIME     TIMESTAMP      NULL,
         CATHLABDEPTIME     TIMESTAMP      NULL,
         CATHINSERTTIME     TIMESTAMP      NULL,
            CATHOUTTIME     TIMESTAMP      NULL,
            ANESPRESENT           INT      NULL,
           ANESCALLEDIN           INT      NULL,
               SEDATION           INT      NULL,
         AIRMNGSPONRESP           INT      NULL,
              AIRMNGLMA           INT      NULL,
            AIRMNGTRACH           INT      NULL,
          AIRMNGBAGMASK           INT      NULL,
             AIRMNGCPAP           INT      NULL,
        AIRMNGELECINTUB           INT      NULL,
        AIRMNGPREVINTUB           INT      NULL,
              ACCESSLOC           INT      NULL,
              VENACCESS           INT      NULL,
          VENLARGSHEATH           INT      NULL,
VENCLOSUREMETHODCOUNTER           INT      NULL,
     VENCLOSUREMETHODND           INT      NULL,
              ARTACCESS           INT      NULL,
          ARTLARGSHEATH           INT      NULL,
ARTCLOSUREMETHODCOUNTER           INT      NULL,
     ARTCLOSUREMETHODND           INT      NULL,
             FLUOROTIME       DECIMAL      NULL,
             FLUORODOSE           INT      NULL,
              FLUORODAP           INT      NULL,
            CONTRASTVOL           INT      NULL,
             SYSHEPARIN           INT      NULL,
             ACTMONITOR           INT      NULL,
                ACTPEAK           INT      NULL,
               HEPFLUSH           INT      NULL,
               INOTROPE           INT      NULL,
            INOTROPEUSE           INT      NULL,
                ECMOUSE           INT      NULL,
                LVADUSE           INT      NULL,
                 HOSPID           INT      NULL,
                  PATID           INT      NULL,
     DTTMCATHLABARRTIME     TIMESTAMP      NULL,
     DTTMCATHLABDEPTIME     TIMESTAMP      NULL,
     DTTMCATHINSERTTIME     TIMESTAMP      NULL,
        DTTMCATHOUTTIME     TIMESTAMP      NULL,
                   AUX5  NVARCHAR(50)      NULL,
                   AUX6  NVARCHAR(50)      NULL,
            REGISTRYVER  NVARCHAR(10)      NULL,
       SCHEDARRIVALDATE     TIMESTAMP      NULL,
              PROCOTHER           INT      NULL,
     EXCLUDEFROMHARVEST           INT      NULL,
               RECORDER           INT      NULL,
           PREPROCHGBND           INT      NULL,
         PREPROCCREATND           INT      NULL,
               SVDEFECT           INT      NULL,
             PREPROCMED           INT      NULL,
             PROCEPCATH           INT      NULL,
         PROCEPABLATION           INT      NULL,
               PROCTPVR           INT      NULL,
    SECONDPARTICIPATING           INT      NULL,
          PROCSTARTDATE     TIMESTAMP      NULL,
          PROCSTARTTIME     TIMESTAMP      NULL,
            PROCENDDATE     TIMESTAMP      NULL,
            PROCENDTIME     TIMESTAMP      NULL,
                 AIRMNG           INT      NULL,
                IABPUSE           INT      NULL,
              PLANEUSED           INT      NULL,
         FLUORODOSEKERM           INT      NULL,
   FLUORODOSEKERM_UNITS           INT      NULL,
          FLUORODOSEDAP           INT      NULL,
    FLUORODOSEDAP_UNITS           INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathData ADD CONSTRAINT PK_S_CDW_IMPACT_CathData PRIMARY KEY (CATHID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathDeviceAssn 
                         (ASSOCIATIONID  INT  NOT NULL,
         DEVICEID  INT  NOT NULL,
DEFECTCOUNTERASSN  INT  NOT NULL,
             SORT  INT  NOT NULL,
       CATHPROCID  INT   NOT NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathDeviceAssn ADD CONSTRAINT PK_S_CDW_IMPACT_CathDeviceAssn PRIMARY KEY (ASSOCIATIONID,DEVICEID,DEFECTCOUNTERASSN,SORT,...);
                       
                      CREATE TABLE S_CDW_IMPACT_CathDevicesUsed 
                         (DEVICEID  INT  NOT NULL,
    CATHID  INT  NOT NULL,
CATHPROCID  INT  NOT NULL,
     DEVID  INT  NOT NULL,
DEVOUTCOME  INT      NULL,
      SORT  INT   NOT NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathDevicesUsed ADD CONSTRAINT PK_S_CDW_IMPACT_CathDevicesUsed PRIMARY KEY (DEVICEID,CATHID,CATHPROCID,DEVID,SORT);
                       
                      CREATE TABLE S_CDW_IMPACT_CathDiagnosis 
                         (DIAGNOSISID            INT  NOT NULL,
           CATHID            INT      NULL,
PREPROCCARDDIAGID            INT      NULL,
    DIAGNOSISNAME  NVARCHAR(255)      NULL,
             SORT            INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathDiagnosis ADD CONSTRAINT PK_S_CDW_IMPACT_CathDiagnosis PRIMARY KEY (DIAGNOSISID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathEvents 
                         (EVENTID      INT  NOT NULL,
                   CATHID      INT      NULL,
                  CARREST      INT      NULL,
              POSTARRHYTH      INT      NULL,
           POSTARRHYTHMED      INT      NULL,
    POSTARRHYTHCARDIOVERS      INT      NULL,
        POSTARRHYTHTEMPPM      INT      NULL,
        POSTARRHYTHPERMPM      INT      NULL,
           POSTNEWREGURGE      INT      NULL,
            POSTTAMPONADE      INT      NULL,
           POSTAIREMBOLUS      INT      NULL,
            POSTEMBSTROKE      INT      NULL,
       POSTDEVMALPOSTHROM      INT      NULL,
             POSTDEVEMBOL      INT      NULL,
       POSTDEVRETRIEVEPCT      INT      NULL,
      POSTDEVRETRIEVESURG      INT      NULL,
             POSTDIALYSIS      INT      NULL,
           POSTINTUBATION      INT      NULL,
                 POSTECMO      INT      NULL,
                 POSTLVAD      INT      NULL,
                POSTBLEED      INT      NULL,
      POSTBLEEDACCESSSITE      INT      NULL,
        POSTBLEEDHEMATOMA      INT      NULL,
        POSTBLEEDHEMASIZE      INT      NULL,
           POSTRETROBLEED      INT      NULL,
              POSTGIBLEED      INT      NULL,
              POSTGUBLEED      INT      NULL,
           POSTOTHERBLEED      INT      NULL,
          POSTTRANSFUSION      INT      NULL,
      HGBPRIORTRANSFUSION  DECIMAL      NULL,
         POSTOTHERVASCOMP      INT      NULL,
          POSTOTHEREVENTS      INT      NULL,
      POSTPLANCARDIACSURG      INT      NULL,
       POSTUNPLANCARDSURG      INT      NULL,
        POSTUNPLANVASSURG      INT      NULL,
      POSTUNPLANOTHERSURG      INT      NULL,
    POSTOTHERSURGCATHCOMP      INT      NULL,
             POSTSUBSCATH      INT      NULL,
              POSTAVBLOCK      INT      NULL,
      POSTARRHYTHRESOLVED      INT      NULL,
  POSTDEVMALPOSTHROMRETCT      INT      NULL,
POSTDEVMALPOSTHROMRETSURG      INT      NULL,
        POSTCORARTERYCOMP      INT      NULL,
              POSTEROSION      INT      NULL,
           POSTESOFISTULA      INT      NULL,
                 POSTLBBB      INT      NULL,
                 POSTRBBB      INT      NULL,
              POSTDROPHGB      INT      NULL,
          POSTPRIORANEMIA      INT      NULL,
            POSTBLOODLOSS      INT      NULL,
     POSTECMOBLOODREPLACE      INT      NULL,
      POSTPERINERVEINJURY      INT      NULL,
     POSTPHNERVEPARALYSIS      INT      NULL,
         POSTPNEUMOTHORAX      INT      NULL,
          POSTPULEMBOLISM      INT      NULL,
      POSTPULVEINSTENOSIS      INT      NULL,
        POSTRADIATIONBURN      INT      NULL,
                  POSTDVT      INT      NULL,
          POSTCONDUITTEAR      INT      NULL,
       POSTCONDUITTEARLOC      INT      NULL,
     POSTCONDUITTEARTREAT      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathEvents ADD CONSTRAINT PK_S_CDW_IMPACT_CathEvents PRIMARY KEY (EVENTID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathHemodynamics 
                         (HEMODYNAMICSID      INT  NOT NULL,
                CATHID      INT  NOT NULL,
      SYSTEMICARTSATNA      INT      NULL,
        SYSTEMICARTSAT  DECIMAL      NULL,
           MIXVENSATNA      INT      NULL,
             MIXVENSAT      INT      NULL,
   SYSTEMVENTSYSPRESNA      INT      NULL,
     SYSTEMVENTSYSPRES  DECIMAL      NULL,
SYSTEMVENTENDDIAPRESNA      INT      NULL,
  SYSTEMVENTENDDIAPRES      INT      NULL,
         SYSTEMSYSBPNA      INT      NULL,
           SYSTEMSYSBP      INT      NULL,
         SYSTEMDIABPNA      INT      NULL,
           SYSTEMDIABP      INT      NULL,
        SYSTEMMEANBPNA      INT      NULL,
          SYSTEMMEANBP      INT      NULL,
      PULMARTSYSPRESNA      INT      NULL,
        PULMARTSYSPRES  DECIMAL      NULL,
     PULMARTMEANPRESNA      INT      NULL,
       PULMARTMEANPRES  DECIMAL      NULL,
     PULMVENTSYSPRESNA      INT      NULL,
       PULMVENTSYSPRES      INT      NULL,
     PULMVASCRESTINDNA      INT      NULL,
       PULMVASCRESTIND  DECIMAL      NULL,
             CARDINDNA      INT      NULL,
               CARDIND  DECIMAL      NULL,
           QPQSRATIONA      INT      NULL,
             QPQSRATIO  DECIMAL       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathHemodynamics ADD CONSTRAINT PK_S_CDW_IMPACT_CathHemodynamics PRIMARY KEY (HEMODYNAMICSID,CATHID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathHistory 
                         (HISTID           INT  NOT NULL,
 HOSPITALIZATIONID           INT  NOT NULL,
        HOSPITALID           INT  NOT NULL,
             PATID           INT  NOT NULL,
CHRONICLUNGDISEASE           INT      NULL,
      COAGDISORDER           INT      NULL,
         HYPERCOAG           INT      NULL,
          HYPOCOAG           INT      NULL,
          DIABETES           INT      NULL,
    HEPATICDISEASE           INT      NULL,
       RENALINSUFF           INT      NULL,
          SEIZURES           INT      NULL,
        SICKLECELL           INT      NULL,
   SINGLEVENTRICLE           INT      NULL,
       PRIORSTROKE           INT      NULL,
        CREATEDATE     TIMESTAMP  NOT NULL,
        LASTUPDATE     TIMESTAMP      NULL,
         UPDATEDBY  NVARCHAR(50)  NOT NULL,
        ARRHYTHMIA           INT      NULL,
           PRIORCM           INT      NULL,
         PRIORCMHX           INT      NULL,
      ENDOCARDITIS           INT      NULL,
                HF           INT      NULL,
              NYHA           INT      NULL,
   HEARTTRANSPLANT           INT      NULL,
        ISCHEMICHD           INT      NULL,
   KAWASAKIDISEASE           INT      NULL,
       RHEUMATICHD           INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathHistory ADD CONSTRAINT PK_S_CDW_IMPACT_CathHistory PRIMARY KEY (HISTID,HOSPITALIZATIONID,HOSPITALID,PATID,CREA...);
                       
                      CREATE TABLE S_CDW_IMPACT_CathInflationCounter 
                         (INFLATIONCOUNTERID      INT  NOT NULL,
               CATHID      INT  NOT NULL,
           CATHPROCID      INT  NOT NULL,
             BALLTECH      INT      NULL,
            SINGDEVID      INT      NULL,
         SINGBALLSTAB      INT      NULL,
     SINGBALLPRESSURE      INT      NULL,
      SINGBALLOUTCOME      INT      NULL,
SINGBALLPOSTPKSYSGRAD  DECIMAL      NULL,
   SINGBALLPOSTINSUFF      INT      NULL,
           DOUBDEVID1      INT      NULL,
        DOUBBALLSTAB1      INT      NULL,
    DOUBBALLPRESSURE1      INT      NULL,
     DOUBBALLOUTCOME1      INT      NULL,
           DOUBDEVID2      INT      NULL,
        DOUBBALLSTAB2      INT      NULL,
    DOUBBALLPRESSURE2      INT      NULL,
     DOUBBALLOUTCOME2      INT      NULL,
DOUBBALLPOSTPKSYSGRAD  DECIMAL      NULL,
   DOUBBALLPOSTINSUFF      INT      NULL,
                 SORT      INT  NOT NULL,
       POSTDILSYSGRAD  DECIMAL      NULL,
        POSTDILREGURG      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathInflationCounter ADD CONSTRAINT PK_S_CDW_IMPACT_CathInflationCounter PRIMARY KEY (INFLATIONCOUNTERID,CATHID,CATHPROCID,SORT);
                       
                      CREATE TABLE S_CDW_IMPACT_CathPAStent 
                         (PASTENTID  INT  NOT NULL,
    CATHID  INT      NULL,
PASPROCIND  INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathPAStent ADD CONSTRAINT PK_S_CDW_IMPACT_CathPAStent PRIMARY KEY (PASTENTID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathPAStentDefect 
                         (DEFECTID      INT  NOT NULL,
           PASTENTID      INT      NULL,
        PASDEFECTLOC      INT      NULL,
   PASOSTIALSTENOSIS      INT      NULL,
   PASDISOBSTRUCTION      INT      NULL,
         PASSIDEJAIL      INT      NULL,
 PASSIDEJAILINTENDED      INT      NULL,
   PASSIDEJAILARTERY      INT      NULL,
 PASDSIDEJAILDECFLOW      INT      NULL,
  PASPREPROXSYSPRESS  DECIMAL      NULL,
  PASPREDISTSYSPRESS  DECIMAL      NULL,
 PASPREPROXMEANPRESS  DECIMAL      NULL,
 PASPREDISTMEANPRESS  DECIMAL      NULL,
  PASPREPROXDIAMETER  DECIMAL      NULL,
  PASPREDISTDIAMETER  DECIMAL      NULL,
   PASPREMINDIAMETER  DECIMAL      NULL,
    PASDEFECTTREATED      INT      NULL,
 PASPOSTPROXSYSPRESS  DECIMAL      NULL,
 PASPOSTDISTSYSPRESS  DECIMAL      NULL,
PASPOSTPROXMEANPRESS  DECIMAL      NULL,
PASPOSTDISTMEANPRESS  DECIMAL      NULL,
 PASPOSTPROXDIAMETER  DECIMAL      NULL,
 PASPOSTDISTDIAMETER  DECIMAL      NULL,
  PASPOSTMINDIAMETER  DECIMAL      NULL,
                SORT      INT   NOT NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathPAStentDefect ADD CONSTRAINT PK_S_CDW_IMPACT_CathPAStentDefect PRIMARY KEY (DEFECTID,SORT);
                       
                      CREATE TABLE S_CDW_IMPACT_CathPatAnatomy 
                         (CATHPATID           INT  NOT NULL,
        HOSPITALID           INT  NOT NULL,
             PATID           INT  NOT NULL,
      DIGEORGESYND           INT      NULL,
      ALAGILLESYND           INT      NULL,
            HERNIA           INT      NULL,
        MARFANSYND           INT      NULL,
          DOWNSYND           INT      NULL,
        HETEROTAXY           INT      NULL,
        NOONANSYND           INT      NULL,
           RUBELLA           INT      NULL,
         TRISOMY13           INT      NULL,
         TRISOMY18           INT      NULL,
        TURNERSYND           INT      NULL,
WILLIAMSBEURENSYND           INT      NULL,
        CREATEDATE     TIMESTAMP  NOT NULL,
        LASTUPDATE     TIMESTAMP      NULL,
         UPDATEDBY  NVARCHAR(50)   NOT NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathPatAnatomy ADD CONSTRAINT PK_S_CDW_IMPACT_CathPatAnatomy PRIMARY KEY (CATHPATID,HOSPITALID,PATID,CREATEDATE,UPDATEDBY);
                       
                      CREATE TABLE S_CDW_IMPACT_CathProcedures 
                         (PROCEDUREID            INT  NOT NULL,
        CATHID            INT      NULL,
SPECIFICPROCID            INT      NULL,
 PROCEDURENAME  NVARCHAR(255)      NULL,
          SORT            INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathProcedures ADD CONSTRAINT PK_S_CDW_IMPACT_CathProcedures PRIMARY KEY (PROCEDUREID);
                       
                      CREATE TABLE S_CDW_IMPACT_CathTPVR 
                         (TPVRID      INT  NOT NULL,
                    CATHID      INT  NOT NULL,
               TPVRCLININD      INT      NULL,
               TPVRHEMOIND      INT      NULL,
       TPVRRVOTDYSFUNCTION      INT      NULL,
                  TPVRECHO      INT      NULL,
      TPVRECHOMEANGRADIENT  DECIMAL      NULL,
       TPVRECHOMAXGRADIENT  DECIMAL      NULL,
          TPVRECHOPVREGURG      INT      NULL,
              TPVRECHOLVEF      INT      NULL,
               TPVRECHOTRS      INT      NULL,
                   TPVRMRI      INT      NULL,
               TPVRMRIRVEF      INT      NULL,
               TPVRMRILVEF      INT      NULL,
         TPVRMRIRVEDVINDEX      INT      NULL,
         TPVRMRIRVESVINDEX      INT      NULL,
         TPVRMRILVEDVINDEX      INT      NULL,
         TPVRMRILVESVINDEX      INT      NULL,
         TPVRMRIPRFRACTION      INT      NULL,
              TPVRRVOTTYPE      INT      NULL,
       TPVRORIGINALCONDUIT      INT      NULL,
         TPVREXISTINGSTENT      INT      NULL,
             TPVRPRIORTPVR      INT      NULL,
      TPVRCATHPEAKGRADIENT  DECIMAL      NULL,
             TPVRNARROWDIA  DECIMAL      NULL,
             TPVRAORTOPERF      INT      NULL,
        TPVRSELECTIVEANGIO      INT      NULL,
       TPVRCORCOMPRESSTEST      INT      NULL,
        TPVRMAXBALLOONSIZE  DECIMAL      NULL,
    TPVRCORCOMPRESSPRESENT      INT      NULL,
       TPVRPREDILATIONPERF      INT      NULL,
         TPVRFIRSTBALLSIZE  DECIMAL      NULL,
           TPVRMAXBALLSIZE  DECIMAL      NULL,
         TPVRHIGHINFLAPERF      INT      NULL,
           TPVRNEWPRESTENT      INT      NULL,
          TPVRNEWSTENTSNUM      INT      NULL,
          TPVRACCESSVESSEL      INT      NULL,
          TPVRDELIBALLSIZE  DECIMAL      NULL,
           TPVRTPVDEPLOYED      INT      NULL,
       TPVRTPVPOSTDILATION      INT      NULL,
         TPVRFINALBALLSIZE  DECIMAL      NULL,
         TPVRFINALPRESSURE      INT      NULL,
          TPVRPEAKRVOTGRAD  DECIMAL      NULL,
      TPVRPOSTPROCPVREGURG      INT      NULL,
         TPVRFINALDIAMETER  DECIMAL      NULL,
     TPVRNOTDEPLOYEDREASON      INT      NULL,
              TPVRPOSTECHO      INT      NULL,
      TPVRPOSTECHOMEANGRAD  DECIMAL      NULL,
       TPVRPOSTECHOMAXGRAD  DECIMAL      NULL,
TPVRPOSTECHOPULVALVEREGURG      INT       NULL)
                      DISTRIBUTE ON RANDOM;
                      ALTER TABLE S_CDW_IMPACT_CathTPVR ADD CONSTRAINT PK_S_CDW_IMPACT_CathTPVR PRIMARY KEY (TPVRID,CATHID);
                      