drop TABLE S_CDW_IMPACT_CATHPROCEDURES;
drop TABLE S_CDW_IMPACT_CATHDIAGNOSIS;

	CREATE TABLE S_CDW_IMPACT_CATHDIAGNOSIS 
	 (SURG_ENC_ID  NVARCHAR(50)      NOT NULL,
	PREPROCCARDDIAGID            INT      NULL,
	DIAGNOSISNAME  NVARCHAR(255)      NULL,
	LOADDT      TIMESTAMP  NOT NULL)
	DISTRIBUTE ON RANDOM;
	--ALTER TABLE S_CDW_IMPACT_CATHDIAGNOSIS ADD CONSTRAINT PK_S_CDW_IMPACT_CATHDIAGNOSIS PRIMARY KEY (DIAGNOSISID);


	CREATE TABLE S_CDW_IMPACT_CATHPROCEDURES 
	 (SURG_ENC_ID  NVARCHAR(50)      NOT NULL,
	SPECIFICPROCID            INT      NULL,
	LOADDT      TIMESTAMP  NOT NULL)
	DISTRIBUTE ON RANDOM;
	--ALTER TABLE S_CDW_IMPACT_CATHPROCEDURES ADD CONSTRAINT PK_S_CDW_IMPACT_CATHPROCEDURES PRIMARY KEY (PROCEDUREID);


ALTER TABLE S_CDW_IMPACT_CATHPROCEDURES OWNER TO CDWSTG;
ALTER TABLE S_CDW_IMPACT_CATHDIAGNOSIS OWNER TO CDWSTG;

GRANT SELECT ON S_CDW_IMPACT_CATHPROCEDURES TO ADMINISTRATION_DATA;
GRANT SELECT ON S_CDW_IMPACT_CATHDIAGNOSIS TO ADMINISTRATION_DATA;
