select * from chop_impact_cathdata
where SURG_ENC_ID in  (2061551027)

update chop_impact_cathdata set pendingimport = 1 where surg_enc_id = 2061551027

update chop_impact_cathdata set pendingimport = 1 where SURG_ENC_ID  in  (2061551027)

select * from cathdata
where emreventid in  (2061551027)


SELECT * FROM CHOP_IMPACT_CATHPROCEDURES
WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CATHPROCEDURES
     WHERE CATHID in (SELECT CATHID FROM CATHDATA WHERE EMREVENTID in  (2061551027))

UPDATE CHOP_IMPACT_CATHPROCEDURES SET PENDINGIMPORT = 1 WHERE SURG_ENC_ID in  (2061551027)


SELECT * FROM CHOP_IMPACT_CATHDIAGNOSIS
WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CATHDIAGNOSIS
     WHERE CATHID  in (SELECT CATHID FROM CATHDATA WHERE EMREVENTID in  (2061551027))
	 order by 2
	 
UPDATE CHOP_IMPACT_CATHDIAGNOSIS SET PENDINGIMPORT = 1 WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CHOP_IMPACT_CATHHISTORY
WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CATHHISTORY
     WHERE HOSPITALIZATIONID  in (SELECT HOSPID FROM CATHDATA WHERE EMREVENTID in  (2061551027))
	 order by 2
	 
UPDATE CHOP_IMPACT_CATHDIAGNOSIS SET PENDINGIMPORT = 1 WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CHOP_IMPACT_CATHEVENTS
WHERE SURG_ENC_ID in  (2061551027)

SELECT * FROM CATHEVENTS
     WHERE CATHID  in (SELECT CATHID FROM CATHDATA WHERE EMREVENTID in  (2061551027))
	 order by 2
	 
UPDATE CHOP_IMPACT_CATHEVENTS SET PENDINGIMPORT = 1 WHERE SURG_ENC_ID in  (2061551027)




UPDATE CHOP_IMPACT_CATHAORTICVALVULOPLASTY SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHARRHYTHMIAHISTORY SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHASDCLOSURE SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHASDDEFECT SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHCOARCPROC SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHCOARCPROCDEVICE SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHDATA SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHDEVICEASSN SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHDEVICESUSED SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHDIAGNOSIS SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHEVENTS SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHHEMODYNAMICS SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHHISTORY SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHINFLATIONCOUNTER SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPASTENT SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPASTENTDEFECT SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPATANATOMY SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPDACLOSURE SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPROCEDURES SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHPULMONARYVALVULOPLASTY SET LOADDT=LOADDT
UPDATE CHOP_IMPACT_CATHTPVR SET LOADDT=LOADDT