WITH IMPACT AS
(SELECT C.R_CATH_ID, 
       P.PAT_MRN_ID,
	   AUXILIARY_5,
	   CATH_LAB_ARRIVAL_DT --SELECT *
  FROM REGISTRY_IMPACT_CATH_DATA C JOIN PATIENT P ON C.PAT_KEY = P.PAT_KEY
                                  JOIN REGISTRY_HOSPITAL_VISIT H ON C.R_HSP_VST_KEY = H.R_HSP_VST_KEY
 WHERE R_CATH_ID = 13465
 )
 
 ,STUDY AS
 (
SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.REQPRID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT,
	    LAST_NM,
		FIRST_NM,
		PATIENT.DOB--SELECT *
FROM CDW_ODS..SENSIS_STUDY STUDY JOIN CDWPRD..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                 JOIN CDWPRD..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
								 JOIN CDW_ODS..SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
								 JOIN CDWPRD..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
								 JOIN CDWPRD..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
								 JOIN CDWPRD..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
								 JOIN CDWPRD..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
								 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
								 LEFT JOIN CDW_ODS..SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
								 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM CDW_ODS..SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
								 LEFT JOIN CDW_ODS..SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
 )
 
 SELECT IMPACT.PAT_MRN_ID,
        CATH_LAB_ARRIVAL_DT,
		AUXILIARY_5,
		SURG_ENC_ID,
		LAST_NM,
		FIRST_NM,
		DOB
FROM IMPACT JOIN STUDY ON IMPACT.AUXILIARY_5 = STUDY.REQPRID


