SELECT 'SELECT '+''''+NAME+''''+', COUNT(*) FROM '+NAME FROM SYS.TABLES WHERE NAME LIKE '%CHOP_IMPACT%'
SELECT 'UPDATE '+NAME+' SET PENDINGIMPORT = 0 ' FROM SYS.TABLES WHERE NAME LIKE '%CHOP_IMPACT%'
update CHOP_IMPACT_CATHTPVR set PENDINGIMPORT = 0

SELECT 'CHOP_IMPACT_CATHAORTICVALVULOPLASTY', COUNT(*) FROM CHOP_IMPACT_CATHAORTICVALVULOPLASTY 
SELECT 'CHOP_IMPACT_CATHARRHYTHMIAHISTORY', COUNT(*) FROM CHOP_IMPACT_CATHARRHYTHMIAHISTORY
SELECT 'CHOP_IMPACT_CATHASDCLOSURE', COUNT(*) FROM CHOP_IMPACT_CATHASDCLOSURE
SELECT 'CHOP_IMPACT_CATHASDDEFECT', COUNT(*) FROM CHOP_IMPACT_CATHASDDEFECT
SELECT 'CHOP_IMPACT_CATHCOARCPROC', COUNT(*) FROM CHOP_IMPACT_CATHCOARCPROC
SELECT 'CHOP_IMPACT_CATHCOARCPROCDEVICE', COUNT(*) FROM CHOP_IMPACT_CATHCOARCPROCDEVICE
SELECT 'CHOP_IMPACT_CATHDATA', COUNT(*) FROM CHOP_IMPACT_CATHDATA
SELECT 'CHOP_IMPACT_CATHDEVICEASSN', COUNT(*) FROM CHOP_IMPACT_CATHDEVICEASSN
SELECT 'CHOP_IMPACT_CATHDEVICESUSED', COUNT(*) FROM CHOP_IMPACT_CATHDEVICESUSED
SELECT 'CHOP_IMPACT_CATHDIAGNOSIS', COUNT(*) FROM CHOP_IMPACT_CATHDIAGNOSIS
SELECT 'CHOP_IMPACT_CATHEVENTS', COUNT(*) FROM CHOP_IMPACT_CATHEVENTS
SELECT 'CHOP_IMPACT_CATHHEMODYNAMICS', COUNT(*) FROM CHOP_IMPACT_CATHHEMODYNAMICS
SELECT 'CHOP_IMPACT_CATHHISTORY', COUNT(*) FROM CHOP_IMPACT_CATHHISTORY
SELECT 'CHOP_IMPACT_CATHINFLATIONCOUNTER', COUNT(*) FROM CHOP_IMPACT_CATHINFLATIONCOUNTER
SELECT 'CHOP_IMPACT_CATHPASTENT', COUNT(*) FROM CHOP_IMPACT_CATHPASTENT
SELECT 'CHOP_IMPACT_CATHPASTENTDEFECT', COUNT(*) FROM CHOP_IMPACT_CATHPASTENTDEFECT
SELECT 'CHOP_IMPACT_CATHPATANATOMY', COUNT(*) FROM CHOP_IMPACT_CATHPATANATOMY
SELECT 'CHOP_IMPACT_CATHPDACLOSURE', COUNT(*) FROM CHOP_IMPACT_CATHPDACLOSURE
SELECT 'CHOP_IMPACT_CATHPROCEDURES', COUNT(*) FROM CHOP_IMPACT_CATHPROCEDURES
SELECT 'CHOP_IMPACT_CATHPULMONARYVALVULOPLASTY', COUNT(*) FROM CHOP_IMPACT_CATHPULMONARYVALVULOPLASTY
SELECT 'CHOP_IMPACT_CATHTPVR', COUNT(*) FROM CHOP_IMPACT_CATHTPVR


UPDATE CHOP_IMPACT_CATHAORTICVALVULOPLASTY SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHARRHYTHMIAHISTORY SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHASDCLOSURE SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHASDDEFECT SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHCOARCPROC SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHCOARCPROCDEVICE SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHDATA SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHDEVICEASSN SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHDEVICESUSED SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHDIAGNOSIS SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHEVENTS SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHHEMODYNAMICS SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHHISTORY SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHINFLATIONCOUNTER SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPASTENT SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPASTENTDEFECT SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPATANATOMY SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPDACLOSURE SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPROCEDURES SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHPULMONARYVALVULOPLASTY SET PENDINGIMPORT = 0 
UPDATE CHOP_IMPACT_CATHTPVR SET PENDINGIMPORT = 0 