with comp as (
select
CoHier.COMPANY_ID,
COMPANY_HIERARCHY_LEVEL1_NAME, 
COMPANY_HIERARCHY_LEVEL2_NAME, 
COMPANY_HIERARCHY_LEVEL3_NAME
from CDW_ODS.WORKDAY.COMPANY_COMPANY_HIERARCHY CoHier
inner join CDW_ODS.WORKDAY.COMPANY Co on CoHier.COMPANY_WID = Co.COMPANY_WID 
inner join CDW_ODS.WORKDAY.COMPANY_HIERARCHY_LEVELS Lvls on CoHier.COMPANY_HIERARCHY_WID = Lvls.COMPANY_HIERARCHY_WID
)
select
comp.COMPANY_HIERARCHY_LEVEL1_NAME, 
comp.COMPANY_HIERARCHY_LEVEL2_NAME, 
comp.COMPANY_HIERARCHY_LEVEL3_NAME,
MD.FULL_DT as DAYS_MONTH,
FINANCE_HB_PB_DAYS_IN_AR.MONTHLY_ASSET_BALANCE, 
FINANCE_HB_PB_DAYS_IN_AR.ROLLING_NET_PATIENT_REVENUE, 
FINANCE_HB_PB_DAYS_IN_AR.NUMBER_OF_ROLLING_DAYS
from
CHOP_ANALYTICS.ADMIN.FINANCE_HB_PB_DAYS_IN_AR
join CDWPRD.ADMIN.MASTER_DATE MD on MD.DT_KEY = to_char(FISCAL_PERIOD_END_DT,'YYYYMMDD')
join comp on comp.COMPANY_ID = FINANCE_HB_PB_DAYS_IN_AR.COMPANY_REFERENCE_ID
where 
FULL_DT between add_months(date_trunc('month',current_date),-15) and add_months(last_day(current_date),-1)
AND 
ROLLING_MONTH_RANGE = 12
AND 
HB_PB_IND = 'HB'
;
