SELECT
HSP_TRANSACTIONS.HSP_ACCOUNT_ID,
HSP_TRANSACTIONS_2.PRIMARY_PAYOR_ID, 
CLARITY_EPM.GL_PREFIX,
CLARITY_EPM.PAYOR_NAME as PAYOR_NM,
ZC_ACCT_CLASS_HA.NAME, 
HSP_ACCOUNT.ADM_DATE_TIME, 
HSP_TRANSACTIONS.TX_POST_DATE as PST_DT,
last_day(HSP_TRANSACTIONS.TX_POST_DATE) as MONTH,
HSP_TRANSACTIONS.TX_AMOUNT AS AMT, 
CASE WHEN CLARITY_EAP.PROC_GROUP_ID IN (97,150) THEN HSP_TRANSACTIONS.TX_AMOUNT END AS REFUNDS,
CASE WHEN TX_TYPE_HA_C = 2 THEN HSP_TRANSACTIONS.TX_AMOUNT END AS PAYMENTS,
HSP_TRANSACTIONS.TX_ID, 
CLARITY_EAP.PROC_CODE, 
CLARITY_EAP.PROC_NAME,
CLARITY_EAP.PROC_CAT,
CLARITY_EAP.PROC_GROUP_ID,
GL.TITLE AS RPT_GRP_6,
TX_TYPE_HA_C
FROM  HSP_TRANSACTIONS_2
LEFT JOIN HSP_TRANSACTIONS ON HSP_TRANSACTIONS.TX_ID = HSP_TRANSACTIONS_2.TX_ID
LEFT JOIN HSP_ACCOUNT ON HSP_ACCOUNT.HSP_ACCOUNT_ID = HSP_TRANSACTIONS.HSP_ACCOUNT_ID
LEFT JOIN ZC_ACCT_CLASS_HA ON HSP_TRANSACTIONS.ACCT_CLASS_HA_C = ZC_ACCT_CLASS_HA.ACCT_CLASS_HA_C 
LEFT JOIN CLARITY_EAP ON HSP_TRANSACTIONS.PROC_ID = CLARITY_EAP.PROC_ID 
LEFT JOIN CLARITY_EPM ON HSP_TRANSACTIONS_2.PRIMARY_PAYOR_ID = CLARITY_EPM.PAYOR_ID
LEFT JOIN ZC_EPM_RPT_GRP_6 GL ON GL.RPT_GRP_SIX = CLARITY_EPM.RPT_GRP_SIX
LEFT JOIN CLARITY_EPG ON CLARITY_EPG.PROC_GROUP_ID = CLARITY_EAP.PROC_GROUP_ID
WHERE
(CLARITY_EAP.PROC_GROUP_ID IN (97,150) --REFUND ADJ,INTERCO REFUND
or
TX_TYPE_HA_C = 2) --Payments
AND 
HSP_TRANSACTIONS.TX_POST_DATE BETWEEN add_months(trunc(current_date,'month'),-12) and (current_date-1)
;