WITH DENIALS1 AS (
SELECT 
BDC_INFO.BDC_ID,
BDC_INFO.CLAIM_PRINT_ID,
BDC_INFO.BILLING_SYS_C,
BDC_INFO.RECORD_STATUS_C,
BDC_INFO.BUCKET_ID,
HSP_ACCOUNT.HSP_ACCOUNT_ID AS HSP_ACCT_ID,
HSP_ACCOUNT.HSP_ACCOUNT_NAME AS HSP_ACCT_NM,
PATIENT.PAT_MRN_ID,
SUBSTRING(HSP_ACCOUNT.PAT_ZIP,1,5) as MAILING_ZIP,
ZC_STATE.NAME AS MAILING_STATE,
--CHOP Market to be loaded as a dimension
HSP_ACCOUNT.TOT_ACCT_BAL,
ZC_ACCT_BASECLS_HA.NAME AS PAT_ACCT_CLASS,
DISCH_DEPT.DEPARTMENT_NAME AS DISCH_DEPT,
case when DISCH_DEPT.SPECIALTY is null then ZC_SPECIALTY.NAME else DISCH_DEPT.SPECIALTY end as SPECIALTY,
ADM_DEPT.DEPARTMENT_NAME AS ADMIT_DEPT,
HSP_ACCOUNT.ADM_DATE_TIME,
HSP_ACCOUNT.DISCH_DATE_TIME,
--DISCH_DEPT_CNTR to be loaded as a dimension
--ADMIT_DEPT_CNTR to be loaded as a dimension
last_day(date_trunc('month',BDC_INFO.BDC_RECEIVE_DATE)) as DENIAL_MONTH,
BDC_INFO.BDC_RECEIVE_DATE,
CLARITY_EPM.PAYOR_ID,
CLARITY_EPM.PAYOR_NAME as BUCKET_PAYER,
HSP_ACCOUNT.PRIMARY_PAYOR_ID,
PRIMARY_PAYOR.PAYOR_NAME,
case when CLARITY_EPM.PAYOR_ID = HSP_ACCOUNT.PRIMARY_PAYOR_ID then 'Y' else 'N' end as PRIMARY_PAYOR,
ZC_EPM_RPT_GRP_6.TITLE AS GL_PAYOR, 
CLARITY_EPP.BENEFIT_PLAN_NAME AS BUCKET_PLAN,
BDC_INFO.IS_INITIAL_DENIAL_YN,
NVL(ZC_OWNING_AREA.NAME,'N/A') as OWNING_AREA_NM,
NVL(ZC_OWNING_AREA.ABBR,'N/A') as OWNING_AREA_ABBR,
BDC_INFO.REMIT_CODE_ID,
BDC_INFO.REMIT_CODE_ID || ' - ' || CLARITY_RMC.REMIT_CODE_NAME  as REMIT_NM_ID,
CLARITY_RMC.REMIT_CODE_NAME,
CLARITY_RMC.SOURCE_AREA_C,
SOURCE_AREA.NAME AS "Denial Source Area",
ZC_RMC_CODE_CAT.NAME AS "Denial Category",
CLARITY_RMC.CODE_CAT_C,
NULL AS DENIAL_STATUS,
ZC_ROOT_CAUSE.NAME as ROOT_CAUSE,
HSP_BDC_DENIAL_DATA.LINE_BILLED_AMOUNT,
HSP_BDC_DENIAL_DATA.LINE_ALLWD_AMT,
HSP_BDC_DENIAL_DATA.LINE_PAID_AMT,
HSP_BDC_DENIAL_DATA.LINE_DENIED_AMT,
CLARITY_SER.PROV_ID AS ATTENDING_PROV_ID,
CLARITY_SER.PROV_NAME AS ATTENDING_PROV,
CASE WHEN PRIMARY_PAYOR.PAYOR_ID IN (
1012,1013,1019,1021,1028,1029,1030,1059,1061,1065,1071,1073,1074,1097,1105,1181) AND BDC_INFO.REMIT_CODE_ID = 252 THEN 'BC 252 Denials' ELSE 'All Others'
END AS BC252,
CASE WHEN CLARITY_EPM.PAYOR_NAME = 'HEALTH PARTNERS' AND BDC_INFO.REMIT_CODE_ID = 29 AND ZC_ACCT_BASECLS_HA.NAME = 'Inpatient' 
AND NVL((date(BDC_INFO.BDC_RECEIVE_DATE) - date(HSP_ACCOUNT.DISCH_DATE_TIME)),0) < 195 THEN 'EXCLUDE' ELSE 'INCLUDE' END AS HP29,
admitdx.current_icd10_list AS Admission_DX,
ATYPE.Point_of_Origin,
ATYPE.Admit_Type,
BTYPE.NAME  AS BUCKET_NAME,
PTSERV.NAME AS SERVICE,
DXLIST.CURRENT_ICD10_LIST AS FINAL_DX,
CASE WHEN RMK.DESCRIPTION IS NULL THEN 0 ELSE 1 END AS REMARK_IND,
HSP_ACCOUNT.ADM_DEPARMENT_ID,
HSP_ACCOUNT.DISCH_DEPT_ID
from CDW_ODS.ADMIN.BDC_INFO
LEFT JOIN CDW_ODS.ADMIN.HSP_BDC_PAYOR on HSP_BDC_PAYOR.BDC_ID = BDC_INFO.BDC_ID
LEFT JOIN CDW_ODS.ADMIN.HSP_BDC_DENIAL_DATA on HSP_BDC_DENIAL_DATA.BDC_ID = BDC_INFO.BDC_ID and HSP_BDC_DENIAL_DATA.LINE_ON_EOB = -1 --and BDC_INFO.IS_INITIAL_DENIAL_YN = 'Y'
LEFT JOIN CDW_ODS.ADMIN.CLARITY_EPM ON HSP_BDC_PAYOR.PAYOR_ID = CLARITY_EPM.PAYOR_ID
LEFT JOIN CDW_ODS.ADMIN.ZC_EPM_RPT_GRP_6 ON CLARITY_EPM.RPT_GRP_SIX = ZC_EPM_RPT_GRP_6.RPT_GRP_SIX
LEFT JOIN CDW_ODS.ADMIN.ZC_OWNING_AREA ON ZC_OWNING_AREA.OWNING_AREA_C = BDC_INFO.OWNING_AREA_C
LEFT JOIN CDW_ODS.ADMIN.HSP_BUCKET on HSP_BUCKET.BUCKET_ID = BDC_INFO.BUCKET_ID
LEFT JOIN CDW_ODS.ADMIN.CLARITY_EPP ON CLARITY_EPP.BENEFIT_PLAN_ID = HSP_BUCKET.BENEFIT_PLAN_ID
LEFT JOIN CDW_ODS.ADMIN.HSP_ACCOUNT ON HSP_ACCOUNT.HSP_ACCOUNT_ID = HSP_BUCKET.HSP_ACCOUNT_ID
LEFT JOIN CDW_ODS.ADMIN.PATIENT ON PATIENT.PAT_ID = HSP_ACCOUNT.PAT_ID
LEFT JOIN CDW_ODS.ADMIN.ZC_STATE ON ZC_STATE.STATE_C = HSP_ACCOUNT.PAT_STATE_C
LEFT JOIN CDW_ODS.ADMIN.CLARITY_SER ON CLARITY_SER.PROV_ID = HSP_ACCOUNT.ATTENDING_PROV_ID
LEFT JOIN CDW_ODS.ADMIN.CLARITY_EPM PRIMARY_PAYOR ON PRIMARY_PAYOR.PAYOR_ID = HSP_ACCOUNT.PRIMARY_PAYOR_ID
LEFT JOIN CDW_ODS.ADMIN.CLARITY_DEP DISCH_DEPT ON DISCH_DEPT.DEPARTMENT_ID = HSP_ACCOUNT.DISCH_DEPT_ID
LEFT JOIN CDW_ODS.ADMIN.CLARITY_DEP ADM_DEPT ON ADM_DEPT.DEPARTMENT_ID = HSP_ACCOUNT.ADM_DEPARMENT_ID
LEFT JOIN CDW_ODS.ADMIN.CLARITY_SER_SPEC ON CLARITY_SER_SPEC.PROV_ID = HSP_ACCOUNT.ATTENDING_PROV_ID and CLARITY_SER_SPEC.LINE = 1
LEFT JOIN CDW_ODS.ADMIN.ZC_SPECIALTY ON ZC_SPECIALTY.SPECIALTY_C = CLARITY_SER_SPEC.SPECIALTY_C
LEFT JOIN CDW_ODS.CLARITY.HSP_BDC_DENIED_DATES HSP_BDC_DENIED_DATES on HSP_BDC_DENIED_DATES.BDC_ID = BDC_INFO.BDC_ID   
LEFT JOIN CDW_ODS.CLARITY.ZC_ROOT_CAUSE on ZC_ROOT_CAUSE.ROOT_CAUSE_C = BDC_INFO.ROOT_CAUSE_C
LEFT JOIN CDW_ODS.ADMIN.ZC_ACCT_BASECLS_HA ON ZC_ACCT_BASECLS_HA.ACCT_BASECLS_HA_C = HSP_ACCOUNT.ACCT_BASECLS_HA_C
LEFT JOIN CDW_ODS.ADMIN.CLARITY_RMC ON CLARITY_RMC.REMIT_CODE_ID = BDC_INFO.REMIT_CODE_ID
LEFT JOIN CDW_ODS.ADMIN.ZC_OWNING_AREA SOURCE_AREA ON SOURCE_AREA.OWNING_AREA_C = CLARITY_RMC.SOURCE_AREA_C
LEFT JOIN CDW_ODS.ADMIN.HSP_BDC_DENIAL_DATA amt ON amt.BDC_ID = BDC_INFO.BDC_ID and amt.line_on_eob = -1
LEFT JOIN CDW_ODS.ADMIN.ZC_PAT_SERVICE PTSERV ON HSP_ACCOUNT.PRIM_SVC_HA_C  = PTSERV.HOSP_SERV_C
LEFT JOIN CDW_ODS.ADMIN.ZC_BKT_TYPE_HA BTYPE ON HSP_BUCKET.BKT_TYPE_HA_C = BTYPE.BKT_TYPE_HA_C
LEFT JOIN CDW_ODS.ADMIN.ZC_RMC_CODE_CAT ON ZC_RMC_CODE_CAT.RMC_CODE_CAT_C = CLARITY_RMC.CODE_CAT_C
LEFT JOIN CDW_ODS.ADMIN.BDC_ASSOC_REMARK_CODES CD ON CD.BDC_ID = BDC_INFO.BDC_ID AND BDC_INFO.RECORD_TYPE_C = 1
LEFT JOIN CDW_ODS.ADMIN.CLARITY_RMC RMK ON RMK.REMIT_CODE_ID = CD.REMARK_CODE_ID AND RMK.DESCRIPTION LIKE 'N522%'
LEFT JOIN (SELECT 
			adm.hsp_account_Id,
			edg.current_icd10_list 
           FROM CDW_ODS.ADMIN.HSP_ACCT_ADMIT_DX adm
           LEFT JOIN CDW_ODS.ADMIN.clarity_edg edg ON adm.admit_dx_id = edg.dx_id
           WHERE adm.line = 1) 
           admitdx ON admitdx.hsp_account_id = HSP_ACCOUNT.HSP_ACCOUNT_ID
LEFT JOIN (SELECT hsp_account_id
                  ,admit_type_ept_c
                  ,admission_src_ept_c
                  ,adm.name AS Admit_Type
                  , adm2.name AS Point_of_Origin
           FROM CDW_ODS.ADMIN.hsp_account_3 hsp3
LEFT JOIN CDW_ODS.ADMIN.zc_hosp_admsn_type adm ON hsp3.admit_type_ept_c = adm.hosp_admsn_type_c
LEFT JOIN CDW_ODS.ADMIN.zc_adm_source adm2 ON adm2.admit_source_c = hsp3.admit_type_ept_c)
		   ATYPE ON ATYPE.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID 
LEFT JOIN (SELECT DX.HSP_ACCOUNT_ID
                  ,DX.DX_ID
                  ,DX.LINE
                  ,EDG.CURRENT_ICD10_LIST 
           FROM CDW_ODS.ADMIN.HSP_ACCT_DX_LIST DX 
           LEFT JOIN CDW_ODS.ADMIN.clarity_edg edg ON DX.DX_ID = edg.dx_id
           WHERE dx.line = 1 
           ) DXLIST ON DXLIST.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID
WHERE 
BDC_INFO.RECORD_TYPE_C = 1
AND
BDC_INFO.BDC_RECEIVE_DATE between add_months(date_trunc('month',current_date),-25) and add_months(last_day(current_date),-1)
AND --These are informational or test codes
BDC_INFO.REMIT_CODE_ID not in (
'1', '100', '101', '102', '118', '123', '128', '129', '133', '158', '159', '169', '177', '179', '18', '193', '2010', '2013', '2020', 
'203', '225', '24', '276', '4023', '4057', '4081', '4086', '41', '42', '45', '49', '5005', '5019', '5045', '5111', '5142', '5258', 
'5525', '5563', '59', '6036', '6063', '6066', '63', '7021', '7023', '7777', '8018', '88', '9018', '9045', '9059', '9071', '9097', 
'92', '97', '9999'
)
AND BDC_INFO.IS_PRIM_PAYER_BDC_YN = 'Y'
AND BDC_INFO.RECORD_STATUS_C <> 99 -- Voided
AND BDC_INFO.BDC_ID not in (24914442,24914444,24904845)
AND HSP_ACCOUNT.HSP_ACCOUNT_ID not in (9005597812)
AND HSP_BDC_DENIAL_DATA.LINE_DENIED_AMT > 0
AND CLARITY_RMC.SOURCE_AREA_C <> 2204
AND CLARITY_RMC.CODE_CAT_C not in ('119','12','181')
AND CASE WHEN RMK.DESCRIPTION IS NULL THEN 0 ELSE 1 END = 0
),
DENIALS2 AS (
SELECT
ROW_NUMBER() OVER (PARTITION BY DENIALS1.HSP_ACCT_ID,DENIALS1.BUCKET_ID,DENIALS1.BDC_RECEIVE_DATE,DENIALS1.LINE_DENIED_AMT ORDER BY DENIALS1.BDC_ID asc) as BDC_1,
DENIALS1.*
FROM DENIALS1
WHERE 
BC252 = 'All Others' 
AND 
HP29 = 'INCLUDE'
)

SELECT * FROM DENIALS2 WHERE BDC_1 = 1
;