SELECT 
last_day(MASTER_DATE.FULL_DT) AS POST_MONTH,
Sum(FACT_TRANSACTION_HB.CHRG_AMT) AS AMT
FROM 
CDWPRD.ADMIN.FACT_TRANSACTION_HB 
LEFT JOIN CDWPRD.ADMIN."PROCEDURE" ON FACT_TRANSACTION_HB.PROC_KEY = "PROCEDURE".PROC_KEY 
LEFT JOIN CDWPRD.ADMIN.MASTER_DATE ON FACT_TRANSACTION_HB.POST_DT_KEY = MASTER_DATE.DT_KEY
WHERE 
MASTER_DATE.FULL_DT between add_months(date_trunc('month',current_date),-16) and add_months(last_day(current_date),-1)
AND 
"PROCEDURE".PROC_TYPE = 'Charge'
GROUP BY 1;