WITH REV AS (
SELECT 
date_trunc('month',MASTER_DATE.FULL_DT) AS CLOSE_MONTH,
PAYOR.PAYOR_ID,
PAYOR.GL_PREFIX,
WORKDAY_PAYOR.PAYOR_NM,
PAYOR.RPT_GRP_6,
sum(CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_DEBIT_MINUS_CREDIT_AMOUNT) AS REV
FROM CDWPRD.ADMIN.WORKDAY_GL_SUMMARY 
LEFT JOIN CDWPRD.ADMIN.WORKDAY_REVENUE_CATEGORY ON WORKDAY_GL_SUMMARY.REVENUE_CAT_KEY = WORKDAY_REVENUE_CATEGORY.REVENUE_CAT_KEY
LEFT JOIN CDWPRD.ADMIN.WORKDAY_LEDGER_ACCOUNT ON WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY = WORKDAY_LEDGER_ACCOUNT.LEDGER_ACCT_KEY
LEFT JOIN CDWPRD.ADMIN.MASTER_DATE ON WORKDAY_GL_SUMMARY.ACCOUNTING_MONTH_DT_KEY = MASTER_DATE.DT_KEY
LEFT JOIN CDWPRD.ADMIN.WORKDAY_PAYOR ON WORKDAY_PAYOR.PAYOR_KEY = WORKDAY_GL_SUMMARY.PAYOR_KEY
LEFT JOIN CDWPRD.ADMIN.PAYOR ON PAYOR.GL_PREFIX = WORKDAY_PAYOR.PAYOR_ID
WHERE 
CDWPRD.ADMIN.WORKDAY_REVENUE_CATEGORY.REVENUE_CAT_ID in ('RC_4000','RC_4001') 
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.COMP_KEY = 100 
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY not in (1257,1012,1085,1181,1230,23011) 
AND MASTER_DATE.FULL_DT between add_months(date_trunc('month',current_date),-14) and add_months(last_day(current_date),-2) 
GROUP BY 1,2,3,4,5),

--Working days in goal month
DAYS_FOR_AVG AS 
(
select 
date_trunc('month',md.full_dt) AS GOAL_MONTH,
count(md.full_dt) AS WORK_DAYS
from 
CDWPRD.ADMIN.MASTER_DATE md
LEFT JOIN CDW_ODS.KRONOS.HOLIDAYDATE DT on md.FULL_DT = dt.START_DATETIME
LEFT JOIN CDW_ODS.KRONOS.KRONOS_HOLIDAY NM on dt.HOLIDAYID = nm.HOLIDAYID AND NM.HOLIDAY_NAME NOT LIKE 'Norman%'
WHERE 
md.WEEKDAY_IND <> 0 
AND 
dt.HOLIDAYID IS null
AND 
md.FULL_DT between add_months(date_trunc('month',current_date),-12) AND last_day(current_date)
GROUP BY 1
),

-- Joins close month to goal month
GOAL AS (
select distinct
add_months(date_trunc('month',md.full_dt),2) AS GOAL_MONTH,
date_trunc('month',md.full_dt) AS CLOSE_MONTH,
PAYOR_ID,
PAYOR_NM,
RPT_GRP_6,
GL_PREFIX,
REV,
WORK_DAYS,
Round(REV/WORK_DAYS) AS DAILY_NET_REV
from 
CDWPRD.ADMIN.MASTER_DATE md
JOIN REV ON REV.CLOSE_MONTH = date_trunc('month',md.full_dt)
JOIN DAYS_FOR_AVG ON DAYS_FOR_AVG.GOAL_MONTH = add_months(date_trunc('month',md.full_dt),2)
WHERE 
md.FULL_DT between add_months(date_trunc('month',current_date),-14) AND add_months(last_day(current_date),-2)
),
-- Populates a day for each working day in the month 
DAYS AS (
select 
date_trunc('month',md.full_dt) AS GOAL_MONTH,
md.full_dt
from 
CDWPRD.ADMIN.MASTER_DATE md
WHERE 
md.FULL_DT between add_months(date_trunc('month',current_date),-12) AND last_day(current_date)
)

SELECT 
DAYS.FULL_DT,
GOAL.GOAL_MONTH,
GOAL.CLOSE_MONTH,
GOAL.GL_PREFIX,
GOAL.PAYOR_NM,
GOAL.RPT_GRP_6,
GOAL.GL_PREFIX,
GOAL.REV AS MONTHLY_REVENUE,
GOAL.WORK_DAYS AS DAYS_FOR_AVG,
GOAL.DAILY_NET_REV
FROM DAYS
JOIN GOAL ON GOAL.GOAL_MONTH = DAYS.GOAL_MONTH
;
