WITH STEP1 AS (
SELECT 
MASTER_DATE.FULL_DT,
sum(CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_DEBIT_MINUS_CREDIT_AMOUNT) AS AMT
FROM CDWPRD.ADMIN.WORKDAY_GL_SUMMARY 
LEFT JOIN CDWPRD.ADMIN.WORKDAY_REVENUE_CATEGORY ON WORKDAY_GL_SUMMARY.REVENUE_CAT_KEY = WORKDAY_REVENUE_CATEGORY.REVENUE_CAT_KEY
LEFT JOIN CDWPRD.ADMIN.WORKDAY_LEDGER_ACCOUNT ON WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY = WORKDAY_LEDGER_ACCOUNT.LEDGER_ACCT_KEY
LEFT JOIN CDWPRD.ADMIN.MASTER_DATE ON WORKDAY_GL_SUMMARY.ACCOUNTING_MONTH_DT_KEY = MASTER_DATE.DT_KEY
WHERE 
CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.REVENUE_CAT_KEY in (1095, 1107)
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.COMP_KEY = 100
AND CDWPRD.ADMIN.WORKDAY_GL_SUMMARY.LEDGER_ACCT_KEY not in (1257,1012,1085,1181,1230)
AND MASTER_DATE.FULL_DT between add_months(date_trunc('month',current_date),-24) and add_months(last_day(current_date),-1)
GROUP BY 1
) --52000
,
STEP2 AS (

SELECT 
FULL_DT as POST_MONTH,
AMT AS NET_REVENUE,
TRUNC(AVG(AMT) OVER(ORDER BY FULL_DT ROWS BETWEEN 4 PRECEDING AND 2 PRECEDING), 2) AS AMT
FROM STEP1
WHERE FULL_DT between add_months(date_trunc('month',current_date),-24) and add_months(last_day(current_date),-1)
)

SELECT 
POST_MONTH,
NET_REVENUE,
AMT
FROM STEP2
WHERE POST_MONTH between add_months(date_trunc('month',current_date),-15) and add_months(last_day(current_date),-2)
;