WITH CATH_STUDY AS
(SELECT * FROM CDW_STG..S_CDW_IMPACT_CATHSTUDY
where surg_enc_id in 
(2048131517,
2053072527,
2058775852,
2060705494
)
)

,SBALTEQ AS
(
SELECT  SBALTEQ.REFNO,
        IP7230,
		IP7245,
		CPOHI,
		IP7250,
		CPOEBD,
		IP7260,
        IP7265
FROM SENSIS_SBALTEQ SBALTEQ JOIN (SELECT REFNO, MAX(SEQNO) SEQNO FROM SENSIS_SBALTEQ GROUP BY REFNO) SBALSEQ ON SBALSEQ.REFNO = SBALTEQ.REFNO AND SBALSEQ.SEQNO = SBALTEQ.SEQNO
)

,DBALTEQ AS
(SELECT DBALTEQ.REFNO,
        IP7230,
		IP7275,
		CPOHI,
		IP7280,
		CPOEBD,
		IP7295,
		CPOHI2,
		IP7300,
		CPOEBD2,
		IP7310,
		IP7315
FROM SENSIS_DBALTEQ DBALTEQ JOIN (SELECT REFNO, MAX(SEQNO) SEQNO FROM SENSIS_DBALTEQ GROUP BY REFNO) DBALSEQ ON DBALSEQ.REFNO = DBALTEQ.REFNO AND DBALSEQ.SEQNO = DBALTEQ.SEQNO
)

	
	SELECT DISTINCT
        SURG_ENC_ID
		,CASE WHEN PVDATA.IP7400 = 1 THEN 1552  
		      WHEN PVDATA.IP7400 = 2 THEN 1553  
			  WHEN PVDATA.IP7400 = 3 THEN 1554  
			  WHEN PVDATA.IP7400 = 4 THEN 2011  
		 ELSE NULL END AS PVPROCIND
		,CASE WHEN PVDATA.IP7405 = 1 THEN 1555 
		      WHEN PVDATA.IP7405 = 2 THEN 1556 
		 ELSE NULL END AS PVMORPHOLOGY
		,PVDATA.IP7410 PVSUBSTENOSIS
		,PVDATA.IP7415 PVDIAMETER
		,CAST(PVDATA.IP7420 AS NUMERIC(4,1)) PVPREPKSYSGRAD
		,NULL AS PVDEFECTTREATED
		,CASE WHEN PVDATA.IP7420 IS NULL THEN 1 ELSE 0 END AS PVPREPKSYSGRADNA
		,CASE WHEN SBALTEQ.REFNO IS NOT NULL THEN 1487
              WHEN DBALTEQ.REFNO IS NOT NULL THEN 1488 END AS PVBALLTECH
		--,IPDINDIC.IP7525 PVBALL1DEVID
		,IPDEVCE.IMPACT  PVBALL1DEVID --SBALTEQ.IP7230 mapped through dicaccdev 
		,null  PVBALL2DEVID --DBALTEQ.IP7230 mapped through dicaccdev
		,COALESCE(DBALTEQ.IP7275,SBALTEQ.IP7245) PVBALLSTAB
		,COALESCE(DBALTEQ.IP7280,SBALTEQ.IP7250) PVBALLPRESSURE
		,CASE WHEN IPDEVCE.IP7090 = 4 THEN 1498
		      WHEN IPDEVCE.IP7090 = 5 THEN 1499
		 ELSE NULL END AS PVBALLOUTCOME
		,CAST(COALESCE(DBALTEQ.IP7310,SBALTEQ.IP7260) AS NUMERIC(4,1)) PVPOSTPKSYSGRAD
		,CASE WHEN COALESCE(DBALTEQ.IP7310,SBALTEQ.IP7260) IS NULL THEN '1'
		       ELSE NULL END PVPOSTPKSYSGRADNA 

  FROM CATH_STUDY STUDY JOIN SENSIS_PVDATA PVDATA ON STUDY.REFNO = PVDATA.REFNO
                        LEFT JOIN SENSIS_IPDINDIC IPDINDIC ON STUDY.REFNO = IPDINDIC.REFNO
						LEFT JOIN SBALTEQ ON SBALTEQ.REFNO = PVDATA.REFNO					
						LEFT JOIN DBALTEQ ON DBALTEQ.REFNO = PVDATA.REFNO	
						LEFT JOIN (SELECT *,ROW_NUMBER() OVER(PARTITION BY REFNO ORDER BY SEQNO) ROW FROM SENSIS_IPDEVCE) IPDEVCE ON STUDY.REFNO = IPDEVCE.REFNO AND ROW =1 
						--LEFT JOIN SENSIS_IP2DVCE IP2DVCE ON STUDY.REFNO = IP2DVCE.REFNO