WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)

SELECT 	        SURG_ENC_ID
		,CASE WHEN COADATA.IP7100 = 1 THEN 1506
		      WHEN COADATA.IP7100 = 2 THEN 1509
			  WHEN COADATA.IP7100 = 3 THEN 1507
			  WHEN COADATA.IP7100 = 4 THEN 1510
			  WHEN COADATA.IP7100 = 5 THEN 1508
			  WHEN COADATA.IP7100 = 6 THEN 1511
			  WHEN COADATA.IP7100 = 7 THEN 4160
		 ELSE NULL END AS COARCPROCIND
		,CAST(COADATA.IP7105 AS NUMERIC(4,1)) COARCPREDIAMETER	
		,CAST(COADATA.IP7110 AS NUMERIC(4,1)) COARCPREPKSYSGRAD
		,COADATA.IP7115 COARCDEFECTTREATED
		,CAST(COADATA.IP7120 AS NUMERIC(4,1)) COARCPOSTDIAMETER		
		,CAST(COADATA.IP7125 AS NUMERIC(4,1)) COARCPOSTPKSYSGRAD				
		,CASE WHEN COADATA.CPOTOC = 1 THEN 4029
		      WHEN COADATA.CPOTOC = 2 THEN 4030
			  ELSE NULL END AS COARCNATURE
		,CASE WHEN COADATA.IP7102 = 1 THEN 4031
		      WHEN COADATA.IP7102 = 1 THEN 4032
			  ELSE NULL END AS COARCPRIORTREAT
		,COADATA.IP7126 COARCADDLAORTOBS
		,COADATA.IP7127 COARCAORTICARCHINTER
		,CAST(COADATA.IP7128 AS NUMERIC(4,1)) COARCPRESYSGRADIENT
		,CAST(COADATA.IP7129 AS NUMERIC(4,1)) COARCPOSTSYSGRADIENT	
		,CASE WHEN COADATA.IP7105 IS NULL THEN 1 ELSE 0 END COARCPREDIAMETERNA			
		,CASE WHEN COADATA.IP7110 IS NULL THEN 1 ELSE 0 END COARCPREPKSYSGRADNA
		,CASE WHEN COADATA.IP7120 IS NULL THEN 1 ELSE 0 END COARCPOSTDIAMETERNA
		,CASE WHEN COADATA.IP7125 IS NULL THEN 1 ELSE 0 END COARCPOSTPKSYSGRADNA


FROM CATH_STUDY STUDY JOIN SENSIS_COADATA COADATA ON STUDY.REFNO = COADATA.REFNO
