WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)
  
  
  
    select
        SURG_ENC_ID
		,CASE WHEN AOVDATA.IP7200 = 1 THEN 1494
		      WHEN AOVDATA.IP7200 = 2 THEN 1496
			  WHEN AOVDATA.IP7200 = 4 THEN 1497
			  ELSE NULL END AS  AVPROCIND
		,CASE WHEN AOVDATA.IP7205 = 1 THEN 1482
		      WHEN AOVDATA.IP7205 = 2 THEN 1483
			  WHEN AOVDATA.IP7205 = 3 THEN 1484
			  WHEN AOVDATA.IP7205 = 4 THEN 1485
			  WHEN AOVDATA.IP7205 = 5 THEN 1486
			  ELSE NULL END AS AVMORPHOLOGY
		,CASE WHEN AOVDATA.IP7210 = 0 THEN 1489
		      WHEN AOVDATA.IP7210 = 1 THEN 1490
		      WHEN AOVDATA.IP7210 = 2 THEN 1491
			  WHEN AOVDATA.IP7210 = 3 THEN 1492
			  WHEN AOVDATA.IP7210 = 4 THEN 1493
			  ELSE NULL END AS AVPREINSUFF
		,cast(AOVDATA.IP7215 as NUMERIC(4,1)) AVDIAMETER
		,CAST(AOVDATA.IP7220 AS NUMERIC(5,1)) AVPREPKSYSTGRAD
		,IP2DVCE.IMPUSE AVDEFECTTREATED
  FROM CATH_STUDY STUDY JOIN SENSIS_AOVDATA AOVDATA ON STUDY.REFNO = AOVDATA.REFNO 
						LEFT JOIN SENSIS_IP2DVCE IP2DVCE ON STUDY.REFNO = IP2DVCE.REFNO
