WITH CATH_STUDY AS
(SELECT cath_study.*, VAI.VSI_KEY FROM CDW_STG_DEV..S_CDW_IMPACT_CATHSTUDY CATH_STUDY JOIN cdwuat..VISIT_ADDL_INFO VAI ON VAI.PAT_KEY = CATH_STUDY.PAT_KEY 
)

,FLOWSHEET AS
(SELECT CATH_STUDY.REFNO,
         VAI.PAT_KEY,
		 VAI.VSI_KEY,
		 FLOW_MEA.REC_DT,
	     MEAS_VAL,
		 FS_ID
FROM 
    CATH_STUDY
	JOIN cdwuat..VISIT_ADDL_INFO VAI ON VAI.PAT_KEY = CATH_STUDY.PAT_KEY 
	JOIN cdwuat..FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
    JOIN cdwuat..FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY AND CAST(FLOW_MEA.REC_DT AS DATE) <= CATH_STUDY.STUDATE
    JOIN cdwuat..FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY
WHERE FS_ID IN (10,11,14)
)



,PAT_CURR_WT AS 
 (SELECT CATH_STUDY.REFNO,
         CATH_STUDY.PAT_KEY,
         STUDATE,
		 FLOW.REC_DT,
	     CAST(MEAS_VAL/35.274 AS NUMERIC(5,2)) PAT_WT,
	     ROW_NUMBER() OVER (PARTITION BY CATH_STUDY.REFNO ORDER BY FLOW.REC_DT DESC) REC_ORDER
FROM 
    CATH_STUDY
	JOIN FLOWSHEET FLOW ON CATH_STUDY.VSI_KEY=FLOW.VSI_KEY 
WHERE FS_ID = 14
)




,PAT_CURR_HT AS
 (SELECT CATH_STUDY.REFNO,
         CATH_STUDY.PAT_KEY,
         STUDATE,
		 FLOW.REC_DT,
	     CAST(MEAS_VAL*2.54 AS NUMERIC(5,2)) PAT_HT,
	     ROW_NUMBER() OVER (PARTITION BY CATH_STUDY.REFNO ORDER BY CAST(MEAS_VAL*2.54 AS NUMERIC(5,2)) DESC) REC_ORDER
FROM 
    CATH_STUDY
	JOIN FLOWSHEET FLOW ON CATH_STUDY.VSI_KEY=FLOW.VSI_KEY 
WHERE FS_ID = 11
)



, PREPROC_HEMO AS
 (select
         CATH_STUDY.PAT_KEY
        ,STUDATE
		,RSLT_DT
		,CATH_STUDY.REFNO
	    ,CASE WHEN COMP.RSLT_COMP_ID in (5, 34) THEN RSLT_NUM_VAL END AS HEMOGLOBIN
        ,EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT) ANESRECDATEDIFF
        ,ROW_NUMBER() OVER (PARTITION BY REFNO ORDER BY EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT)) REC_ORDER
--SELECT *
 from CATH_STUDY JOIN cdwuat..PROCEDURE_ORDER_RESULT RSLT ON RSLT.PAT_KEY = CATH_STUDY.PAT_KEY AND CAST(RSLT_DT AS DATE) <= STUDATE
                 join cdwuat..RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY

 WHERE 1=1
   AND COMP.RSLT_COMP_ID IN (5, 34)
   AND RSLT_NUM_VAL <> 9999999
   AND EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT) BETWEEN 0 and 2592000

)

, PREPROC_LABS AS
( SELECT CATH_STUDY.REFNO
         ,PH
		 ,PCO2
		 ,CAST(HGB AS NUMERIC (5,2)) HGB
		 ,PAT_MRN_ID
        ,ROW_NUMBER() OVER (PARTITION BY CATH_STUDY.REFNO ORDER BY EXTRACT(EPOCH FROM SH_ACC_TM-AUTOTIME) DESC) REC_ORDER
  FROM CATH_STUDY JOIN SENSIS_BG BG ON CATH_STUDY.REFNO = BG.REFNO
    WHERE HGB IS NOT NULL
)



, PREPROC_CREAT AS
 (select
         CATH_STUDY.PAT_KEY
        ,STUDATE
		,SH_ACC_TM
		,PREND
		,RSLT_DT
        ,CATH_STUDY.REFNO
	    ,CASE WHEN COMP.RSLT_COMP_ID = 84 THEN RSLT_NUM_VAL END AS CREATININE
        ,EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT) ANESRECDATEDIFF
        ,ROW_NUMBER() OVER (PARTITION BY REFNO ORDER BY EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT), RSLT.PROC_ORD_KEY) REC_ORDER
--SELECT *
 from CATH_STUDY JOIN cdwuat..PROCEDURE_ORDER_RESULT RSLT ON RSLT.PAT_KEY = CATH_STUDY.PAT_KEY AND CAST(RSLT_DT AS DATE) <= STUDATE
                 join cdwuat..RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY

 WHERE 1=1
   AND COMP.RSLT_COMP_ID IN (84)
   AND RSLT_NUM_VAL <> 9999999
   AND (EXTRACT(EPOCH FROM SH_ACC_TM-RSLT_DT) BETWEEN 0 and 2592000 or RSLT_DT BETWEEN SH_ACC_TM AND PREND)
   
)


, PREPROC_O2SAT AS
 (SELECT
         CATH_STUDY.PAT_KEY,
         STUDATE,
		 SH_ACC_TM,
		 CATH_STUDY.REFNO,
		 FLOW.REC_DT,
	     TO_NUMBER(ISNULL(MEAS_VAL,'0'),'999.99') AS O2SAT,
		 EXTRACT(EPOCH FROM SH_ACC_TM-FLOW.REC_DT) diff,
	     ROW_NUMBER() OVER (PARTITION BY CATH_STUDY.REFNO ORDER BY EXTRACT(EPOCH FROM SH_ACC_TM-FLOW.REC_DT)) REC_ORDER
FROM 
    CATH_STUDY
	JOIN FLOWSHEET FLOW ON CATH_STUDY.VSI_KEY=FLOW.VSI_KEY 
WHERE FS_ID = 10
   AND EXTRACT(EPOCH FROM SH_ACC_TM-FLOW.REC_DT) BETWEEN 0 and 2592000
)




,PREPROC_MEDS AS 
(SELECT CATH.REFNO
      ,MIN(CASE WHEN PRMEDS.IP4045 in (1,2,3,4,5,6,7,8,9) THEN '1' ELSE '2' END)	 PREPROCMED
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 1	THEN '1' ELSE '2' END)   PREPROCANTIARR
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 2	THEN '1' ELSE '2' END)	 PREPROCANTICOAG
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 3	THEN '1' ELSE '2' END)	 PREPROCANTIHYP
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 4	THEN '1' ELSE '2' END)	 PREPROCANTIPLATELET
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 5	THEN '1' ELSE '2' END)	 PREPROCBB
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 6	THEN '1' ELSE '2' END)	 PREPROCDIURETIC
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 7	THEN '1' ELSE '2' END)	 PREPROCPROSTA
	  ,MIN(CASE WHEN PRMEDS.IP4045 = 9	THEN '1' ELSE '2' END)	 PREPROCVASO	  
FROM CATH_STUDY CATH JOIN SENSIS_PRMEDS PRMEDS ON CATH.REFNO = PRMEDS.REFNO
                     JOIN SENSIS_DICIP4045 DICIP4045 ON DICIP4045.CODE = PRMEDS.IP4045 
GROUP BY CATH.REFNO				 
)

,PREPROC_COND AS
(SELECT CATH.PAT_KEY 
       ,CATH.STUDATE
	   ,CATH.REFNO
	   ,IP3245 SVDEFECT
	   ,IP4030 NEC
	   ,IP4035 SEPSIS
	   ,IP4040 PREG
FROM CATH_STUDY CATH JOIN SENSIS_PREPCON PREPCON ON CATH.REFNO = PREPCON.REFNO
)

,PREPROC_RHY
AS
(SELECT CATH.REFNO
      ,MIN(CASE WHEN PRECG.IP4060 = 1	THEN '1' ELSE '2' END)	 PREPROCSINUS
	  ,MIN(CASE WHEN PRECG.IP4060 = 2	THEN '1' ELSE '2' END)   PREPROCAET
	  ,MIN(CASE WHEN PRECG.IP4060 = 3	THEN '1' ELSE '2' END)	 PREPROCSVT
	  ,MIN(CASE WHEN PRECG.IP4060 = 4	THEN '1' ELSE '2' END)	 PREPROCAFIB
	  ,MIN(CASE WHEN PRECG.IP4060 = 5	THEN '1' ELSE '2' END)	 PREPROCJUNCT
	  ,MIN(CASE WHEN PRECG.IP4060 = 6	THEN '1' ELSE '2' END)	 PREPROCIDIO
	  ,MIN(CASE WHEN PRECG.IP4060 = 7	THEN '1' ELSE '2' END)	 PREPROCAVB2
	  ,MIN(CASE WHEN PRECG.IP4060 = 8	THEN '1' ELSE '2' END)	 PREPROCAVB3
	  ,MIN(CASE WHEN PRECG.IP4060 = 9	THEN '1' ELSE '2' END)	 PREPROCPACED
FROM CATH_STUDY CATH JOIN SENSIS_PRECG PRECG ON CATH.REFNO = PRECG.REFNO
GROUP BY CATH.REFNO
                     
)

,PROC_PERF AS
(SELECT CATH.PAT_KEY 
       ,CATH.STUDATE
	   ,CATH.REFNO
	   	,PEDPP.IP5000 PROCDXCATH
		,PEDPP.IP5001 PROCASD
		,PEDPP.IP5002 PROCCOARC
		,PEDPP.IP5003 PROCAORTICVALV
		,PEDPP.IP5004 PROCPULMONARYVALV
		,PEDPP.IP5005 PROCPDA
		,PEDPP.IP5006 PROCPROXPASTENT
		,PEDPP.IP5007 PROCEPCATH
		,PEDPP.IP5008 PROCEPABLATION
		,PEDPP.IP5009 PROCTPVR
 FROM CATH_STUDY CATH JOIN SENSIS_PEDPP PEDPP ON CATH.REFNO = PEDPP.REFNO
)

, SPEC_PROC AS
(SELECT CATH.PAT_KEY 
       ,CATH.STUDATE
,PEDPR.*
 FROM CATH_STUDY CATH JOIN SENSIS_PEDPR PEDPR ON CATH.REFNO = PEDPR.REFNO
 )
 
 ,AIRWAY AS
 ( SELECT CATH.REFNO
        ,IP5071 AIRMNG
	    ,MAX(CASE WHEN IP5075 = '2' THEN '1' ELSE '2' END ) AS AIRMNGLMA
	    ,MAX(CASE WHEN IP5075 = '3' THEN '1' ELSE '2' END ) AS AIRMNGTRACH
		,MAX(CASE WHEN IP5075 = '4' THEN '1' ELSE '2' END ) AS AIRMNGBAGMASK
		,MAX(CASE WHEN IP5075 = '5' THEN '1' ELSE '2' END ) AS AIRMNGCPAP
		,MAX(CASE WHEN IP5075 = '6' THEN '1' ELSE '2' END ) AS AIRMNGELECINTUB
		,MAX(CASE WHEN IP5075 = '7' THEN '1' ELSE '2' END ) AS AIRMNGPREVINTUB
		,ROW_NUMBER() OVER (PARTITION BY CATH.REFNO ORDER BY AIRMNG) AIRWAY_ROW		
--SELECT * FROM SENSIS_DICIP5075
 FROM CATH_STUDY CATH JOIN SENSIS_IMARWY IMARWY  ON CATH.REFNO = IMARWY.REFNO
                           JOIN SENSIS_DICIP5075 IP5075 ON IMARWY.IP5075 = IP5075.CODE
 GROUP BY CATH.REFNO, IP5071
 )
 
 ,VENOUS_LOC AS
 
 (SELECT A.REFNO,
		CASE WHEN VEIN+ARTERY = 2 THEN 1456
		     WHEN VEIN = 1 THEN 1454
			 WHEN ARTERY = 1 THEN 1455
			 ELSE NULL END AS ACCESSLOC,
		CASE WHEN ENTSIT = 1 THEN 1564 
		     WHEN ENTSIT = 2 THEN 1565 
			 WHEN ENTSIT = 3 THEN 1566 
			 WHEN ENTSIT = 4 THEN 1567 
			 WHEN ENTSIT = 5 THEN 1568 
			 WHEN ENTSIT = 6 THEN 1569 
			 WHEN ENTSIT = 7 THEN 1570 
			 WHEN ENTSIT = 8 THEN 1571 
			 WHEN ENTSIT = 9 THEN 1572 
			 WHEN ENTSIT = 10 THEN 1573 
		 ELSE 1575 END AS VENACCESS,
		VENLARGSHEATH VENLARGSHEATH,
		2 AS VENCLOSUREMETHODND,
		COALESCE(SIZEORDER,1) SIZEORDER
   FROM		
   
	 (SELECT CATH.REFNO
			,MAX(CASE WHEN UPPER(SITE.MEANING) LIKE '%VEIN%' THEN 1 ELSE 0 END) AS VEIN
			,MAX(CASE WHEN UPPER(SITE.MEANING) LIKE '%ARTERY%' THEN 1 ELSE 0 END) AS ARTERY 
	 FROM CATH_STUDY CATH JOIN SENSIS_ASR ASR ON CATH.REFNO = ASR.REFNO
	                      JOIN SENSIS_DICSHESIZ DICSHESIZ ON ASR.SHESIZE = DICSHESIZ.CODE
						  LEFT JOIN SENSIS_DICES1TE SITE ON SITE.CODE = ASR.ENTSIT
		   GROUP BY CATH.REFNO
	  ) A
	  
	  LEFT JOIN
	  
	 (SELECT REFNO,
	         ENTSIT,
			 VENLARGSHEATH,
			 ROW_NUMBER() OVER (PARTITION BY REFNO ORDER BY VENLARGSHEATH DESC, SHTIME, SEQNO) SIZEORDER
        FROM
		     (SELECT CATH.REFNO
					,SITE.MEANING
					,ASR.ENTSIT
					,SHTIME
					,ASR.SEQNO
					--,DICSHESIZ.MEANING SHESIZE
					 ,CASE WHEN LENGTH(REGEXP_REPLACE(TRIM(BOTH ' ' FROM SUBSTRING(DICSHESIZ.MEANING,INSTR(DICSHESIZ.MEANING, 'F ')-2,2)),'[^0-9]','')) >= 1
                           THEN CAST(REGEXP_REPLACE(TRIM(BOTH ' ' FROM SUBSTRING(DICSHESIZ.MEANING,INSTR(DICSHESIZ.MEANING, 'F ')-2,2)),'[^0-9]','') AS INTEGER)
						   ELSE 0 END AS  VENLARGSHEATH
			  FROM CATH_STUDY CATH JOIN SENSIS_ASR ASR ON CATH.REFNO = ASR.REFNO
			                      JOIN SENSIS_DICSHESIZ DICSHESIZ ON ASR.SHESIZE = DICSHESIZ.CODE
								  LEFT JOIN SENSIS_DICES1TE SITE ON SITE.CODE = ASR.ENTSIT
			  WHERE UPPER(SITE.MEANING) LIKE '%VEIN%'
			  ) B
      )ACCESS
	  
	  ON A.REFNO = ACCESS.REFNO 
)


,ARTERIAL_LOC AS
 
 (SELECT ACCESS.REFNO,
		CASE WHEN ENTSIT = 14 THEN 1459 
		     WHEN ENTSIT = 15 THEN 1460
			 WHEN ENTSIT = 16 THEN 1461 
			 WHEN ENTSIT = 17 THEN 1462 
			 WHEN ENTSIT = 18 THEN 1463 
			 WHEN ENTSIT = 19 THEN 1464 
			 WHEN ENTSIT = 20 THEN 1465 
			 WHEN ENTSIT = 21 THEN 1466
        END AS ARTACCESS,
		ARTLARGSHEATH,
		2 AS ARTCLOSUREMETHODND,
		SIZEORDER
   FROM		
  
	  
	 (SELECT REFNO,
	         ENTSIT,
			 ARTLARGSHEATH,
			 ROW_NUMBER() OVER (PARTITION BY REFNO ORDER BY ARTLARGSHEATH DESC, SHTIME, SEQNO) SIZEORDER
        FROM
		     (SELECT CATH.REFNO
					,SITE.MEANING
					,ASR.ENTSIT
					,SHTIME
					,ASR.SEQNO
					--,DICSHESIZ.MEANING SHESIZE
					 ,CASE WHEN LENGTH(REGEXP_REPLACE(TRIM(BOTH ' ' FROM SUBSTRING(DICSHESIZ.MEANING,INSTR(DICSHESIZ.MEANING, 'F ')-2,2)),'[^0-9]','')) >= 1
                           THEN CAST(REGEXP_REPLACE(TRIM(BOTH ' ' FROM SUBSTRING(DICSHESIZ.MEANING,INSTR(DICSHESIZ.MEANING, 'F ')-2,2)),'[^0-9]','') AS INTEGER)
						   ELSE 0 END AS  ARTLARGSHEATH
			  FROM CATH_STUDY CATH JOIN SENSIS_ASR ASR ON CATH.REFNO = ASR.REFNO
			                      JOIN SENSIS_DICSHESIZ DICSHESIZ ON ASR.SHESIZE = DICSHESIZ.CODE
								  LEFT JOIN SENSIS_DICES1TE SITE ON SITE.CODE = ASR.ENTSIT
			  WHERE UPPER(SITE.MEANING) LIKE '%ARTERY%'
			  ) B
      )ACCESS
	  

)

,XRAY_PLANE AS
( SELECT STUDY.REFNO,
         MAX(CASE WHEN PLANE = 'A' THEN 1 ELSE 0 END) AS PLANEA,
		 MAX(CASE WHEN PLANE = 'B' THEN 1 ELSE 0 END) AS PLANEB		 
  FROM CATH_STUDY STUDY JOIN SENSIS_XRAY XRAY ON STUDY.REFNO = XRAY.REFNO
  GROUP BY STUDY.REFNO
)

,HEPARIN AS

(SELECT DISTINCT
         REFNO
  FROM
  (SELECT ME.REFNO,
         ME.AUTOTIME,
		 MEDICA,
		 ME.AMOUNT
  FROM CATH_STUDY STUDY JOIN SENSIS_ME ME ON STUDY.REFNO = ME.REFNO
  WHERE MEDICA IN (8,26)
  
  UNION ALL
  
  SELECT ZA.REFNO,
		 ZA.AUTOTIME,
		 ZA.MEDICA,
		 ZA.AMOUNT
  FROM CATH_STUDY STUDY JOIN SENSIS_ZA ZA ON STUDY.REFNO = ZA.REFNO
  WHERE MEDICA IN (8,26)
  ) HEP

)

,ACT AS

(
SELECT ACT.REFNO,
       MAX(ACT.ACT) ACTPEAK
  FROM CATH_STUDY STUDY JOIN SENSIS_ACT ACT ON STUDY.REFNO = ACT.REFNO
GROUP BY ACT.REFNO  

)


,CATH_PROCEDURE AS --NEED TO MAP THE PROVIDER FROM SENSIS TO CA PROVIDERS?
(SELECT  CATH.PAT_KEY 
        ,CATH.STUDATE
		,CATH.REFNO
	    ,CASE WHEN APTVER2.PTSTAT = 2 THEN 1522
		      WHEN APTVER2.PTSTAT = 3 THEN 1523
			  WHEN APTVER2.PTSTAT = 4 THEN 1524
			  WHEN APTVER2.PTSTAT = 5 THEN 1525
			  WHEN APTVER2.PTSTAT = 6 THEN 1526
			  WHEN APTVER2.PTSTAT = 7 THEN 1527
		ELSE NULL END AS HOSPSTATUS
		,CASE WHEN APTVER2.DPRSTAT = 1 THEN 982 
		      WHEN APTVER2.DPRSTAT = 2 THEN 983 
			  WHEN APTVER2.DPRSTAT = 3 THEN 984 
			  WHEN APTVER2.DPRSTAT = 4 THEN 985 
		ELSE NULL END AS PROCSTATUS
		,PHYS.DOPER OPERATORNAME
		,PHYS.NPI1 OPERATORNPI
		,CASE WHEN ISNULL(SECOND_PHYS.MULTIPHYS,0) = 1 THEN 2
		      WHEN ISNULL(SECOND_PHYS.MULTIPHYS,0) > 1 THEN 1
		 ELSE NULL END AS SECONDPARTICIPATING
		,APTVER2.IP5025 TRAINEE
		,CT.CASEID AUX5
		,CT.PATIM SCHEDARRIVALDATE
	   	,ASR.SHTIME PROCSTARTDATE --SHEATH ACCESS
		,ASR.SHTIME PROCSTARTTIME
		,CAST(POCT.PLTIM AS DATE) PROCENDDATE
		,POCT.PREND PROCENDTIME
	    ,APTVER2.IP5060 ANESPRESENT
		,CASE WHEN APTVER2.IP5060 = 1 THEN NULL
		      WHEN APTVER2.IP5060 = 2 AND APTVER2.IP5065 > 1 THEN 2
			  WHEN APTVER2.IP5060 = 2 AND APTVER2.IP5065 = 1 THEN 1
			  ELSE NULL END AS ANESCALLEDIN
		,CASE WHEN APTVER2.IP5070 = 1 THEN 1557
		      WHEN APTVER2.IP5070 = 2 THEN 1558 
			  WHEN APTVER2.IP5070 = 3 THEN 1559 
			  WHEN APTVER2.IP5070 = 4 THEN 1560 
			  WHEN APTVER2.IP5070 = 5 THEN 1561 
			  WHEN APTVER2.IP5070 = 6 THEN 1562 
			  WHEN APTVER2.IP5070 = 7 THEN 1563 
		 ELSE NULL END AS SEDATION
	    ,AIRMNG
		,AIRMNGLMA
		,AIRMNGTRACH
		,AIRMNGBAGMASK
		,AIRMNGCPAP
		,AIRMNGELECINTUB
		,AIRMNGPREVINTUB
		,XRAYBSUM.FLTIME FLUOROTIME
		,ANGIO.TOT_COST CONTRASTVOL
		,APTVER3.IP5160 INOTROPE
		,CASE WHEN APTVER3.IP5165 = 1 THEN 1528  
              WHEN APTVER3.IP5165 = 2 THEN 1529 
              WHEN APTVER3.IP5165 = 3 THEN 1530
			  WHEN APTVER3.IP5165 = 4 THEN 1531
			  WHEN APTVER3.IP5165 = 5 THEN 1532
		 ELSE NULL END AS INOTROPEUSE
		,CASE WHEN APTVER3.IP5170 = 548 THEN 1515
		      WHEN APTVER3.IP5170 = 549 THEN 1516
			  WHEN APTVER3.IP5170 = 551 THEN 1517
		ELSE NULL END AS ECMOUSE
		,CASE WHEN APTVER3.IP5175 = 548 THEN 1515
		      WHEN APTVER3.IP5175 = 549 THEN 1516
			  WHEN APTVER3.IP5175 = 551 THEN 1517
		ELSE NULL END AS LVADUSE
		,CASE WHEN APTVER3.IP5180 = 548 THEN 1515
		      WHEN APTVER3.IP5180 = 549 THEN 1516
			  WHEN APTVER3.IP5180 = 551 THEN 1517
		ELSE NULL END AS IABPUSE
		,CASE WHEN XRAY_PLANE.PLANEA+XRAY_PLANE.PLANEB = 2 THEN 4090
              WHEN XRAY_PLANE.PLANEA+XRAY_PLANE.PLANEB = 1 THEN 4089
			  ELSE NULL END AS PLANEUSED
		,CAST(XRAYBSUM.DOSE AS INTEGER) FLUORODOSEDAP
		,4084 AS FLUORODOSEDAP_UNITS
		,CAST(XRAYBSUM.SKNDS AS INTEGER) FLUORODOSEKERM
		,4087 as FLUORODOSEKERM_UNITS
FROM CATH_STUDY CATH LEFT JOIN SENSIS_APTVER2 APTVER2 ON CATH.REFNO = APTVER2.REFNO
                     LEFT JOIN SENSIS_APTVER3 APTVER3 ON CATH.REFNO = APTVER3.REFNO
                     LEFT JOIN SENSIS_PHYS PHYS ON PHYS.REFNO = CATH.REFNO AND SEQNO = 1
					 LEFT JOIN (SELECT REFNO, COUNT(NPI1) MULTIPHYS FROM SENSIS_PHYS GROUP BY REFNO) SECOND_PHYS ON SECOND_PHYS.REFNO = CATH.REFNO
					 LEFT JOIN SENSIS_CT CT ON CATH.REFNO = CT.REFNO
					 LEFT JOIN SENSIS_POCT POCT ON CATH.REFNO = POCT.REFNO
					 LEFT JOIN AIRWAY ON CATH.REFNO = AIRWAY.REFNO AND AIRWAY_ROW = 1
					 LEFT JOIN SENSIS_XRAYBSUM XRAYBSUM ON CATH.REFNO = XRAYBSUM.REFNO
					 LEFT JOIN (SELECT REFNO, ROUND(SUM(COST),0)  TOT_COST FROM SENSIS_ANGIO GROUP BY REFNO) ANGIO ON CATH.REFNO = ANGIO.REFNO
					 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SHTIME FROM SENSIS_ASR GROUP BY REFNO) ASR ON ASR.REFNO = CATH.REFNO
					 LEFT JOIN XRAY_PLANE ON CATH.REFNO = XRAY_PLANE.REFNO
					 
)



SELECT   DISTINCT 
        SURG_ENC_ID
		,CATH_CASE_ID
       ,PROCDXCATH
	   ,PROCASD
	   ,CAST(COALESCE(HEIGHT,HT.PAT_HT) AS NUMERIC(5,2)) HEIGHT	   
	   ,CAST(COALESCE(WEIGHT,WT.PAT_WT) AS NUMERIC(5,2)) WEIGHT
	   ,CASE WHEN COALESCE(PREPROC_LABS.HGB,HEMO.HEMOGLOBIN) > 99 THEN NULL  ELSE COALESCE(PREPROC_LABS.HGB,HEMO.HEMOGLOBIN) END AS  PREPROCHGB
	   ,CAST(CREAT.CREATININE AS NUMERIC(4,2)) PREPROCCREAT
	   ,CAST(O2SAT.O2SAT AS INTEGER) PREPROCO2
	   ,NEC
	   ,SEPSIS
	   ,PREG	   
	  ,COALESCE(PREPROCANTIARR,'2') PREPROCANTIARR
      ,COALESCE(PREPROCANTICOAG,'2') PREPROCANTICOAG
      ,COALESCE(PREPROCANTIHYP,'2') PREPROCANTIHYP
      ,COALESCE(PREPROCANTIPLATELET,'2') PREPROCANTIPLATELET
      ,COALESCE(PREPROCBB,'2') PREPROCBB
      ,COALESCE(PREPROCDIURETIC,'2') PREPROCDIURETIC
      ,COALESCE(PREPROCPROSTA,'2') PREPROCPROSTA
      ,COALESCE(PREPROCVASO,'2') PREPROCVASO
      ,COALESCE(PREPROCSINUS,'2') PREPROCSINUS
      ,COALESCE(PREPROCAET,'2') PREPROCAET
      ,COALESCE(PREPROCSVT,'2') PREPROCSVT
      ,COALESCE(PREPROCAFIB,'2') PREPROCAFIB
      ,COALESCE(PREPROCJUNCT,'2') PREPROCJUNCT
      ,COALESCE(PREPROCIDIO,'2') PREPROCIDIO
      ,COALESCE(PREPROCAVB2,'2') PREPROCAVB2
      ,COALESCE(PREPROCAVB3,'2') PREPROCAVB3
      ,COALESCE(PREPROCPACED,'2') PREPROCPACED
      ,PROCCOARC
      ,PROCAORTICVALV
      ,PROCPULMONARYVALV
      ,PROCPDA
      ,PROCPROXPASTENT	  
      ,HOSPSTATUS
      ,PROCSTATUS
      ,TRAINEE
      ,OPERATORNAME OPERATORID
      ,ANESPRESENT
      ,ANESCALLEDIN
      ,SEDATION
      ,COALESCE(AIRMNGLMA,'2') AIRMNGLMA
      ,COALESCE(AIRMNGTRACH,'2') AIRMNGTRACH
      ,COALESCE(AIRMNGBAGMASK,'2') AIRMNGBAGMASK
      ,COALESCE(AIRMNGCPAP,'2') AIRMNGCPAP
      ,COALESCE(AIRMNGELECINTUB,'2') AIRMNGELECINTUB
      ,COALESCE(AIRMNGPREVINTUB,'2') AIRMNGPREVINTUB
      ,ACCESSLOC
      ,VENACCESS
      ,VENLARGSHEATH
      ,VENCLOSUREMETHODND
      ,ARTACCESS
      ,ARTLARGSHEATH
      ,ARTCLOSUREMETHODND
      ,CAST(FLUOROTIME AS NUMERIC(4,1)) FLUOROTIME
      ,CAST(CONTRASTVOL AS INTEGER) CONTRASTVOL
      ,CASE WHEN NOT(HEPARIN.REFNO IS NULL) THEN 1
	        ELSE 2
			END AS SYSHEPARIN --NEED TO ADD THIS
      ,CASE WHEN NOT(ACTPEAK IS NULL) THEN 1 ELSE 2 END AS ACTMONITOR
      ,ACTPEAK 
      ,INOTROPE
      ,INOTROPEUSE
      ,ECMOUSE
      ,LVADUSE
      ,AUX5
      ,SCHEDARRIVALDATE
      , 2 PROCOTHER
      ,CASE WHEN COALESCE(PREPROC_LABS.HGB,HEMO.HEMOGLOBIN) IS NULL THEN 1 ELSE 2 END AS PREPROCHGBND
      ,CASE WHEN CREAT.CREATININE IS NULL THEN 1 ELSE 2 END AS PREPROCCREATND
	  ,SVDEFECT
      ,COALESCE(PREPROCMED,'2') PREPROCMED
	  ,PROCEPCATH
      ,PROCEPABLATION
	  ,PROCTPVR
      ,SECONDPARTICIPATING
      ,PROCSTARTDATE
      ,PROCSTARTTIME
      ,PROCENDDATE
      ,PROCENDTIME
      ,AIRMNG
      ,IABPUSE
      ,PLANEUSED
      ,FLUORODOSEKERM
      ,FLUORODOSEKERM_UNITS
      ,FLUORODOSEDAP
      ,FLUORODOSEDAP_UNITS
FROM CATH_STUDY CATH LEFT JOIN PAT_CURR_WT WT ON CATH.PAT_KEY = WT.PAT_KEY AND CATH.STUDATE = WT.STUDATE AND WT.REC_ORDER = 1
                     LEFT JOIN PAT_CURR_HT HT ON CATH.PAT_KEY = HT.PAT_KEY AND CATH.STUDATE = HT.STUDATE AND HT.REC_ORDER = 1
					 LEFT JOIN PREPROC_LABS ON PREPROC_LABS.REFNO = CATH.REFNO AND PREPROC_LABS.REC_ORDER = 1
					 LEFT JOIN PREPROC_HEMO HEMO ON CATH.REFNO = HEMO.REFNO AND HEMO.REC_ORDER = 1
					 LEFT JOIN PREPROC_CREAT CREAT ON CATH.REFNO = CREAT.REFNO  AND CREAT.REC_ORDER = 1
					 LEFT JOIN PREPROC_O2SAT O2SAT ON CATH.REFNO = O2SAT.REFNO  AND O2SAT.REC_ORDER = 1
					 LEFT JOIN PREPROC_MEDS PREMEDS ON CATH.REFNO = PREMEDS.REFNO
					 LEFT JOIN PREPROC_COND PRECOND ON CATH.REFNO = PRECOND.REFNO
					 LEFT JOIN PREPROC_RHY PRERHY ON CATH.REFNO = PRERHY.REFNO
					 LEFT JOIN PROC_PERF ON CATH.REFNO = PROC_PERF.REFNO
					 LEFT JOIN CATH_PROCEDURE ON CATH.REFNO = CATH_PROCEDURE.REFNO
					 LEFT JOIN VENOUS_LOC ON CATH.REFNO = VENOUS_LOC.REFNO AND  VENOUS_LOC.SIZEORDER = 1
					 LEFT JOIN ARTERIAL_LOC ON CATH.REFNO = ARTERIAL_LOC.REFNO AND ARTERIAL_LOC.SIZEORDER = 1 
					 LEFT JOIN HEPARIN ON HEPARIN.REFNO = CATH.REFNO
					 LEFT JOIN ACT ON ACT.REFNO = CATH.REFNO