WITH CATH_STUDY AS
(/*SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
*/

SELECT * FROM CDW_STG_DEV..S_CDW_IMPACT_CATHSTUDY
)
  
--AOV
,AOV_SINGLE AS (    select
        STUDY.REFNO
		,SURG_ENC_ID
        ,CASE WHEN SBALTEQ.REFNO IS NOT NULL THEN 1487
			  ELSE NULL END AS BALLTECH
		,SINGIPDEVCE.IMPACT SINGDEVID			  
		,SBALTEQ.IP7245 SINGBALLSTAB 
		,SBALTEQ.IP7250 SINGBALLPRESSURE
        ,CASE WHEN SINGIPDEVCE.IP7090 = 4 THEN 1498
			  WHEN SINGIPDEVCE.IP7090 = 5 THEN 1499
          ELSE NULL END AS SINGBALLOUTCOME    
        ,NULL AS SINGBALLPOSTPKSYSGRAD
		,NULL AS SINGBALLPOSTINSUFF		
		,NULL AS DOUBDEVID1
        ,NULL AS DOUBBALLSTAB1
        ,NULL AS DOUBBALLPRESSURE1
        ,NULL AS DOUBBALLOUTCOME1
        ,NULL AS DOUBDEVID2
        ,NULL AS DOUBBALLSTAB2
        ,NULL AS DOUBBALLPRESSURE2
        ,NULL AS DOUBBALLOUTCOME2
        ,NULL AS DOUBBALLPOSTPKSYSGRAD
        ,NULL AS DOUBBALLPOSTINSUFF
        ,SBALTEQ.IP7230 AS SORT 
		,CAST(SBALTEQ.IP7260 AS NUMERIC(4,1)) AS POSTDILSYSGRAD
		,CASE WHEN IP7265 = 0 THEN 4024
		      WHEN IP7265 = 1 THEN 4025
			  WHEN IP7265 = 2 THEN 4026
			  WHEN IP7265 = 3 THEN 4027
			  WHEN IP7265 = 4 THEN 4028
			  ELSE NULL END AS POSTDILREGURG
		 
  FROM CATH_STUDY STUDY JOIN SENSIS_AOVDATA AOVDATA ON STUDY.REFNO = AOVDATA.REFNO
                        JOIN SENSIS_SBALTEQ SBALTEQ ON STUDY.REFNO = SBALTEQ.REFNO
						JOIN SENSIS_IPDEVCE SINGIPDEVCE ON SBALTEQ.REFNO = SINGIPDEVCE.REFNO AND SBALTEQ.SEQNO = SINGIPDEVCE.SEQNO
			)
			



,AOV_DOUBLE AS
(    select
        STUDY.REFNO
		,SURG_ENC_ID		
        ,CASE WHEN DBALTEQ.REFNO IS NOT NULL THEN 1488
			  ELSE NULL END AS BALLTECH
		,NULL AS SINGDEVID			  
		,NULL AS SINGBALLSTAB 
		,NULL AS SINGBALLPRESSURE
        ,NULL AS SINGBALLOUTCOME  
        ,NULL AS SINGBALLPOSTPKSYSGRAD
		,NULL AS SINGBALLPOSTINSUFF
		,DBLIPDEVCE.IMPACT AS DOUBDEVID1
        ,DBALTEQ.IP7275 AS DOUBBALLSTAB1
        ,DBALTEQ.IP7280 AS DOUBBALLPRESSURE1
        ,CASE WHEN DBLIPDEVCE.IP7090 = 4 THEN 1498
			  WHEN DBLIPDEVCE.IP7090 = 5 THEN 1499
          ELSE NULL END AS DOUBBALLOUTCOME1    
        ,NULL AS DOUBDEVID2
        ,DBALTEQ.IP7295 AS DOUBBALLSTAB2
        ,DBALTEQ.IP7300 AS DOUBBALLPRESSURE2
        ,NULL AS DOUBBALLOUTCOME2
		,NULL AS DOUBBALLPOSTPKSYSGRAD
        ,NULL AS DOUBBALLPOSTINSUFF
		,DBALTEQ.IP7230 SORT
        ,CAST(DBALTEQ.IP7310 AS NUMERIC(4,1)) AS POSTDILSYSGRAD
		,CASE WHEN DBALTEQ.IP7315 = 0 THEN 1489
		      WHEN DBALTEQ.IP7315 = 1 THEN 1490
			  WHEN DBALTEQ.IP7315 = 2 THEN 1491
			  WHEN DBALTEQ.IP7315 = 3 THEN 1492
			  WHEN DBALTEQ.IP7315 = 4 THEN 1493
		ELSE NULL END AS POSTDILREGURG

  FROM CATH_STUDY STUDY JOIN SENSIS_AOVDATA AOVDATA ON STUDY.REFNO = AOVDATA.REFNO
						JOIN SENSIS_DBALTEQ DBALTEQ ON STUDY.REFNO = DBALTEQ.REFNO
						JOIN SENSIS_IPDEVCE DBLIPDEVCE ON DBALTEQ.REFNO = DBLIPDEVCE.REFNO AND DBALTEQ.SEQNO = DBLIPDEVCE.SEQNO
			)	
			

						
--PV
/*,PV_SINGLE AS (  select
        STUDY.REFNO
		,SURG_ENC_ID		
        ,CASE WHEN SBALTEQ.REFNO IS NOT NULL THEN 1487
			  ELSE NULL END AS BALLTECH
		,SINGIPDEVCE.IMPACT SINGDEVID			  
		,SBALTEQ.IP7245 SINGBALLSTAB 
		,SBALTEQ.IP7250 SINGBALLPRESSURE
        ,CASE WHEN SINGIPDEVCE.IP7090 = 4 THEN 1498
			  WHEN SINGIPDEVCE.IP7090 = 5 THEN 1499
          ELSE NULL END AS SINGBALLOUTCOME    
        ,CAST(SBALTEQ.IP7260 AS NUMERIC(4,1)) SINGBALLPOSTPKSYSGRAD
		,CASE WHEN SBALTEQ.IP7265 = 0 THEN 1489
		      WHEN SBALTEQ.IP7265 = 1 THEN 1490
			  WHEN SBALTEQ.IP7265 = 2 THEN 1491
			  WHEN SBALTEQ.IP7265 = 3 THEN 1492
			  WHEN SBALTEQ.IP7265 = 4 THEN 1493
		ELSE NULL END AS SINGBALLPOSTINSUFF		
		,NULL AS DOUBDEVID1
        ,NULL AS DOUBBALLSTAB1
        ,NULL AS DOUBBALLPRESSURE1
        ,NULL AS DOUBBALLOUTCOME1
        ,NULL AS DOUBDEVID2
        ,NULL AS DOUBBALLSTAB2
        ,NULL AS DOUBBALLPRESSURE2
        ,NULL AS DOUBBALLOUTCOME2
        ,NULL AS DOUBBALLPOSTPKSYSGRAD
        ,NULL AS DOUBBALLPOSTINSUFF
        ,SBALTEQ.IP7230 AS SORT
  FROM CATH_STUDY STUDY JOIN SENSIS_PVDATA PVDATA ON STUDY.REFNO = PVDATA.REFNO
                        JOIN SENSIS_SBALTEQ SBALTEQ ON STUDY.REFNO = SBALTEQ.REFNO
						JOIN SENSIS_IPDEVCE SINGIPDEVCE ON SBALTEQ.REFNO = SINGIPDEVCE.REFNO AND SBALTEQ.SEQNO = SINGIPDEVCE.SEQNO
		)
	

		
,PV_DOUBLE AS ( select
        STUDY.REFNO
		,SURG_ENC_ID		
        ,CASE WHEN DBALTEQ.REFNO IS NOT NULL THEN 1488
			  ELSE NULL END AS BALLTECH
		,NULL AS SINGDEVID			  
		,NULL AS SINGBALLSTAB 
		,NULL AS SINGBALLPRESSURE
        ,NULL AS SINGBALLOUTCOME  
        ,NULL AS SINGBALLPOSTPKSYSGRAD
		,NULL AS SINGBALLPOSTINSUFF
		,DBLIPDEVCE.IMPACT AS DOUBDEVID1
        ,DBALTEQ.IP7275 AS DOUBBALLSTAB1
        ,DBALTEQ.IP7280 AS DOUBBALLPRESSURE1
        ,CASE WHEN DBLIPDEVCE.IP7090 = 4 THEN 1498
			  WHEN DBLIPDEVCE.IP7090 = 5 THEN 1499
          ELSE NULL END AS DOUBBALLOUTCOME1    
        ,NULL AS DOUBDEVID2
        ,DBALTEQ.IP7295 AS DOUBBALLSTAB2
        ,DBALTEQ.IP7300 AS DOUBBALLPRESSURE2
        ,NULL AS DOUBBALLOUTCOME2
        ,CAST(DBALTEQ.IP7310 AS NUMERIC(4,1)) AS DOUBBALLPOSTPKSYSGRAD
		,CASE WHEN DBALTEQ.IP7315 = 0 THEN 1489
		      WHEN DBALTEQ.IP7315 = 1 THEN 1490
			  WHEN DBALTEQ.IP7315 = 2 THEN 1491
			  WHEN DBALTEQ.IP7315 = 3 THEN 1492
			  WHEN DBALTEQ.IP7315 = 4 THEN 1493
		ELSE NULL END AS DOUBBALLPOSTINSUFF
        ,DBALTEQ.IP7230 AS SORT
  FROM CATH_STUDY STUDY JOIN SENSIS_PVDATA PVDATA ON STUDY.REFNO = PVDATA.REFNO
						JOIN SENSIS_DBALTEQ DBALTEQ ON STUDY.REFNO = DBALTEQ.REFNO
						JOIN SENSIS_IPDEVCE DBLIPDEVCE ON DBALTEQ.REFNO = DBLIPDEVCE.REFNO AND DBALTEQ.SEQNO = DBLIPDEVCE.SEQNO
		)
		

*/


SELECT 
	     SURG_ENC_ID
		,BALLTECH
		,SINGDEVID			  
		,SINGBALLSTAB 
		,SINGBALLPRESSURE
	    ,SINGBALLOUTCOME    
	    ,SINGBALLPOSTPKSYSGRAD
		,SINGBALLPOSTINSUFF		
		,DOUBDEVID1
	    ,DOUBBALLSTAB1
	    ,DOUBBALLPRESSURE1
	    ,DOUBBALLOUTCOME1
	    ,DOUBDEVID2
	    ,DOUBBALLSTAB2
	    ,DOUBBALLPRESSURE2
	    ,DOUBBALLOUTCOME2
	    ,DOUBBALLPOSTPKSYSGRAD
	    ,DOUBBALLPOSTINSUFF
	    ,SORT
		,POSTDILSYSGRAD
		,POSTDILREGURG
	  
FROM
(
	(SELECT AOV_SINGLE.* 
	FROM  CATH_STUDY JOIN AOV_SINGLE ON CATH_STUDY.REFNO = AOV_SINGLE.REFNO
	)
UNION ALL
	(SELECT AOV_DOUBLE.* 
	FROM  CATH_STUDY JOIN AOV_DOUBLE ON CATH_STUDY.REFNO = AOV_DOUBLE.REFNO
	 ) 
/*UNION ALL
	(SELECT PV_SINGLE.* 
	FROM  CATH_STUDY JOIN PV_SINGLE ON CATH_STUDY.REFNO = PV_SINGLE.REFNO
	)
UNION ALL
	(SELECT PV_DOUBLE.* 
	FROM  CATH_STUDY JOIN PV_DOUBLE ON CATH_STUDY.REFNO = PV_DOUBLE.REFNO
	 )
	  */
 ) UNIONALL
 
				 