WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)

  
    select
        SURG_ENC_ID
		,CASE WHEN ASDATA.IP7025 = 'No' then NULL
		      ELSE CAST(ASDATA.IP7025 AS NUMERIC(4,1)) END ASDSIZE
		,ASDEFCT.IP7030 ASDBALLSIZPERF
		,ASDEFCT.IP7035 ASDSTRETCHDIAMETER
		,ASDEFCT.IP7040 ASDSTRETCHDIAMETERSIZE
		,ASDEFCT.IP7045 ASDSTOPFLOWTECH
		,ASDEFCT.IP7050 ASDSTOPFLOWTECHSIZE
		,ASDEFCT.IP7055 ASDRIMMEAS
		,CAST(ASDEFCT.IP7060 AS NUMERIC(4,1)) ASDIVCRIMLENGTH
		,CAST(ASDEFCT.IP7065 AS NUMERIC(4,1)) ASDAORTRIMLENGTH
		--,ASDDEFTREAT
		--,ASDNOTREATREASON
		,CASE WHEN ASDEFCT.IP7080 = 1 THEN 1480
		      WHEN ASDEFCT.IP7080 = 2 THEN 1481 
			  ELSE NULL END AS ASDRESSHUNT
		,ASDEFCT.SEQNO SORT		
		,CAST(ASDEFCT.IP7066 AS NUMERIC(4,1)) ASDPOSTRIMLENGTH
		,ASDATA.IP7015 ASDMULTIFENESTRATED
  FROM CATH_STUDY STUDY JOIN SENSIS_ASDEFCT ASDEFCT ON STUDY.REFNO = ASDEFCT.REFNO
                        JOIN SENSIS_ASDATA ASDATA ON STUDY.REFNO = ASDATA.REFNO
						
						--select * from sensis_dicip7080