WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
and pat_mrn_id = '02605602'
)

  
  SELECT 
          SURG_ENC_ID
  		,CASE WHEN IPPRDEF.IP7710 = 1 THEN 1533
		      WHEN IPPRDEF.IP7710 = 2 THEN 1534 
			ELSE NULL END AS PASDEFECTLOC
		,NULL AS PASOSTIALSTENOSIS
		,IPPRDEF.IP7720 PASDISOBSTRUCTION
		,IPPRDEF.IP7725 PASSIDEJAIL
		,IPPRDEF.IP7730 PASSIDEJAILINTENDED
		,CASE WHEN IPPRDEF.IP7735 =1 THEN 1542
		      WHEN IPPRDEF.IP7735 =2 THEN 1543 
		 ELSE NULL END AS PASSIDEJAILARTERY
		,IPPRDEF.IP7740 PASDSIDEJAILDECFLOW
		,CAST(IPVENT1.IP7745 AS NUMERIC(4,1)) PASPREPROXSYSPRESS
		,CAST(IPVENT1.IP7750 AS NUMERIC(4,1)) PASPREDISTSYSPRESS
		,CAST(IPVENT1.IP7755 AS NUMERIC(4,1)) PASPREPROXMEANPRESS
		,CAST(IPVENT1.IP7760 AS NUMERIC(4,1)) PASPREDISTMEANPRESS
		,CAST(IPVENT1.IP7765 AS NUMERIC(3,1)) PASPREPROXDIAMETER
		,CAST(IPVENT1.IP7770 AS NUMERIC(3,1)) PASPREDISTDIAMETER
		,CAST(IPVENT1.IP7775 AS NUMERIC(3,1)) PASPREMINDIAMETER
		,NULL PASDEFECTTREATED
		,CAST(IPVENT2.IP7785 AS NUMERIC(4,1)) PASPOSTPROXSYSPRESS
		,CAST(IPVENT2.IP7790 AS NUMERIC(4,1)) PASPOSTDISTSYSPRESS
		,CAST(IPVENT2.IP7795 AS NUMERIC(4,1)) PASPOSTPROXMEANPRESS
		,CAST(IPVENT2.IP7800 AS NUMERIC(4,1)) PASPOSTDISTMEANPRESS
		,CAST(IPVENT2.IP7805 AS NUMERIC(3,1)) PASPOSTPROXDIAMETER
		,CAST(IPVENT2.IP7810 AS NUMERIC(3,1)) PASPOSTDISTDIAMETER
		,CAST(IPVENT2.IP7815 AS NUMERIC(3,1)) PASPOSTMINDIAMETER
		,IPPRDEF.SEQNO SORT
FROM CATH_STUDY STUDY JOIN SENSIS_IPPRDEF IPPRDEF ON STUDY.REFNO = IPPRDEF.REFNO
                      JOIN SENSIS_IPVENT1 IPVENT1 ON STUDY.REFNO = IPVENT1.REFNO AND IPPRDEF.SEQNO = IPVENT1.SEQNO
					  JOIN SENSIS_IPVENT2 IPVENT2 ON STUDY.REFNO = IPVENT2.REFNO AND IPPRDEF.SEQNO = IPVENT2.SEQNO
					  