WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 									 
WHERE POCT.PRTYPE <> 10 --Fluoro
)
SELECT   
        PAT_MRN_ID
		,MIN(GENCOND.IP3100) DIGEORGESYND
		,MIN(GENCOND.IP3105) ALAGILLESYND
		,MIN(GENCOND.IP3110) HERNIA
		,MIN(GENCOND.IP3125) MARFANSYND
		,MIN(GENCOND.IP3115) DOWNSYND
		,MIN(GENCOND.IP3120) HETEROTAXY
		,MIN(GENCOND.IP3130) NOONANSYND
		,MIN(GENCOND.IP3135) RUBELLA
		,MIN(GENCOND.IP3140) TRISOMY13
		,MIN(GENCOND.IP3145) TRISOMY18
		,MIN(GENCOND.IP3150) TURNERSYND
		,MIN(GENCOND.IP3155) WILLIAMSBEURENSYND
		,MAX(BRTHINF.PRMBRTH) AS PREMATURE
		,MAX(BRTHINF.GSTAGE) AS GESTAGEWEEKS
		,MAX(BRTHINF.BRTHWT) AS BIRTHWTKG
		--SELECT *
		FROM CATH_STUDY STUDY
 			 LEFT JOIN SENSIS_GENCOND GENCOND ON STUDY.REFNO = GENCOND.REFNO
			 LEFT JOIN SENSIS_BRTHINF BRTHINF ON BRTHINF.REFNO = STUDY.REFNO 
	    GROUP BY PAT_MRN_ID