WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO --select * from SENSIS_POCT study
  )

  
  
  
    SELECT
        SURG_ENC_ID
        ,CM.IP8150 POSTOTHEREVENTID

  FROM CATH_STUDY STUDY JOIN SENSIS_CM CM ON STUDY.REFNO = CM.REFNO