WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWPRD..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWPRD..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWPRD..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWPRD..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWPRD..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWPRD..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro 
--AND PAT_MRN_ID = '56047877' AND STUDATE = '2017-12-07 00:00:00'
)

  SELECT
         SURG_ENC_ID
		,IPDEVCE.IP7089 DEFECTCOUNTERASSN
		,CAST(SEQNO AS INT) SORT
		,CASE WHEN IMPUSE IN (1,2,3) THEN 2004
		  WHEN IMPUSE IN (16,17,18) THEN 2009
		  WHEN IMPUSE IN (13,14,15) THEN 2008
			ELSE IMPUSE END AS CATHPROCID
FROM CATH_STUDY STUDY JOIN SENSIS_IPDEVCE IPDEVCE ON STUDY.REFNO = IPDEVCE.REFNO
WHERE IPDEVCE.IMPACT IS NOT NULL AND IMPUSE IN (1,2,3,13,14,15,16,17,18) 

 
UNION ALL 
 
SELECT
        SURG_ENC_ID
		,IP2DVCE.IP7089 DEFECTCOUNTERASSN
		,CAST(SEQNO AS INT) SORT
        ,3625 CATHPROCID
FROM CATH_STUDY STUDY JOIN SENSIS_IP2DVCE IP2DVCE ON STUDY.REFNO = IP2DVCE.REFNO
WHERE IP2DVCE.IMPACT IS NOT NULL 
