WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)
  
  
    SELECT
        SURG_ENC_ID
        ,CASE WHEN IP2HRSK.IP3161 = 1 THEN 4005
		      WHEN IP2HRSK.IP3161 = 2 THEN 4006
			  WHEN IP2HRSK.IP3161 = 3 THEN 4007
			  WHEN IP2HRSK.IP3161 = 4 THEN 4008
			  WHEN IP2HRSK.IP3161 = 5 THEN 4009
			  WHEN IP2HRSK.IP3161 = 6 THEN 4010
			  WHEN IP2HRSK.IP3161 = 7 THEN 4011
			  WHEN IP2HRSK.IP3161 = 8 THEN 4012
			  WHEN IP2HRSK.IP3161 = 9 THEN 4013
			  WHEN IP2HRSK.IP3161 = 10 THEN 4014
			  WHEN IP2HRSK.IP3161 = 11 THEN 4015
			  WHEN IP2HRSK.IP3161 = 12 THEN 4016
			  WHEN IP2HRSK.IP3161 = 13 THEN 4017
			  WHEN IP2HRSK.IP3161 = 14 THEN 4018
			  WHEN IP2HRSK.IP3161 = 15 THEN 4020
			  WHEN IP2HRSK.IP3161 = 16 THEN 4021
			  ELSE NULL END AS ARRHYTHMIAHX
		,DICIP3161.MEANING 	ARRHYTHMIAHXTERM  


  FROM CATH_STUDY STUDY JOIN SENSIS_IP2HRSK IP2HRSK ON STUDY.REFNO = IP2HRSK.REFNO
                        LEFT JOIN SENSIS_DICIP3161 DICIP3161 ON DICIP3161.CODE = IP2HRSK.IP3161
  
  --SELECT * FROM CDW_ODS_UAT..SENSIS_IP2HRSK WHERE REFNO = 53352