WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)

SELECT  
        SURG_ENC_ID
		,IP2HRSK.IP3200 CHRONICLUNGDISEASE
		,IP2HRSK.IP3205 COAGDISORDER 
		,CASE WHEN IP2HRSK.IP3205 = 1 
		      THEN IP2HRSK.IP3210 
			ELSE NULL END AS HYPERCOAG
		,CASE WHEN IP2HRSK.IP3205 = 1
		      THEN IP2HRSK.IP3215 
			ELSE NULL END AS HYPOCOAG
		,IP2HRSK.IP3220 DIABETES
		,IP2HRSK.IP3225 HEPATICDISEASE		
		,IP2HRSK.IP3230 RENALINSUFF
		,IP2HRSK.IP3235 SEIZURES
		,IP2HRSK.IP3240 SICKLECELL		
		,IP2HRSK.IP3250 PRIORSTROKE
        ,IP2HRSK.IP3160 ARRHYTHMIA
--		,IP2HRSK.IP3161 ARRHYTHMIAHX
		,IP2HRSK.IP3170 PRIORCM
		,CASE WHEN IP2HRSK.IP3175 = 1 THEN 4097
		     WHEN IP2HRSK.IP3175 = 2 THEN 4098 
			 WHEN IP2HRSK.IP3175 = 3 THEN 4099
			 WHEN IP2HRSK.IP3175 = 4 THEN 4100
			 WHEN IP2HRSK.IP3175 = 5 THEN 4101
			 WHEN IP2HRSK.IP3175 = 6 THEN 4102
			ELSE NULL END AS PRIORCMHX
		,IP2HRSK.IP3221 ENDOCARDITIS
		,IP2HRSK.IP3222 HF
		,CASE WHEN IP2HRSK.IP3223 = 1 THEN 1423
		      WHEN IP2HRSK.IP3223 = 2 THEN 1424
		      WHEN IP2HRSK.IP3223 = 3 THEN 1425
			  WHEN IP2HRSK.IP3223 = 4 THEN 1426
			ELSE NULL END AS NYHA
		,IP2HRSK.IP3224 HEARTTRANSPLANT
		,IP2HRSK.IP3226 ISCHEMICHD
		,IP2HRSK.IP3227 KAWASAKIDISEASE
		,IP2HRSK.IP3231 RHEUMATICHD

 FROM CATH_STUDY STUDY JOIN (SELECT *, MIN(SEQNO) OVER (PARTITION BY REFNO ORDER BY SEQNO) NEWSEQ FROM SENSIS_IP2HRSK) IP2HRSK ON STUDY.REFNO = IP2HRSK.REFNO and IP2HRSK.NEWSEQ = IP2HRSK.SEQNO
 
ORDER BY 1