WITH CATH_STUDY AS
(SELECT STUDY.REFNO, 
        STUDY.ADMISSID, 
		CAST(V1.ENC_ID AS INT)  SURG_ENC_ID,
		STUDY.ACCESSNO,
		STUDY.ORDNUM,
        STUDATE,
		SH_ACC_TM,
		POCT.PREND,
		PATIENT_MATCH.PAT_KEY, 
		PAT_MRN_ID,
		PD.HEIGHT,
		PD.WEIGHT  --SELECT *
FROM SENSIS_STUDY STUDY JOIN CDWUAT..PATIENT_MATCH ON STUDY.REFNO = PATIENT_MATCH.SRC_SYS_ID AND SRC_SYS_NM = 'SENSIS'
                                     JOIN CDWUAT..PATIENT ON PATIENT.PAT_KEY = PATIENT_MATCH.PAT_KEY
									 JOIN SENSIS_CT CT ON STUDY.REFNO = CT.REFNO
									 JOIN CDWUAT..PROCEDURE_ORDER PO ON PO.PROC_ORD_ID = STUDY.ORDNUM
									 JOIN CDWUAT..OR_CASE_ORDER OCO ON OCO.ORD_KEY = PO.PROC_ORD_KEY
									 JOIN CDWUAT..OR_LOG ON OR_LOG.CASE_KEY = OCO.OR_CASE_KEY
									 JOIN CDWUAT..VISIT V1 ON V1.VISIT_KEY = OR_LOG.VISIT_KEY
									 --JOIN VISIT V2 ON V2.VISIT_KEY = OR_LOG.ADMIT_VISIT_KEY
									 LEFT JOIN SENSIS_PD PD ON STUDY.REFNO = PD.REFNO
									 LEFT JOIN (SELECT REFNO, MIN(SHTIME) SH_ACC_TM FROM SENSIS_ASR GROUP BY REFNO) SHEATH ON STUDY.REFNO = SHEATH.REFNO
									 LEFT JOIN SENSIS_POCT POCT ON STUDY.REFNO = POCT.REFNO 
WHERE POCT.PRTYPE <> 10 --Fluoro
)
SELECT 	
        SURG_ENC_ID
        ,COALESCE(IPPOEVNT.IP8000,2) CARREST
		,COALESCE(IPPOEVNT.IP8005,2) POSTARRHYTH
		,COALESCE(IPPOEVNT.IP8006,2) POSTAVBLOCK
		,COALESCE(IPPOEVNT.IP8007,2) POSTARRHYTHRESOLVED
		,COALESCE(IPPOEVNT.IP8010,2) POSTARRHYTHMED
		,COALESCE(IPPOEVNT.IP8015,2) POSTARRHYTHCARDIOVERS
		,COALESCE(IPPOEVNT.IP8020,2) POSTARRHYTHTEMPPM
		,COALESCE(IPPOEVNT.IP8025,2) POSTARRHYTHPERMPM
		,COALESCE(IPPOEVNT.IP8030,2) POSTNEWREGURGE
		,COALESCE(IPPOEVNT.IP8035,2) POSTTAMPONADE
		,COALESCE(IPPOEVNT.IP8040,2) POSTAIREMBOLUS
		,COALESCE(IPPOEVNT.IP8045,2) POSTEMBSTROKE
		,COALESCE(IPPOEVNT.IP8050,2) POSTDEVMALPOSTHROM
	--	,COALESCE(IPPOEVNT.IP8050,2) POSTDEVMALPOSTHROMRETCT
		,COALESCE(IPPOEVNT.IP8055,2) POSTDEVEMBOL
		,COALESCE(IPPOEVNT.IP8060,2) POSTDEVRETRIEVEPCT
		,COALESCE(IPPOEVNT.IP8065,2) POSTDEVRETRIEVESURG
		,COALESCE(IPPOEVNT.IP8070,2) POSTDIALYSIS
		,COALESCE(IPPOEVNT.IP8071,2) POSTCORARTERYCOMP
		,COALESCE(IPPOEVNT.IP8072,2) POSTEROSION
		,COALESCE(IPPOEVNT.IP8073,2) POSTESOFISTULA
		,COALESCE(IPPOEVNT.IP8074,2) POSTLBBB
		,COALESCE(IPPOEVNT.IP8075,2) POSTINTUBATION
		,COALESCE(IPPOEVNT.IP8076,2) POSTRBBB
		,COALESCE(IPPOEVNT.IP8080,2) POSTECMO
		,COALESCE(IPPOEVNT.IP8085,2) POSTLVAD
		,COALESCE(IPPOEVNT.IP8090,2) POSTBLEED
		,COALESCE(IPPOEVNT.IP8095,2) POSTBLEEDACCESSSITE
		,COALESCE(IPPOEVNT.IP8100,2) POSTBLEEDHEMATOMA
		,COALESCE(IPPOEVNT.IP8110,2) POSTRETROBLEED
		,COALESCE(IPPOEVNT.IP8115,2) POSTGIBLEED
		,COALESCE(IPPOEVNT.IP8120,2) POSTGUBLEED
		,COALESCE(IPPOEVNT.IP8125,2) POSTOTHERBLEED
		,COALESCE(IPPOEVNT.IP8130,2) POSTTRANSFUSION
		,COALESCE(IPPOEVNT.IP8131,2) POSTDROPHGB
		,COALESCE(IPPOEVNT.IP8132,2) POSTPRIORANEMIA
		,COALESCE(IPPOEVNT.IP8133,2) POSTBLOODLOSS
		,COALESCE(IPPOEVNT.IP8134,2) POSTECMOBLOODREPLACE
		,COALESCE(IPPOEVNT.IP8140,2) POSTOTHERVASCOMP
		,COALESCE(IPPOEVNT.IP8145,2) POSTOTHEREVENTS
		,COALESCE(IPPEVEN2.IP8155,2) POSTPLANCARDIACSURG
		,COALESCE(IPPEVEN2.IP8160,2) POSTUNPLANCARDSURG
		,COALESCE(IPPEVEN2.IP8165,2) POSTUNPLANVASSURG
		,COALESCE(IPPEVEN2.IP8170,2) POSTUNPLANOTHERSURG
		,COALESCE(IPPEVEN2.IP8175,2) POSTOTHERSURGCATHCOMP
		,COALESCE(IPPEVEN2.IP8180,2) POSTSUBSCATH
		,COALESCE(IPPOEVNT.IP8200,2) POSTPERINERVEINJURY
		,COALESCE(IPPOEVNT.IP8205,2) POSTPHNERVEPARALYSIS
		,COALESCE(IPPOEVNT.IP8210,2) POSTPNEUMOTHORAX
		,COALESCE(IPPOEVNT.IP8215,2) POSTPULEMBOLISM 
		,COALESCE(IPPOEVNT.IP8220,2) POSTPULVEINSTENOSIS
		,COALESCE(IPPOEVNT.IP8225,2) POSTRADIATIONBURN
		,COALESCE(IPPOEVNT.IP8230,2) POSTDVT
		,COALESCE(IPPOEVNT.IP8235,2) POSTCONDUITTEAR
		,COALESCE(IPPOEVNT.IP8236,2) POSTCONDUITTEARLOC 
		,COALESCE(IPPOEVNT.IP8237,2) POSTCONDUITTEARTREAT
FROM CATH_STUDY STUDY LEFT JOIN SENSIS_IPPEVEN2 IPPEVEN2 ON STUDY.REFNO = IPPEVEN2.REFNO
			          LEFT JOIN SENSIS_IPPOEVNT IPPOEVNT ON STUDY.REFNO = IPPOEVNT.REFNO