WITH CATH_STUDY AS
(SELECT * FROM CDW_STG_DEV..S_CDW_IMPACT_CATHSTUDY
)

,DEVICE AS
(SELECT  STUDY.REFNO 
        ,COADFECT.SEQNO
        ,SURG_ENC_ID
		,IPDEVCE.IMPACT COARCDEVID
		,CASE WHEN COADFECT.IP7140 = 1 THEN 1504
		      WHEN COADFECT.IP7140 = 2 THEN 1505 
			  ELSE NULL END AS COARCDEVTYPE
		,CASE WHEN COADFECT.IP7145 = 1 THEN 1502
		      WHEN COADFECT.IP7145 = 2 THEN 1500
			  WHEN COADFECT.IP7145 = 3 THEN 1503
			  WHEN COADFECT.IP7145 = 4 THEN 1501
			  ELSE NULL END AS COARCBALLPURP
		,COADFECT.IP7150 COARCBALLPRESSURE
		,CASE WHEN COADFECT.IP7155 = 1 THEN 1498
		      WHEN COADFECT.IP7155 = 2 THEN 1499
		ELSE NULL END AS COARCBALLOUTCOME
		,CASE WHEN COADFECT.IP7160 = 1 THEN 1512
		      WHEN COADFECT.IP7160 = 2 THEN 1513
			  WHEN COADFECT.IP7160 = 3 THEN 1514
		ELSE NULL END AS COARCSTENTOUTCOME
		,CAST(COADFECT.IP7165 AS NUMERIC(4,1)) COARCPOSTINSTENTDIAMETER
		,CAST(COADFECT.IP7135 AS INTEGER) SORTORDER
	    ,CASE WHEN COADFECT.IP7165 IS NOT NULL THEN '1' ELSE '0' END AS COARCPOSTINSTENTDIAMASSESSED
FROM CATH_STUDY STUDY JOIN SENSIS_COADFECT COADFECT ON STUDY.REFNO = COADFECT.REFNO
                      JOIN SENSIS_IPDEVCE IPDEVCE ON COADFECT.REFNO = IPDEVCE.REFNO AND COADFECT.SEQNO = IPDEVCE.SEQNO
)

,IMP_BALLOON AS
(SELECT  STUDY.REFNO
        ,COADFECT.SEQNO
        ,SURG_ENC_ID
		,COADFECT.IMPACT COARCDEVID
		,'1504' AS COARCDEVTYPE
		,CASE WHEN COADFECT.CATHETER IS NULL THEN NULL 
			  ELSE 1503 END AS COARCBALLPURP
		,CAST(COADFECT.CPOSTIN AS VARCHAR(8)) COARCBALLPRESSURE
		,CASE WHEN COADFECT.CPOVDS = 2038 THEN 1499
		      WHEN COADFECT.CPOVDS = 2039 THEN 1498
		ELSE NULL END AS COARCBALLOUTCOME
		,NULL AS COARCSTENTOUTCOME
		,NULL AS COARCPOSTINSTENTDIAMETER
		,40 SORTORDER
	    ,NULL AS COARCPOSTINSTENTDIAMASSESSED
FROM CATH_STUDY STUDY JOIN SENSIS_COADFECT COADFECT ON STUDY.REFNO = COADFECT.REFNO
WHERE COADFECT.IMPACT IS NOT NULL
)


,REDIAL_BALLOON AS
(SELECT  STUDY.REFNO
        ,COADFECT.SEQNO
        ,SURG_ENC_ID
		,COADFECT.IMPACT2 COARCDEVID
		,'1504' AS COARCDEVTYPE
		,CASE WHEN COADFECT.CPOPSD = 1 THEN 1501
			  ELSE NULL END AS COARCBALLPURP
		,CAST(COADFECT.CPORP AS VARCHAR(8)) COARCBALLPRESSURE
		,CASE WHEN COADFECT.CPOVDS = 2038 THEN 1499
		      WHEN COADFECT.CPOVDS = 2039 THEN 1498 
			 ELSE NULL END AS COARCBALLOUTCOME
		,NULL AS COARCSTENTOUTCOME
		,NULL COARCPOSTINSTENTDIAMETER
		,50  SORTORDER
	    ,NULL AS COARCPOSTINSTENTDIAMASSESSED
FROM CATH_STUDY STUDY JOIN SENSIS_COADFECT COADFECT ON STUDY.REFNO = COADFECT.REFNO		
WHERE COADFECT.IMPACT2 IS NOT NULL)


,COARC_DEVICES AS
(SELECT * FROM DEVICE UNION ALL
 SELECT * FROM IMP_BALLOON UNION ALL
 SELECT * FROM REDIAL_BALLOON
 )



SELECT  CATH_STUDY.SURG_ENC_ID
		,COARCDEVID
		,COARCDEVTYPE
		,COARCBALLPURP
		,COARCBALLPRESSURE
		,COARCBALLOUTCOME
		,COARCSTENTOUTCOME
		,COARCPOSTINSTENTDIAMETER
		,ROW_NUMBER() OVER (PARTITION BY CATH_STUDY.REFNO ORDER BY SORTORDER,SEQNO) SORT
	    ,COARCPOSTINSTENTDIAMASSESSED
FROM CATH_STUDY JOIN COARC_DEVICES ON CATH_STUDY.REFNO = COARC_DEVICES.REFNO
ORDER BY SURG_ENC_ID