SELECT PATID,
       LASTNAME,
	   FIRNAME,
	   MIDNAME,
	   PATBIRTH,
	   CASE WHEN PATSEX = 1 THEN 29
	        WHEN PATSEX = 2 THEN 28
			ELSE NULL END AS GENDER
		--SELECT *  
FROM CDW_ODS..SENSIS_PATIENT
