select MEDRECN,
       SURGDT,
	   count(SURGNUM)
from

	(SELECT ca.CASELINKNUM,
	       ca.MEDRECN,
		   CA.SURGDT,
		   ROW_NUMBER() OVER (PARTITION BY MEDRECN,CA.SURGDT ORDER BY SURGDTTM) SURGNUM
	FROM

		(SELECT CASELINKNUM,
		        MEDRECN,
				SURGDT SURGDTTM,
				CAST(SURGDT AS DATE) SURGDT
		 FROM CDWDEV..CARDIOACCESS_CASES
		 WHERE CAST(SURGDT AS DATE) >= '2005-01-01 00:00:00'
		 ) CA
	 
	 left join 
	 
		 (SELECT DISTINCT
		        cast(ISNULL(or_log.LOG_ID,'') as integer)  CASELINKNUM
			   ,PAT.PAT_MRN_ID	
			   ,PAT.PAT_KEY
			   ,TO_DATE(OR_LOG.SURG_DT_KEY,'YYYYMMDD') SURGDT
			   ,IN_ROOM.IN_ROOM
		FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
		                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
												 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
												 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
												 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
												 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
												 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
		                                         LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) IN_ROOM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000001' group by VISIT_KEY) IN_ROOM ON IN_ROOM.VISIT_KEY = ANESLINK.OR_LOG_VISIT_KEY 
		WHERE 1=1
		 -- AND SERVICE.SRC_ID = 910 
		  ORDER BY 1) CDW


	ON CDW.PAT_MRN_ID = CA.MEDRECN AND CDW.SURGDT = CA.SURGDT
	)A
	
	GROUP BY 1,2