SELECT DISTINCT
       PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,OR_PROC.OR_PROC_NM
       ,DATE(MD.FULL_DT) PROC_START_DT  
FROM  OR_CASE   JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
				JOIN OR_LOG_ALL_PROCEDURES AS ORL_PROC ON OR_LOG.LOG_KEY = ORL_PROC.LOG_KEY --BRINGS IN PROCEDURES AND ANESTHESIA TYPE
				JOIN OR_PROCEDURE AS OR_PROC ON OR_PROC.OR_PROC_KEY = ORL_PROC.OR_PROC_KEY
				JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
				JOIN OR_LOG_ANES_STAFF ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
				JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY	
				JOIN MASTER_DATE AS MD ON OR_LOG.SURG_DT_KEY = MD.DT_KEY --TO GET SURGERY DATE INFO (FY, CY)

										
WHERE 1=1
  AND SERVICE.SRC_ID = 910 --CARDIAC SERVICE 
  AND ORDINAL = 1
  AND ALL_PROC_PANEL_NUM = 1
  --AND OR_CASE_ID = '98697'
  ORDER BY DATE(MD.FULL_DT) DESC


 
