
SELECT 'CHOP_CCAS_ANESTHESIA_AIRWAY', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_AIRWAY UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_MONITOR', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_MONITOR UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_POSTOPICU', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_POSTOPICU UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_PREOPMEDS', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_PREOPMEDS UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_PROCOAGULANTS', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_PROCOAGULANTS UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_TECHNIQUE', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_TECHNIQUE UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_TRANSFUSION', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_TRANSFUSION UNION ALL
SELECT 'CHOP_CCAS_ANESTHESIA_NIRS', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_NIRS

SELECT 'ANESTHESIAAIRWAY', COUNT(*) FROM  ANESTHESIAAIRWAY UNION ALL
--SELECT 'ANESTHESIA_ANTIFIBRINOLYTICS', COUNT(*) FROM  CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS UNION ALL
SELECT 'ANESTHESIAMONITOR', COUNT(*) FROM  ANESTHESIAMONITOR UNION ALL
SELECT 'ANESTHESIAPOSTOPICU', COUNT(*) FROM  ANESTHESIAPOSTOPICU UNION ALL
SELECT 'ANESTHESIAPREOPMEDS', COUNT(*) FROM  ANESTHESIAPREOPMEDS UNION ALL
SELECT 'PROCOAGULANTS', COUNT(*) FROM  PROCOAGULANTS UNION ALL
SELECT 'ANESTHESIATECHNIQUE', COUNT(*) FROM  ANESTHESIATECHNIQUE UNION ALL
SELECT 'TRANSFUSION', COUNT(*) FROM  TRANSFUSION UNION ALL
SELECT 'NIRS', COUNT(*) FROM  NIRS

--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_AIRWAY;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_MONITOR;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_POSTOPICU;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_PREOPMEDS;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_PROCOAGULANTS;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_TECHNIQUE;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_TRANSFUSION;
--TRUNCATE TABLE CHOP_CCAS_ANESTHESIA_NIRS;

--DROP TABLE CHOP_CCAS_ANESTHESIA_AIRWAY;
--DROP TABLE CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS;
--DROP TABLE CHOP_CCAS_ANESTHESIA_MONITOR;
--DROP TABLE CHOP_CCAS_ANESTHESIA_POSTOPICU;
--DROP TABLE CHOP_CCAS_ANESTHESIA_PREOPMEDS;
--DROP TABLE CHOP_CCAS_ANESTHESIA_PROCOAGULANTS;
--DROP TABLE CHOP_CCAS_ANESTHESIA_TECHNIQUE;
--DROP TABLE CHOP_CCAS_ANESTHESIA_TRANSFUSION;

select * from CHOP_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS
select * from CHOP_CCAS_ANESTHESIA_AIRWAY
select * from CHOP_CCAS_ANESTHESIA_MONITOR
select * from CHOP_CCAS_ANESTHESIA_POSTOPICU
select * from CHOP_CCAS_ANESTHESIA_PREOPMEDS
select * from CHOP_CCAS_ANESTHESIA_PROCOAGULANTS
select * from CHOP_CCAS_ANESTHESIA_TECHNIQUE
select * from CHOP_CCAS_ANESTHESIA_TRANSFUSION
SELECT * FROM CHOP_CCAS_ANESTHESIA_NIRS


