 SELECT DISTINCT TABLE_NAME FROM _V_ODBC_COLUMNS1
 WHERE TABLE_SCHEM = 'RYBAD'

SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_AIRWAY' FROM S_CDW_CCAS_ANESTHESIA_AIRWAY UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS' FROM  S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_CASES' FROM  S_CDW_CCAS_ANESTHESIA_CASES UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_CODES' FROM  S_CDW_CCAS_ANESTHESIA_CODES UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_MONITOR' FROM  S_CDW_CCAS_ANESTHESIA_MONITOR UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_NIRS' FROM  S_CDW_CCAS_ANESTHESIA_NIRS UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_POSTOPICU' FROM  S_CDW_CCAS_ANESTHESIA_POSTOPICU UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_PREOPMEDS' FROM  S_CDW_CCAS_ANESTHESIA_PREOPMEDS UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS' FROM  S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_TECHNIQUE' FROM  S_CDW_CCAS_ANESTHESIA_TECHNIQUE UNION ALL
SELECT COUNT(*) ROWCOUNT, 'S_CDW_CCAS_ANESTHESIA_TRANSFUSION' FROM  S_CDW_CCAS_ANESTHESIA_TRANSFUSION 