WITH ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 37340) TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 37317 group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 26289 group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 26286 group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 26275 group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 37330 group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, max(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 37286 group by VISIT_KEY ) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
  AND OR_CASE.DICT_OR_SVC_KEY = 240997 --Cardiac Service 
 --AND ANES_PROV_KEY = 421751 --Dr Manrique listed as the anesthesia provider
 -- and pat_mrn_id = '56219030'
 -- and OR_LOG.LOG_ID = 231447

 
--and OR_CASE.SURG_DT_KEY = 20170824
 )
 
 ,PAT_WT AS
 (SELECT FLOW_REC.VSI_KEY,    
       CAST(AVG(CAST(MEAS_VAL/35.274 AS NUMERIC(7,1))) AS NUMERIC(5,1)) PAT_WT
FROM 
     CDW.FLOWSHEET_RECORD FLOW_REC
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY 
WHERE FS_ID IN (14)
GROUP BY 1
)

,
SPO2 AS
(SELECT  fr.vsi_key SP02_VSI_KEY
         ,C.OR_LOG_KEY SPO2_LOG_KEY
         ,REC_DT SPO2_REC_DT
	     ,MEAS_VAL_NUM AS SpO2 --SELECT DISTINCT ISNULL(MEAS_VAL,'0')
 from  ANESTHESIA_ENCOUNTER_LINK c 
     JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = C.VISIT_KEY
	INNER JOIN CDW.VISIT_STAY_INFO vsi on VAI_HSP.VISIT_KEY = vsi.VISIT_KEY
	INNER JOIN CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	INNER JOIN CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	INNER JOIN CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
	JOIN ENCS ON  ENCS.OR_LOG_KEY = C.OR_LOG_KEY  and ANES_START_DTTM >= REC_DT 
 
 WHERE 1=1	
	   AND f.FS_KEY IN (121161) --SpO2
       --AND OR_LOG_KEY = '5098014'	
)

,O2SUPP AS
(SELECT  fr.vsi_key O2SUPP_VSI_KEY
         , '1' AS O2SUPP
         ,C.OR_LOG_KEY O2SUPP_LOG_KEY
         ,REC_DT O2SUPP_DT
	     ,MEAS_VAL AS O2SUPP_VAL 
 from   
     ANESTHESIA_ENCOUNTER_LINK c 
     JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = C.VISIT_KEY
	INNER JOIN CDW.VISIT_STAY_INFO vsi on VAI_HSP.VISIT_KEY = vsi.VISIT_KEY
	INNER JOIN CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	INNER JOIN CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	INNER JOIN CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
	JOIN  ENCS  ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY and ANES_START_DTTM > REC_DT
 WHERE 1=1	
	   AND f.FS_KEY IN (133355) --O2Supp
	   and MEAS_VAL <> 'Not applicable'
	--   AND OR_LOG_KEY = '5098014'	
)
,
PREMEDS AS 
(SELECT
	vsi.vsi_key,
	min(case when lower(DISP_NM) like '%premed%given%' and UPPER(MEAS_VAL) IN ('CONTINUOUS INFUSION FROM FLOOR', 'YES') THEN '1' ELSE '2' end) as PREMED_GIVEN,
	min(case when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'IM%' THEN '525' 
	         when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'IV%' THEN '526' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'INTRANASAL%' THEN '527' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'PO%' THEN '528' 
			 when lower(DISP_NM) like '%premed%route%' and UPPER(MEAS_VAL) LIKE 'RECTAL%' THEN '529' end) as PREMED_ROUTE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%ATROPINE%' then '1' else '2' end) as ATROPINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DEMEROL%' then '1' else '2' end) as DEMEROL,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DEXMEDETOMIDINE%' then '1' else '2' end) as DEXMEDETOMIDINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%DIAZEPAM%' then '1' else '2' end) as DIAZEPAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%FENTANYL%' then '1' else '2' end) as FENTANYL,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%GLYCOPYRROLATE%' then '1' else '2' end) as GLYCOPYRROLATE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%KETAMINE%' then '1' else '2' end) as KETAMINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%LORAZEPAM%' then '1' else '2' end) as LORAZEPAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%MIDAZOLAM%' then '1' else '2' end) as MIDAZOLAM,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%MORPHINE%' then '1' else '2' end) as MORPHINE,
	min(case when lower(DISP_NM) like '%premed%options%' AND UPPER(MEAS_VAL) like '%PENTOBARBITAL%' then '1' else '2' end) as PENTOBARBITAL --SELECT distinct (case when lower(DISP_NM) like '%premed%route%' then MEAS_VAL end)
from ENCS  
     JOIN ANESTHESIA_ENCOUNTER_LINK c ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY 
	join CDW.VISIT_STAY_INFO vsi on c.ANES_VISIT_KEY = vsi.VISIT_KEY
	join CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
	join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY

where lower(DISP_NM) like '%premed%'
-- and VSI.VSI_KEY = '31604862'
group by vsi.vsi_key
)
,
ARTERIAL_LINE AS
(SELECT DISTINCT 
		FR.VSI_KEY,
        PLACE_DT ART_LINE_PLACE_DT,
		REMOVE_DT ART_LINE_REMOVE_DT,
		'1' AS ARTERIAL_LINE,
        min(CASE WHEN UPPER(LDA_SITE) = 'RADIAL' THEN '1' ELSE '2' END) AS ART_RADIAL,
		min(CASE WHEN UPPER(LDA_SITE) = 'BRACHIAL' THEN '1' ELSE '2' END) AS ART_BRACHIAL,
		min(CASE WHEN UPPER(LDA_SITE) = 'AXILLARY' THEN '1' ELSE '2' END) AS ART_AXILLARY,
		min(CASE WHEN UPPER(LDA_SITE) = 'FEMORAL' THEN '1' ELSE '2' END) AS ART_FEMORAL,
		min(CASE WHEN UPPER(LDA_SITE) = 'ULNAR' THEN '1' ELSE '2' END) AS ART_ULNAR,
		min(CASE WHEN UPPER(LDA_SITE) = 'PEDAL' THEN '1' ELSE '2' END) AS ART_DORSALIS_PEDIS,
		min(CASE WHEN UPPER(LDA_SITE) = 'POSTERIOR TIBIAL' THEN '1' ELSE '2' END) AS ART_POSTERIOR_TIBIAL,
		min(CASE WHEN UPPER(LDA_SITE) = 'UMBILICAL' THEN '1' ELSE '2' END) AS ART_UMBILICAL,
		min(CASE WHEN UPPER(LDA_DISP) LIKE '%CUTDOWN%' THEN '1' ELSE '2' END) AS CUTDOWN,
	    min(CASE WHEN UPPER(LDA_DISP) LIKE '%CUTDOWN%' and UPPER(LDA_SITE) = 'RADIAL' THEN '1' ELSE '2' END) AS CUTDOWN_RADIAL,
	    min(CASE WHEN UPPER(LDA_DISP) LIKE '%CUTDOWN%' and (UPPER(LDA_SITE) = 'ULNAR'  or UPPER(MEAS_CMT) = 'MEDIAL') THEN '1' ELSE '2' END) AS CUTDOWN_ULNAR,
		min(CASE WHEN UPPER(LDA_DISP) LIKE '%CUTDOWN%' and UPPER(LDA_SITE) = 'FEMORAL' THEN '1' ELSE '2' END) AS CUTDOWN_FEMORAL,
		min(CASE WHEN UPPER(LDA_DISP) LIKE '%CUTDOWN%' AND UPPER(LDA_SITE) <> 'RADIAL' AND UPPER(LDA_SITE) <> 'ULNAR' AND UPPER(LDA_SITE) <> 'FEMORAL' AND UPPER(MEAS_CMT) <> 'MEDIAL' THEN '1' ELSE '2' END) AS CUTDOWN_OTHER,	
		min(CASE WHEN UPPER(MEAS_VAL) = 'ULTRASOUND' THEN '1' ELSE '2' END) AS ART_ULTRA,
		min(CASE WHEN UPPER(LDA_DESC) LIKE '%INTRACARDIAC%' THEN '1' ELSE '2' END) AS ART_SURG_PLACE
from CDW.PATIENT_LDA lda
	join CDW.VISIT_STAY_INFO_ROWS vsr on lda.PAT_LDA_KEY = vsr.PAT_LDA_KEY
	join CDW.FLOWSHEET_RECORD fr on vsr.VSI_KEY = fr.VSI_KEY
	join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
  --  JOIN ENCS ON ENCS.ANES_VSI_KEY = FR.VSI_KEY --CHANGED 7/9/2018 after data validation session
    JOIN ENCS ON ENCS.HSP_VAI_KEY = FR.VSI_KEY

where 1=1
  AND vsr.SEQ_NUM = fm.OCCURANCE /*Necessary to match the specific instance of the flowsheet recording to the correct measure value*/
  AND LDA.FS_KEY IN (138702,138697,139076,138841) --  UAC SINGLE AND UAC DOUBLE LUMENS, ARTERIAL LINE
 -- AND FR.VSI_KEY = '31604862'
 GROUP BY 1,2,3,4
)

,TMP AS 
( SELECT 
       tmp.log_key,
       TMP.ENTRY_DT,
	   TMP.TMP,
	   isnull(TMPSITE.TMP_SITE,410) TMP_SITE,
	   ROW_NUMBER() OVER (PARTITION BY TMP.log_key ORDER BY TMP.TMP) TMP_ORDER
	   
FROM
	   (select  
	          or_log.log_key,  
			 ENTRY_DT,--FLOW_MEA.FS_KEY, FLOW_MEA.MEAS_VAL
	         CAST(((fm.MEAS_VAL_num)-32)*(5/9.0) AS NUMERIC(4,1)) TMP
		from or_log
			join anesthesia_encounteR_link ael on or_log.log_key = ael.or_log_key
			join visit_stay_info vsi on ael.ANES_VISIT_KEY = vsi.VISIT_KEY
			join flowsheet_record fr on vsi.VSI_KEY = fr.VSI_KEY
			join flowsheet_measure fm on fr.FS_REC_KEY = fm.FS_REC_KEY
			join flowsheet f on fm.FS_KEY = f.FS_KEY
			JOIN  ENCS  ON ENCS.OR_LOG_KEY = ael.OR_LOG_KEY and fm.REC_DT BETWEEN ENCS.ANES_START_TM AND ENCS.ANES_STOP_DOC_TM
		where 
		f.FS_ID in (7727,7717,7715,7725,7729,7723,7735,7733,7719)
		--and meas_val_num > 95.0
		) TMP

left JOIN		
		
	  (SELECT *
	  FROM
	     ( SELECT
		    or_log.log_key,
			ENTRY_DT,
	        CASE WHEN UPPER(FLOW_MEA.MEAS_VAL) = 'AXILLARY' THEN 414
			         WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ORAL' THEN 410 --Nasal
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'RECTAL' THEN 413
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ESOPHAGEAL PROBE' THEN 411
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'TEMPORAL' THEN  409 --Skin 2894 Tympanic?
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'BLADDER PROBE' THEN 412
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'CORE TEMPERATURE (ECMO, SWAN GANZ)' THEN 2895
					 WHEN  UPPER(FLOW_MEA.MEAS_VAL) IS NULL THEN NULL END TMP_SITE,
			ROW_NUMBER() OVER (PARTITION BY VAI.VSI_KEY ORDER BY ENTRY_DT) TMP_SITE_ORDER
		FROM 
		    or_log
			join anesthesia_encounteR_link ael on or_log.log_key = ael.or_log_key 
			join CDW.VISIT_ADDL_INFO VAI ON VAI.VISIT_KEY = ael.VISIT_KEY
		    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
		    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
		    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
			JOIN ENCS ON ENCS.HSP_VAI_KEY = VAI.VSI_KEY and FLOW_MEA.REC_DT BETWEEN ENCS.ANES_START_TM AND ENCS.ANES_STOP_DOC_TM
		WHERE FLOW_MEA.FS_KEY IN (133512) --134071,148995,149098,148987,148979,149089,)
		 AND MEAS_VAL IS NOT NULL
		) TMPSTE
      WHERE TMP_SITE_ORDER = 1
	 ) TMPSITE
 ON TMP.log_key = TMPSITE.log_key 
)



,
PCP AS
(SELECT VSI_KEY,
        PERC_PLACE_DT,
		PERC_REMOVE_DT,
		INS_BY,
		PCP,
        MIN(CASE WHEN SIDE = 'RIGHT' AND INS_VESSEL = 'INTERNAL JUGULAR' THEN '1' ELSE '2' END) AS RIGHT_INTERNAL_JUGULAR,
		MIN(CASE WHEN SIDE = 'RIGHT' AND INS_VESSEL = 'SUBCLAVIAN' THEN '1' ELSE '2' END) AS RIGHT_SUBCLAVIAN,
		MIN(CASE WHEN SIDE = 'RIGHT' AND INS_VESSEL = 'FEMORAL' THEN '1' ELSE '2' END) AS RIGHT_FEMORAL_VEIN,
        MIN(CASE WHEN SIDE = 'LEFT' AND INS_VESSEL = 'INTERNAL JUGULAR' THEN '1' ELSE '2' END) AS LEFT_INTERNAL_JUGULAR,
		MIN(CASE WHEN SIDE = 'LEFT' AND INS_VESSEL = 'SUBCLAVIAN' THEN '1' ELSE '2' END) AS LEFT_SUBCLAVIAN,
		MIN(CASE WHEN SIDE = 'LEFT' AND INS_VESSEL = 'FEMORAL' THEN '1' ELSE '2' END) AS LEFT_FEMORAL_VEIN,
		MIN(CASE WHEN SIDE IN ('RIGHT','LEFT') AND NOT(INS_VESSEL IN ('INTERNAL JUGULAR','SUBCLAVIAN','FEMORAL','INTERNAL JUGULAR','SUBCLAVIAN','FEMORAL')) THEN '1' ELSE '2' END) AS PCP_OTHER
        
FROM
	(SELECT DISTINCT 
			FR.VSI_KEY,
	        PLACE_DT AS PERC_PLACE_DT,
			REMOVE_DT AS PERC_REMOVE_DT,
		    '1' AS PCP,
			MAX(CASE WHEN F.FS_KEY = 133550  THEN UPPER(MEAS_VAL) ELSE '' END) AS SIDE,
			MAX(CASE WHEN F.FS_KEY = 133544  THEN UPPER(MEAS_VAL) ELSE '' END) AS INS_VESSEL,
	        MAX(CASE WHEN F.FS_KEY = 133572  THEN UPPER(MEAS_VAL) ELSE '' END) AS INS_TECH,
			MAX(CASE WHEN F.FS_KEY = 133563  THEN UPPER(MEAS_VAL) ELSE '' END) AS INS_BY
	from CDW.PATIENT_LDA lda 
	    join CDW.VISIT_STAY_INFO VSI ON VSI.VISIT_KEY = LDA.VISIT_KEY
		join CDW.VISIT_STAY_INFO_ROWS vsr on VSI.VSI_KEY = vsr.VSI_KEY
		join CDW.FLOWSHEET_RECORD fr on vsr.VSI_KEY = fr.VSI_KEY
		join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
		join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
		join CDW.FLOWSHEET_LDA_GROUP lda_group on vsr.FS_KEY = lda_group.FS_KEY
		JOIN ENCS ON ENCS.ANES_VSI_KEY = FR.VSI_KEY

	where 1=1
	  AND vsr.SEQ_NUM = fm.OCCURANCE /*Necessary to match the specific instance of the flowsheet recording to the correct measure value*/
	  AND lda_group.DICT_LDA_TYPE_KEY in (20862,20861,21280, 21290) -- PICC, CVA, LA OR RA
	  AND F.FS_KEY IN (133550,133544,133563,133572)
	GROUP BY 1,2,3,4
	)a
GROUP BY 1,2,3,4,5
)



, ENC_SPO2 AS 
(SELECT *
   FROM 
       (SELECT ENCS.*
	           ,SPO2.*
			   ,EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT) ANESRECDATEDIFF
			   ,ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT)) SPO2_ORDER
		FROM   ENCS  LEFT JOIN  SPO2  ON ENCS.OR_LOG_KEY = SPO2.SPO2_LOG_KEY and EXTRACT(EPOCH FROM ANES_START_DTTM-SPO2_REC_DT) > 0 --> prior to start of procedure AND ROWNO = 1 AND SPORDER = 1
	    )ENC_SPO2_ROWNO
WHERE SPO2_ORDER = 1
)


, ENC_SPO2_O2SUPP AS 
(SELECT *
   FROM 
       (SELECT ENC_SPO2.*
	           ,O2SUPP.*
			   ,EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT) ANESO2DATEDIFF
			   ,ROW_NUMBER() OVER (PARTITION BY ENC_SPO2.OR_LOG_KEY ORDER BY EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT)) O2SUPP_ORDER
		FROM   ENC_SPO2  LEFT JOIN  O2SUPP  ON ENC_SPO2.OR_LOG_KEY = O2SUPP.O2SUPP_LOG_KEY and EXTRACT(EPOCH FROM ANES_START_DTTM-O2SUPP_DT) > 0 --> prior to start of procedure AND ROWNO = 1 AND SPORDER = 1
	    )ENC_SPO2_O2SUPP_ROWNO
WHERE O2SUPP_ORDER = 1
)

 , INDUCT_MEDS AS 
(SELECT INDUCTMED.VISIT_KEY
       ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%TRACH%' OR UPPER(DICT_NM) LIKE '%MASK%' THEN '1' ELSE '2' END) AS INHALATION
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%TRACH%' OR UPPER(DICT_NM) LIKE '%MASK%'
	              AND UPPER(MED_ORD_NM) LIKE '%SEVOFLURANE%' THEN '1' ELSE '2' END) AS INH_SEVOFLURANE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%TRACH%' OR UPPER(DICT_NM) LIKE '%MASK%'
	              AND UPPER(MED_ORD_NM) LIKE '%ISOFLURANE%' THEN '1' ELSE '2' END) AS INH_ISOFLURANE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%' THEN '1' ELSE '2' END) AS INTRAVENOUS
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%SODIUM THIOPENTAL%' THEN '1' ELSE '2' END) AS INTV_SODIUM_THIO
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%KETAMINE%' THEN '1' ELSE '2' END) AS INTV_KETAMINE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%ETOMIDATE%' THEN '1' ELSE '2' END) AS INTV_ETOMIDATE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%PROPOFOL%' THEN '1' ELSE '2' END) AS INTV_PROPOFOL
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%FENTANYL%' THEN '1' ELSE '2' END) AS INTV_FENTANYL
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%MIDAZOLAM%' THEN '1' ELSE '2' END) AS INTV_MIDAZOLAM
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%DEXEMEDETOMIDINE%' THEN '1' ELSE '2' END) AS INTV_DEXEMEDETOMIDINE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%SUFENTANIL%' THEN '1' ELSE '2' END) AS INTV_SUFENTANIL
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAVENOUS%'
	              AND UPPER(MED_ORD_NM) LIKE '%REMIFENTANIL%' THEN '1' ELSE '2' END) AS INTV_REMIFENTANIL
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAMUSCULAR%' THEN '1' ELSE '2' END) AS INTRAMUSCULAR
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAMUSCULAR%'
	              AND UPPER(MED_ORD_NM) LIKE '%KETAMINE%' THEN '1' ELSE '2' END) AS INTRA_KETAMINE
	   ,MIN(CASE WHEN UPPER(DICT_NM) LIKE '%INTRAMUSCULAR%'
	              AND UPPER(MED_ORD_NM) LIKE '%MIDAZOLAM%' THEN '1' ELSE '2' END) AS INTRA_MIDAZOLAM
FROM  ENCS JOIN MEDICATION_ADMINISTRATION INDUCTMED ON  INDUCTMED.VISIT_KEY = ENCS.ANES_VISIT_KEY and INDUCTMED.ACTION_DT BETWEEN ENCS.ANES_START_TM AND ENCS.ANESREADY_TM 
           JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = INDUCTMED.MED_ORD_KEY  
		   LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = INDUCTMED.DICT_RTE_KEY
GROUP BY INDUCTMED.VISIT_KEY
)

,REGANES AS
(select DISTINCT 
       ENCS.ANES_VISIT_KEY
      ,1 AS REGIONAL_ANES
 	  ,MIN(CASE WHEN UPPER(ELEM_VAL) LIKE '%THORACIC EPIDURAL%' THEN 585
	        WHEN UPPER(ELEM_VAL) LIKE '%LUMBAR EPIDURAL%' THEN 586
			WHEN UPPER(ELEM_VAL) LIKE '%CAUDAL EPIDURAL%' THEN 587
		    WHEN UPPER(ELEM_VAL) LIKE '%LUMBAR EPIDURAL%' AND UPPER(ELEM_VAL) LIKE '%SHOT%' THEN 588
			WHEN UPPER(ELEM_VAL) LIKE '%CAUDAL (SACRAL)%' OR UPPER(ELEM_VAL) LIKE '%CAUDAL (LUMBAR)%' OR UPPER(ELEM_VAL) LIKE '%CAUDAL (THORACIC)%' THEN 589
			WHEN UPPER(ELEM_VAL) LIKE '%INTRATHECAL%' OR UPPER(ELEM_VAL) LIKE '%SUBARACHNOID (SPINAL)%' THEN 590
		    WHEN UPPER(ELEM_VAL) LIKE '%PARAVERTEBRAL%' AND UPPER(ELEM_VAL) LIKE '%SHOT%' THEN 3712
			WHEN UPPER(ELEM_VAL) LIKE '%PARAVERTEBRAL%' AND UPPER(ELEM_VAL) LIKE '%CATHETER%' THEN 3713
			WHEN UPPER(CONCEPT_DESC) <> 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) NOT LIKE '%LUMBAR%' 
			                                                          AND UPPER(ELEM_VAL) NOT LIKE '%CAUDAL%'
																	  AND UPPER(ELEM_VAL) NOT LIKE '%INTRATHECAL%' 
																	  AND UPPER(ELEM_VAL) NOT LIKE '%SUBARACHNOID%' 
																	  AND UPPER(ELEM_VAL) NOT LIKE '%PARAVERTEBRAL%' 
																	  THEN 3036
		END) AS REGANESSITE --
		,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%BUPIVACAINE%' THEN 1 ELSE 2 END) AS REGANESDRUGBUP
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%BUPIVICAINE%%FENTANYL' THEN 1 ELSE 2 END) AS REGANESDRUGBUPFEN
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%CLONIDINE%' THEN 1 ELSE 2 END) AS REGANESDRUGCLON
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%FENTANYL%' THEN 1 ELSE 2 END) AS REGANESDRUGFEN
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%HYDROMORPHONE%' THEN 1 ELSE 2 END) AS REGANESDRUGHYDRO
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%LIDOCAINE%' THEN 1 ELSE 2 END) AS REGANESDRUGLIDO
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%MORPHINE%' THEN 1 ELSE 2 END) AS REGANESDRUGMORPH
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%ROPIVICAINE%' THEN 1 ELSE 2 END) AS REGANESDRUGROP
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%ROPIVICAINE%%FENTANYL%' THEN 1 ELSE 2 END) AS REGANESDRUGROPFEN
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) LIKE '%TETRACAINE%' THEN 1 ELSE 2 END) AS REGANESDRUGTETRA
      	,MIN(CASE WHEN UPPER(CONCEPT_DESC) = 'ANES BLOCK LOCAL ANESTHETIC' AND UPPER(ELEM_VAL) NOT LIKE '%BUPIVACAINE%' 
		                                                               AND UPPER(ELEM_VAL) NOT LIKE '%CLONIDINE%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%FENTANYL%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%HYDROMORPHONE%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%LIDOCAINE%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%MORPHINE%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%ROPIVACAINE%'
																	   AND UPPER(ELEM_VAL) NOT LIKE '%TETRACAINE%'
																	   THEN 1 ELSE 2 END) AS REGANESDRUGOTH 
     
from ENCS
	join CDW.PROCEDURE_ORDER po on ENCS.ANES_VISIT_KEY = po.VISIT_KEY
	join CDW.SMART_DATA_ELEMENT sde on po.PROC_ORD_KEY = sde.PROC_ORD_KEY
	join CDW.CLINICAL_CONCEPT cc on sde.CONCEPT_KEY = cc.CONCEPT_KEY
WHERE 1=1
  AND ((UPPER(PROC_ORD_DESC) LIKE '%BLOCK%' AND UPPER(PROC_ORD_DESC) LIKE '%NEURAXIAL%') OR
       (UPPER(PROC_ORD_DESC) LIKE '%BLOCK%' AND UPPER(PROC_ORD_DESC) LIKE '%GENERAL%') )
  AND ((UPPER(CONCEPT_DESC) LIKE '%BLOCK%' AND UPPER(CONCEPT_DESC) LIKE '%NEURAXIAL%') OR
       (UPPER(CONCEPT_DESC) LIKE '%BLOCK%' AND UPPER(CONCEPT_DESC) LIKE '%GENERAL%') )
  OR (CC.CONCEPT_DESC = 'ANES BLOCK LOCAL ANESTHETIC')
GROUP BY 1,2
)	   

 , AIRWAY AS
(
SELECT  FR.VSI_KEY
       ,PLACE_DT AIRWAY_PLACE_DT
       ,REMOVE_DT AIRWAY_REM_DT
	   ,MIN(CASE WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) = '' THEN 472
	             WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%BAG%' THEN 473 
				 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%CANNULAE%' THEN 474 
				 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) = 'LARYNGEAL MASK AIRWAY' THEN 475 
				 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%ENDOTRACHEAL%' THEN 476 
				 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%TRACHEOSTOMY%' THEN 477 
				 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%SIMPLE MASK%' THEN 2808 
	         END) AS AIRWAYTYPE
	   ,MIN(CASE WHEN F.FS_KEY=159586 AND MEAS_VAL = '1' THEN 465
	             WHEN F.FS_KEY=159586 AND MEAS_VAL = '1.5' THEN 466
				 WHEN F.FS_KEY=159586 AND MEAS_VAL = '2' THEN 467
				 WHEN F.FS_KEY=159586 AND MEAS_VAL = '2.5' THEN 468
				 WHEN F.FS_KEY=159586 AND MEAS_VAL = '3' THEN 469
				 WHEN F.FS_KEY=159586 AND MEAS_VAL = '4' THEN 470
				 WHEN F.FS_KEY=159586 AND MEAS_VAL = '5' THEN 471 END) AS AIRWAYSIZELMA
	   ,MIN(CASE WHEN F.FS_KEY=139145 AND MEAS_VAL = '2.5' THEN 453 
	             WHEN F.FS_KEY=139145 AND MEAS_VAL = '3' THEN 454
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '3.5' THEN 455
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '4' THEN 456
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '4.5' THEN 457
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '5' THEN 458
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '5.5' THEN 459
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '6' THEN 460
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '6.5' THEN 461
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '7' THEN 462
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '7.5' THEN 463
				 WHEN F.FS_KEY=139145 AND MEAS_VAL = '8' THEN 464
				 ELSE 2807 END) AS ENDOTRACH_SZ
	   ,MIN(CASE WHEN F.FS_KEY=139128 AND UPPER(MEAS_VAL) = 'YES' THEN 1
	             WHEN F.FS_KEY=139128 AND UPPER(MEAS_VAL) = 'NO' THEN 2 
				 ELSE '1119' END) AS CUFFED
	   ,MIN(CASE WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%ORAL%' THEN 450
	             WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%NASAL%' THEN 451
	   			 WHEN F.FS_KEY=139115 AND UPPER(MEAS_VAL) LIKE '%TRACHEOSTOMY%' THEN 452
		    END) AS AIRWAYSITE
	   ,ENDOBRONCH_ISO.ENDOBRONCH_ISO
	   ,NULL  AS ENDOBRONCH_ISO_METH --N/A
	   ,'2' AS ICUTYPE_USED --NOT USED   
	  -- ,F.FS_KEY
	  -- ,F.DISP_NM
	  -- ,MEAS_VAL SELECT DISTINCT F.FS_KEY, F.DISP_NM
from CDW.PATIENT_LDA lda
	join CDW.VISIT_STAY_INFO_ROWS vsr on lda.PAT_LDA_KEY = vsr.PAT_LDA_KEY
	join CDW.FLOWSHEET_RECORD fr on vsr.VSI_KEY = fr.VSI_KEY
	join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
	join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
	join CDW.FLOWSHEET_TEMPLATE_GROUP ftg on vsr.FS_KEY = ftg.FS_KEY
	join CDW.FLOWSHEET_TEMPLATE ft on ftg.FS_TEMP_KEY = ft.FS_TEMP_KEY
	join CDW.FLOWSHEET_LDA_GROUP lda_group on vsr.FS_KEY = lda_group.FS_KEY
	join CDW.CDW_DICTIONARY dict_type on lda_group.DICT_LDA_TYPE_KEY = dict_type.DICT_KEY
    JOIN ENCS ON ENCS.ANES_VSI_KEY = FR.VSI_KEY
	LEFT JOIN (SELECT VISIT_KEY, 1 AS ENDOBRONCH_ISO FROM VISIT_ED_EVENT EVENT WHERE EVENT_TYPE_KEY = 37355) ENDOBRONCH_ISO ON ENDOBRONCH_ISO.VISIT_KEY = ENCS.ANES_VISIT_KEY

where 1=1
  AND vsr.SEQ_NUM = fm.OCCURANCE /*Necessary to match the specific instance of the flowsheet recording to the correct measure value*/
  AND dict_type.dict_key in (544804,20865)
    and airway_PLACE_DT <> airway_REM_DT
group BY FR.VSI_KEY, PLACE_DT, REMOVE_DT, ENDOBRONCH_ISO
)


 , BLEED_MGT AS
( SELECT 
     VISIT_KEY
	,MIN(1) AS ANTIFIBUSAGE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' THEN '1' ELSE '2' END) AS ANTIFIBEPUSE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' AND BOLUS = 1  AND BOLUS_ORDER = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END)  ANTIFIBEPLOAD
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' AND BOLUS = 0 THEN CAST(DOSE AS INTEGER) END)  ANTIFIBEPINFRATE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' AND BOLUS = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT)  AS INTEGER) END) ANTIFIBEPPRIME
--	,MIN(NULL) ANTIFIBEPPRIMEDOSE -- not used
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' THEN '1' ELSE '2' END) AS ANTIFIBTRANEXUSE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' AND BOLUS = 1 AND BOLUS_ORDER = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END )ANTIFIBTRANEXLOAD
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' AND BOLUS = 0 THEN CAST(DOSE AS INTEGER) END) ANTIFIBTRANEXINFRATE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' AND BOLUS = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END) ANTIFIBTRANEXPRIME
--	,MIN(NULL) ANTIFIBTRANEXPRIMEDOSE --not used
--	,MIN(NULL) ANTIFIBTRASYLUSE --not used
--	,MIN(NULL) ANTIFIBTRASYLLOAD --not used
--	,MIN(NULL) ANTIFIBTRASYLPRIME --not used
--	,MIN(NULL) ANTIFIBTRASYLINFRATE  --not used 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY VISIT_KEY,BOLUS ORDER BY ACTION_DT, MED_ORD_KEY) BOLUS_ORDER

		FROM         
		   (SELECT
		         ANTIFIB.MED_ORD_KEY
				,DISCR_DOSE
			   , MED_ORD_NM
			   , CASE WHEN UPPER(MED_ORD_NM) LIKE '%BOLUS%' THEN 1 ELSE 0 END AS BOLUS
		       , ANTIFIB.SEQ_NUM
		       , ANTIFIB.VISIT_KEY
		       , ANTIFIB.ACTION_DT
			   , ANTIFIB.DICT_DOSE_UNIT_KEY
		       , ANTIFIB.DOSE
		       , ANTIFIB.INFSN_RATE
			   , MEDORD.DOSAGE_WEIGHT_KG 
			   , PAT_WT.PAT_WT
			FROM  ENCS JOIN MEDICATION_ADMINISTRATION ANTIFIB ON  ANTIFIB.VISIT_KEY = ENCS.ANES_VISIT_KEY   
			           JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = ANTIFIB.MED_ORD_KEY  
					   LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = ANTIFIB.DICT_RTE_KEY
					   LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = ANTIFIB.DICT_RSLT_KEY
					   LEFT JOIN PAT_WT ON ENCS.HSP_VAI_KEY = PAT_WT.VSI_KEY 
			WHERE 1=1
			  AND (UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' OR UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%')
			  and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) --GIVEN MEDS
			) ANTIFIB

	)	ANTIFIBTMP	 
GROUP BY VISIT_KEY 
)
 
, PROCOAG AS
 (SELECT VISIT_KEY
       ,'1' AS ProcoagUsage
	   ,'1' AS ProcoagFactorVIIa
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT DISTINCT
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , MEDORD.DOSAGE_WEIGHT_KG 
		FROM  ENCS JOIN MEDICATION_ADMINISTRATION PROCOAG ON PROCOAG.VISIT_KEY = ENCS.ANES_VISIT_KEY  
		           JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = PROCOAG.MED_ORD_KEY  
				   LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = PROCOAG.DICT_RTE_KEY
				   LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = PROCOAG.DICT_RSLT_KEY
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 1=1
		  AND (UPPER(MED_ORD_NM) LIKE '%FACTOR VIIA%')
		  and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) --GIVEN MEDS
		  )FACT7
	  --AND PROCOAG.VISIT_KEY = '112395108' 
	)FACT7SEQ
GROUP BY VISIT_KEY 
)

 ,TRANSF AS 
(SELECT vsi_key 
		,MIN('1') as TRANSFUSION
        ,ISNULL(MIN(CASE WHEN FS_KEY = 159169 THEN 1 ELSE 2 END),0) AS CELLSAVER
        ,ISNULL(MIN(CASE WHEN FS_KEY = 159498 THEN UNITS END),0) AS PRBC_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 159034 THEN UNITS END),0) AS FFP_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 159432 THEN UNITS END),0) AS FRESHPLAS_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 000000 THEN UNITS END),0) AS SDPHERESIS_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 159265 THEN UNITS END),0) AS PLATE_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 159162 THEN UNITS END),0) AS CYRO_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 172128 THEN UNITS END),0) AS FWB_UNITS
		,ISNULL(MIN(CASE WHEN FS_KEY = 159529 THEN UNITS END),0) AS WB_UNITS 
FROM
	(SELECT vsi.vsi_key, F.FS_KEY, COUNT(DISTINCT MEAS_VAL) UNITS
	from ENCS  
	     JOIN ANESTHESIA_ENCOUNTER_LINK c ON ENCS.OR_LOG_KEY = C.OR_LOG_KEY 
		join CDW.VISIT_STAY_INFO vsi on c.ANES_VISIT_KEY = vsi.VISIT_KEY
		join CDW.FLOWSHEET_RECORD fr on vsi.VSI_KEY = fr.VSI_KEY
		join CDW.FLOWSHEET_MEASURE fm on fr.FS_REC_KEY = fm.FS_REC_KEY
		join CDW.FLOWSHEET f on fm.FS_KEY = f.FS_KEY
	where F.FS_KEY IN (159162,135493,159034,135499,159265,135490,159498,135508,159529,159432,172128,159169)
	group by vsi.vsi_key, F.FS_KEY
	) UNITS
GROUP BY VSI_KEY
)

, ICU_FIO2 AS
(SELECT  FLOW_REC.vsi_key
         ,REC_DT ICU_FIO2_DT
		 --,ENCS.HANDOFF_TM
	    ,CASE WHEN MEAS_VAL IS NULL THEN NULL ELSE CAST(CAST(MEAS_VAL AS INTEGER)/100.0 AS NUMERIC(5,2)) END AS ICU_FIO2_VAL
		,ROW_NUMBER() OVER (PARTITION BY FLOW_REC.VSI_KEY ORDER BY FLOW_MEA.REC_DT) ICU_FIO2_ORDER 
FROM  CDW.VISIT_ADDL_INFO VAI 
    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
WHERE 1=1
   AND FLOW.FS_KEY = 137409	   
)


, ICU_SPO2 AS
(SELECT  FLOW_REC.vsi_key
         ,REC_DT ICU_SPO2_DT
		-- ,ENCS.HANDOFF_TM
	     ,MEAS_VAL AS ICU_SPO2_VAL
		 ,ROW_NUMBER() OVER (PARTITION BY FLOW_REC.VSI_KEY ORDER BY FLOW_MEA.REC_DT) ICU_SPO2_ORDER
FROM  CDW.VISIT_ADDL_INFO VAI 
    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
 WHERE 1=1	
   AND FLOW.FS_KEY = 121161 --SPO2
)

,ICU_TMP AS 
(SELECT TMP.VSI_KEY,
       TMP.ENTRY_DT ICU_TMP_DT,
	   TMP.TMP ICU_TMP,
	   TMPSITE.TMP_SITE ICU_TMP_SITE,
	   ROW_NUMBER() OVER (PARTITION BY TMP.VSI_KEY ORDER BY TMP.ENTRY_DT) ICU_TMP_ORDER
	   
FROM
	   (SELECT
		    VAI.VSI_KEY,  
			ENTRY_DT,--FLOW_MEA.FS_KEY, FLOW_MEA.MEAS_VAL
	        CAST(((FLOW_MEA.MEAS_VAL)-32)*(5/9.0) AS NUMERIC(4,1)) TMP
		FROM 
		    CDW.VISIT_ADDL_INFO VAI 
		    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
		    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
		    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
			JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT >= ENCS.HANDOFF_TM
		WHERE FLOW_MEA.FS_KEY IN (121170)
		 AND MEAS_VAL IS NOT NULL
		) TMP

INNER JOIN		
		
	   (SELECT
	    VAI.VSI_KEY,  
		ENTRY_DT,
        CASE WHEN UPPER(FLOW_MEA.MEAS_VAL) = 'AXILLARY' THEN 414
		         WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ORAL' THEN 410 --Nasal
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'RECTAL' THEN 413
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ESOPHAGEAL PROBE' THEN 411
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'TEMPORAL' THEN  409 --Skin 2894 Tympanic?
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'BLADDER PROBE' THEN 412
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'CORE TEMPERATURE (ECMO, SWAN GANZ)' THEN 2895
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) IS NULL THEN NULL END TMP_SITE

		FROM 
		    CDW.VISIT_ADDL_INFO VAI 
		    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
		    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
		    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
			JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT >= ENCS.HANDOFF_TM
		WHERE FLOW_MEA.FS_KEY IN (133512) 
		 AND MEAS_VAL IS NOT NULL
		) TMPSITE

 ON TMP.VSI_KEY = TMPSITE.VSI_KEY AND TMP.ENTRY_DT = TMPSITE.ENTRY_DT
)

, ICU_LABS AS
 (select RSLT.PROC_ORD_KEY
       ,RSLT.VISIT_KEY
	   , '1' AS ICU_LABS
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY = 50085 THEN regexp_replace(RSLT_VAL, '[<>]', '') END) AS PH
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY = 50692 THEN regexp_replace(RSLT_VAL, '[<>]', '') END) AS PCO2
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY = 51936 THEN regexp_replace(RSLT_VAL, '[<>]', '') END) AS PO2
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY = 51216 THEN regexp_replace(RSLT_VAL, '[<>]', '') END) AS BASEEXCESS
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY = 53433 THEN regexp_replace(RSLT_VAL, '[<>]', '') END) AS LACTATE
	   ,RSLT_DT --SELECT *
	   ,ROW_NUMBER() OVER (PARTITION BY RSLT.VISIT_KEY ORDER BY RSLT_DT) LAB_ORDER
 from PROCEDURE_ORDER_RESULT RSLT join RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY
                                  JOIN ENCS ON ENCS.VISIT_KEY = RSLT.VISIT_KEY AND ENCS.PROCSTOP_TM < RSLT_DT
 WHERE 1=1
   AND RSLT.RSLT_COMP_KEY IN (50085,50692,51936,51216,53433)
   GROUP BY RSLT.PROC_ORD_KEY, RSLT.VISIT_KEY, RSLT_DT
)

, ICU_HEMATOCRIT AS
 (select RSLT.PROC_ORD_KEY
       ,RSLT.VISIT_KEY
	   , '1' AS ICU_HEMAT
	   ,MIN(CASE WHEN RSLT.RSLT_COMP_KEY IN (49400, 54509) THEN RSLT_NUM_VAL END) AS HEMATOCRIT
	   ,RSLT_DT --SELECT *
	   ,ROW_NUMBER() OVER (PARTITION BY RSLT.VISIT_KEY ORDER BY RSLT_DT) HEMAT_ORDER
 from PROCEDURE_ORDER_RESULT RSLT join RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY
                                  JOIN ENCS ON ENCS.VISIT_KEY = RSLT.VISIT_KEY AND ENCS.PROCSTOP_TM < RSLT_DT
 WHERE 1=1
   AND RSLT.RSLT_COMP_KEY IN (49400,54509)
   GROUP BY RSLT.PROC_ORD_KEY, RSLT.VISIT_KEY, RSLT_DT
)

-- MAIN SELECT STATEMENT BELOW

SELECT 
isnull(pat_mrn_id,'') mrn,
ISNULL(LOG_ID,'') CaseNumber
--ANEST PREOP / SEDATION
,SPO2 PreopO2Sat
,COALESCE(O2SUPP,'2') PreopOxygen
,ANES_START_TM PLocTransDT
,ISNULL(PREMED_GIVEN,'2') PreopSed
,ISNULL(PREMED_ROUTE,'')  PreopSedRte
,ISNULL(ATROPINE,'2') PreopSedDrugAtro
,ISNULL(DEMEROL,'2') PreopSedDrugDem
,ISNULL(DEXMEDETOMIDINE,'2') PreopSedDrugDex
,ISNULL(DIAZEPAM,'2')PreopSedDrugDiaz
,ISNULL(FENTANYL,'2') PreopSedDrugFent
,ISNULL(GLYCOPYRROLATE,'2') PreopSedDrugGlyco
,ISNULL(KETAMINE,'2') PreopSedDrugKet
,ISNULL(LORAZEPAM,'2') PreopSedDrugLoraz
,ISNULL(MIDAZOLAM,'2') PreopSedDrugMidaz
,ISNULL(MORPHINE,'2') PreopSedDrugMorph
,ISNULL(PENTOBARBITAL,'2') PreopSedDrugPent
------ VALIDATED ABOVE DATA ELEMENTS FOR PILOT
--ANEST INTRAOP / MONITORING
,ISNULL(ARTERIAL_LINE,'2') ArtLine
,ISNULL(ART_RADIAL,'2') ArtLineTypeRad
,ISNULL(ART_BRACHIAL,'2') ArtLineTypeBrach
,ISNULL(ART_AXILLARY,'2') ArtLineTypeAx
,ISNULL(ART_FEMORAL,'2') ArtLineTypeFem
,ISNULL(ART_ULNAR,'2') ArtLineTypeUlnar 
,ISNULL(ART_DORSALIS_PEDIS,'2') ArtLineTypeDors
,ISNULL(ART_POSTERIOR_TIBIAL,'2') ArtLineTypePost
,ISNULL(ART_UMBILICAL,'2') ArtLineTypeCent
,ISNULL(ART_LINE_SITU,'2') ArtLinePreProc
,ISNULL(CUTDOWN,'2') Cutdown
,ISNULL(CUTDOWN_RADIAL,'2') CutdownRad
,ISNULL(CUTDOWN_ULNAR,'2') CutdownUln
,ISNULL(CUTDOWN_FEMORAL,'2') CutdownFem
,ISNULL(CUTDOWN_OTHER,'2') CutdownOth 
,ISNULL(PCP,'2') PerCentPress
,ISNULL(RIGHT_INTERNAL_JUGULAR,'2') PCPLocRJug
,ISNULL(RIGHT_SUBCLAVIAN,'2') PCPLocRSub
,ISNULL(RIGHT_FEMORAL_VEIN,'2') PCPLocRFem
,ISNULL(LEFT_INTERNAL_JUGULAR,'2') PCPLocLJug
,ISNULL(LEFT_SUBCLAVIAN,'2') PCPLocLSub
,ISNULL(LEFT_FEMORAL_VEIN,'2') PCPLocLFem
,ISNULL(PCP_OTHER,'2') PCPLocOth
,ISNULL(CVP_PICC_LA_RA_LINE_IN_SITU,'2') CVPPICCPreProc
,ISNULL(CVP_PLACED_BY_ANES,'2') CVPPlaced
,ISNULL(ART_SURG_PLACE,'2') SurgMonLines
,TMP LowIntraopTemp
,TMP_SITE IntraopTempSite
,ISNULL(TEE,'2') TEE
--ANEST INTRAOP /ANESTHETIC TECHNIQUE
,INDUCTION_DTTM InductionDT
,INHALATION IndTypeInh
,INH_SEVOFLURANE IndAgentInhalSevo
,INH_ISOFLURANE IndAgentInhalIso
,INTRAVENOUS IndTypeIV
,INTV_SODIUM_THIO IndAgentIVSodT
,INTV_KETAMINE IndAgentIVKet
,INTV_ETOMIDATE IndAgentIVEtom
,INTV_PROPOFOL IndAgentIVProp
,INTV_FENTANYL IndAgentIVFent
,INTV_MIDAZOLAM IndAgentIVMid
,INTV_DEXEMEDETOMIDINE IndAgentIVDex
,INTV_SUFENTANIL IndAgentIVSuf
,INTV_REMIFENTANIL IndAgentIVRem
,INTRAMUSCULAR IndTypeIM
,INTRA_KETAMINE IndAgentIMKet
,INTRA_MIDAZOLAM IndAgentIMMid
,ISNULL(REGIONAL_ANES,'2') RegionalAnes
,REGANESSITE
,REGANESDRUGBUP
,REGANESDRUGBUPFEN
,REGANESDRUGCLON
,REGANESDRUGFEN
,REGANESDRUGHYDRO
,REGANESDRUGLIDO
,REGANESDRUGMORPH
,REGANESDRUGROP
,REGANESDRUGROPFEN
,REGANESDRUGTETRA
,REGANESDRUGOTH
     
--ANEST INTRAOP / AIRWAY
,ISNULL(AIRWAY_SITU,2) AIRWAYINSITU
,AIRWAYTYPE
,AIRWAYSIZELMA
,ENDOTRACH_SZ AIRWAYSIZEINTUB
,CUFFED
,AIRWAYSITE 
,ISNULL(ENDOBRONCH_ISO,'2') EndobroncIso
,ENDOBRONCH_ISO_METH EndobroncIsoMeth
,ANES_READY_DTTM EndOfInductDT --N/A
--BLEEDING MGT / ANTIFIBRINOLYTICS
,ISNULL(ANTIFIBUSAGE,'2') ANTIFIBUSAGE
,ISNULL(ANTIFIBEPUSE,'2') ANTIFIBEPUSE
,ANTIFIBEPLOAD
,ANTIFIBEPPRIME
,ANTIFIBEPINFRATE
,ISNULL(ANTIFIBTRANEXUSE,'2') ANTIFIBTRANEXUSE
,ANTIFIBTRANEXLOAD
,ANTIFIBTRANEXPRIME
,ANTIFIBTRANEXINFRATE
--BLEEDING MGT / PROCOAGULANTS
,ISNULL(ProcoagUsage,'2') ProcoagUsage
,ISNULL(ProcoagFactorVIIa,'2') ProcoagFactorVIIa
,ProcoagFactorVIIa1
,ProcoagFactorVIIa2
,ProcoagFactorVIIa3
--TRANSFUSION TAB
--,'???' AutologousTrans
,ISNULL(CELLSAVER,2) CellSavSal
--,'???' TransfusBldProdAny
,ISNULL(Transfusion,'2') Transfusion
,PRBC_UNITS BldProdPRBCDur
,FFP_UNITS BldProdFFPDur
,FRESHPLAS_UNITS BldProdFreshPDur
,SDPHERESIS_UNITS BldProdSnglPlatDur
,PLATE_UNITS BldProdIndPlatDur
,CYRO_UNITS BldProdCryoDur
,FWB_UNITS BldProdFreshWBDur
,WB_UNITS  BldProdWBDur
,TO_CHAR(HANDOFF_TM,'MM/DD/YYYY HH24:MI') ICUArrDt
,ICU_FIO2_VAL InitialFiO2

,ICU_TMP TempICUArr
,ICU_TMP_SITE TempSite
,ICU_SPO2_VAL InitPulseOx
,ISNULL(ICU_LABS,'2')  ICUPACULabs
,PH
,PCO2
,PO2
,BASEEXCESS
,LACTATE
,HEMATOCRIT

FROM

( 
SELECT ENC_SPO2_O2SUPP.*,
       PREMEDS.*,
	   ARTERIAL_LINE.*,
	   ARTERIAL_LINE_SITU.ART_LINE_SITU,
	   COALESCE(PCPSITU.PCP,PCPPOST.PCP,'2') PCP,
       COALESCE(PCPSITU.RIGHT_INTERNAL_JUGULAR,PCPPOST.RIGHT_INTERNAL_JUGULAR,'2') RIGHT_INTERNAL_JUGULAR,
	   COALESCE(PCPSITU.RIGHT_SUBCLAVIAN,PCPPOST.RIGHT_SUBCLAVIAN,'2') RIGHT_SUBCLAVIAN,
	   COALESCE(PCPSITU.RIGHT_FEMORAL_VEIN,PCPPOST.RIGHT_FEMORAL_VEIN,'2') RIGHT_FEMORAL_VEIN,
 	   COALESCE(PCPSITU.LEFT_INTERNAL_JUGULAR,PCPPOST.LEFT_INTERNAL_JUGULAR,'2') LEFT_INTERNAL_JUGULAR,
 	   COALESCE(PCPSITU.LEFT_SUBCLAVIAN,PCPPOST.LEFT_SUBCLAVIAN,'2') LEFT_SUBCLAVIAN,
	   COALESCE(PCPSITU.LEFT_FEMORAL_VEIN,PCPPOST.LEFT_FEMORAL_VEIN,'2') LEFT_FEMORAL_VEIN,
	   COALESCE(PCPSITU.PCP_OTHER,PCPPOST.PCP_OTHER,'2') PCP_OTHER,
	   CASE WHEN PCPSITU.PERC_PLACE_DT < ANES_START_DTTM and PCPSITU.PERC_REMOVE_DT > ANES_START_DTTM THEN '1' ELSE '2' END AS CVP_PICC_LA_RA_LINE_IN_SITU,
	   COALESCE(PCPSITU.INS_BY,PCPPOST.INS_BY,'2') CVP_PLACED_BY_ANES,
	   TMP.TMP,
	   TMP.TMP_SITE,
	   INDUCT_MEDS.*,
	   REGANES.*,
	   AIRWAY.*,
	   AIRWAY_SITU.AIRWAY_SITU,
	   BLEED_MGT.*,
	   PROCOAG.*,
	   TRANSF.*,
	   ICU_FIO2.*,
	   ICU_SPO2.*,
	   ICU_TMP.*,
	   ICU_LABS.*,
	   ICU_HEMATOCRIT.*
FROM ENC_SPO2_O2SUPP LEFT JOIN PREMEDS ON PREMEDS.vsi_key = ENC_SPO2_O2SUPP.ANES_VSI_KEY
					 LEFT JOIN (SELECT ARTERIAL_LINE.*, '1' ART_LINE_SITU, ROW_NUMBER() OVER (PARTITION BY ARTERIAL_LINE.VSI_KEY ORDER BY ART_LINE_PLACE_DT DESC) ROWNO
					              FROM ARTERIAL_LINE JOIN ENC_SPO2_O2SUPP ON ARTERIAL_LINE.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY 
								 WHERE ARTERIAL_LINE.ART_LINE_PLACE_DT < ANES_START_DTTM and ARTERIAL_LINE.ART_LINE_REMOVE_DT > ANES_START_DTTM) ARTERIAL_LINE_SITU ON ARTERIAL_LINE_SITU.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY and ARTERIAL_LINE_SITU.ROWNO = 1
					 LEFT JOIN (SELECT ARTERIAL_LINE.*, ROW_NUMBER() OVER (PARTITION BY ARTERIAL_LINE.VSI_KEY ORDER BY ART_LINE_PLACE_DT) ROWNO
					              FROM ARTERIAL_LINE JOIN ENC_SPO2_O2SUPP ON ARTERIAL_LINE.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY 
								 WHERE ARTERIAL_LINE.ART_LINE_PLACE_DT >= ANES_START_DTTM) ARTERIAL_LINE ON ARTERIAL_LINE.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY and ARTERIAL_LINE.ROWNO = 1
					 LEFT JOIN (SELECT PCP.*, ROW_NUMBER() OVER (PARTITION BY PCP.VSI_KEY ORDER BY PERC_PLACE_DT DESC)  ROWNO
					              FROM PCP JOIN ENC_SPO2_O2SUPP ON ENC_SPO2_O2SUPP.HSP_VAI_KEY = PCP.VSI_KEY 
								 WHERE PCP.PERC_PLACE_DT < ANES_START_DTTM and PCP.PERC_REMOVE_DT > ANES_START_DTTM) PCPSITU ON PCPSITU.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY and PCPSITU.ROWNO = 1
					 LEFT JOIN (SELECT PCP.*, ROW_NUMBER() OVER (PARTITION BY PCP.VSI_KEY ORDER BY PERC_PLACE_DT) ROWNO
					              FROM PCP JOIN ENC_SPO2_O2SUPP ON ENC_SPO2_O2SUPP.HSP_VAI_KEY = PCP.VSI_KEY 
								 WHERE PCP.PERC_PLACE_DT >= ANES_START_DTTM ) PCPPOST ON PCPPOST.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY AND PCPPOST.ROWNO =1
					 LEFT JOIN TMP ON TMP.LOG_KEY = ENC_SPO2_O2SUPP.LOG_KEY	AND TMP_ORDER = 1
					 LEFT JOIN INDUCT_MEDS ON INDUCT_MEDS.VISIT_KEY = ENC_SPO2_O2SUPP.ANES_VISIT_KEY
					 LEFT JOIN REGANES ON REGANES.ANES_VISIT_KEY = ENC_SPO2_O2SUPP.ANES_VISIT_KEY
					 LEFT JOIN (SELECT AIRWAY.*, '1' AIRWAY_SITU, ROW_NUMBER() OVER (PARTITION BY AIRWAY.VSI_KEY ORDER BY AIRWAY_PLACE_DT DESC)  ROWNO
					              FROM AIRWAY JOIN ENC_SPO2_O2SUPP ON ENC_SPO2_O2SUPP.ANES_VSI_KEY = AIRWAY.VSI_KEY 
								 WHERE AIRWAY.AIRWAY_PLACE_DT < ANES_START_DTTM and AIRWAY.AIRWAY_REM_DT > ANES_START_DTTM) AIRWAY_SITU ON AIRWAY_SITU.VSI_KEY = ENC_SPO2_O2SUPP.ANES_VSI_KEY and AIRWAY_SITU.ROWNO = 1
					 LEFT JOIN (SELECT AIRWAY.*, ROW_NUMBER() OVER (PARTITION BY AIRWAY.VSI_KEY ORDER BY AIRWAY_PLACE_DT) ROWNO
					              FROM AIRWAY JOIN ENC_SPO2_O2SUPP ON ENC_SPO2_O2SUPP.ANES_VSI_KEY = AIRWAY.VSI_KEY  
								 WHERE AIRWAY.AIRWAY_PLACE_DT >= ANES_START_DTTM ) AIRWAY ON AIRWAY.VSI_KEY = ENC_SPO2_O2SUPP.ANES_VSI_KEY AND AIRWAY.ROWNO =1
					 LEFT JOIN BLEED_MGT ON BLEED_MGT.VISIT_KEY = ENC_SPO2_O2SUPP.ANES_VISIT_KEY
					 LEFT JOIN PROCOAG ON PROCOAG.VISIT_KEY = ENC_SPO2_O2SUPP.ANES_VISIT_KEY
					 LEFT JOIN TRANSF ON TRANSF.VSI_KEY = ENC_SPO2_O2SUPP.ANES_VSI_KEY
					 LEFT JOIN ICU_FIO2 ON ICU_FIO2.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY AND ICU_FIO2_ORDER = 1
					 LEFT JOIN ICU_SPO2 ON ICU_SPO2.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY AND ICU_SPO2_ORDER = 1
					 LEFT JOIN ICU_TMP ON ICU_TMP.VSI_KEY = ENC_SPO2_O2SUPP.HSP_VAI_KEY AND ICU_TMP_ORDER = 1
					 LEFT JOIN ICU_LABS ON ICU_LABS.VISIT_KEY = ENC_SPO2_O2SUPP.VISIT_KEY AND LAB_ORDER = 1
					 LEFT JOIN ICU_HEMATOCRIT ON ICU_HEMATOCRIT.VISIT_KEY = ENC_SPO2_O2SUPP.VISIT_KEY AND HEMAT_ORDER = 1
					 
WHERE 1=1 

) A

--ORDER BY 1 DESC