select
    stg_fact_external_glean_historical_cohort_metrics.hashed_mrn_key as hashed_mrn,
    cast(stg_fact_external_glean_historical_cohort_metrics.age_in_months as int) as age_in_months,
    stg_fact_external_glean_historical_cohort_metrics.age_years_historical,
    stg_fact_external_glean_historical_cohort_metrics.sex,
    stg_fact_external_glean_historical_cohort_metrics.facility,
    date(stg_fact_external_glean_historical_cohort_metrics.today) as today,
    date(stg_fact_external_glean_historical_cohort_metrics.last_neph_visit) as last_neph_visit,
    date(stg_fact_external_glean_historical_cohort_metrics.next_neph_appt) as next_neph_appt,
    stg_fact_external_glean_historical_cohort_metrics.gd_primary_dx_last_neph_visit,
    stg_fact_external_glean_historical_cohort_metrics.phenotype,
    date(stg_fact_external_glean_historical_cohort_metrics.kidney_biopsy_date) as kidney_biopsy_date,
    stg_fact_external_glean_historical_cohort_metrics.kidney_biopsy_result,
    stg_fact_external_glean_historical_cohort_metrics.genetic_testing_done,
    stg_fact_external_glean_historical_cohort_metrics.remission_status,
    date(stg_fact_external_glean_historical_cohort_metrics.remission_status_date) as remission_status_date,
    stg_fact_external_glean_historical_cohort_metrics.last_ua_protein_yr,
    date(stg_fact_external_glean_historical_cohort_metrics.last_urinalysis_date_3yr) as last_urinalysis_date_3yr,
    stg_fact_external_glean_historical_cohort_metrics.admission_count_past_30_days,
    stg_fact_external_glean_historical_cohort_metrics.ip_days_past_30_days,
    date(stg_fact_external_glean_historical_cohort_metrics.last_covid_19_vaccine) as last_covid_19_vaccine,
    date(
        stg_fact_external_glean_historical_cohort_metrics.current_season_flu_vaccine
    ) as current_season_flu_vaccine,
    date(stg_fact_external_glean_historical_cohort_metrics.most_recent_pneumovax) as most_recent_pneumovax,
    date(
        stg_fact_external_glean_historical_cohort_metrics.second_most_recent_pneumovax
    ) as second_most_recent_pneumovax,
    date(stg_fact_external_glean_historical_cohort_metrics.most_recent_prevnar_13) as most_recent_prevnar_13,
    date(
        stg_fact_external_glean_historical_cohort_metrics.second_most_recent_prevnar_13
    ) as second_most_recent_prevnar_13,
    date(
        stg_fact_external_glean_historical_cohort_metrics.third_most_recent_prevnar_13
    ) as third_most_recent_prevnar_13,
    date(
        stg_fact_external_glean_historical_cohort_metrics.fourth_most_recent_prevnar_13
    ) as fourth_most_recent_prevnar_13,
    stg_fact_external_glean_historical_cohort_metrics.imm_rec_rev,
    stg_fact_external_glean_historical_cohort_metrics.tb_screen,
    stg_fact_external_glean_historical_cohort_metrics.nutrition_counseling,
    stg_fact_external_glean_historical_cohort_metrics.patient_family_education,
    stg_fact_external_glean_historical_cohort_metrics.site_name,
    stg_fact_external_glean_historical_cohort_metrics.flu_ind,
    stg_fact_external_glean_historical_cohort_metrics.pneumovax_first_ind,
    stg_fact_external_glean_historical_cohort_metrics.pneumovax_second_ind,
    stg_fact_external_glean_historical_cohort_metrics.n_pneumovax,
    stg_fact_external_glean_historical_cohort_metrics.prevnar_first_ind,
    stg_fact_external_glean_historical_cohort_metrics.prevnar_second_ind,
    stg_fact_external_glean_historical_cohort_metrics.prevnar_third_ind,
    stg_fact_external_glean_historical_cohort_metrics.prevnar_fourth_ind,
    stg_fact_external_glean_historical_cohort_metrics.n_prevnar,
    stg_fact_external_glean_historical_cohort_metrics.first_prevnar_before_2_ind,
    stg_fact_external_glean_historical_cohort_metrics.second_prevnar_before_2_ind,
    stg_fact_external_glean_historical_cohort_metrics.third_prevnar_before_2_ind,
    stg_fact_external_glean_historical_cohort_metrics.fourth_prevnar_before_2_ind,
    stg_fact_external_glean_historical_cohort_metrics.n_prevnar_before_age_2,
    stg_fact_external_glean_historical_cohort_metrics.relapse_ind,
    stg_fact_external_glean_historical_cohort_metrics.urine_protein_remisson_ind,
    stg_fact_external_glean_historical_cohort_metrics.urine_protein_complete_ind,
    stg_fact_external_glean_historical_cohort_metrics.smartform_remission_ind,
    stg_fact_external_glean_historical_cohort_metrics.remission_all_ind,
    stg_fact_external_glean_historical_cohort_metrics.smartform_used_ind,
    stg_fact_external_glean_historical_cohort_metrics.covid_vacc_ind,
    stg_fact_external_glean_historical_cohort_metrics.covid_vacc_eligible_ind,
    stg_fact_external_glean_historical_cohort_metrics.new_onset_ind,
    stg_fact_external_glean_historical_cohort_metrics.imm_rec_rev_ind,
    stg_fact_external_glean_historical_cohort_metrics.tb_ind,
    stg_fact_external_glean_historical_cohort_metrics.rd_counseling_ind,
    stg_fact_external_glean_historical_cohort_metrics.pat_fam_edu_ind,
    stg_fact_external_glean_historical_cohort_metrics.kidney_biopsy_done_ind,
    stg_fact_external_glean_historical_cohort_metrics.genetic_testing_done_ind,
    stg_fact_external_glean_historical_cohort_metrics.pcv_13_up_to_date_ind,
    stg_fact_external_glean_historical_cohort_metrics.pcv_13_eligible_ind,
    stg_fact_external_glean_historical_cohort_metrics.pneumovax_up_to_date_ind,
    stg_fact_external_glean_historical_cohort_metrics.pneumococcal_up_to_date_ind,
    stg_fact_external_glean_historical_cohort_metrics.active_glean_patient_ind
from
    {{ref('stg_fact_external_glean_historical_cohort_metrics')}}
        as stg_fact_external_glean_historical_cohort_metrics

union all

select
    stg_fact_chop_glean_historical_cohort_metrics.hashed_mrn,
    stg_fact_chop_glean_historical_cohort_metrics.age_months_historical,
    stg_fact_chop_glean_historical_cohort_metrics.age_years_historical,
    stg_fact_chop_glean_historical_cohort_metrics.sex,
    stg_fact_chop_glean_historical_cohort_metrics.facility,
    stg_fact_chop_glean_historical_cohort_metrics.historical_date,
    stg_fact_chop_glean_historical_cohort_metrics.last_neph_visit,
    stg_fact_chop_glean_historical_cohort_metrics.next_neph_appt,
    stg_fact_chop_glean_historical_cohort_metrics.gd_primary_dx_last_neph_visit,
    stg_fact_chop_glean_historical_cohort_metrics.phenotype,
    stg_fact_chop_glean_historical_cohort_metrics.kidney_biopsy_date,
    stg_fact_chop_glean_historical_cohort_metrics.kidney_biopsy_result,
    stg_fact_chop_glean_historical_cohort_metrics.genetic_testing_performed,
    stg_fact_chop_glean_historical_cohort_metrics.remission_status,
    stg_fact_chop_glean_historical_cohort_metrics.remission_status_date,
    stg_fact_chop_glean_historical_cohort_metrics.urine_protein,
    stg_fact_chop_glean_historical_cohort_metrics.last_urinalysis_3yr,
    stg_fact_chop_glean_historical_cohort_metrics.admission_count_past_30_days,
    stg_fact_chop_glean_historical_cohort_metrics.ip_days_past_30_days,
    stg_fact_chop_glean_historical_cohort_metrics.last_covid_19_vaccine,
    stg_fact_chop_glean_historical_cohort_metrics.most_recent_flu_vaccine,
    stg_fact_chop_glean_historical_cohort_metrics.most_recent_pneumovax,
    stg_fact_chop_glean_historical_cohort_metrics.second_most_recent_pneumovax,
    stg_fact_chop_glean_historical_cohort_metrics.most_recent_prevnar_13,
    stg_fact_chop_glean_historical_cohort_metrics.second_most_recent_prevnar_13,
    stg_fact_chop_glean_historical_cohort_metrics.third_most_recent_prevnar_13,
    stg_fact_chop_glean_historical_cohort_metrics.fourth_most_recent_prevnar_13,
    stg_fact_chop_glean_historical_cohort_metrics.imm_rec_rev,
    stg_fact_chop_glean_historical_cohort_metrics.tb,
    stg_fact_chop_glean_historical_cohort_metrics.rd_counseling,
    stg_fact_chop_glean_historical_cohort_metrics.patient_family_education,
    stg_fact_chop_glean_historical_cohort_metrics.site_name,
    stg_fact_chop_glean_historical_cohort_metrics.flu_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pneumovax_first_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pneumovax_second_ind,
    stg_fact_chop_glean_historical_cohort_metrics.n_pneumovax,
    stg_fact_chop_glean_historical_cohort_metrics.prevnar_first_ind,
    stg_fact_chop_glean_historical_cohort_metrics.prevnar_second_ind,
    stg_fact_chop_glean_historical_cohort_metrics.prevnar_third_ind,
    stg_fact_chop_glean_historical_cohort_metrics.prevnar_fourth_ind,
    stg_fact_chop_glean_historical_cohort_metrics.n_prevnar,
    stg_fact_chop_glean_historical_cohort_metrics.first_prevnar_before_2_ind,
    stg_fact_chop_glean_historical_cohort_metrics.second_prevnar_before_2_ind,
    stg_fact_chop_glean_historical_cohort_metrics.third_prevnar_before_2_ind,
    stg_fact_chop_glean_historical_cohort_metrics.fourth_prevnar_before_2_ind,
    stg_fact_chop_glean_historical_cohort_metrics.n_prevnar_before_age_2,
    stg_fact_chop_glean_historical_cohort_metrics.relapse_ind,
    stg_fact_chop_glean_historical_cohort_metrics.urine_protein_remisson_ind,
    stg_fact_chop_glean_historical_cohort_metrics.urine_protein_complete_ind,
    stg_fact_chop_glean_historical_cohort_metrics.smartform_remission_ind,
    stg_fact_chop_glean_historical_cohort_metrics.remission_all_ind,
    stg_fact_chop_glean_historical_cohort_metrics.smartform_used_ind,
    stg_fact_chop_glean_historical_cohort_metrics.covid_vacc_ind,
    stg_fact_chop_glean_historical_cohort_metrics.covid_vacc_eligible_ind,
    stg_fact_chop_glean_historical_cohort_metrics.new_onset_ind,
    stg_fact_chop_glean_historical_cohort_metrics.imm_rec_rev_ind,
    stg_fact_chop_glean_historical_cohort_metrics.tb_ind,
    stg_fact_chop_glean_historical_cohort_metrics.rd_counseling_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pat_fam_edu_ind,
    stg_fact_chop_glean_historical_cohort_metrics.kidney_biopsy_done_ind,
    stg_fact_chop_glean_historical_cohort_metrics.genetic_testing_done_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pcv_13_up_to_date_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pcv_13_eligible_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pneumovax_up_to_date_ind,
    stg_fact_chop_glean_historical_cohort_metrics.pneumococcal_up_to_date_ind,
    stg_fact_chop_glean_historical_cohort_metrics.active_glean_patient_ind
from
    {{ref('stg_fact_chop_glean_historical_cohort_metrics')}}
        as stg_fact_chop_glean_historical_cohort_metrics
where rn = 1
