--CREATE TABLE REGISTRY_STS_ANESTHESIA_PROCOAGULANTS
--AS

WITH ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY	
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000051') TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000008' group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000049' group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000002' group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '100248' group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000046' group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000015' group by VISIT_KEY) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
  AND SERVICE.SRC_ID = 910 --Cardiac Service 
 )
 
  ,PAT_WT AS
 (SELECT FLOW_REC.VSI_KEY,    
       CAST(AVG(CAST(MEAS_VAL/35.274 AS NUMERIC(7,1))) AS NUMERIC(5,1)) PAT_WT
FROM 
     CDW.FLOWSHEET_RECORD FLOW_REC
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY 
WHERE FS_ID IN (14)
GROUP BY 1
)
 

 
, PROCOAG AS
 (SELECT VISIT_KEY
       ,1 AS ProcoagUsage
	   ,1 AS ProcoagFactorVIIa
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa3 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM
		(SELECT DISTINCT
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , MEDORD.DOSAGE_WEIGHT_KG 
		FROM  ENCS JOIN MEDICATION_ADMINISTRATION PROCOAG ON PROCOAG.VISIT_KEY = ENCS.ANES_VISIT_KEY  
		           JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = PROCOAG.MED_ORD_KEY  
				   LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = PROCOAG.DICT_RTE_KEY
				   LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = PROCOAG.DICT_RSLT_KEY
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 1=1
		  AND (UPPER(MED_ORD_NM) LIKE '%FACTOR VIIA%')
		  and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) --GIVEN MEDS
		  )FACT7
	  --AND PROCOAG.VISIT_KEY = '112395108' 
	)FACT7SEQ
GROUP BY VISIT_KEY 
)

 
SELECT 

		cast(ISNULL(LOG_ID,'') as integer)  CaseNumber 
		,CAST(ISNULL(ProcoagUsage,2) as integer)   ProcoagUsage
		,CAST(ISNULL(ProcoagFactorVIIa,2) as integer)  ProcoagFactorVIIa
		,CAST(ProcoagFactorVIIa1 as  integer)  ProcoagFactorVIIa1
		,CAST(ProcoagFactorVIIa2 as integer)  ProcoagFactorVIIa2
		,CAST(ProcoagFactorVIIa3 as integer) ProcoagFactorVIIa3
FROM
	(SELECT ENCS.*,
			PROCOAG.*
		FROM ENCS 
				  LEFT JOIN PROCOAG ON PROCOAG.VISIT_KEY = ENCS.ANES_VISIT_KEY
	) ENC
ORDER BY 1