with sq_ekg_study_detail_measurements as (
    select

        leadid as lead_id,
        leadidtext,
        p_onsetampl,
        p_peakampl,
        p_duration,
        p_area,
        p_peaktime,
        pp_peakampl,
        pp_duration,
        pp_area,
        pp_peaktime,
        q_peakampl,
        q_duration,
        q_area,
        q_peaktime,
        r_peakampl,
        r_duration,
        r_area,
        r_peaktime,
        s_peakampl,
        s_duration,
        s_area,
        s_peaktime,
        rp_peakampl,
        rp_duration,
        rp_area,
        rp_peaktime,
        sp_peakampl,
        sp_duration,
        sp_area,
        sp_peaktime,
        stj,
        stm,
        ste,
        maxst,
        minst,
        t_special,
        qrs_balance,
        qrs_deflection,
        max_r_ampl,
        max_s_ampl,
        t_peakampl,
        t_duration,
        t_area,
        t_peaktime,
        tp_peakampl,
        tp_duration,
        tp_area,
        tp_peaktime,
        t_end,
        pfull_area,
        qrs_area,
        tfull_area,
        qrsint,
        bitflag,
        testid || 'Muse' as ekg_study_id
    from {{ source('muse_ods', 'muse_tstecgmeasmatrixdetails') }}
)
select
    cast(ekg_study.ekg_study_id as varchar(25)) as ekg_study_id,
    cast(lead_id as integer) as lead_id,
    cast(leadidtext as varchar(10)) as leadidtext,
    cast(p_onsetampl as integer) as p_onsetampl,
    cast(p_peakampl as integer) as p_peakampl,
    cast(p_duration as integer) as p_duration,
    cast(p_area as integer) as p_area,
    cast(p_peaktime as integer) as p_peaktime,
    cast(pp_peakampl as integer) as pp_peakampl,
    cast(pp_duration as integer) as pp_duration,
    cast(pp_area as integer) as pp_area,
    cast(pp_peaktime as integer) as pp_peaktime,
    cast(q_peakampl as integer) as q_peakampl,
    cast(q_duration as integer) as q_duration,
    cast(q_area as integer) as q_area,
    cast(q_peaktime as integer) as q_peaktime,
    cast(r_peakampl as integer) as r_peakampl,
    cast(r_duration as integer) as r_duration,
    cast(r_area as integer) as r_area,
    cast(r_peaktime as integer) as r_peaktime,
    cast(s_peakampl as integer) as s_peakampl,
    cast(s_duration as integer) as s_duration,
    cast(s_area as integer) as s_area,
    cast(s_peaktime as integer) as s_peaktime,
    cast(rp_peakampl as integer) as rp_peakampl,
    cast(rp_duration as integer) as rp_duration,
    cast(rp_area as integer) as rp_area,
    cast(rp_peaktime as integer) as rp_peaktime,
    cast(sp_peakampl as integer) as sp_peakampl,
    cast(sp_duration as integer) as sp_duration,
    cast(sp_area as integer) as sp_area,
    cast(sp_peaktime as integer) as sp_peaktime,
    cast(stj as integer) as stj,
    cast(stm as integer) as stm,
    cast(ste as integer) as ste,
    cast(maxst as integer) as maxst,
    cast(minst as integer) as minst,
    cast(t_special as integer) as t_special,
    cast(qrs_balance as integer) as qrs_balance,
    cast(qrs_deflection as integer) as qrs_deflection,
    cast(max_r_ampl as integer) as max_r_ampl,
    cast(max_s_ampl as integer) as max_s_ampl,
    cast(t_peakampl as integer) as t_peakampl,
    cast(t_duration as integer) as t_duration,
    cast(t_area as integer) as t_area,
    cast(t_peaktime as integer) as t_peaktime,
    cast(tp_peakampl as integer) as tp_peakampl,
    cast(tp_duration as integer) as tp_duration,
    cast(tp_area as integer) as tp_area,
    cast(tp_peaktime as integer) as tp_peaktime,
    cast(t_end as integer) as t_end,
    cast(pfull_area as integer) as pfull_area,
    cast(qrs_area as integer) as qrs_area,
    cast(tfull_area as integer) as tfull_area,
    cast(qrsint as integer) as qrsint,
    cast(bitflag as integer) as bitflag
from sq_ekg_study_detail_measurements
inner join {{ ref('ekg_study') }} as ekg_study
     on sq_ekg_study_detail_measurements.ekg_study_id = ekg_study.ekg_study_id
