{{ config(meta = {
    'critical': true
}) }}

select
    census_tract.census_tract_key,
    raw_equity_coi2_index.geoid as census_tract_geoid_2010,
    raw_equity_coi2_index.year as observation_year,
    raw_equity_coi2_index.in100::integer as top_100_metro_area_ind,
    raw_equity_coi2_index.msaid15::integer as metro_area_fips,
    raw_equity_coi2_index.msaname15 as metro_area_name,
    raw_equity_coi2_index.countyfips as county_fips,
    raw_equity_coi2_index.statefips as state_fips,
    raw_equity_coi2_index.stateusps as state_usps,
    raw_equity_coi2_index.pop as acs_pediatric_population,
    raw_equity_coi2_index.z_ed_nat as zscore_education_domain_natl_norm,
    raw_equity_coi2_index.z_he_nat as zscore_healthenv_domain_natl_norm,
    raw_equity_coi2_index.z_se_nat as zscore_socioeconomic_domain_natl_norm,
    raw_equity_coi2_index.z_coi_nat as zscore_coi_natl_norm,
    raw_equity_coi2_index.c5_ed_nat as opportunity_lvl_education_domain_natl_norm,
    raw_equity_coi2_index.c5_he_nat as opportunity_lvl_healthenv_domain_natl_norm,
    raw_equity_coi2_index.c5_se_nat as opportunity_lvl_socioeconomic_domain_natl_norm,
    raw_equity_coi2_index.c5_coi_nat as opportunity_lvl_coi_natl_norm,
    raw_equity_coi2_index.r_ed_nat as opportunity_score_education_domain_natl_norm,
    raw_equity_coi2_index.r_he_nat as opportunity_score_healthenv_domain_natl_norm,
    raw_equity_coi2_index.r_se_nat as opportunity_score_socioeconomic_domain_natl_norm,
    raw_equity_coi2_index.r_coi_nat as opportunity_score_coi_natl_norm,
    raw_equity_coi2_index.c5_ed_stt as opportunity_lvl_education_domain_state_norm,
    raw_equity_coi2_index.c5_he_stt as opportunity_lvl_healthenv_domain_state_norm,
    raw_equity_coi2_index.c5_se_stt as opportunity_lvl_socioeconomic_domain_state_norm,
    raw_equity_coi2_index.c5_coi_stt as opportunity_lvl_coi_state_norm,
    raw_equity_coi2_index.r_ed_stt as opportunity_score_education_domain_state_norm,
    raw_equity_coi2_index.r_he_stt as opportunity_score_healthenv_domain_state_norm,
    raw_equity_coi2_index.r_se_stt as opportunity_score_socioeconomic_domain_state_norm,
    raw_equity_coi2_index.r_coi_stt as opportunity_score_coi_state_norm,
    raw_equity_coi2_index.c5_ed_met as opportunity_lvl_education_domain_metro_norm,
    raw_equity_coi2_index.c5_he_met as opportunity_lvl_healthenv_domain_metro_norm,
    raw_equity_coi2_index.c5_se_met as opportunity_lvl_socioeconomic_domain_metro_norm,
    raw_equity_coi2_index.c5_coi_met as opportunity_lvl_coi_metro_norm,
    raw_equity_coi2_index.r_ed_met as opportunity_score_education_domain_metro_norm,
    raw_equity_coi2_index.r_he_met as opportunity_score_healthenv_domain_metro_norm,
    raw_equity_coi2_index.r_se_met as opportunity_score_socioeconomic_domain_metro_norm,
    raw_equity_coi2_index.r_coi_met as opportunity_score_coi_metro_norm,
    raw_equity_coi2_factors.ed_apenr as factor_education_ratio_students_apcourse_gt1,
    raw_equity_coi2_factors.ed_attain as factor_education_pct_adult_college_degree,
    raw_equity_coi2_factors.ed_college as factor_education_pct_college_enrollment,
    raw_equity_coi2_factors.ed_ecenrol as factor_education_pct_ece_enrollment,
    raw_equity_coi2_factors.ed_hsgrad as factor_education_pct_highschool_graduates,
    raw_equity_coi2_factors.ed_math as factor_education_pct_math_proficiency,
    raw_equity_coi2_factors.ed_reading as factor_education_pct_reading_proficiency,
    raw_equity_coi2_factors.ed_schpov as factor_education_pct_school_poverty,
    raw_equity_coi2_factors.ed_teachxp as factor_education_pct_new_teachers,
    raw_equity_coi2_factors.ed_prxece as factor_education_count_ece_centers,
    raw_equity_coi2_factors.ed_prxhqece as factor_education_count_naeyc_accredited_centers,
    raw_equity_coi2_factors.he_food as factor_healthenv_food_availability,
    raw_equity_coi2_factors.he_green as factor_healthenv_access_to_green_space,
    raw_equity_coi2_factors.he_heat as factor_healthenv_count_summer_days_temp_gt90f,
    raw_equity_coi2_factors.he_hlthins as factor_healthenv_pct_health_insurance_coverage,
    raw_equity_coi2_factors.he_ozone as factor_healthenv_avg_ozone_concentration,
    raw_equity_coi2_factors.he_pm25 as factor_healthenv_avg_microparticle_concentration_pm25,
    raw_equity_coi2_factors.he_vacancy as factor_healthenv_pct_vacant_housing,
    raw_equity_coi2_factors.he_walk as factor_healthenv_epa_walkability_index,
    raw_equity_coi2_factors.he_suprfnd as factor_healthenv_avg_superfund_sites_2mi_radius,
    raw_equity_coi2_factors.he_rsei as factor_healthenv_index_industrial_pollutants,
    raw_equity_coi2_factors.se_povrate as factor_socioeconomic_pct_below_poverty_rate,
    raw_equity_coi2_factors.se_public as factor_socioeconomic_pct_public_assistance,
    raw_equity_coi2_factors.se_home as factor_socioeconomic_pct_home_ownership,
    raw_equity_coi2_factors.se_occ as factor_socioeconomic_pct_highskill_employment,
    raw_equity_coi2_factors.se_mhe as factor_socioeconomic_median_household_income,
    raw_equity_coi2_factors.se_emprat as factor_socioeconomic_pct_employed_adults_25_54,
    raw_equity_coi2_factors.se_jobprox as factor_socioeconomic_pct_worker_commute_gt1hr,
    raw_equity_coi2_factors.se_single as factor_socioeconomic_pct_single_parent_households
from
    {{source('ods', 'raw_equity_coi2_index')}} as raw_equity_coi2_index
    inner join {{source('ods', 'raw_equity_coi2_factors')}} as raw_equity_coi2_factors
        on raw_equity_coi2_index.geoid = raw_equity_coi2_factors.geoid
        and raw_equity_coi2_index.year = raw_equity_coi2_factors.year
    inner join {{source('cdw', 'census_tract')}} as census_tract
        on raw_equity_coi2_index.geoid = census_tract.fips::bigint
