SELECT 'S_CDW_CCAS_ANESTHESIA_AIRWAY', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_AIRWAY UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_MONITOR', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_MONITOR UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_POSTOPICU', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_POSTOPICU UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_PREOPMEDS', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_PREOPMEDS UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_TECHNIQUE', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_TECHNIQUE UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_TRANSFUSION', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_TRANSFUSION UNION ALL
SELECT 'S_CDW_CCAS_ANESTHESIA_NIRS', COUNT(*) FROM  S_CDW_CCAS_ANESTHESIA_TRANSFUSION

DROP TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY;
DROP TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS;
--DROP TABLE S_CDW_CCAS_ANESTHESIA_CASES;
DROP TABLE S_CDW_CCAS_ANESTHESIA_CODES;
DROP TABLE S_CDW_CCAS_ANESTHESIA_MONITOR;
DROP TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU;
DROP TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS;
DROP TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS;
DROP TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE;
DROP TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION;

TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_AIRWAY;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS;
--TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_CASES;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_CODES;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_MONITOR;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_POSTOPICU;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_PREOPMEDS;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_TECHNIQUE;
TRUNCATE TABLE S_CDW_CCAS_ANESTHESIA_TRANSFUSION;

select * from S_CDW_CCAS_ANESTHESIA_ANTIFIBRINOLYTICS
select * from S_CDW_CCAS_ANESTHESIA_AIRWAY
select * from S_CDW_CCAS_ANESTHESIA_MONITOR
select * from S_CDW_CCAS_ANESTHESIA_POSTOPICU
select * from S_CDW_CCAS_ANESTHESIA_PREOPMEDS
select * from S_CDW_CCAS_ANESTHESIA_PROCOAGULANTS
select * from S_CDW_CCAS_ANESTHESIA_TECHNIQUE
select * from S_CDW_CCAS_ANESTHESIA_TRANSFUSION
