--CREATE TABLE REGISTRY_STS_ANESTHESIA_PROCOAGULANTS
--AS

WITH ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY	
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000051') TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000008' group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000049' group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000002' group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '100248' group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000046' group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000015' group by VISIT_KEY) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
--  AND SERVICE.SRC_ID IN (910,923) --Cardiac Service 
   and ANESSTAFF.DICT_OR_ANES_TYPE_KEY= 241354
	AND VSI_ANES.VSI_KEY > 0
 )
 
  ,PAT_WT AS
 (SELECT FLOW_REC.VSI_KEY,    
       CAST(AVG(CAST(MEAS_VAL/35.274 AS NUMERIC(7,1))) AS NUMERIC(5,1)) PAT_WT
FROM 
     CDW.FLOWSHEET_RECORD FLOW_REC
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY 
WHERE FS_ID IN (14)
GROUP BY 1
)
 
 , BLEED_MGT AS
( SELECT 
     VISIT_KEY
	,MIN(1) AS ANTIFIBUSAGE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' THEN 1 ELSE 2 END) AS ANTIFIBEPUSE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' AND BOLUS = 1  AND BOLUS_ORDER = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END)  ANTIFIBEPLOAD
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%' AND BOLUS = 0 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT)  AS INTEGER) END)  ANTIFIBEPINFRATE
	,MIN(2) ANTIFIBEPPRIME
--	,MIN(NULL) ANTIFIBEPPRIMEDOSE -- not used
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' THEN 1 ELSE 2 END) AS ANTIFIBTRANEXUSE
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' AND BOLUS = 1 AND BOLUS_ORDER = 1 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END )ANTIFIBTRANEXLOAD
	,MIN(CASE WHEN UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' AND BOLUS = 0 THEN CAST(DOSE/COALESCE(DOSAGE_WEIGHT_KG,PAT_WT) AS INTEGER) END) ANTIFIBTRANEXINFRATE
	,MIN(2) ANTIFIBTRANEXPRIME
--	,MIN(NULL) ANTIFIBTRANEXPRIMEDOSE --not used
--	,MIN(NULL) ANTIFIBTRASYLUSE --not used
--	,MIN(NULL) ANTIFIBTRASYLLOAD --not used
--	,MIN(NULL) ANTIFIBTRASYLPRIME --not used
--	,MIN(NULL) ANTIFIBTRASYLINFRATE  --not used 
FROM
	(SELECT *, ROW_NUMBER() OVER (PARTITION BY VISIT_KEY,BOLUS ORDER BY ACTION_DT, MED_ORD_KEY) BOLUS_ORDER

		FROM         
		   (SELECT
		         ANTIFIB.MED_ORD_KEY
				,DISCR_DOSE
			   , MED_ORD_NM
			   , CASE WHEN UPPER(MED_ORD_NM) LIKE '%BOLUS%' THEN 1 ELSE 0 END AS BOLUS
		       , ANTIFIB.SEQ_NUM
		       , ANTIFIB.VISIT_KEY
		       , ANTIFIB.ACTION_DT
			   , ANTIFIB.DICT_DOSE_UNIT_KEY
		       , ANTIFIB.DOSE
		       , ANTIFIB.INFSN_RATE
			   , MEDORD.DOSAGE_WEIGHT_KG 
			   , PAT_WT.PAT_WT
			FROM  ENCS JOIN MEDICATION_ADMINISTRATION ANTIFIB ON  ANTIFIB.VISIT_KEY = ENCS.ANES_VISIT_KEY   
			           JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = ANTIFIB.MED_ORD_KEY  
					   LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = ANTIFIB.DICT_RTE_KEY
					   LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = ANTIFIB.DICT_RSLT_KEY
					   LEFT JOIN PAT_WT ON ENCS.HSP_VAI_KEY = PAT_WT.VSI_KEY 
			WHERE 1=1
			  AND (UPPER(MED_ORD_NM) LIKE '%TRANEXAMIC ACID%' OR UPPER(MED_ORD_NM) LIKE '%AMINOCAPROIC ACID%')
			  and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) --GIVEN MEDS
			) ANTIFIB

	)	ANTIFIBTMP	 
GROUP BY VISIT_KEY 
)


 
SELECT 
		cast(ISNULL(LOG_ID,'') as integer)  CaseNumber 
		,cast(ISNULL(ANTIFIBUSAGE,2) as integer) ANTIFIBUSAGE
		,cast(ISNULL(ANTIFIBEPUSE,2) as integer) ANTIFIBEPUSE
		,cast((CASE WHEN ANTIFIBEPLOAD > 300 THEN 300 ELSE ANTIFIBEPLOAD END) as integer) IANTIFIBEPLOAD
		,cast((CASE WHEN ANTIFIBEPPRIME > 200 THEN 200 ELSE ANTIFIBEPPRIME END) as integer) IANTIFIBEPPRIME
		,cast((CASE WHEN ANTIFIBEPINFRATE > 300 THEN 300 ELSE ANTIFIBEPINFRATE END) as integer) IANTIFIBEPINFRATE
		,cast(ISNULL(ANTIFIBTRANEXUSE,2) as integer) ANTIFIBTRANEXUSE
		,cast((CASE WHEN ANTIFIBTRANEXLOAD > 150 THEN 150 ELSE ANTIFIBTRANEXLOAD END) as integer) IANTIFIBTRANEXLOAD
		,cast((CASE WHEN ANTIFIBTRANEXPRIME  > 50 THEN 50 ELSE ANTIFIBTRANEXPRIME END) as integer) IANTIFIBTRANEXPRIME
		,cast((CASE WHEN ANTIFIBTRANEXINFRATE  > 150 THEN 150 ELSE ANTIFIBTRANEXINFRATE END) as integer) IANTIFIBTRANEXINFRATE
		,2 as ANTIFIBTRANEXPRIMEDOSE
		,2 as POCCOAGTSTUTIL


FROM
	(SELECT ENCS.*,
	        BLEED_MGT.*
		FROM ENCS LEFT JOIN BLEED_MGT ON BLEED_MGT.VISIT_KEY = ENCS.ANES_VISIT_KEY

	) ENC
	
	ORDER BY 1