with 
events as
(
select
        evt.visit_key
		,event_id
		,event_dt
from 
     visit_ed_event evt 
	 inner join master_event_type evttype on evt.event_type_key = evttype.event_type_key 
     inner join anesthesia_encounter_link on anesthesia_encounter_link.anes_visit_key = evt.visit_key
where  
      evttype.event_id in ('1120000051','1120000008','1120000049', '1120000002','100248','1120000046','1120000015')

)
,encs as 
(select distinct
       aneslink.or_log_key
	   ,or_log.log_key	
	   ,anes_key
	   ,anes_event_visit_key
	   ,anes_visit_key
	   ,or_case.or_case_key
	   ,or_log_visit_key
	   ,proc_visit_key
	   ,aneslink.visit_key
	   ,vsi_anes.vsi_key anes_vsi_key
	   ,vai_hsp.vsi_key hsp_vai_key
	   --,aneslink.anes_start_tm anes_start_dttm
       ,pat.pat_mrn_id
       ,or_log.log_id
	   ,to_char(aneslink.anes_start_tm,'MM/DD/YYYY HH24:MI') anes_start_dttm
	   ,aneslink.anes_start_tm anes_start_tm  
	   ,aneslink.anes_end_tm anes_end_tm
	   ,coalesce(tee,2) tee
	   ,induct.induct_tm
	   ,isnull(to_char(induct.induct_tm,'MM/DD/YYYY HH24:MI'),to_char(aneslink.anes_start_tm,'MM/DD/YYYY HH24:MI')) induction_dttm
	   ,anesready.anesready_tm
	   ,anesstop.anesstop_tm
	   ,procstop.procstop_tm
	   ,to_char(anesready.anesready_tm,'MM/DD/YYYY HH24:MI') anes_ready_dttm
	   ,coalesce(handoff.handoff_tm,anesstop_tm) handoff_tm
	   ,to_char(handoff.handoff_tm,'MM/DD/YYYY HH24:MI') handoff_dttm
	   ,anes_stop_doc.anes_stop_doc_tm
from  anesthesia_encounter_link aneslink inner join or_case on aneslink.or_case_key = or_case.or_case_key
                                         inner join or_log on or_case.log_key = or_log.log_key
										 left join visit_addl_info vai_hsp on vai_hsp.visit_key = aneslink.visit_key
										 left join visit_stay_info vsi_anes on vsi_anes.visit_key = aneslink.anes_visit_key
										 left join patient pat on pat.pat_key = or_case.pat_key
										 join or_log_anes_staff anesstaff on anesstaff.log_key = or_log.log_key
										 join cdw_dictionary anestype on anestype.dict_key = anesstaff.dict_or_anes_type_key
										 join cdw_dictionary service on service.dict_key = or_case.dict_or_svc_key
										 left join (select 1 tee ,visit_key from events where event_id = '1120000051') tee on tee.visit_key = aneslink.anes_visit_key
										 left join (select visit_key, max(event_dt) induct_tm from events where event_id = '1120000008' group by visit_key) induct on induct.visit_key = aneslink.anes_visit_key
										 left join (select visit_key, max(event_dt) anesready_tm from events where event_id = '1120000049' group by visit_key) anesready on anesready.visit_key = aneslink.anes_visit_key
										 left join (select visit_key, max(event_dt) anesstop_tm from events where event_id = '1120000002' group by visit_key) anesstop on anesstop.visit_key = aneslink.anes_visit_key  
										 left join (select visit_key, max(event_dt) procstop_tm from events where event_id = '100248' group by visit_key) procstop on procstop.visit_key = aneslink.anes_visit_key 
										 left join (select visit_key, max(event_dt) handoff_tm from events where event_id = '1120000046' group by visit_key) handoff on handoff.visit_key = aneslink.anes_visit_key
								     	 left join (select visit_key, max(event_dt) anes_stop_doc_tm from events where event_id = '1120000015' group by visit_key) anes_stop_doc on anes_stop_doc.visit_key = aneslink.anes_visit_key 
where 1=1
--  and service.src_id in (910,923) --cardiac service 
    and anestype.src_id= 7.0000
	and vsi_anes.vsi_key > 0
 )

 
  ,PAT_WT AS
 (SELECT FLOW_REC.VSI_KEY,    
       CAST(AVG(MEAS_VAL_NUM/35.274) AS NUMERIC(5,1)) PAT_WT
FROM 
     CDW.FLOWSHEET_RECORD FLOW_REC
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY 
WHERE FS_ID IN (14)
GROUP BY 1
)
 

,MEDS AS
(
SELECT DISTINCT
        MEADMIN.MED_ORD_KEY
	   , MED_ORD_NM
	   , MED_ORD_DESC
	   , MEADMIN.SEQ_NUM
	   , MEADMIN.VISIT_KEY
	   , MEADMIN.ACTION_DT
	   , MEADMIN.DOSE
	   , MEADMIN.INFSN_RATE
	, COALESCE(MEDORD.DOSAGE_WEIGHT_KG,PAT_WT.PAT_WT) DOSAGE_WEIGHT_KG 
 FROM  
       ENCS 
	    JOIN MEDICATION_ADMINISTRATION MEADMIN ON MEADMIN.VISIT_KEY = ENCS.ANES_VISIT_KEY  
        JOIN MEDICATION_ORDER MEDORD ON MEDORD.MED_ORD_KEY = MEADMIN.MED_ORD_KEY  
	    LEFT JOIN CDW_DICTIONARY ROUTE ON ROUTE.DICT_KEY = MEADMIN.DICT_RTE_KEY
	    LEFT JOIN CDW.CDW_DICTIONARY DICT_RSLT_KEY ON DICT_RSLT_KEY.DICT_KEY = MEADMIN.DICT_RSLT_KEY
		LEFT JOIN PAT_WT ON ENCS.HSP_VAI_KEY = PAT_WT.VSI_KEY 
WHERE
	 (
	 (UPPER(MED_ORD_NM) LIKE '%FACTOR%VIIA%') or (UPPER(MED_ORD_DESC) LIKE '%FACTOR%VIIA%')
	 OR (UPPER(MED_ORD_NM) LIKE '%KCENTRA%') or (UPPER(MED_ORD_DESC) LIKE '%KCENTRA%')
	 or (UPPER(MED_ORD_NM) LIKE '%FEIBA%') or (UPPER(MED_ORD_DESC) LIKE '%FEIBA%')
	 OR (UPPER(MED_ORD_NM) LIKE '%PROFILNINE%') or (UPPER(MED_ORD_DESC) LIKE '%PROFILNINE%')
	 OR (UPPER(MED_ORD_NM) LIKE '%OCTAPLEX%') or (UPPER(MED_ORD_DESC) LIKE '%OCTAPLEX%')
	 OR (UPPER(MED_ORD_NM) LIKE '%AT3%') or (UPPER(MED_ORD_DESC) LIKE '%AT3%')
	 OR (UPPER(MED_ORD_NM) LIKE '%FIBRINOGEN%') or (UPPER(MED_ORD_DESC) LIKE '%FIBRINOGEN%')
	 OR (UPPER(MED_ORD_NM) LIKE '%DESMOPRESSIN%')  or (UPPER(MED_ORD_DESC) LIKE '%DESMOPRESSIN%')
	 OR (UPPER(MED_ORD_NM) LIKE '%DDAVP%') or (UPPER(MED_ORD_DESC) LIKE '%DDAVP%')
	 )
	 and DICT_RSLT_KEY.SRC_ID IN (105, 102, 122.0020, 6, 103, 1, 106, 112, 117) 
	 AND MEADMIN.VISIT_KEY<>0
)


, FACT7 AS (
 
		SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
           ,ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
		FROM MEDS PROCOAG 
		WHERE
		     	 (UPPER(MED_ORD_NM) LIKE '%FACTOR%VIIA%') or (UPPER(MED_ORD_DESC) LIKE '%FACTOR%VIIA%')
		  	
)

, FACTORVIIA AS
 (SELECT  
        VISIT_KEY
       ,1 AS ProcoagUsage
	   ,1 AS ProcoagFactorVIIa
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS ProcoagFactorVIIa3 
FROM
	 FACT7
GROUP BY 
     VISIT_KEY 
)

,KCENT AS (
SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
 		   , DOSAGE_WEIGHT_KG 
            , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ           
		FROM  
             MEDS PROCOAG
		WHERE
		    (UPPER(MED_ORD_NM) LIKE '%KCENTRA%') or  (UPPER(MED_ORD_DESC) LIKE '%KCENTRA%')
)		           

, KCENTRA AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCMPLXCON4
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4DS3 
FROM
	KCENT
GROUP BY VISIT_KEY 
)

, FEIBA_SETUP AS (
SELECT 
	     PROCOAG.MED_ORD_KEY
       , PROCOAG.SEQ_NUM
       , PROCOAG.VISIT_KEY
       , PROCOAG.ACTION_DT
       , PROCOAG.DOSE
       , PROCOAG.INFSN_RATE
	   , DOSAGE_WEIGHT_KG
       , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM  
       MEDS AS PROCOAG
	WHERE
	      (UPPER(MED_ORD_NM) LIKE '%FEIBA%') or  (UPPER(MED_ORD_DESC) LIKE '%FEIBA%')

    )
, FEIBA AS
 (SELECT 
       VISIT_KEY
	   ,1 AS PPROCMPLXCON4W7A
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON4W7A3 
FROM
	FEIBA_SETUP
GROUP BY
     VISIT_KEY 
)

, PROFIL_SETUP AS (
SELECT 
		     PROCOAG.MED_ORD_KEY
	       , PROCOAG.SEQ_NUM
	       , PROCOAG.VISIT_KEY
	       , PROCOAG.ACTION_DT
	       , PROCOAG.DOSE
	       , PROCOAG.INFSN_RATE
		   , DOSAGE_WEIGHT_KG
           , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
		FROM MEDS PROCOAG 
		--GROUP BY INDUCTMED.VISIT_KEY
		WHERE 
		      (UPPER(MED_ORD_NM) LIKE '%PROFILNINE%') or  (UPPER(MED_ORD_DESC) LIKE '%PROFILNINE%')
		  
)

, PROFILNINE AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCMPLXCON3
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCMPLXCON3DS3 
FROM
	PROFIL_SETUP
GROUP BY VISIT_KEY 
)

,OCTA_SETUP AS (
SELECT 
     PROCOAG.MED_ORD_KEY
   , PROCOAG.SEQ_NUM
   , PROCOAG.VISIT_KEY
   , PROCOAG.ACTION_DT
   , PROCOAG.DOSE
   , PROCOAG.INFSN_RATE
   , DOSAGE_WEIGHT_KG
   , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
FROM MEDS PROCOAG 
--GROUP BY INDUCTMED.VISIT_KEY
WHERE 
     (UPPER(MED_ORD_NM) LIKE '%OCTAPLEX%') or  (UPPER(MED_ORD_DESC) LIKE '%OCTAPLEX%')

)

, OCTAPLEX AS
 (SELECT VISIT_KEY
	   ,1 AS POCTAPLEX
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS OCTAPLEXDS3 
FROM
     OCTA_SETUP
GROUP BY VISIT_KEY 
)

, FIBRIN_SETUP AS 
(
  SELECT 
	     PROCOAG.MED_ORD_KEY
       , PROCOAG.SEQ_NUM
       , PROCOAG.VISIT_KEY
       , PROCOAG.ACTION_DT
       , PROCOAG.DOSE
       , PROCOAG.INFSN_RATE
	   , DOSAGE_WEIGHT_KG 
       , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM  MEDS PROCOAG  
	--GROUP BY INDUCTMED.VISIT_KEY
	WHERE 
	      (UPPER(MED_ORD_NM) LIKE '%FIBRINOGEN%') or  (UPPER(MED_ORD_DESC) LIKE '%FIBRINOGEN%')

)

, FIBRINOGEN AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGFIBRIN
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGFIBRIN3
FROM
   FIBRIN_SETUP
GROUP BY VISIT_KEY 
)

, AT3_SETUP AS (
    SELECT 
	     PROCOAG.MED_ORD_KEY
       , PROCOAG.SEQ_NUM
       , PROCOAG.VISIT_KEY
       , PROCOAG.ACTION_DT
       , PROCOAG.DOSE
       , PROCOAG.INFSN_RATE
	   , DOSAGE_WEIGHT_KG
       , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM  MEDS PROCOAG 
	WHERE
	     (UPPER(MED_ORD_NM) LIKE '%AT3%') or  (UPPER(MED_ORD_DESC) LIKE '%AT3%')

)

, AT3 AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGANTITHROM
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGANTITHROM3 
FROM
	AT3_SETUP
GROUP BY VISIT_KEY 
)

, DESMO_SETUP AS 
(

	SELECT 
	     PROCOAG.MED_ORD_KEY
       , PROCOAG.SEQ_NUM
       , PROCOAG.VISIT_KEY
       , PROCOAG.ACTION_DT
       , PROCOAG.DOSE
       , PROCOAG.INFSN_RATE
	   , DOSAGE_WEIGHT_KG
       , ROW_NUMBER() OVER (PARTITION BY MED_ORD_KEY ORDER BY ACTION_DT) MED_ADMIN_SEQ
	FROM  MEDS PROCOAG 

	--GROUP BY INDUCTMED.VISIT_KEY
	WHERE 
	     (UPPER(MED_ORD_NM) LIKE '%DESMOPRESSIN%') OR (UPPER(MED_ORD_NM) LIKE '%DDAVP%')
		 OR
		  (UPPER(MED_ORD_DESC) LIKE '%DESMOPRESSIN%') OR (UPPER(MED_ORD_DESC) LIKE '%DDAVP%')

		  
)

, DESMOPRESSIN AS
 (SELECT VISIT_KEY
	   ,1 AS PPROCOAGDESMO
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 1 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO1
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 2 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO2
	   ,ISNULL(MIN(CASE WHEN MED_ADMIN_SEQ = 3 THEN CAST(DOSE/DOSAGE_WEIGHT_KG AS NUMERIC(10,2))END),0) AS PROCOAGDESMO3 
FROM
       DESMO_SETUP
GROUP BY VISIT_KEY 
)

, ENC AS
(
      SELECT ENCS.*,
			FACTORVIIA.*,
			KCENTRA.*,
			FEIBA.*,
			PROFILNINE.*,
			OCTAPLEX.*,
			FIBRINOGEN.*,
			AT3.*,
			DESMOPRESSIN.*
		FROM ENCS 
				  LEFT JOIN FACTORVIIA   ON FACTORVIIA.VISIT_KEY = ENCS.ANES_VISIT_KEY
				  LEFT JOIN KCENTRA      ON KCENTRA.VISIT_KEY = ENCS.ANES_VISIT_KEY
                  LEFT JOIN FEIBA        ON FEIBA.VISIT_KEY = ENCS.ANES_VISIT_KEY
				  LEFT JOIN PROFILNINE   ON PROFILNINE.VISIT_KEY = ENCS.ANES_VISIT_KEY
                  LEFT JOIN OCTAPLEX     ON OCTAPLEX.VISIT_KEY = ENCS.ANES_VISIT_KEY					  
				  LEFT JOIN FIBRINOGEN   ON FIBRINOGEN.VISIT_KEY = ENCS.ANES_VISIT_KEY	
				  LEFT JOIN AT3          ON AT3.VISIT_KEY = ENCS.ANES_VISIT_KEY	
				  LEFT JOIN DESMOPRESSIN ON DESMOPRESSIN.VISIT_KEY = ENCS.ANES_VISIT_KEY	

)

SELECT 

		CAST(ISNULL(LOG_ID,'') AS INTEGER)  CASENUMBER 
		,CAST(ISNULL(PROCOAGUSAGE,2) AS INTEGER)   PROCOAGUSAGE
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PROCOAGFACTORVIIA,2) AS INTEGER) END PROCOAGFACTORVIIA
		,CAST(PROCOAGFACTORVIIA1 AS INTEGER)  PROCOAGFACTORVIIA1
		,CAST(PROCOAGFACTORVIIA2 AS INTEGER)  PROCOAGFACTORVIIA2
		,CAST(PROCOAGFACTORVIIA3 AS INTEGER) PROCOAGFACTORVIIA3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON4,2) as integer) END  PPROCMPLXCON4
		,CAST(PROCMPLXCON4DS1 as integer) PROCMPLXCON4DS1
		,CAST(PROCMPLXCON4DS2 as integer) PROCMPLXCON4DS2
		,CAST(PROCMPLXCON4DS3 as integer) PROCMPLXCON4DS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON4W7A,2) as integer) END PPROCMPLXCON4W7A
		,CAST(PROCMPLXCON4W7A1 as integer) PROCMPLXCON4W7A1
		,CAST(PROCMPLXCON4W7A2 as integer) PROCMPLXCON4W7A2
		,CAST(PROCMPLXCON4W7A3 as integer) PROCMPLXCON4W7A3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCMPLXCON3,2) as integer) END PPROCMPLXCON3
		,CAST(PROCMPLXCON3DS1 as integer) PROCMPLXCON3DS1
		,CAST(PROCMPLXCON3DS2 as integer) PROCMPLXCON3DS2
		,CAST(PROCMPLXCON3DS3 as integer) PROCMPLXCON3DS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(POCTAPLEX,2) as integer) END POCTAPLEX
		,CAST(OCTAPLEXDS1 as integer) OCTAPLEXDS1
		,CAST(OCTAPLEXDS2 as integer) OCTAPLEXDS2
		,CAST(OCTAPLEXDS3 as integer) OCTAPLEXDS3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGFIBRIN,2) as integer) END PPROCOAGFIBRIN
		,CAST(PROCOAGFIBRIN1 as integer) PROCOAGFIBRIN1
		,CAST(PROCOAGFIBRIN2 as integer) PROCOAGFIBRIN2
		,CAST(PROCOAGFIBRIN3 as integer) PROCOAGFIBRIN3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGANTITHROM,2) as integer) END PPROCOAGANTITHROM
		,CAST(PROCOAGANTITHROM1 as integer) PROCOAGANTITHROM1
		,CAST(PROCOAGANTITHROM2 as integer) PROCOAGANTITHROM2
		,CAST(PROCOAGANTITHROM3 as integer) PROCOAGANTITHROM3
		,CASE WHEN PROCOAGUSAGE = 1 THEN CAST(ISNULL(PPROCOAGDESMO,2) as integer) END PPROCOAGDESMO
	    ,CAST(PROCOAGDESMO1 as integer) PROCOAGDESMO1
		,CAST(PROCOAGDESMO2 as integer) PROCOAGDESMO2
		,CAST(PROCOAGDESMO3 as integer) PROCOAGDESMO3
   
FROM
     ENC