WITH ENCS AS 
(SELECT DISTINCT
       ANESLINK.OR_LOG_KEY
	   ,OR_LOG.LOG_KEY	
	   ,ANES_KEY
	   ,ANES_EVENT_VISIT_KEY
	   ,ANES_VISIT_KEY
	   ,OR_CASE.OR_CASE_KEY
	   ,OR_LOG_VISIT_KEY
	   ,PROC_VISIT_KEY
	   ,ANESLINK.VISIT_KEY
	   ,VSI_ANES.VSI_KEY ANES_VSI_KEY
	   ,VAI_HSP.VSI_KEY HSP_VAI_KEY
	   --,ANESLINK.ANES_START_TM ANES_START_DTTM
       ,PAT.PAT_MRN_ID
	   ,OR_LOG.PAT_KEY
       ,OR_LOG.LOG_ID
	   ,TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI') ANES_START_DTTM
	   ,ANESLINK.ANES_START_TM ANES_START_TM  
	   ,ANESLINK.ANES_END_TM ANES_END_TM
	   ,COALESCE(TEE,2) TEE
	   ,INDUCT.INDUCT_TM
	   ,ISNULL(TO_CHAR(INDUCT.INDUCT_TM,'MM/DD/YYYY HH24:MI'),TO_CHAR(ANESLINK.ANES_START_TM,'MM/DD/YYYY HH24:MI')) INDUCTION_DTTM
	   ,ANESREADY.ANESREADY_TM
	   ,ANESSTOP.ANESSTOP_TM
	   ,PROCSTOP.PROCSTOP_TM
	   ,TO_CHAR(ANESREADY.ANESREADY_TM,'MM/DD/YYYY HH24:MI') ANES_READY_DTTM
	   ,COALESCE(HANDOFF.HANDOFF_TM,ANESSTOP_TM) HANDOFF_TM
	   ,TO_CHAR(HANDOFF.HANDOFF_TM,'MM/DD/YYYY HH24:MI') HANDOFF_DTTM
	   ,ANES_STOP_DOC.ANES_STOP_DOC_TM
FROM  ANESTHESIA_ENCOUNTER_LINK ANESLINK INNER JOIN OR_CASE ON ANESLINK.OR_CASE_KEY = OR_CASE.OR_CASE_KEY
                                         INNER JOIN OR_LOG ON OR_CASE.LOG_KEY = OR_LOG.LOG_KEY
										 LEFT JOIN VISIT_ADDL_INFO VAI_HSP ON VAI_HSP.VISIT_KEY = ANESLINK.VISIT_KEY
										 LEFT JOIN VISIT_STAY_INFO VSI_ANES ON VSI_ANES.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN PATIENT PAT ON PAT.PAT_KEY = OR_CASE.PAT_KEY
										 JOIN or_log_anes_staff ANESSTAFF ON ANESSTAFF.LOG_KEY = OR_LOG.LOG_KEY
										 JOIN CDW_DICTIONARY SERVICE ON SERVICE.DICT_KEY = OR_CASE.DICT_OR_SVC_KEY
										 LEFT JOIN (SELECT 1 TEE ,VISIT_KEY FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000051') TEE ON TEE.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) INDUCT_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000008' group by VISIT_KEY) INDUCT ON INDUCT.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESREADY_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000049' group by VISIT_KEY) ANESREADY ON ANESREADY.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANESSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000002' group by VISIT_KEY) ANESSTOP ON ANESSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY  
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) PROCSTOP_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '100248' group by VISIT_KEY) PROCSTOP ON PROCSTOP.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
										 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) HANDOFF_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000046' group by VISIT_KEY) HANDOFF ON HANDOFF.VISIT_KEY = ANESLINK.ANES_VISIT_KEY
								     	 LEFT JOIN (SELECT VISIT_KEY, MAX(EVENT_DT) ANES_STOP_DOC_TM FROM VISIT_ED_EVENT EVT JOIN MASTER_EVENT_TYPE EVTTYPE ON EVT.EVENT_TYPE_KEY = EVTTYPE.EVENT_TYPE_KEY WHERE EVTTYPE.EVENT_ID = '1120000015' group by VISIT_KEY) ANES_STOP_DOC ON ANES_STOP_DOC.VISIT_KEY = ANESLINK.ANES_VISIT_KEY 
WHERE 1=1
--  AND SERVICE.SRC_ID IN (910,923) --Cardiac Service 
   and ANESSTAFF.DICT_OR_ANES_TYPE_KEY= 241354
	AND VSI_ANES.VSI_KEY > 0
 )
 
 
, ICU_FIO2 AS
(select A.VSI_KEY,
       A.HANDOFF_TM,
       A.ICU_FIO2_DT,
	   A.OR_LOG_KEY,
	   A.ICU_FIO2_VAL,
	   A.ICU_FIO2_ORDER,
	  CASE WHEN ICU_FIO2_VAL IS NULL AND ICU_FIO2_ORDER = 1 THEN LEAD (ICU_FIO2_VAL) OVER (PARTITION BY OR_LOG_KEY ORDER BY ICU_FIO2_DT) ELSE ICU_FIO2_VAL END ICU_FIO2_VAL_FINAL
from
(
SELECT  FLOW_REC.vsi_key
        ,REC_DT ICU_FIO2_DT
		,ENCS.OR_LOG_KEY
		,ENCS.HANDOFF_TM
	    ,CASE WHEN MEAS_VAL IS NULL THEN NULL ELSE CAST(CAST(MEAS_VAL AS INTEGER)/100.0 AS NUMERIC(5,2)) END AS ICU_FIO2_VAL
		,ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY FLOW_MEA.REC_DT, FLOW_MEA.ENTRY_DT) ICU_FIO2_ORDER 
FROM  CDW.VISIT_ADDL_INFO VAI 
    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
WHERE 1=1
   AND FLOW.FS_ID = 40002468	   
) a
)


, ICU_SPO2 AS
(SELECT  FLOW_REC.vsi_key
         ,REC_DT ICU_SPO2_DT
		,ENCS.OR_LOG_KEY
	     ,MEAS_VAL AS ICU_SPO2_VAL
		 ,ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY FLOW_MEA.ENTRY_DT, FLOW_MEA.REC_DT) ICU_SPO2_ORDER
FROM  CDW.VISIT_ADDL_INFO VAI 
    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
	JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
 WHERE 1=1	
   AND FLOW.FS_ID = 10 --SPO2
)

,ICU_TMP AS 
	( select  
	     ENCS.OR_LOG_KEY,
		 ENTRY_DT,--FLOW_MEA.FS_KEY, FLOW_MEA.MEAS_VAL
	     CAST(((FLOW_MEA.MEAS_VAL_num)-32)*(5/9.0) AS NUMERIC(4,1)) ICU_TMP,
		 ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY ENTRY_DT, REC_DT) ICU_TMP_ORDER  
		FROM 
		    CDW.VISIT_ADDL_INFO VAI 
		    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
		    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
		    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
			JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
		WHERE FLOW.FS_ID IN (6)
		 AND MEAS_VAL IS NOT NULL
	) 

,ICU_TMPSITE AS
	     ( SELECT
		    ENCS.OR_LOG_KEY,  
			ENTRY_DT,
			CASE WHEN UPPER(FLOW_MEA.MEAS_VAL) = 'AXILLARY' THEN 414
		         WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ORAL' THEN 410 --Nasal
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'RECTAL' THEN 413
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'ESOPHAGEAL PROBE' THEN 411
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'TEMPORAL' THEN  409 --Skin 2894 Tympanic?
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'BLADDER PROBE' THEN 412
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) = 'CORE TEMPERATURE (ECMO, SWAN GANZ)' THEN 2895
				 WHEN  UPPER(FLOW_MEA.MEAS_VAL) IS NULL THEN NULL END ICU_TMP_SITE,
			ROW_NUMBER() OVER (PARTITION BY ENCS.OR_LOG_KEY ORDER BY ENTRY_DT, REC_DT) TMP_SITE_ORDER
		FROM 
		    CDW.VISIT_ADDL_INFO VAI 
		    JOIN CDW.FLOWSHEET_RECORD FLOW_REC ON FLOW_REC.VSI_KEY=VAI.VSI_KEY 
		    INNER JOIN CDW.FLOWSHEET_MEASURE FLOW_MEA ON FLOW_MEA.FS_REC_KEY = FLOW_REC.FS_REC_KEY
		    INNER JOIN CDW.FLOWSHEET FLOW ON FLOW.FS_KEY=FLOW_MEA.FS_KEY 
			JOIN ENCS ON ENCS.HSP_VAI_KEY = FLOW_REC.VSI_KEY and FLOW_MEA.REC_DT > ENCS.HANDOFF_TM
		WHERE FLOW.FS_ID IN (40000303) 
		 AND MEAS_VAL IS NOT NULL
      )

, ICU_LABS AS
 (select RSLT.PROC_ORD_KEY
       ,RSLT.VISIT_KEY
	   , 1 AS ICU_LABS
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID = 27 THEN RSLT_NUM_VAL END) AS PH
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID = 28 THEN RSLT_NUM_VAL END) AS PCO2
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID = 29 THEN RSLT_NUM_VAL END) AS PO2
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID = 31 THEN RSLT_NUM_VAL END) AS BASEEXCESS
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID = 3722 THEN RSLT_NUM_VAL END) AS LACTATE
	   ,RSLT_DT --SELECT *
	   ,ROW_NUMBER() OVER (PARTITION BY RSLT.VISIT_KEY ORDER BY RSLT_DT, PROC_ORD_KEY) LAB_ORDER 
 from PROCEDURE_ORDER_RESULT RSLT join RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY
                                  JOIN ENCS ON ENCS.VISIT_KEY = RSLT.VISIT_KEY AND ENCS.PROCSTOP_TM < RSLT_DT
 WHERE 1=1
   AND COMP.RSLT_COMP_ID IN (3722,31,29,27,28)
   AND RSLT_NUM_VAL <> 9999999
   GROUP BY RSLT.PROC_ORD_KEY, RSLT.VISIT_KEY, RSLT_DT
)

, ICU_HEMATOCRIT AS
 (select RSLT.PROC_ORD_KEY
       ,RSLT.VISIT_KEY
	   , 1 AS ICU_HEMAT
	   ,MIN(CASE WHEN COMP.RSLT_COMP_ID IN (53,6649) THEN RSLT_NUM_VAL END) AS HEMATOCRIT
	   ,RSLT_DT --SELECT *
	   ,ROW_NUMBER() OVER (PARTITION BY RSLT.VISIT_KEY ORDER BY RSLT_DT, PROC_ORD_KEY) HEMAT_ORDER
 from PROCEDURE_ORDER_RESULT RSLT join RESULT_COMPONENT COMP ON RSLT.RSLT_COMP_KEY = COMP.RSLT_COMP_KEY
                                  JOIN ENCS ON ENCS.VISIT_KEY = RSLT.VISIT_KEY AND ENCS.PROCSTOP_TM < RSLT_DT
 WHERE 1=1
   AND COMP.RSLT_COMP_ID IN (53,6649)
   AND RSLT.RSLT_NUM_VAL <= 100
   GROUP BY RSLT.PROC_ORD_KEY, RSLT.VISIT_KEY, RSLT_DT
)

, OR_DISP AS
(SELECT SDE.PAT_KEY, 
        ENTERED_DT, 
		CASE WHEN ELEM_VAL = 'Phase 2 and then home' THEN 2859	
            WHEN ELEM_VAL = 'Inpatient floor - planned (re)admission' THEN 2860	
	        WHEN ELEM_VAL = 'ICU - planned (re)admission' THEN 2861	
	        WHEN ELEM_VAL = 'Inpatient floor - unplanned (re)admission' THEN 2862	
	    ELSE 2863 END AS DISPUNDERANES
		,ROW_NUMBER() OVER (PARTITION BY SDE.PAT_KEY ORDER BY ENTERED_DT) DATE_ORDER
FROM SMART_DATA_ELEMENT SDE JOIN ENCS ON SDE.PAT_KEY = ENCS.PAT_KEY  AND CAST(ENTERED_DT AS DATE)= CAST(ANES_STOP_DOC_TM AS DATE) 
WHERE 1=1
  AND  CONCEPT_KEY = 4582327	
  )

SELECT 
     cast(ISNULL(LOG_ID,'') as integer) CaseNumber
	,HANDOFF_TM ICUArrDt
	,CAST(ICU_FIO2_VAL AS DECIMAL(4,2)) InitialFiO2
	,CAST(ICU_TMP AS DECIMAL(4,1)) TempICUArr
	,CAST(ICU_TMP_SITE AS INTEGER) TempSite
	,CAST(ICU_SPO2_VAL AS DECIMAL(4,1)) InitPulseOx
	,ISNULL(ICU_LABS,2)  ICUPACULabs
	,CAST(PH AS DECIMAL (4,2)) PH
	,CAST(PCO2 AS INTEGER) PC02
	,CAST(PO2 AS INTEGER) PO2
	,CAST(BASEEXCESS AS INTEGER) BASEEXCESS
	,CAST(LACTATE AS DECIMAL (4,2)) LACTATE
	,CAST(HEMATOCRIT AS DECIMAL (4,1)) HEMATOCRIT
	,CAST(DISPUNDERANES AS INTEGER) DISPUNDERANES
	,2 as TEMPPACE
	,2 as PERIANESDEMISE

FROM

( 
		SELECT ENCS.*,
			   ICU_FIO2_VAL,
			   ICU_SPO2.*,
			   ICU_TMP.*,
			   ICU_TMPSITE.*,
			   ICU_LABS.*,
			   ICU_HEMATOCRIT.*,
			   COALESCE(DISPUNDERANES,2861) DISPUNDERANES
		FROM ENCS 
				 LEFT JOIN ICU_FIO2 ON ICU_FIO2.OR_LOG_KEY = ENCS.OR_LOG_KEY AND ICU_FIO2_ORDER = 1
				 LEFT JOIN ICU_SPO2 ON ICU_SPO2.OR_LOG_KEY = ENCS.OR_LOG_KEY AND ICU_SPO2_ORDER = 1
				 LEFT JOIN ICU_TMP ON ICU_TMP.OR_LOG_KEY = ENCS.OR_LOG_KEY AND ICU_TMP_ORDER = 1
				 LEFT JOIN ICU_TMPSITE ON ICU_TMPSITE.OR_LOG_KEY = ENCS.OR_LOG_KEY AND TMP_SITE_ORDER = 1
				 LEFT JOIN ICU_LABS ON ICU_LABS.VISIT_KEY = ENCS.VISIT_KEY AND LAB_ORDER = 1
				 LEFT JOIN ICU_HEMATOCRIT ON ICU_HEMATOCRIT.VISIT_KEY = ENCS.VISIT_KEY AND HEMAT_ORDER = 1
				 LEFT JOIN OR_DISP ON ENCS.PAT_KEY = OR_DISP.PAT_KEY AND CAST(ENTERED_DT AS DATE)= CAST(ANES_STOP_DOC_TM AS DATE) AND DATE_ORDER =1
							 
		WHERE 1=1 

) A	

ORDER BY 1