--BACKUP TABLES
select surg_enc_id, preproccarddiagid, diagnosisname, loaddt, md5, pendingimport 
into  CHOP_IMPACT_CATHDIAGNOSIS_bkp
from CHOP_IMPACT_CATHDIAGNOSIS


--SELECT * INTO CATHPROCEDURES_bkp
--from CathProcedures

SELECT * FROM CHOP_IMPACT_CATHDIAGNOSIS_bkp

select surg_enc_id, SPECIFICPROCID, loaddt, md5, pendingimport 
into  CHOP_IMPACT_CATHPROCEDURES_bkp 
from CHOP_IMPACT_CATHPROCEDURES

SELECT * FROM CHOP_IMPACT_CATHPROCEDURES_bkp

--DROP EXISTING TABLES
DROP TABLE CHOP_IMPACT_CATHDIAGNOSIS
DROP TABLE CHOP_IMPACT_CATHPROCEDURES

--CREATE NEW TABLES
CREATE TABLE [dbo].[CHOP_IMPACT_CATHDIAGNOSIS](
	[SURG_ENC_ID] [nvarchar](50) NOT NULL,
	[PREPROCCARDDIAGID] [int] NOT NULL,
	[DIAGNOSISNAME] [nvarchar](255) NULL,
	[LOADDT] [datetime] NOT NULL,
	[MD5] [varchar](50) NOT NULL,
	[PENDINGIMPORT] [int] NOT NULL,
 CONSTRAINT [PK_CHOP_IMPACT_CATHDIAGNOSIS] PRIMARY KEY CLUSTERED 
(
	[SURG_ENC_ID] ASC,
	[PREPROCCARDDIAGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]




CREATE TABLE [dbo].[CHOP_IMPACT_CATHPROCEDURES](
	[SURG_ENC_ID] [nvarchar](50) NOT NULL,
	[SPECIFICPROCID] [int] NOT NULL,
	[LOADDT] [datetime] NOT NULL,
	[MD5] [varchar](50) NOT NULL,
	[PENDINGIMPORT] [int] NOT NULL,
 CONSTRAINT [PK_CHOP_IMPACT_CATHPROCEDURES] PRIMARY KEY CLUSTERED 
(
	[SURG_ENC_ID] ASC,
	[SPECIFICPROCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



--BACKFILL FROM BACKUPS
INSERT INTO CHOP_IMPACT_CATHDIAGNOSIS
SELECT SURG_ENC_ID,
       PREPROCCARDDIAGID,
	   DIAGNOSISNAME,
	   MIN(LOADDT) LOADDT,
	   MIN(MD5) MD5,
	   MIN(PENDINGIMPORT) PENDINGIMPORT
  FROM CHOP_IMPACT_CATHDIAGNOSIS_bkp  
  GROUP BY SURG_ENC_ID,
       PREPROCCARDDIAGID,
	   DIAGNOSISNAME


INSERT INTO CHOP_IMPACT_CATHPROCEDURES
SELECT SURG_ENC_ID,
       SPECIFICPROCID,
	   MIN(LOADDT) LOADDT,
	   MIN(MD5) MD5,
	   MIN(PENDINGIMPORT) PENDINGIMPORT
  FROM CHOP_IMPACT_CATHPROCEDURES_bkp  
  GROUP BY SURG_ENC_ID,
       SPECIFICPROCID
	   ORDER BY 1