select
    stg_adt_all.visit_event_key,
    stg_adt_all.patient_name,
    stg_adt_all.mrn,
    stg_adt_all.dob,
    stg_adt_all.csn,
    stg_adt_all.encounter_date,
    stg_adt_all.hospital_admit_date,
    stg_adt_all.hospital_discharge_date,
    stg_adt_all.department_name,
    stg_adt_all.department_group_name,
    stg_adt_all.department_center_id,
    stg_adt_all.department_center_abbr,
    stg_adt_all.intended_use_group,
    stg_adt_all.bed_care_group,
    stg_adt_all.initial_service,
    stg_adt_all.dept_enter_date as enter_date,
    stg_adt_all.dept_exit_date as exit_date,
    stg_adt_all.dept_los_hrs as los_hrs,
    stg_adt_all.dept_los_days	as los_days,
    stg_adt_all.currently_admitted_ind,
    stg_adt_all.dept_exit_date_or_current_date as exit_date_or_current_date,
    stg_adt_all.dept_los_hrs_as_of_today as los_hrs_as_of_today,
    stg_adt_all.dept_los_days_as_of_today as los_days_as_of_today,
    stg_adt_all.all_department_order,
    stg_adt_all.inpatient_department_order,
    stg_adt_all.last_department_ind,
    stg_adt_all.pat_key,
    stg_adt_all.hsp_acct_key,
    stg_adt_all.visit_key,
    stg_adt_all.dept_key
from
    {{ref('stg_adt_all')}} as stg_adt_all
where
    stg_adt_all.department_ind = 1
